### ISSUE TITLE
How to add CanDestroy nbt tag ? 

### ISSUE THREAD

**Issue by RocheErwan** [ShaneBeee/SkBee#10]
Hi, first sorry for my english!

I have been trying for several hours to add the thing tag to an item via SkBee, but impossible to get there. 

The code: 
```
command /cantdestroy:
  trigger:
    add "{CanDestroy:[""minecraft:stone"",""#minecraft:logs""]}" to nbt of player's tool
```

It return me this: 
Invalid use of quotes ("). If you want to use quotes in "quoted text", double them: "". (message-matin.sk, line 35: add "{CanDestroy:[""minecraft:stone"",""#minecraft:logs""]}"to nbt of player's tool')

Do you know why ? Thanks for the support in advance

**Comment by Romitou** [comment]
Hello, double thé #.

**Comment by RocheErwan** [comment]
`Invalid amount or placement of brackets. Please make sure that each opening bracket has a corresponding closing bracket. (message-matin.sk, line 35: add ""{CanDestroy:[""minecraft:stone"",""#minecraft:logs""]}"" to nbt of player's tool')`

It's not working either :/

**Comment by ShaneBeee** [comment]
that's because you doubled up the quotes before/after your NBT 
WRONG:
```vb
add ""{Blah}""
```
CORRECT:
```vb
add "{Blah}"
```

**Comment by RocheErwan** [comment]
The two configuration made the same Issue : 
`Invalid use of quotes ("). If you want to use quotes in "quoted text", double them: "". (message-matin.sk, line 35: add "{CanDestroy:[""minecraft:stone""],[""#minecraft:logs""]}" to nbt of player's tool')`

**Comment by ShaneBeee** [comment]
Im closing this as this is not an SkBee issue, this is user error.
Romitou already answered you, you need to double up your #

**Comment by RocheErwan** [comment]
Damn, i'm sorry! 
I did not read his message well. It's time I go to sleep ..
It's working now. Thanks guys !
