### ISSUE TITLE
[BUG] Structure loading breaks script

### ISSUE THREAD

**Issue by mpschorr** [ShaneBeee/SkBee#100]
**Describe the bug**
Loading a structure does not allow the script to continue.

**To Reproduce**
Use this code:
```
broadcast "%{_id}% 1"
load structure "%{_id}%_generator" at {_loc}
broadcast "%{_id}% 2"
```
I have a structure, 3x1x3, named "coal_generator", {_id} is "coal", {_loc} is a valid location, and SkBee installed.

**Expected behavior**
I expected it to broadcast "coal 1", load the structure at {_loc}, and then broadcast "coal 2".
It only broadcasts "coal 1".

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.

**Version Info:**
 - **SkBee Version:** 1.9.1
-  **Skript Version:** Skript 2.5.3-MH
 - **Server Version/Platform:** Paper 

**Additional context**
{_loc} is valid because if I use ```set block at {_loc} to oak planks``` it sets it to oak planks.

**Comment by ShaneBeee** [comment]
Thanks for letting me know.
I will look into this, and try to replicate said issue, and do my best to fix it.

**Comment by ShaneBeee** [comment]
Ok, i did a test, with the following code:
```vb
command /test:
	trigger:
		broadcast "ABOUT TO PASTE A STRUCTURE"
		paste structure "test" at location of target block
		broadcast "DONE PASTING STRUCTURE"
```

This was the result:
(i can't upload an image) but it worked as expected. It broadcasted both messages, as well as pasted the structure.

Does the structure paste for you?
Do you get any console errors?

**Comment by mpschorr** [comment]
After writing this, I contacted the administrators of the server host I used, and apparently it was a fault on their end.
