### ISSUE TITLE
Can not remove NBT from item

### ISSUE THREAD

**Issue by bloggy** [ShaneBeee/SkBee#102]
**Describe the bug**
Unable to remove custom nbt tag from an item

**To Reproduce**
The player's tool has the Custom NBT Tag "CustomUUID" set. Now I run this code:
`delete tag "CustomUUID" of player's tool`
But it does not work (NBT tag still there) - no errors.

**Expected behavior**
should delete / remove nbt tag
dd screenshots/errors to help explain your problem.

**Version Info:**
 - **SkBee Version:** SkBee v1.9.0
-  **Skript Version:** Skript v2.5.3
 - **Server Version/Platform** This server is running Tuinity version git-Tuinity-"957a2ef" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Additional context**

**Comment by ShaneBeee** [comment]
as per the docs:
https://skripthub.net/docs/?id=4070
```
As of 1.6.0 you can also set/delete tags, but only with NBT compounds, not NBT strings.
```
