### ISSUE TITLE
[SUGGESTION] Change biome of selected cuboid 

### ISSUE THREAD

**Issue by GoldenMyst** [ShaneBeee/SkBee#103]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like an effect to change biomes of the selected blocks/cuboid.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ShaneBeee** [comment]
what?
An event for biome changes? Biomes don't naturally change, therefor no event would be called.

**Comment by GoldenMyst** [comment]
> what?
> An event for biome changes? Biomes don't naturally change, therefor no event would be called.

I meant effect

**Comment by ShaneBeee** [comment]
Skript already has an effect for changing biomes.

I highly recommend checking the docs before asking me to add something to SkBee, when Skript already has it, and has had it for years.
