### ISSUE TITLE
[SUGGESTION] Per world Tablist

### ISSUE THREAD

**Issue by Lennord** [ShaneBeee/SkBee#105]
Hello, I would like to know if it was possible to make a tablist per world system on SkBee?

**Comment by ShaneBeee** [comment]
Im confused is this a suggestion or a question?
If its a question = no, its not possible... SkBee has no syntaxes for tablists.

If its a suggestion = I will look into it in the future.

**Comment by Lennord** [comment]
> Im confused is this a suggestion or a question?
> If its a question = no, its not possible... SkBee has no syntaxes for tablists.
> 
> If its a suggestion = I will look into it in the future.

This is a suggestion

**Comment by ShaneBeee** [comment]
I will not be adding this to SkBee, from my understanding this would include heavy use of packets, which SkBee is not going to do
