### ISSUE TITLE
Server crashes on multiple nbt tags

### ISSUE THREAD

**Issue by CapCreeperGR** [ShaneBeee/SkBee#106]
**Describe the bug**
So I found out that when I use the expression: with nbt "{nbt1}" and "{nbt2}" the whole server crashes

**To Reproduce**
use the expression mentioned above anywhere

**Expected behavior**
I expected that the item would just have 2 nbt tags

**Screenshots/Errors**
Not much to show. Just when I /sk reload scripts the server crashes and I can't show console logs because I am using minehut which does not have a way to see the console

**Version Info:**
 - SkBee Version: I am not sure how to get the version. Probably the latest one though
-  Skript Version: 2.5.3 MH
 - Server Version/Platform: Paperspigot 1.16.4.R0-1 Snapshot

**Comment by ShaneBeee** [comment]
> I am using minehut which does not have a way to see the console

yes it does. If you need help, please reach out to someone on Minehut to explain to you how to get logs. Its the same as any server.

I need a log to solve an issue since you've provided nearly no info.
