### ISSUE TITLE
Server compund error

### ISSUE THREAD

**Issue by SzczurekYT** [ShaneBeee/SkBee#107]
Hello I found error in my server console. It's related to nbt compound and my script. I made script that basically allows me to sit and unsit not my and wild dogs.

This error doesn't break anything

Here is log and informations: https://pastebin.com/4ErRhA4p
And here is my script: https://pastebin.com/GHVq4PzP

**Comment by ShaneBeee** [comment]
The code you provided does not match the error you provided.
Code uses tag "Sitting" whereas the error references tag "Owner"

**Comment by SzczurekYT** [comment]
I realized that the occurred with older version of script that I don't have, maybe there was bug in my code.

**Comment by ShaneBeee** [comment]
Try updating to 1.10.1 (just released it) maybe it was fixed, as I did do some small fixes with NBT recently.

**Comment by SzczurekYT** [comment]
Ok, I will update plugin. Also I tested this and now error doesn't occur there probably was a bug in my script. I think we can close this.

**Comment by ShaneBeee** [comment]
ok cool. If you continue having issues, don't be afraid to reply here, and we can dig into it.
