### ISSUE TITLE
[BUG] Addon does not work (displays red)

### ISSUE THREAD

**Issue by Boro221** [ShaneBeee/SkBee#108]
Addon does not work on my server. No error is displayed in the console when starting the server, but when I enter the command /plugins, the plugin is red. I have skript 1.5.3, and my server version is 1.16.3

**Version Info:**
 - **SkBee Version:** 1.10.1
-  **Skript Version:** Skript 2.5.3
 - **Server Version/Platform** Spigot 1.16.3

**Comment by ShaneBeee** [comment]
> No error is displayed in the console when starting the server, but when I enter the command /plugins, the plugin is red

this is literally impossible. If the plugin is read, that means it nots enabled, and if its not enabled, there would 100% be an error of some sorts.
IF you are unsure, please attach a copy of your log when the server is loading.

**Comment by Boro221** [comment]
Oh sorry, I found it now..

[SkBee] Enabling SkBee v1.10.1
Server thread/INFO]: [0;37;22m[[0;36;1mSk[0;36;22mBee[0;37;22m] [0;31;1mDependency Skript was not found, plugin disabling[m
[Server thread/INFO]: [SkBee] Disabling SkBee v1.10.1

**Comment by ShaneBeee** [comment]
Ive seen this happen before.
Im not sure what is causing this to happen, but some plugin on the server is changing load order of the plugins, and pushing SkBee to either load before Skript (not in your case) or load after Skript has stopped accepting registrations.

That said, there is nothing I can do about this.
I recommend removing some plugins from your server (in groups) and try to find out which plugin is causing this to happen.

**Comment by ShaneBeee** [comment]
From my understanding this was an issue on Paper, which they fixed.
It says you're using Spigot here, which seems odd, as ive never seen this happen on Spigot.
That said, I do believe this is a server issue, screwing up dependency load order, which I cant control.
Im closing this as its out of my control.
