### ISSUE TITLE
[BUG] NBT Tags

### ISSUE THREAD

**Issue by Kormic1** [ShaneBeee/SkBee#109]
**Describe the bug**
Well... In SkBee I found two issues with NBT tags, but they are so related that I found it unnecessary to report them separately.

First issue is that you can't use nested tags. In older SkBee versions (ex. 1.4.7) it was causing internal error, but in the newest version it basically returns "none".

My code:
```
command /check-nbt:
	trigger:
		set {_tag} to tag "StoredEnchantments;lvl" of player's tool's nbt
		send "%{_tag}%" to sender
```

I found second issue when I tried to workaround first issue. You can't use variables when trying to get NBT tag.

My code:
```
command /check-nbt:
	trigger:
		set {_nbt::*} to player's tool's nbt, "StoredEnchantments" and "id"
		loop {_nbt::*}:
			exit loop if (loop-index parsed as number) is size of {_nbt::*}
			set {_nbtTag} to tag "%{_nbt::%loop-index parsed as number + 1%}%" of loop-value
		send "%{_nbtTag}%" to sender
```

When I attempted to use code above, there was an internal error.

Yes, I tried to parse 'loop-index' as integer as well.

I even tried to do it as simple with this code:

```
command /check-nbt:
	trigger:
		set {_nbt::*} to player's tool's nbt, "StoredEnchantments" and "id"
		loop {_nbt::*}:
			exit loop if (loop-index parsed as number) is size of {_nbt::*}
			set {_n} to loop-index parsed as number + 1
			set {_t} to "%{_nbt::%{_n}%}%"
			set {_t2} to loop-value
			set {_nbtTag} to tag {_t} of loop-value
		send "%{_nbtTag}%" to sender
```

I was changing few things (mostly variables) in this code and i discovered that 'loop-value' causes error.

**To Reproduce**

Just use the code i gave above.

**Expected behavior**

I expected that nested tags will work seamlessly. They didn't, so I tried to make a workaround which didn't work too.

**Screenshots/Errors**

Internal error from second issue here:
https://pastebin.com/jVR4ugf3

**Version Info:**
 - **SkBee Version:** 1.10.2
-  **Skript Version:** 2.5.3
 - **Server Version/Platform** Spigot 1.12.2

**Additional context**

The only workaround at this moment is code below which is an example of doing this.

Getting value of tag "id" of tag "StoredEnchantments" of player's tool's nbt:

```
command /check-nbt:
	trigger:
		set {_t} to tag "StoredEnchantments" of player's tool's nbt
		set {_t} to tag "id" of "%{_t}%"
		send "%{_t}%" to sender
```

**Comment by ShaneBeee** [comment]
First issue:
your code:
```vb
set {_tag} to tag "StoredEnchantments;lvl" of player's tool's nbt
```
stored enchants are a list, example of a book item:
```
{id: "minecraft:enchanted_book", tag: {StoredEnchantments: [{id: "minecraft:power", lvl: 1s}]}, Count: 1b}
```
lvl is not a nested tag, its part of a list, so you would have to loop the list, or pull elements from said list.

Second issue:
I have no clue what exactly is going on here... but it looks like you're trying to do the same thing as issue one, and again, ID/LVL are not nested tags, as they are part of a list.

**Comment by Kormic1** [comment]
You're right, my bad. I'm so sorry for wasting your time. Problem solved.
