### ISSUE TITLE
Team Glows Don’t work

### ISSUE THREAD

**Issue by tinker1233** [ShaneBeee/SkBee#11]
Anything to do with team glow colours aren’t working , it’s showing the joining of teams but only showing a white glow . When doing /team list it will show the existing teams as per usual . And will Show that you’ve been added to a team upon joining. But not actually show that team colour when glowing. When I go to use /team remove and try and tab the existing teams, they do not show on a list.

**Comment by ShaneBeee** [comment]
well thank you for that extremely detailed bug report

**Comment by ShaneBeee** [comment]
Closing due to lack of information.
