### ISSUE TITLE
[SUGGESTION] Multiple lines of player name tag

### ISSUE THREAD

**Issue by varthex** [ShaneBeee/SkBee#111]
![2021-02-01_00 33 54](https://user-images.githubusercontent.com/47464626/106401902-1db78280-6427-11eb-8695-243c40140415.png)

**Comment by ShaneBeee** [comment]
From my understanding, this is done by using armorstands and/or other entities, riding the player.
To my knowledge, you can easily do this already in Skript, I dont see why SkBee would need this.
