### ISSUE TITLE
[SUGGESTION] Check if tool was repaired via NBT

### ISSUE THREAD

**Issue by Misio12320** [ShaneBeee/SkBee#112]
**Is your feature request related to a problem? Please describe.**
I would like to fix my diamond sword of sharpness VI created via custom anvil recipes by diamonds but max 3 times.

**Describe the solution you'd like**
Add a support to SkBee to check if the item was repaired via NBT. If it was repaired 3 times it should say "too expensive"

**Describe alternatives you've considered**
I don't have ideas. I think I said everything what I mean.

**Additional context**
Everything is said above. Have a good day :3

**Comment by ShaneBeee** [comment]
I'm not exactly sure what you are asking here. 
Based on what I understand, you're trying to find repair costs, which is already done in vanilla MC.

Here is for example, the NBT of a diamond sword after repairing it once:
```
NBT: {
 id: "minecraft:diamond_sword",
 tag: {
  RepairCost: 1,
  Damage: 0
 },
 Count: 1b
}
```
Here is the NBT of the same item, after repairing it again:
```
 NBT: {
 id: "minecraft:diamond_sword",
 tag: {
  RepairCost: 3,
  Damage: 0
 },
 Count: 1b
}
```
As you can see, the repair costs is show there, and you can do with it whatever you'd like.

**Comment by ShaneBeee** [comment]
closing as im not totally sure what you're asking for here, nor have I gotten a reply in 21 days
