### ISSUE TITLE
[BUG]/trigger commands stop working after installing SkBee

### ISSUE THREAD

**Issue by Jarngeir** [ShaneBeee/SkBee#119]
After installing SkBee V1.12.4, all /trigger commands from datapacks stop working.
Produces a response of "You cannot trigger this objective yet"

**To Reproduce**
Install Skript, & SkBee, as well as any datapack that has a /trigger function. 

**Expected behavior**
/trigger to work as normal

**Screenshots/Errors**
With SkBee
https://i.imgur.com/wVD813w.png

Without SkBee
https://i.imgur.com/W0EEjAl.png

**Version Info:**
 - **SkBee Version:** - 1.12.4
-  **Skript Version:**  -Skript 2.6-alpha1
 - **Server Version/Platform** - Purpur-1427 (MC: 1.17.1)

**Comment by ShaneBeee** [comment]
try disabling scoreboards in SkBee's config.
SkBee's boards give each player their own scoreboard, and that might be messing with your data pack

**Comment by ShaneBeee** [comment]
closing due to no reply, hopefully your issue was resolved
