### ISSUE TITLE
Can't edit the nbt tags of an item in an entity from the 'item spawn' event

### ISSUE THREAD

**Issue by Tai1er** [ShaneBeee/SkBee#12]
I'm using this code in 1.12.2 with Skript 2.4.1, Sk-NBeeT and I'm trying to update it to 1.14.4, 2.5 and SkBee
```
on item spawn:
    set {_id} to random integer between 0 and 4294967296
    add "{display:{Name:"" ""},HideFlags:63,CanPlaceOn:[%{blocks}%],id:%{_id}%}" to nbt of event-item
```

_set_, _add_ and _reset_ do nothing on the event-item's nbt but displaying it is working.
I have no problem with the nbt of the event-entity but I don't know if SkBee has a syntax to edit a tag inside the _item_ tag of the entity without manipulate the content of the _item_ tag and rewrite it completely.

I got no errors, only no effects. Same problem with Skript 2.4.1.

**Comment by ShaneBeee** [comment]
My guess is your NBT is invalid

**Comment by Tai1er** [comment]
I have fixed the _display_ tag but I still get no formating errors.
I already use the exact same tags outside an entity without problems.

For exemple:
```
function itemsNbt() :: text:
	set {_id} to random integer between 0 and 4294967296
	return "{display:{Name:'{""text"":"" ""}'},HideFlags:63,id:%{_id}%,CanPlaceOn:[%{blocks}%]}"
```
` ... to close then run function manufacturingValidate({_p},unlit campfire with nbt itemsNbt(),5 stick)`

**Comment by ShaneBeee** [comment]
Hmm I'm not really sure what to tell ya.
Have you tried applying this NBT via vanilla commands?
Quite often people make mistakes in their NBT and immediately blame me, when its just user error.
Try spawn a dropped item with vanilla commands and the same NBT tag and see what happens.

As for testing, I can't test this since I don't actually know what's in your `{blocks}` variable.

**Comment by Tai1er** [comment]
Yeah of course, I understand.
No I'm not using vanilla command, but I get no problem with the vanilla command too. I'm using SkBee directly to use thoses nbt tags somewhere else in my code without problems except in the _item spawn_ event.

The `{blocks}` is a long string that contains all the formated vanilla named blocks I want the block to be placed on. I got the same problem without this.

This is the point of my problem. I got no problems except in this specific case. I can't set, add or reset any tags in the even-item.

This example is perfectly working:
```
command /test:
	trigger:
		give stick with nbt "{HideFlags:63}" to player
```

This is two basic examples of code which doesn't work.
```
on item spawn:
	broadcast nbt of event-item
	add "HideFlags:63" to nbt of event-item
	broadcast nbt of event-item
```
or
```
on item spawn:
	broadcast nbt of event-item
	reset nbt of event-item
	broadcast nbt of event-item
```
In this last example, I can give me a stick with "{HideFlags:63}" tag with the vanilla command, but it doesn't reset the tags when the item is spawned on my feet or when I drop it from my inventory.
The broadcasts display both _{HideFlags:63}_

**Comment by ShaneBeee** [comment]
Ok looking thru Skript's code, this appears to be a Skript issue.
When using event-item, Skript creates a new item type based on the item stack of the entity.
This in itself is a clone of the original item, so applying NBT to it, won't translate back to the original item.

That said 2 things you could do:
1) You could add NBT to the event-entity. The issue with this is the NBT of an entity will be a bit different than the item
2) You could get the item, cancel the event (preventing the item spawning), add NBT to the item and drop it (therefor spawning a new item)

**Comment by Tai1er** [comment]
Ok, Thank you for your research. :)
1. I will try to see how I can edit subtag in the item tag of the entity without a complexe string manipulation.
2. I doens't take the item velocity since it's in the entity but it's not a problem in my case.
