### ISSUE TITLE
[BUG] Skbee make all my file.sk broken 

### ISSUE THREAD

**Issue by LowScarlet** [ShaneBeee/SkBee#120]
**Describe the bug**
All the .sk files were corrupted when I installed the latest skbee version 1.13.0, after that I went back to version 1.12.1 but the problem persists

**To Reproduce**
-

**Expected behavior**
It shouldn't be

**Screenshots/Errors**
[If applicable, add screenshots/errors to help explain your problem.](https://gist.githubusercontent.com/LowScarlet/a747fa149bac9ef2d5f2304e862b4e69/raw/8665116ce38c80737472ae9a036f8e1aae90c097/Skript)

**Version Info:**
 - **SkBee Version:** 1.13.0
-  **Skript Version:** 2.6-nightly-3d4bd39
 - **Server Version/Platform** 1.17.1 paper

**Additional context**

**Comment by ShaneBeee** [comment]
Hey, I only understand English. If you require help I'm going to need the issue posted in English.

**Comment by LowScarlet** [comment]
> Hey, I only understand English. If you require help I'm going to need the issue posted in English.

I think i have edit it

**Comment by ShaneBeee** [comment]
for the time being, try disabling structures in the SkBee config.
I'm not entirely sure why this error is happening, but I know that its coming from something to do with structures

**Comment by LowScarlet** [comment]
> for the time being, try disabling structures in the SkBee config. I'm not entirely sure why this error is happening, but I know that its coming from something to do with structures

work, but can you fix it?

**Comment by ShaneBeee** [comment]
Im going to try, but based on the lack of info/code you've provided, I have no way to recreate this error.
I can tell from the stacktrace, thats its looking for a classinfo (which is there), which im confused by. Other than that, I have no way of knowing what caused the error.
If I see it again, and more info is provided, ill do my best to try fix it. 
But as of right now, this issue doesnt contain any useful information other than the stack trace error

**Comment by LowScarlet** [comment]
> Im going to try, but based on the lack of info/code you've provided, I have no way to recreate this error. I can tell from the stacktrace, thats its looking for a classinfo (which is there), which im confused by. Other than that, I have no way of knowing what caused the error. If I see it again, and more info is provided, ill do my best to try fix it. But as of right now, this issue doesnt contain any useful information other than the stack trace error

ok.. right now i don't need the structure feature so no problem, but maybe i don't need to close this issue right?..

**Comment by ShaneBeee** [comment]
for now im going to close it, as I dont have sufficient information to recreate a case
