### ISSUE TITLE
[BUG] SkBee Breaking Vanilla "/team" glow colors, and "/team" tab complete.

### ISSUE THREAD

**Issue by Dogloverblue** [ShaneBeee/SkBee#122]
**Describe the bug**
With SkBee install, doing team commands such as "/team modify " will produce strange tab completions that are "line1", "line10", line11", "line12", "line13", "line14", "line15", "line2", "line3", "line4", "line5", "line6", "line7", "line8", "line9". In the EXACT order.

The glowing colors of teams will also be broken, resulting in the color of your glow being white, no matter what color your team is.

**To Reproduce**
With Skript and SkBee installed, Run these following commands:

/team create red "Red"                                     //Command runs fine.
/team modify red color red                             //Command will execute fine, but the tab complete will be wonky here
/team join red                                                //Command will execute fine, but the tab complete will also be wonky here
/effect give @s glowing 100 1                       //You will have the incorrect glow color, when you are meant to glow red, you will glow white instead.

**Expected behavior**. 
Your team glowing color should change based on your team color, and team tab complete should be all of the created teams:
Expected:
/team create red "Red"
/team modify red color red            //the tab complete after the "modify" is just "red" (and any other created teams)
/team join red                                //the tab complete after the "join" is just "red" (and any other created teams)
/effect give @s glowing 100 1       //You will glow red for 100 seconds. Your glowing color is bright red.

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/64995932/147021793-cc4b54f0-32d4-4156-bbfe-95d663cdaf81.png)
![image](https://user-images.githubusercontent.com/64995932/147022015-03167190-50cc-42ba-91b0-1882ff46c479.png)

**Version Info:**
 - **SkBee Version:** 1.14.0 & Some older version used for 1.16.5 (it was some time ago)
-  **Skript Version:** 2.6 & 2.5.3
 - **Server Version/Platform** Tested on Paper 1.18.1 &  Paper 1.16.5

**Additional context**
This might affect other aspects of vanilla teams, but I do not know.
I also have no skripts loaded at all, just having SkBee installed at all will affect this.

**Comment by ShaneBeee** [comment]
This is not a bug, this is just a side effect of how SkBee handles scoreboards.
Long story short, each player is given their own scoreboard, and these teams you are seeing, are made for each line of the scoreboard. (Scoreboard lines in SkBee are actually team prefixes)

That said, using the vanilla Scoreboard command will not work. If you need to, disable scoreboards in the SkBee config, and restart your server. This will put everything back to normal.
