### ISSUE TITLE
[BUG] Full Bound isnt a full bound - 1.18

### ISSUE THREAD

**Issue by RealRayli** [ShaneBeee/SkBee#123]
Hey ShaneBee,

i found a bug by creating a full bound in 1.18

If you create a full bound, its not a full. Its only from 0 up to 319. | But it should be -64 up to 319.

-> **SkBee Version:** 1.14.0
-> **Skript Version:** 2.6
-> **Server Version/Platform** Paper 1.18

Greetings and MerryChristmas,
-RealRay

**Comment by ShaneBeee** [comment]
fixed in latest update
