### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Craafter** [ShaneBeee/SkBee#124]
**Describe the solution you'd like**
I ask, if possible add a particle system (since no adodn exists for 1.17.X)

P.S: Congratulations on this addon!

**Comment by ShaneBeee** [comment]
Skbee already has a particle system

**Comment by Craafter** [comment]
> Skbee already has a particle system

Can you send me the link for the docs? I have never seen

**Comment by ShaneBeee** [comment]
The link for the docs is on the main page of this repo

**Comment by Craafter** [comment]
> The link for the docs is on the main page of this repo

Interesting! Will there be any other updates affected ?

**Comment by ShaneBeee** [comment]
What do you mean?

**Comment by Craafter** [comment]
> What do you mean?

New additions, systems (maybe GUI system)

**Comment by ShaneBeee** [comment]
No I do not plan to do a gui system.

**Comment by Craafter** [comment]
> No I do not plan to do a gui system.

Will you be able to think again (in the future)?

**Comment by ShaneBeee** [comment]
Nope.  I do not plan on doing a gui system

**Comment by Craafter** [comment]
> Nope. I do not plan on doing a gui system

I also used SkBee. Thank you!
