### ISSUE TITLE
[BUG] set tab completions to <none> variables will invalidate all tab completions

### ISSUE THREAD

**Issue by lewis252310** [ShaneBeee/SkBee#125]
**Describe the bug**
Set tab completions to `<none> variables/list variables` will invalidate all tab completions.
But only happens when it is the last sentence.
It maybe is a bug, I think.

**To Reproduce**
```
command /cmd [<text>] [<text>]:
	trigger:
		send "test cmd" to player

on skbee tab complete of "/cmd":
	set {_arg1::*} to "arg11" and "arg12"
	if player is op:
		add "urop" to {_arg1::*}
	set skbee tab completions for position 1 to {_arg1::*}
	
	if tab arg-1 is "arg11":
		set {_b1::*} to "arg21", "arg22" and "arg23"
	else if tab arg-1 is "arg12":
		set {_b1::*} to "a long long long long long text test"
	else if tab arg-1 is "urop":
		set {_b1::*} to "HI" and "operator"
	if {_b1::*} is set:
		set skbee tab completions for position 2 to {_b1::*}

	set skbee tab completions for position 3 to {_none::*}  # <-----this line
```
If `set skbee tab completions for position 3 to {_none::*}` at last, it will let all tab completions become invalidate.
But if I move it up a little...
```
command /cmd [<text>] [<text>]:
	trigger:
		send "test cmd" to player

on skbee tab complete of "/cmd":
	set {_arg1::*} to "arg11" and "arg12"
	if player is op:
		add "urop" to {_arg1::*}
	set skbee tab completions for position 1 to {_arg1::*}
	set skbee tab completions for position 3 to {_none::*}  # <-----this line
	
	if tab arg-1 is "arg11":
		set {_b1::*} to "arg21", "arg22" and "arg23"
	else if tab arg-1 is "arg12":
		set {_b1::*} to "a long long long long long text test"
	else if tab arg-1 is "urop":
		set {_b1::*} to "HI" and "operator"
	if {_b1::*} is set:
		set skbee tab completions for position 2 to {_b1::*}
```
If not enter tab arg-2, it also invalidate.
And enter tab arg-2 after, this bug will be fixed by `set skbee tab completions for position 2 to {_b1::*}`

**Expected behavior**
It maybe should be ignored or treated as not set.
Like `set skbee tab completions to ""`

**Screenshots/Errors**
![#0](https://user-images.githubusercontent.com/59472089/147895103-4fa97259-8c16-4414-ae15-d10242114318.png)

**Version Info:**
 - **SkBee Version:** 1.14.1
 - **Skript Version:** Skript-2.6
 - **Server Version/Platform** Purpur-1.18.1-1477
 - **Other Skript Addon:** SkQuery-4.1.5, skript-db-1.3.3, skript-gui-1.3-beta1, skript-yaml-1.4

**Additional context**
Thank you for making this addon, it is my favorite one.

**Comment by ShaneBeee** [comment]
Ok, so this is actually a bug with Skript. (Not sure if its truly classified as a bug, or its just a weird thing)

anyways, what is happening here... Skript has different change modes based on how you change an expression, ex: set, delete, reset, add, remove.

During the use of `set tab completions for position 1 to "blah" and "bloop"`, Skript is using change mode SET
During the use of `set tab completions for position 2 to {_emptyList::*}`, Skript oddly uses change mode DELETE

That said, setting a tab completion to an empty list, simply just deletes it. 
After a bunch of testing, I found if you set a tab complete to an empty string it works, ie:
```vb
set tab completions for position 1 to "blah" and "bloop"
set tab completions for position 2 to ""
```
This works totally fine :)

Im going to close this issue for now, as there isnt really anything I can do on my side. Maybe in the future Skript will fix this odd thing, but for now, just use an empty String.

**Comment by lewis252310** [comment]
No problem, Sir.
Glad to let you know about this problem
Hope it helps you.
Now that we know how it works, then we have a way to respond

P.S.
This is a little note for who are looking for same problems
**Need to confirm that it is not a `<none> variables/list variables` before `set tab completions`**
Like this (also I used now)
```js
if {_var::*} is set:
	set skbee tab completions for position 2 to {_var1::*}
```
Or make sure there is at least one empty string in `{_var::*}`
