### ISSUE TITLE
[SUGGESTION] Placing structures without air

### ISSUE THREAD

**Issue by aient** [ShaneBeee/SkBee#126]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Example: `place structure {_s} ignoring air at location above target block of player`

**Describe alternatives you've considered**
There are no alternatives to pasting a structure/schematic in the newer versions of minecraft/skript so I believe that SkBee can go far with using structures to do so.

**Additional context**
When placing a structure, air is included. This is not suitable for placing structures at unknown locations replacing blocks with air.
![image](https://user-images.githubusercontent.com/54190650/148267720-9d3c23fe-7d4a-4aba-93be-911a071dd97c.png)

**Comment by ShaneBeee** [comment]
Just like vanilla minecraft structures, if you want air ignored in your structure replace the air with structure voids
