### ISSUE TITLE
Custom Nbt not working properly

### ISSUE THREAD

**Issue by Ruubgaming** [ShaneBeee/SkBee#129]
**Describe the bug**
When using custom nbts they are working fine on all* blocks except shulkerboxes.

*Blocks I have tested ex: Doors, wood, grass blocks

**To Reproduce**
Putting a custom nbt on a shulkerbox:

```
set {_nbt} to nbt compound of {_block}
set {_nbt} to tag "MyWay" of {_nbt}
set {_nbt} to tag "BoxID" of {_nbt}
add "{custom:{BoxID:%{_nbt}%}}" to nbt of {_item}
```

When changing **MyWay** to **custom** it does work.

**Expected behavior**
nbt shows `{MyWay:{BoxID:%number%}}`

**Screenshots/Errors**

No errors.

**Version Info:**
 - **SkBee Version:** 1.14.2
-  **Skript Version:** Skript 2.6
 - **Server Version/Platform** git-paper-167 (1.18.1)

**Comment by ShaneBeee** [comment]
```vb
set {_nbt} to tag "MyWay" of {_nbt}
set {_nbt} to tag "BoxID" of {_nbt}
```
As stated in the wiki, when using custom NBT on entities and blocks, it has to be in the "custom" tag of said entity or block.

ex:
```vb
set {_n} to nbt of block
set tag "custom;MyWay" of {_n} to "blah"
```
