### ISSUE TITLE
Custom player head on Skript GUI

### ISSUE THREAD

**Issue by xFreakss** [ShaneBeee/SkBee#131]
How can i use SkBee to place a custom player head from minecraft-heads.com inside a GUI made with Skript and SkQuery?

I tried:

make gui slot 0 of player with player head with custom nbt "{SkullOwner:{Id:""91a87f07-e075-4b85-b99a-3b0e8a0e5e32"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDI2MTFhNjlhZjRmZDhhZDVlNmE0ZjYzMWUzMGJlOTk5MzJlMmEyMmU0ZTEwNTA2YmVhNjg0YmU2NDhlNjM0In19fQ==""}]}}}" named "&8 " with lore "" to do nothing

Im using Purpur-1521
With Skript 2.6
With SkBee 1.14.2
With SkQuery 4.1.5
With SkRayFall+v1.9.26

**Comment by ShaneBeee** [comment]
Here is the wiki for nbt heads 
ps://github.com/ShaneBeee/SkBee/wiki/NBT-Heads

**Comment by xFreakss** [comment]
I saw it but i wont figure how to make it work on my script
