### ISSUE TITLE
[SUGGESTION] all bounds 

### ISSUE THREAD

**Issue by MrScopes** [ShaneBeee/SkBee#132]
**Is your feature request related to a problem? Please describe.**
Not really, just think it could be a nice addition.

**Describe the solution you'd like**
an `all bounds` expression, loopable of course

**Describe alternatives you've considered**
Skript-reflect
![image](https://user-images.githubusercontent.com/29683770/151489789-f06c3ef8-f531-4836-bfa8-634f337638ea.png)

**Comment by drewtadlock** [comment]
loop-bound would be cool

**Comment by MrScopes** [comment]
loop-bound would be cool

**Comment by ShaneBeee** [comment]
Ill work on adding an all bounds expression.
also, loop-bound would be automatically done when looping all bounds

**Comment by ShaneBeee** [comment]
Added in 1.15.0
