### ISSUE TITLE
[BUG] Lots of Minecraft Tags don't work

### ISSUE THREAD

**Issue by EarthAgar** [ShaneBeee/SkBee#134]
**Describe the bug**
There are a lot of Minecraft Item Tags from [here](https://minecraft.fandom.com/wiki/Tag#Item_tags) that don't return any items.

**To Reproduce**
```
function bs():
    set {_a} to material choice of minecraft tag "crops"
    broadcast "%{_a}%"
```

**Expected behavior**
I should be given the following items for the `#crop` tag: `beetroots, carrots, potatoes, wheat, melon_stem, pumpkin_stem`

**Screenshots/Errors**
Whats given with the above code: 
![image](https://user-images.githubusercontent.com/27425322/153480247-f7bb8d23-d9a2-4515-ab03-a4d62a7c3eca.png)

**Version Info:**
 - **SkBee Version:** 1.15.0
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** git-Paper-187

**Comment by ShaneBeee** [comment]
This tag specially is a BLOCK tag. Minecraft/Bukkit has some tags that are item or block specific.
If the way you written it doesn't work, you'll have to do
`set {_a} to material choice of minecraft block tag "crops"`

Why they set it up like this, I dunno. But thats just how it works
