### ISSUE TITLE
Regarding new scoreboard condition

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#138]
It is totally QoL feature. It will make Skript less suffer.

I think there is should be new expressoin syntax to check content of scoreboard value, like: `line %integer% of %players%'s scoreboard`

Few usage examples in my dream:
```
if line 3 of player's scoreboard is "test":
	send "yes!"
```

**Comment by ShaneBeee** [comment]
I will look into adding this soon, should be an easy change
