### ISSUE TITLE
[SUGGESTION] ' instead of " for nbt

### ISSUE THREAD

**Issue by MrScopes** [ShaneBeee/SkBee#139]
**Is your feature request related to a problem? Please describe.**
Doubling quotes each time is atrocious in nbt

**Describe the solution you'd like**
Allow for \`, ', ~ or some character for nbt\
`diamond sword with nbt '{Damage:1}'`

**Describe alternatives you've considered**
Doubling quotes

**Comment by MrScopes** [comment]
another approach to this could be using regex for a custom string to only end at the end of the text

**Comment by ShaneBeee** [comment]
I dont think this is something I would do, a few reason:
a) this doesn't really follow the standards of Skript and patterns, for example, the pattern for something like this would have to be `%item type% with nbt '(regex pattern)'`, this in itself wont show nicely in the docs, and will be extremely confusing for people new to this
b) I would have to create 2 different expressions (well actually, 2 patterns for one expression), to make sure the old string version works. This in itself can generally get messy. 
c) regex stuff like this in patterns tends to take a long time to parse. And with MC NBT having a similar pattern as variables (both containing brackets), this will make it extra hard on the parser
d) I have a future plan to remove stringified versions of NBT, which would be replaced by nbt compounds (which are already in plan)

At the end of the day, I don't see this being something most people would find useful. It seems like a ton of work on my side, simply so people can manage double quotes (which in itself is super simple to do, copy your nbt string to another editor, replace all quotes with double quotes, copy back to your script file)
