### ISSUE TITLE
Console Spam on nbt add

### ISSUE THREAD

**Issue by Emrolehero** [ShaneBeee/SkBee#14]
My server version: Spigot 1.15.2
I use SkBee 1.3.0
Latest version of Skript
The code:
on steering vehicle right:
	if player's vehicle is {proprio::%player%}:
		set {_yaw} to yaw of player's vehicle + 5
		add "{Rotation:[0f,%{_yaw}%f,0f]}}" to nbt of {proprio::%player%}
And that code spam me that in the console: https://pastebin.com/ERDr5ui1
Please help !

**Comment by Emrolehero** [comment]
The code is working, there is no problem expect the spam in console Idk why, it talks about threads, maybe add cooldown for nbt stuff adding with skbee like skstuff, I think they had a cooldown for that

**Comment by ShaneBeee** [comment]
`me.limeglass.skacket.listeners.PacketListeners$1` 
Well, seems like the issue is coming from another add-on

**Comment by Emrolehero** [comment]
Hum, yeah the event "on steering vehicle right:" is from Skacket plugin, but it can't be compounds between this plugin and skbee, I don't have another plugin to modify nbt, so the expression can only be used by skbee... :/
The current item is: add "{Pose:{Head:[0f,30f,0f]}}" to the object nbt of {proprio::%the player%}(as java.lang.Object)
Skacket is only here for packets, I will try to disable packet listener on his config...

**Comment by Emrolehero** [comment]
Oh I can't disable it... Are you sure the error is not from skbee because it’s an event that repeats itself very quickly, it can maybe create compounds.

**Comment by Emrolehero** [comment]
And above all how to solve this problem?

**Comment by Emrolehero** [comment]
I tried to replace the event:
on chat:
	if player's vehicle is {proprio::%player%}:
		add "{Rotation:[%yaw of player's vehicle + 5%f,0.0f]}" to nbt of {proprio::%player%}

And yes it's working and there is not errors in console, but i need to use vehicle steer event

**Comment by Emrolehero** [comment]
I will contact limeglass

**Comment by ShaneBeee** [comment]
I mixed your messages together, there is no need to spam reply to this issue. 
I get emails for every reply, and I don't feel like getting emails every 10 seconds when you need to respond.

As for your issue, I already stated your NBT string is most likely invalid, since that IS what the error says.

**Comment by TheLimeGlass** [comment]
> 
> 
> `me.limeglass.skacket.listeners.PacketListeners$1`
> Well, seems like the issue is coming from another add-on
> 
> `tk.shanebee.bee.api.NBT.NbtApiException: Exception while merging two NBTCompounds!`
> There seems to also be an issue merging two compounds.
This is your addon's error not mine. This user contacted me. Skacket is reading the packet incoming from the event.

**Comment by ShaneBeee** [comment]
So looking further at the error, this is the relevant issue:
```
Caused by: tk.shanebee.bee.api.NBT.NbtApiException: Exception while setting the NBTCompound of an Entity
```
This is actually coming from the NBT-API I use, and I have no control over that. 
Ultimately, the issue I'm assuming is the NBT itself possibly not being correct.

**Comment by Emrolehero** [comment]
I already tested with another nbts like {Small:1b}, same error: https://pastebin.com/qSHBi0WU
The code:
on steering vehicle right:
	if player's vehicle is {proprio::%player%}:
		add "{Small:1b}" to nbt of {proprio::%player%}

Or with invisible nbt: https://pastebin.com/kgzkBa9m same error :/

on steering vehicle right:
	if player's vehicle is {proprio::%player%}:
		add "{Invisible:1}" to nbt of {proprio::%player%}

The nbt are working perfectly, but the console spam that error.
The nbts are correct, I really don't know why it's give me errors, maybe try to install skacket and try the code in your own server, it will give you errors too. However, this give me error only with skacket steer events, not with Misk steer events, but I really want to use Skacket because Misk is discontinued and have a lot of bugs.

**Comment by ShaneBeee** [comment]
Hmm I'm not sure what to tell ya.
The last 2 errors you sent don't even look like SkBee errors, but Sk-NBeeT errors.

But as you stated these errors only happen when using Skacket.
Me installing that add-on is going to do nothing. My addon directly works with NBT-API and I have no control over how it handles NBT, and if for some reason its not working with Skacket theres absolutely nothing I can do.

**Comment by Emrolehero** [comment]
Yeah, I tried with Sk-NBeeT too, it gives me same error.
I want to try last thing with the "that packet addon", can you give me the vehicle steer packet from protocollib in order to replace the steer event from skacket.

**Comment by ShaneBeee** [comment]
Glad to see you got it working :)
And thank you 👍
