### ISSUE TITLE
[SUGGESTION] play animations on entities

### ISSUE THREAD

**Issue by UsainSrht** [ShaneBeee/SkBee#142]
Setting entities animation is not easy so why not skbee makes it easy?

Basically, an effect that plays animation on entities. 
```
play %animation% on %entities%
play (cast spell) on (all evokers in radius 5 of player)
play (spin attack) on player #riptide with trident 
```

The reason why I want this feture added to skbee is skbee has chest animation effects. :P

**Comment by ShaneBeee** [comment]
Im curious which animations you are referring to?
Like, are you referring to Bukkit's [ENTITY EFFECT](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/EntityEffect.html)s?

**Comment by UsainSrht** [comment]
> Im curious which animations you are referring to? Like, are you referring to Bukkit's [ENTITY EFFECT](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/EntityEffect.html)s?

That is already possible with vanilla skript's visual effects.
I'm mentioning about animations like evoker casting spell, skeleton stretching bow, player using riptide.

**Comment by ShaneBeee** [comment]
When I have some time, I will take a look at what API is available for different entities.
