### ISSUE TITLE
[BUG] Custom nbt problem

### ISSUE THREAD

**Issue by UsainSrht** [ShaneBeee/SkBee#143]
I've made a custom enchantments skript with usage of skbee's custom nbts. And when I gave myself a new enchantment book with custom nbt its setting other custom books in my inventory.

**To Reproduce**
```
command /nbtbug:
    trigger:
        nbtbug(player)
function nbtbug(p: player):
    create gui with virtual chest inventory named "nbtbug":
        make gui slot (0) with (stone):
            nbtbuglevel({_p}, "stone")
        make gui slot (1) with (diamond):
            nbtbuglevel({_p}, "stone")
        make gui slot (2) with (grass block):
            nbtbuglevel({_p}, "stone")
    open (last gui) to {_p}
function nbtbuglevel(p: player, id: string):
    create gui with virtual chest inventory named "nbtbug %{_id}%":
        loop 3 times:
            set {_lvl} to loop-number
            make gui slot (loop-number - 1) with ({_id} parsed as itemtype):
                give (((enchanted book) with nbt "{custom:{id:""%{_id}%"",lvl:%{_lvl}%}}")) to {_p}
        make gui slot (8) with ((arrow) named "back"):
            nbtbug({_p})
    open (last gui) to {_p}
```
1 /nbtbug
2 select stone
3 select 3rd stone
4 back
5 select diamond
6 select 2nd diamond
7 back
8 select grass
9 select 1st grass
10 hold the stone
11 run `!send nbt of tool`
12 hold diamond
13 run `!send nbt of tool`
14 hold grass
15 run `!send nbt of tool`

**Expected behavior**
No broken nbts

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/59025999/158050946-0e86fb98-0e9b-46e8-bf7e-3d16e3decc2f.png)

**Version Info:**
 - **SkBee Version:** 1.15.1
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** 1.18.2

**Additional context**
I've tested this with those methods as well
- giving books with effect commands (didn't break nbts)
- onyl one gui (no cross gruis) (didn't break nbts)
It doesn't rename the books' names but changes id and lvl nbt tags.

**Comment by ShaneBeee** [comment]
Can you please test this without Skript-GUI

I downloaded Skript-GUI and followed your test, and yes it is somehow modifying the other items. This shouldn't happen.

When I did a test without GUIs, that kind of mimics what you're doing, it wasnt modifying the items
test: 
```vb
command /test:
	trigger:
		give player an enchanted book with nbt "{custom:{id:""stone"",lvl:1}}"
		wait 1 second
		give player an enchanted book with nbt "{custom:{id:""diamond"",lvl:2}}"
		wait 1 second
		give player an enchanted book with nbt "{custom:{id:""grass block"",lvl:3}}"
```

Outcome:
<img width="966" alt="Screen Shot 2022-03-22 at 9 09 35 AM" src="https://user-images.githubusercontent.com/20008482/159527053-24306d6c-ce76-417e-a310-e64a1ab2eb5f.png">

My guess is somehow the GUI is interfering and modifying other items, im really not sure how. But testing without a gui, it works as expected

**Comment by UsainSrht** [comment]
I tested without skript-gui (started server without it) and used vanilla gui. The results are same. 

```
command /nbtbugvanilla:
    trigger:
        nbtbugvanilla(player)
function nbtbugvanilla(p: player):
    set {_g} to a new chest inventory named "nbtbug"
    set slot 0 of {_g} to stone
    set slot 1 of {_g} to diamond
    set slot 2 of {_g} to grass block
    open {_g} to {_p}
function nbtbugvanillalevel(p: player, id: string):
    set {_g} to a new chest inventory named "nbtbug %{_id}%"
    loop 3 times:
        set slot (loop-number - 1) of {_g} to ({_id} parsed as itemtype)
    set slot (8) of {_g} to ((arrow) named "back")
    open {_g} to {_p}

on inventory click:
    if (name of event-inventory) = "nbtbug":
        cancel event
        nbtbugvanillalevel(player, "%plain event-slot%")
    else if (name of event-inventory) contains "nbtbug":
        cancel event
        set {_id} to substring of (name of event-inventory) from 8 to (length of (name of event-inventory))
        if (index of event-slot) = 0, 1 or 2:
            give (((enchanted book) with nbt "{custom:{id:""%{_id}%"",lvl:%index of event-slot + 1%}}")) to player
        else if (index of event-slot) = 8:
            nbtbugvanilla(player)
```

**Comment by UsainSrht** [comment]
I think this is a SkBee issue cuz this code breaks nbts too
```
command /nbtbugs:
    trigger:
        loop 3 times:
            set {_id} to (random element out of ("stone", "diamond" and "grass"))
            give (((enchanted book) with nbt "{custom:{id:""%{_id}%"",lvl:%loop-number%}}")) to player
```

**Comment by UsainSrht** [comment]
@ShaneBeee Did you see my last replies?

**Comment by ShaneBeee** [comment]
yes I did see your reply. I haven't taken a look yet. Just got a new computer a short bit ago, so slowly working on setting everything up.
Im truly confused how NBT could be doing this. It seems odd how it could be manipulating another item.
When I have more time Ill take a closer look and see if its something I can even fix

**Comment by ShaneBeee** [comment]
ok, I've done a bunch of testing, and im completely baffled.
This literally makes no sense.
I don't see how SkBee could be doing this. It appears at some point the NBT of the previous item is getting manipulated.

This could potentially be an issue in Skript or even in the server software itself.
Its almost like Skript isn't giving a new item. 

I literally have no clue what could possibly be done to fix this

**Comment by UsainSrht** [comment]
> ok, I've done a bunch of testing, and im completely baffled. This literally makes no sense. I don't see how SkBee could be doing this. It appears at some point the NBT of the previous item is getting manipulated.
> 
> This could potentially be an issue in Skript or even in the server software itself. Its almost like Skript isn't giving a new item.
> 
> I literally have no clue what could possibly be done to fix this
> 
> Im marking this as a non SkBee issue, as I really don't think its an issue with SkBee

Alright, thank you for you effort. I'll contact with paper. And try to reproduce this issue on other server softwares. Have a good day best skript addon developer.
