### ISSUE TITLE
[BUG] World change causes pathfind to break

### ISSUE THREAD

**Issue by tacticalNukes** [ShaneBeee/SkBee#148]
So for example if I got
```
while {_ent} is alive:
    if {_p}'s world is not {_ent}'s world:
         teleport {_ent} to {_p}
    set path target of {_ent} to location at {_p}
    wait 10 ticks
```

If I would change world for example the entity would get teleported to me, but it stops finding me as a path target.
I've tested and it's still running the loop but it just stops walking after me

**Version Info:**
 - **SkBee Version:** 1.15.0
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** paper-408 (1.17.1)

**Comment by ShaneBeee** [comment]
Ok after doing some testing, I found that yes, the entity stops pathfinding after moving to another world.
But I then did some testing with Skript-reflect and noticed this isn't actually a bug with SkBee, unfortunately this seems to be an issue with Paper, and this isn't something I am able to fix.
