### ISSUE TITLE
Custom Crafting Recipe error

### ISSUE THREAD

**Issue by Ch3wzz** [ShaneBeee/SkBee#150]
I tried doing
 `on load:	
register new shaped recipe for 4 string using white wool, air, air, air, air, air, air, air and air`
![image](https://user-images.githubusercontent.com/93747561/160946649-0a485843-6505-4dea-bf4f-e31784f6f77b.png)
![image](https://user-images.githubusercontent.com/93747561/160946717-61f3f781-1d4b-4267-9380-de96844831fb.png)
![image](https://user-images.githubusercontent.com/93747561/160946746-8ff0a879-7305-476f-8118-28afaf0326bd.png)
![image](https://user-images.githubusercontent.com/93747561/160946763-af469554-5507-442a-9976-0b90e7ce81ea.png)

**Comment by ShaneBeee** [comment]
1) That line of code isnt even SkBee code
2) that error is caused by Skellett

Nothing here has anything to do with SkBee
