### ISSUE TITLE
Tab Complete message argument.

### ISSUE THREAD

**Issue by Varatros** [ShaneBeee/SkBee#153]
Is there a way to add the \<message> tab complete used in commands like /tell to SkBee tab complete?

![image](https://user-images.githubusercontent.com/66185110/161862920-fab016ee-1c2e-499b-920b-edbe41f5a320.png)

I'm creating a Skript which allows users to input a custom name and knowing if this is something I can create in Skript would be nice.

**Comment by ShaneBeee** [comment]
I don't quite understand the question here, but this issue tracker is for issues and suggestions, not for general questions on how to use SkBee.
If you need help using SkBee, please join the skUnity, where you can find 100s of people to help you solve your problem.

**Comment by Varatros** [comment]
I was referring to how if you type a command that accepts a message as it's argument, like /tell or /say, it puts <message> as the tab complete argument like in the picture I sent. I looked in the docs and couldn't find anything showing how to do this, but I'll make a post in skUnity asking how I should. Thanks!
