### ISSUE TITLE
[BUG]Unable to create Books with pages

### ISSUE THREAD

**Issue by phillysports2** [ShaneBeee/SkBee#154]
Trying to create a book with custom text does not work and scripts will not allow the command with the code to add stuff to pages

https://prnt.sc/nK6jGbFphBnF

to add the text to  the said pages

https://prnt.sc/V1lYGGF31d9d
https://prnt.sc/dC0rildUEz8j
https://prnt.sc/nK6jGbFphBnF
https://prnt.sc/EKr5ZRdwsq5K

**Version Info:**
 - 1.15.2
-  2.6.1
 - Paper 1.18.2

I've tried having the underscore(_) in the variable as well!

**Comment by UsainSrht** [comment]
Here's a working example
```
set {_i} to a written book
set {_nl} to text component of newline
set {_pmc} to text component of "&dsome text"
set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
open book {_i} to {_p} #or give {_i} to {_p}
```

**Comment by phillysports2** [comment]
> Here's a working example
> 
> ```
> set {_i} to a written book
> set {_nl} to text component of newline
> set {_pmc} to text component of "&dsome text"
> set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
> open book {_i} to {_p} #or give {_i} to {_p}
> ```

still doesnt work.

**Comment by phillysports2** [comment]
> I'm using SkBee 1.15.2, Skript 2.6.1 and Purpur 1.18.2 and it's working for me. Are you getting any console error or smth?

nope it just doesnt give or open the book

**Comment by UsainSrht** [comment]
> set {_i} to a written book
> set {_nl} to text component of newline
> set {_pmc} to text component of "&dsome text"
> set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
> open book {_i} to {_p} #or give {_i} to {_p}

Make sure you set title and author of book as well as {_p} is player

**Comment by phillysports2** [comment]
> > set {_i} to a written book
> > set {_nl} to text component of newline
> > set {_pmc} to text component of "&dsome text"
> > set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
> > open book {_i} to {_p} #or give {_i} to {_p}
> 
> Make sure you set title and author of book as well as {_p} is player

still have the invalid book tag text (https://prnt.sc/Z6uhidKXV_ie)

**Comment by UsainSrht** [comment]
I'm using this code
```
function book(p: player, give: boolean):
    set {_i} to a written book
    set {_nl} to text component of newline
    set {_pmc} to text component of "&dsome text"
    set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
    set book author of {_i} to "author"
    set book title of {_i} to "title"
    if {_give} = false:
        open book {_i} to {_p}
    else:
        give {_i} to {_p}
```
You can test this.

**Comment by phillysports2** [comment]
`command /bookster:
	trigger:
		set {_i} to a written book
		set {_nl} to text component of newline
		set {_pmc} to text component of "&dsome text"
		set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
		set book author of {_book} to "Mickey Mouse"
		set book title of {_book} to "&b&lDeath &b&lCoordinates!"
		give {_i} to player
`
its meant to be a death coords book but im using the command to test it

**Comment by phillysports2** [comment]
> I'm using this code
> 
> ```
> function book(p: player, give: boolean):
>     set {_i} to a written book
>     set {_nl} to text component of newline
>     set {_pmc} to text component of "&dsome text"
>     set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
>     set book author of {_i} to "author"
>     set book title of {_i} to "title"
>     if {_give} = false:
>         open book {_i} to {_p}
>     else:
>         give {_i} to {_p}
> ```
> 
> You can test this.

```command /bookster:
	trigger:
		set {_i} to a written book
		set {_nl} to text component of newline
		set {_pmc} to text component of "&dsome text"
		set (page 1 of book {_i}) to {_pmc}, {_nl}, {_pmc}
		set book author of {_book} to "Mickey Mouse"
		set book title of {_book} to "&b&lDeath &b&lCoordinates!"
		give {_i} to player```
		
just testing with the command but how would i even give myself that book with your code

**Comment by UsainSrht** [comment]
> give {_i} to player

Isn't this gives you book?

**Comment by phillysports2** [comment]
> > give {_i} to player
> 
> Isn't this gives you book?

theres nothing telling it to start the code to give me the book nothing happens when i reload the skript either

**Comment by UsainSrht** [comment]
put this inside trigger section `book(player, false)`

**Comment by phillysports2** [comment]
https://prnt.sc/3-yP6J2Yb2rF

**Comment by phillysports2** [comment]
> > https://prnt.sc/3-yP6J2Yb2rF
> 
> I said put it in trigger section. You should put the function code to your code and make a command that triggers `book(player, false)`

so that works but now how would i get it to be a death book when someone dies it puts all the info into the book and when they respawn it gives the book cause my code breaks it all

**Comment by UsainSrht** [comment]
> > > https://prnt.sc/3-yP6J2Yb2rF
> > 
> > 
> > I said put it in trigger section. You should put the function code to your code and make a command that triggers `book(player, false)`
> 
> so that works but now how would i get it to be a death book when someone dies it puts all the info into the book and when they respawn it gives the book cause my code breaks it all

This is not a place for asking skript related questions. Go to skunity discord or somewhere else.

**Comment by phillysports2** [comment]
shocker

**Comment by ShaneBeee** [comment]
closing this as the issue was solved
