### ISSUE TITLE
[BUG] Can't set compound list tag of %item% to list

### ISSUE THREAD

**Issue by erenkarakal** [ShaneBeee/SkBee#156]
**Describe the bug**
When trying to set the compound list tag of an item to an nbt list, It throws a bound error.

**To Reproduce**
```
    set compound list tag "BlockEntityTag;Items" of nbt of player's tool to {_nbt::*}
    # {_nbt::*} being:
    # {Count:1b,Slot:1b,id:"minecraft:stone"}
    # {Count:1b,Slot:16b,id:"minecraft:diorite"}
```

**Expected behavior**
Set the NBT to list

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/67760502/162992868-84457f0f-7928-4eff-a15a-f0f96986a744.png)

**Version Info:**
Skript 2.6.1
SkBee 1.15.2
Paper 1.18.2

**Comment by ShaneBeee** [comment]
as per docs:
"As of 1.10.0 you can get/set specific tag types of NBT compounds, allowing for more detailed control of what type your tag is going to be."

You can only set tag types for NBT compounds, not just the NBT of an item
