### ISSUE TITLE
[SUGGESTION] Add a skript version of "getStoredEnchantLevel()"

### ISSUE THREAD

**Issue by Dago-Duck** [ShaneBeee/SkBee#157]
**Is your feature request related to a problem? Please describe.**
I recently tried to get the level of an enchantment stored in an enchanted book. According to the Skript Hub documentation, it's not really possible to just get the level of a predefined enchantment.

**Describe the solution you'd like**
When getting all stored enchantments from a book, I assume it calls the "getStoredEnchants()" method, also including "getStoredEnchantLevel(Enchantment)" would [at least to my knowledge] fill the last gap regarding stored enchantments. 

**Describe alternatives you've considered**
This is somewhat possible by setting a list to the stored enchantments, but that'll include the enchantment type as well. Of course, this could be then put into a text, remove all spaces and letters, and parse the leftover number as an integer, but it's a bunch of extra steps. 

**Additional context**
The final thing I'd like to create is a way for players to go beyond the minecraft default levels of enchantments, such as sharpness 10, quick charge 4 or looting 5.

Thanks for your work, Shane!
Also, if this is already possible, would you mind "updating" the examples given on Skript Hub?

**Comment by ShaneBeee** [comment]
I ended up doing this a little differently.
To make it more universal, I added 2 new expressions, 1 to get the level of an enchantment type, and another to get the enchantment of an enchantment type

**Comment by Dago-Duck** [comment]
That's even better. Thanks a lot for adding this to SkBee!
