### ISSUE TITLE
[BUG] Using path finding to location of player causes the server to crash.

### ISSUE THREAD

**Issue by MrZomka** [ShaneBeee/SkBee#161]
**Describe the bug**
Using path finding to location of player  causes the server to crash.

**To Reproduce**
Use Paper or Purpur 1.18.2, Skript 2.6.1 and SkBee 1.15.2
Then the following Skript:
`command /pet:
  trigger:
    spawn cow at location of player
    set {_cow} to last spawned cow
    while {_cow} exists:
      set path target with speed 1.3 of {_cow} to player`

**Expected behavior**
The spawned cow should follow the player.

**Screenshots/Errors**
https://paste.gg/p/anonymous/58f96296bb1c47da8fb403e231131d18

**Version Info:**
 - **SkBee Version:** 1.15.2
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** Paper 1.18.2 and Purpur 1.18.2

**Additional context**

**Comment by zimzaza4** [comment]
Ummm
try add `wait 5 tick`?

**Comment by MrZomka** [comment]
Ah! Thank you! It worked! :)
Also, it's great to see you here, I love your work on the CustomModelData support for Geyser haha!
