### ISSUE TITLE
[BUG] Cant use virtual furnace's

### ISSUE THREAD

**Issue by gagsabg** [ShaneBeee/SkBee#165]
Why cant i use the virtual furnaces, cant use this "give player a virtual furnace item as diamond named "MyFurnace" with gui name "PORTABLE FURNACE" with cook speed multiplier 1.5" it give me error "Can't understand this condition/effect: give player a virtual furnace item as diamond named "MyFurnace" with gui name "PORTABLE FURNACE" with cook speed multiplier 1.5"
And please can u give me more examples about nbt compound and more
I m russian and wanna teach this beautiful

**Comment by ShaneBeee** [comment]
This is an issue tracker. 
If you have an issue, please report it here
But if you are just looking for help on how to use SkBee, please check out skUnity's discord, there are plenty of people there who use SkBee and can help you
