### ISSUE TITLE
[BUG] Resource Pack Translations don't work.

### ISSUE THREAD

**Issue by IllagerCaptain** [ShaneBeee/SkBee#168]
**Describe the bug**
Translations added by resource packs display the raw string.

**To Reproduce**
Activate a resource pack with a custom string added to a language file (Ex. `en_us.json`), then send a translated message using it via SkBee.

**Expected behavior**
It would send the custom translated message.

**Version Info:**
 - **SkBee Version:** 1.15.3
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** Purpur 1.18.2

**Comment by ShaneBeee** [comment]
are you sending this message to the server or the client?

**Comment by IllagerCaptain** [comment]
> Just to check, is this something Minecraft even allows? SkBee just links into Spigot/Bukkit's API for translations so I don't think there would be much I could do about it here.

Yes it is, I've done it using commands in vanilla.

**Comment by IllagerCaptain** [comment]
Might need to use NMS or whatever it's called.

**Comment by ShaneBeee** [comment]
Due to the major differences between Bukkit API and NMS, its not something I can easily change over.
It would involve me re-writing a good chunk of my code for text components.

That said, I don't have a resource pack with a lang file, so I won't really have anything to test with and/or reproduce the error.
If you are willing to send over your pack, I can try to do some testing, and see specifically if this is an SkBee issue, or a Bukkit/Spigot issue.

**Comment by ShaneBeee** [comment]
Okay I threw a lang file into a resource pack I was using.

Outcome:

<img width="1080" alt="Screen Shot 2022-05-13 at 10 13 58 AM" src="https://user-images.githubusercontent.com/20008482/168334634-31adcf61-3018-44ab-b398-d91dfd39894f.png">

**Comment by IllagerCaptain** [comment]
> Okay I threw a lang file into a resource pack I was using.
> 
> Outcome:
> 
> <img alt="Screen Shot 2022-05-13 at 10 13 58 AM" width="1080" src="https://user-images.githubusercontent.com/20008482/168334634-31adcf61-3018-44ab-b398-d91dfd39894f.png">

Try under a namespace other than `minecraft`, that's what I was doing.

**Comment by ShaneBeee** [comment]
same outcome for me

**Comment by IllagerCaptain** [comment]
> same outcome for me

Are you on Purpur server software?

**Comment by ShaneBeee** [comment]
no Im on paper

**Comment by IllagerCaptain** [comment]
Could be a Purpur issue?

**Comment by ShaneBeee** [comment]
possibly

**Comment by IllagerCaptain** [comment]
I'm not home, could you reproduce this outcome on Purpur 1.18.2? (https://api.purpurmc.org/v2/purpur/1.18.2/latest/download)

**Comment by IllagerCaptain** [comment]
If the bug affects Purpur 1.18.2 then I'll make a bug report there.

**Comment by ShaneBeee** [comment]
Sorry but I have no desire to test other server software.
Seeing that it works on Paper, and I can not reproduce this issue, tells me this is not an SkBee issue

**Comment by IllagerCaptain** [comment]
Okay, thanks anyways.

**Comment by IllagerCaptain** [comment]
I'll test it in my own time on a Purpur server with only SkBee and report it to Purpur if applicable.

**Comment by IllagerCaptain** [comment]
@ShaneBeee this _is_ an SkBee issue, its just the formatting. See #170.
