### ISSUE TITLE
[BUG] Resource pack translations don't work under certain conditions.

### ISSUE THREAD

**Issue by IllagerCaptain** [ShaneBeee/SkBee#170]
**Describe the bug**
Depending on the way you formatted the effect, resource pack translations may or may not work

**To Reproduce**
See below image.

**Expected behavior**
No matter the formatting of the effect, it should work.

**Screenshots/Errors**
![2022-05-16_14 30 01](https://user-images.githubusercontent.com/76600137/168668243-4bcbfd79-8510-4d7c-a677-f68c1aa66a24.png)

**Version Info:**
 - **SkBee Version:** 1.15.3
-  **Skript Version:** 2.6.1
 - **Server Version/Platform** Paper 1.18.2

**Additional context**
Discovered whilst testing #168

**More information found:**
Apparently it works for the SkBee send component effect but not by other means that were sent using the expression.

**Comment by IllagerCaptain** [comment]
> `send` is a Skript effect for sending objects, because I cannot manipulate the Skript effect, long story short, SkBee basically does `component.toString()` here. So it'll send whatever the server would find in the toString method of the component.
> 
> `send component` is an SkBee effect, for sending components
> 
> I see no issue here

Then why does it work with vanilla translations?

**Comment by ShaneBeee** [comment]
Because vanilla translations are also stored in the server software.

**Comment by IllagerCaptain** [comment]
> Because vanilla translations are also stored in the server software.

Makes sense I guess, I have a purposed solution at #171 that would help with my problem.
