### ISSUE TITLE
[SUGGESTION] Component versions of all skript effects/expressions/etc that use text

### ISSUE THREAD

**Issue by IllagerCaptain** [ShaneBeee/SkBee#171]
**Is your feature request related to a problem? Please describe.**
I want to make stuff work with custom translations, but Skript does not support it and SkBee only supports some things.

**Describe the solution you'd like**
All Skript effects, etc, that include text in the syntax to have a SkBee varient that uses text components.

**Describe alternatives you've considered**
If that isn't plausible, then maybe for some things, specifically UI names (Ex. Chest UIs) and death messages.

**Comment by UsainSrht** [comment]
Uhm, spigot only supports text when you want to change death message [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/PlayerDeathEvent.html#setDeathMessage(java.lang.String)). 
And SkBee's components are md_5 text components. So you can't use them together.
If you are using paper or paper forks you can use MiniMessage components [here](https://jd.papermc.io/paper/1.18/org/bukkit/event/entity/PlayerDeathEvent.html#deathMessage(net.kyori.adventure.text.Component)).

**Comment by ShaneBeee** [comment]
I don't plan on using Paper's AdventureAPI for text components. 
This is mainly due to it wouldn't work on Spigot, and to make it work on Spigot I would have to use two completely different APIs, which I don't want to do, nor do I want to have to re-write the whole component system.
Maybe in the future if Skript supports Paper only, and drops Spigot support, but until then I want to keep offering Spigot support

**Comment by UsainSrht** [comment]
> I don't plan on using Paper's AdventureAPI for text components. This is mainly due to it wouldn't work on Spigot, and to make it work on Spigot I would have to use two completely different APIs, which I don't want to do, nor do I want to have to re-write the whole component system. Maybe in the future if Skript supports Paper only, and drops Spigot support, but until then I want to keep offering Spigot support

Shane can you share a statistic that shows server softwares of servers that using skbee?

**Comment by ShaneBeee** [comment]
Paper is definitely the winner here, and I know that
<https://bstats.org/plugin/bukkit/SkBee/6719#serverSoftware>

The main issue is Paper's AdventureAPI is vastly different that Spigot/Bungee's component API. 
That said, currently I do not wish to have to re-write my code to work with AdventureAPI.

Right now SkBee's component system works very well for most people. While I do understand Spigot's API is missing a LOT of things that components work with, therefor SkBee is missing them as well, I feel that the majority of SkBee/Skript users, probably wouldn't use those things. 

Maybe in the future, once I have spent some time checking out AdventureAPI, I will consider re-writing it, but it won't be happening anytime soon.

**Comment by UsainSrht** [comment]
Are ya open for some prs?

**Comment by ShaneBeee** [comment]
I am, but its something I will have to heavily review. 
It worries me having code in my own plugin that I don't understand, because if there is an issue, I wouldn't be able to fix it.

**Comment by IllagerCaptain** [comment]
> Maybe in the future, once I have spent some time checking out AdventureAPI, I will consider re-writing it, but it won't be happening anytime soon.

You could make the feature check if you have Paper and only allow it if so. If the server is using Spigot, you could make it send a warning on reload like "This effect requires Paper. Ignoring." or something along those lines.

**Comment by ShaneBeee** [comment]
> > Maybe in the future, once I have spent some time checking out AdventureAPI, I will consider re-writing it, but it won't be happening anytime soon.
> 
> You could make the feature check if you have Paper and only allow it if so. If the server is using Spigot, you could make it send a warning on reload like "This effect requires Paper. Ignoring." or something along those lines.

that's not the issue here. The issue would be having to re-write all the current stuff using AdventureAPI as well as using Spigot/Bungee API so it works on Spigot. 
I haven't worked with AdventureAPI yet. The little bit I have fiddled around with it, its such a freaking mess (not that bungee is any better), and it just turned me off.

So like I said, maybe in the future I'll check it out, but its super low priority for me right now.
