### ISSUE TITLE
[BUG] Issue modifying NBT Compound

### ISSUE THREAD

**Issue by RedPxnda** [ShaneBeee/SkBee#172]
**Describe the bug**
When trying to edit an entity's NBT Compound, I get thrown a massive error.

**To Reproduce**
Edit the nbt compound of an entity.

**Expected behavior**
NBT Compound should be edited

**Screenshots/Errors**
  **Code:**
        set {_nbt} to nbt compound of player's vehicle
        set {_pose} to 0.0
        set tag "Pose;Head" of {_nbt} to {_pose}
  **Error: [https://pastebin.com/b5mppnhr](https://pastebin.com/b5mppnhr)**
**Version Info:**
 - **SkBee Version:** (ex: 1.15.2)
-  **Skript Version:** (ex: Skript 2.6.1)
 - **Server Version/Platform** (ex: PaperSpigot 1.18.2)

**Comment by ShaneBeee** [comment]
I'll have to suppress the error.
My guess is its coming from the fact that you're trying to set the "Head" value to a single number, when the head value of an armor stand (assuming that's what you're using) is actually a list of 3 numbers, this can be seen here:

<img width="1392" alt="Screen Shot 2022-05-17 at 5 45 27 PM" src="https://user-images.githubusercontent.com/20008482/168934647-b89b9479-8269-4167-aa98-6b8093fb4362.png">

**Comment by RedPxnda** [comment]
Ya, I just had this convo with someone in skript discord.
my new code is:
`on steering vehicle jump:
    set {_nbt} to nbt compound of player's vehicle
    set {_pose::*} to tag "Pose;Head" of {_nbt}
    if {_pose::*} is not set:
        set {_pose::*} to 0.0, 0.0 and 0.0
    set {_firstpose} to {_pose::1}
    remove 0.86 from {_firstpose}
    set float list tag "Pose;Head" of nbt compound of player's vehicle to {_firstpose}, 0 and 0`
    but the error persists.

**Comment by ShaneBeee** [comment]
I tried your code, but I did it in a command, as I don't have whatever add-on you're using for the vehicle steer thing.

Anyways, no errors, and the head is moving (see the diff between the two pics)
<img width="966" alt="Screen Shot 2022-05-18 at 10 31 12 AM" src="https://user-images.githubusercontent.com/20008482/169105794-2d16cb4a-68c2-40fd-93c6-768074e12d62.png">
<img width="966" alt="Screen Shot 2022-05-18 at 10 31 28 AM" src="https://user-images.githubusercontent.com/20008482/169105809-0b28bfdd-c408-45b8-b70e-08ca6049f50d.png">

I'm not saying your issue doesn't exist, I'm just stating here that I am not getting any errors, and the code appears to be working.

**Comment by RedPxnda** [comment]
Odd. I suppose it could be an issue with Skacket, just that nothing really jumped out in the error that was skacket related
