### ISSUE TITLE
[SUGGESTION] Stats of Interest Effect

### ISSUE THREAD

**Issue by IllagerCaptain** [ShaneBeee/SkBee#176]
**Describe the solution you'd like**
The ability to set frozen time, on fire time, air left while underwater, etc via an effect. Example:
`set [ticks] (frozen|[on ]fire|(breath|air|in water)) to %number% for %entity%` 

**Describe alternatives you've considered**
Only adding frozen. Example:
`set [ticks] frozen to %number% for %entity%`

**Comment by UsainSrht** [comment]
I think, things that doable easily with skript-reflect shouldn't be in SkBee. I mean team, component support is not easy with skript-reflect but you can just do `player.setFreezeTicks(200)`. But its Shane's plugin so he'll do whatever he wants.
