### ISSUE TITLE
[SUGGESTION] Easy custom head 

### ISSUE THREAD

**Issue by 1hmd** [ShaneBeee/SkBee#177]
this is a suggestion to make the custom head much easier to use or to add to gui 

`set slot 0 of player's current inventory to player head with nbt "{SkullOwner:{Id:""3fd44f85-9f07-4a4e-9854-ee57476ce1b8"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWU4ODkwODc0YTMwNjZmNDI2ZTY2ZTM3NDM4ZjQ1YWIyOWE1YmYyNTgyZGI3M2NiNGNmZjY5NTRhNTc4ZWYifX19""}]}}}" with name "Vegemite"
` 
this is what i have to do if I want to add custom head from mchead to my gui menu

**Comment by ShaneBeee** [comment]
so what exactly are you proposing?

**Comment by 1hmd** [comment]
can you make it easier to have heads form this site like https://minecraft-heads.com/
`skull of ("Vegemite" from minecraft heads)`

instead of this

`head with nbt "{SkullOwner:{Id:""3fd44f85-9f07-4a4e-9854-ee57476ce1b8"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWU4ODkwODc0YTMwNjZmNDI2ZTY2ZTM3NDM4ZjQ1YWIyOWE1YmYyNTgyZGI3M2NiNGNmZjY5NTRhNTc4ZWYifX19""}]}}}" with name "Vegemite"`

**Comment by ShaneBeee** [comment]
I won't be doing that anytime soon, as I have never done anything with website APIs
Honestly, I don't really see the point of this. Copying the head data as you are already doing is insanely simple. 

At the end of the day, you can already copy the head data and paste it into your script. 

SkBee's main purpose is to extend from the Bukkit API, and add Minecraft related stuff. 
What you're asking here is for me to pull a bunch of information from a website, which frankly is just out of the scope of SkBee.
