### ISSUE TITLE
[BUG] Boss Bars

### ISSUE THREAD

**Issue by pwuddle** [ShaneBeee/SkBee#178]
**Describe the bug**
Boss Bars broke due to of the the last updates.

**To Reproduce**
Use skBee's Boss Bar syntax.

**Expected behavior**
![image](https://user-images.githubusercontent.com/105949629/172066500-7520bd1f-fd9c-4e7f-a045-5514c18e36d7.png)

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/105949629/172066774-3d53c611-31bc-4e7c-ac15-7088ace7c5e5.png)
![image](https://user-images.githubusercontent.com/105949629/172066780-ed04608c-93d8-41c4-8ed3-f73a2d79f470.png)
by using the simple examples from SkriptHub, it doesn't work. Furthermore, it does not work with selfmade/created boss bars using the skBee syntax.

**Version Info:**
 - **SkBee Version:** 1.16.0-Beta3
-  **Skript Version:** 2.6.2
 - **Server Version/Platform** paper-1.18.2.jar

**Comment by ShaneBeee** [comment]
Hi, thanks for the bug report, unfortunately I can not replicate

Using the following code:
```vb
command /testbar:
	trigger:
		set {_bar} to boss bar named "le-bar"
		set bar color of {_bar} to bar blue
		set bar style of {_bar} to segmented 20
		set bar title of {_bar} to "Le-Title"
		add all players to bar players of {_bar}
```

This is the result of the reload:
```vb
> sk reload test
[13:49:16 INFO]: [Skript] Reloading test.sk...
[13:49:16 INFO]: [Skript] Successfully reloaded test.sk. (115ms)
```

This is what happens in game:
<img width="966" alt="Screen Shot 2022-06-05 at 1 49 11 PM" src="https://user-images.githubusercontent.com/20008482/172070028-f8497ca6-8cc5-49ad-8abf-a5c599aa0162.png">
The bar appears to load just fine.

**Comment by ShaneBeee** [comment]
If you could do me a favour, send me either a copy/paste or a screenshot of your server console when SkBee is loading

**Comment by pwuddle** [comment]
`05.06 22:15:44 [Server] INFO [skRayFall] Enabling skRayFall v1.9.27
05.06 22:15:44 [Server] INFO [skRayFall] Yay! You are running skRayFall 1.9.27!
05.06 22:15:44 [Server] INFO [skRayFall] Nathan and Lewis <3 you.
05.06 22:15:44 [Server] INFO [skRayFall] Cooking Bacon...
05.06 22:15:44 [Server] INFO [skRayFall] Getting more bacon for the army of citizens...
05.06 22:15:44 [Server] INFO [skRayFall] Got bacon for the EffectLib particle ninjas!
05.06 22:15:44 [Server] INFO [skRayFall] No Votifier Found! *Checks oven for finished bacon*
05.06 22:15:44 [Server] INFO [skRayFall] Enabling general 1.8+ bacon!
05.06 22:15:44 [Server] INFO [skRayFall] Getting the general 1.9+ bacon!
05.06 22:15:44 [Server] INFO [skRayFall] Getting the extra special 1.17+ bacon!
05.06 22:15:44 [Server] INFO [skRayFall] Bacon is ready!
05.06 22:15:44 [Server] INFO [SkBee] Enabling SkBee v1.16.0-Beta2
05.06 22:15:44 [Server] INFO [SkBee] Loading NBTApi...
05.06 22:15:44 [Server] INFO [SkBee] [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
05.06 22:15:44 [Server] INFO [SkBee] [NBTAPI] NMS support 'MC1_18_R2' loaded!
05.06 22:15:44 [Server] INFO [SkBee] [NBTAPI] Found Gson: class com.google.gson.Gson
05.06 22:15:44 [Server] INFO [SkBee] Successfully loaded NBTApi!
05.06 22:15:44 [Server] INFO [SkBee] NBT Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Recipe Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Scoreboard Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Bound Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Text Component Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Pathfinding Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] New Structure Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Other Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Virtual Furnace Elements disabled via config
05.06 22:15:44 [Server] INFO [SkBee] World Creator Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] Game Event Elements successfully loaded
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! [Skript] Severe Error:
05.06 22:15:44 [Server] ERROR #!#! SkBee's class com.shanebeestudios.skbee.elements.bossbar.types.Types generated an exception while loading
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! Something went horribly wrong with Skript.
05.06 22:15:44 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
05.06 22:15:44 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
05.06 22:15:44 [Server] ERROR #!#! Following plugins are probably related to this error in some way:
05.06 22:15:44 [Server] ERROR #!#! SkBee (https://github.com/ShaneBeee/SkBee) 
05.06 22:15:44 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
05.06 22:15:44 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
05.06 22:15:44 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
05.06 22:15:44 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
05.06 22:15:44 [Server] ERROR #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! Stack trace:
05.06 22:15:44 [Server] ERROR #!#! java.lang.IllegalArgumentException: Can't register org.bukkit.boss.BarColor with the code name bossbarcolor because that name is already used by boss bar color
05.06 22:15:44 [Server] ERROR #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:90)
05.06 22:15:44 [Server] ERROR #!#!     at SkBee-1.16.0-Beta2.jar//com.shanebeestudios.skbee.elements.bossbar.types.Types.<clinit>(Types.java:72)
05.06 22:15:44 [Server] ERROR #!#!     at java.base/java.lang.Class.forName0(Native Method)
05.06 22:15:44 [Server] ERROR #!#!     at java.base/java.lang.Class.forName(Class.java:466)
05.06 22:15:44 [Server] ERROR #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117)
05.06 22:15:44 [Server] ERROR #!#!     at SkBee-1.16.0-Beta2.jar//com.shanebeestudios.skbee.SkBee.loadBossBarElements(SkBee.java:338)
05.06 22:15:44 [Server] ERROR #!#!     at SkBee-1.16.0-Beta2.jar//com.shanebeestudios.skbee.SkBee.onEnable(SkBee.java:111)
05.06 22:15:44 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
05.06 22:15:44 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
05.06 22:15:44 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
05.06 22:15:44 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
05.06 22:15:44 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
05.06 22:15:44 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
05.06 22:15:44 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
05.06 22:15:44 [Server] ERROR #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
05.06 22:15:44 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
05.06 22:15:44 [Server] ERROR #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
05.06 22:15:44 [Server] ERROR #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! Version Information:
05.06 22:15:44 [Server] ERROR #!#!   Skript: 2.6.2 (latest)
05.06 22:15:44 [Server] ERROR #!#!     Flavor: skriptlang-github
05.06 22:15:44 [Server] ERROR #!#!     Date: 19:12:53.596652600
05.06 22:15:44 [Server] ERROR #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
05.06 22:15:44 [Server] ERROR #!#!   Minecraft: 1.18.2
05.06 22:15:44 [Server] ERROR #!#!   Java: 17 (OpenJDK 64-Bit Server VM 17+20-202105042342)
05.06 22:15:44 [Server] ERROR #!#!   OS: Linux amd64 4.18.0-348.2.1.el8_5.x86_64
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! Server platform: Paper
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! Current node: null
05.06 22:15:44 [Server] ERROR #!#! Current item: null
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! Thread: Server thread
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! Language: english
05.06 22:15:44 [Server] ERROR #!#! Link parse mode: DISABLED
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] ERROR #!#! End of Error.
05.06 22:15:44 [Server] ERROR #!#! 
05.06 22:15:44 [Server] INFO [SkBee] BossBar Elements successfully loaded
05.06 22:15:44 [Server] INFO [SkBee] This is a BETA build, things may not work as expected, please report any bugs on GitHub
05.06 22:15:44 [Server] INFO [SkBee] https://github.com/ShaneBeee/SkBee/issues
05.06 22:15:44 [Server] INFO [SkBee] Successfully enabled v1.16.0-Beta2 in 0.29 seconds
05.06 22:15:44 [Server] INFO [skript-placeholders] Enabling skript-placeholders v1.5.2*`

**Comment by pwuddle** [comment]
![image](https://user-images.githubusercontent.com/105949629/172070980-65bff676-e37e-449d-b100-b83d9a6d1317.png)
![image](https://user-images.githubusercontent.com/105949629/172070983-c0513c78-7e58-4861-bc1f-9f869556652a.png)
![image](https://user-images.githubusercontent.com/105949629/172070993-7a27e49b-b5c4-4750-bbc7-92b282adf472.png)
![image](https://user-images.githubusercontent.com/105949629/172071002-c0b22ca8-3bdc-4fe8-bac9-b865e356c9c2.png)
![image](https://user-images.githubusercontent.com/105949629/172071009-11622136-99a2-4ddf-bf13-4137e220b155.png)

**Comment by ShaneBeee** [comment]
ok, so it seems another plugin has registered bar color or something.
Ill make sure to do some checks for that by the next update

**Comment by pwuddle** [comment]
Issue Resolved after removing addon SkRayfall. :)
