### ISSUE TITLE
[BUG] With Residence is SkBee forced to start before Skript

### ISSUE THREAD

**Issue by Mtn16** [ShaneBeee/SkBee#182]
**Describe the bug**
When I have the Residence plugin on the server, the SkBee plugin is forced to run before the Skript, which causes an error. If I subsequently restart SkBee using the PlugMan plugin, an error is displayed that the Skript no longer accepts registrations.

**Expected behavior**
I tried to run the SkBee plugin when the Residence plugin was installed on the server. (This is really only a bug with the Residence plugin - I tested it)

**Screenshots/Errors**
https://imgur.com/a/K9AGvC7

**Version Info:**
 - **SkBee Version:** 1.16.0
-  **Skript Version:** 2.6.3
 - **Server Version/Platform** PaperMC 1.17.1 (with OpenJDK 17)

**Comment by ShaneBeee** [comment]
> This is really only a bug with the Residence plugin - I tested it

This right here. This isn't an SkBee issue, this is another plugin forcing load order to change somehow.

I know Purpur and Paper both had issues with this, there is nothing I can do on my end that will fix this, but there is something you can do, see this thread: https://github.com/ShaneBeee/SkBee/issues/152

**Comment by Mtn16** [comment]
I alredy fixed this. I edited plugin.yml And set Skript as depend, not softdepend. Thank youDne 11. 6. 2022 15:03 napsal uživatel Shane Bee ***@***.***>:

This is really only a bug with the Residence plugin - I tested it

This right here. This isn't an SkBee issue, this is another plugin forcing load order to change somehow.
I know Purpur and Paper both had issues with this, there is nothing I can do on my end that will fix this, but there is something you can do, see this thread: #152
