### ISSUE TITLE
[SUGGESTION] Make Particles visible from > 30 meters

### ISSUE THREAD

**Issue by 4L0N50asd** [ShaneBeee/SkBee#183]
**Is your feature request related to a problem? Please describe.**
I would like to use SkBee's particles system making other players can see the particles if they are >30 blocks far from the location of the particle. Until now, you can see the particles only if you're <30 blocks near to the location of them, that's because particles have 2 visble modes. The "normal" one and the "force" one.

You can see this using Minecraft vanilla's command, its use is `/particle <particle> <x> <y> <z> <offset x> <offset y> <offset z> <speed> <count> [<force | normal>] [@selector]`

Normal means only players <30 blocks from the particle will see them. Force means you can see these particles from a larger distance, not infinite, but at least you don't have the limit of 30 blocks.

**Describe the solution you'd like**
Add `force` and `normal` options to the expression:
`(lerp|draw|make) %number% [of] %particle% [particle] [using %itemtype/blockdata/dustoption/dusttransition/vibration%] %directions% %locations% [with offset %vector%] [with extra %number%] [(for|to) %players%]` ``[in force/normal mode]``

**Describe alternatives you've considered**
Add an option to specify at which distance you can see these particles, something like `lerp ..... [visible at %number% distance]`

**Comment by ShaneBeee** [comment]
I'll work on this soon.
Ill add an option to force.
I can't do a visible distance as you last suggested, as the API only has a boolean to force (not a number)
