### ISSUE TITLE
[SUGGESTION] Bound Special Values

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#191]
**Is your feature request related to a problem? Please describe.**
```vb
on break:
  if bound id at player's location is "example.one", "example.two" and "example.three":
    cancel event
```
Having to create lists like this and hard code them when we can just do it in game with custom-made commands much faster
(this can become a hassle when you have so many events such as pvp, build, break, death, damage, etc.)
**Describe the solution you'd like**
A syntax that adds more information to a bound, simply it's something that will add an extra YAML value of your choosing
Example:
```
set value %string% of bound %bound% to %string%
delete value %string% of bound %bound%
value %string% of bound %bound%
all values of bound %bound%`
```
```vb
on break:
  if value "break" of bound (bound at player's location) is false:
    cancel event
```
I'd think the values in the folder would be under a custom tag
Example:
custom:
  break: false
  build: false
  pvp: false

**Additional context**
I'm not saying it should be strictly boolean because people might be able to use other numbers or a string for something

**Comment by ShaneBeee** [comment]
this is an interesting idea, I quite like it. Ill put it on my todo, and take a look at a way to execute this.

**Comment by ShaneBeee** [comment]
added in SkBee 2.0.0
