### ISSUE TITLE
[BUG] Add to nbt compounds bug

### ISSUE THREAD

**Issue by Demarky** [ShaneBeee/SkBee#194]
**Describe the bug**

https://github.com/ShaneBeee/SkBee/wiki/NBTCompound#add
I'm trying to make the following code work without errors

`add "{custom:{quantidade:%{_t}%}}" to nbt of event-entity`

this way works fine, but it appears that "nbt" will no longer be supported in the future
when I change "nbt" to "nbt compound" it gives the following error

`add "{custom:{quantidade:%{_t}%}}" to nbt compound of event-entity`

"{custom:{quantidade:%{_t}%}}" can't be added to an nbt compound because the former is not an nbt compound

To try to solve it I tried to do the following

`set {_n} to nbt compound from "{custom:{quantidade:%{_t}%}}"`
`add {_n} to nbt compound of event-entity`

No errors appeared, but the code didn't work

**Expected behavior**
Should add nbt to entity

**Version Info:**
 - **SkBee Version:** (ex: 1.16.2 (latest))
-  **Skript Version:** (ex: Skript 2.6 (latest) )
 - **Server Version/Platform** (ex: paper 1.19)

**Comment by ShaneBeee** [comment]
Ahh yes, I think I see the issue.
When merging two compounds I did not manage for custom compound stuff
