### ISSUE TITLE
[SUGGESTION] Suggestions from the people

### ISSUE THREAD

**Issue by ShaneBeee** [ShaneBeee/SkBee#195]
The purpose of this thread is to get ideas from the people on what you guys' would like added to SkBee. 
This could be new stuff or maybe something from a dead or underused addon. Or maybe an addon that just hasn't been given the love from the dev that it deserves. 
Before suggesting things, I would like to quickly talk about what my goal with SkBee is.

## The Goal:
My main goal with SkBee is to open up the Bukkit API/Minecraft to Skripters. What I mean by this is, I want to provide syntax that works with things already in Minecraft. I don't want to add new "systems" so to speak (ex: GUIs) and I don't want to make "lazy syntax" for things that can already be done in vanilla Skript (meaning I don't want to make one liners for things that people are too lazy to write 3+ lines of code, or syntax that returns a static value like an expression for PI, we all know the numbers for PI, we don't need an expression for that).

## Before Suggesting:
- Please make sure your suggestion isn't already in Skript/SkBee/any other active addon.
- Please make sure your suggestion is something generally Minecraft related and exists in the Bukkit API (provide API links if you know how to find them) (Paper API is acceptable as well)
- Please make sure your suggestion does NOT require another external API

## Suggestions:
- [x] absorption hearts
- [ ] custom enchants
- [x] load/unload chunk
- [x] breed event parents
- [x] player demo screen
- [x] time span numbers `(ticks|seconds|minutes|hours) of %timespan%`
- [x] advancement events
- [x] world border stuff (both world and client side borders)

**Comment by Mqson31** [comment]
Absorption hearts from Skellet
https://docs.skunity.com/syntax/search/id:441

**Comment by Epikest** [comment]
- [ ] absolute value
- [ ] block hardness
- [ ] break block naturally
- [ ] breeding parents
- [ ] load and unload chunk
- [ ] clicked item, inventory, row, slot, etc.
- [ ] item in slot
- [ ] cooldowns

**Comment by Epikest** [comment]
> Absorption hearts from Skellet https://docs.skunity.com/syntax/search/id:441

already suggested though, how could you miss it?

**Comment by Mqson31** [comment]
- [ ] Vanilla teams
- [ ] Scoreboard that doesn't affect Teams

**Comment by ShaneBeee** [comment]
> from skellett:
> 
> * [ ]  absolute value
> * [ ]  block hardness
> * [ ]  break block naturally

Skript already has block hardness and break block naturally
> * [ ]  breeding parents
> * [ ]  load and unload chunk
> * [ ]  clicked item, inventory, row, slot, etc.

I feel like most of the clicked stuff is already in skript
> * [ ]  item in slot
> * [ ]  cooldowns

material cooldowns? I have already added that to SkBee, coming in the next big update
> * [ ]  hide enchants

This can already be done in SkBee
> * [ ]  itemframe item

Skript has this
> * [ ]  remove nbt

This can already be done in SkBee (its just hiding all flags)
> * [ ]  file management

I won't do this since Skent exists
> * [ ]  yaml

I won't do this since Skript-yaml is kind of the top one for yaml

**Comment by ShaneBeee** [comment]
> * [ ]  Vanilla teams
> * [ ]  Scoreboard that doesn't affect Teams

this has already been done in SkBee 1.16.x, I completely re-did the scoreboard setup in SkBee, scoreboards are now packet scoreboards (which won't affect teams), and team related syntax is now vanilla teams.

**Comment by Epikest** [comment]
> > from skellett:
> > 
> > * [ ]   absolute value
> > * [ ]   block hardness
> > * [ ]   break block naturally
> 
> Skript already has block hardness and break block naturally
> 
> > * [ ]   breeding parents
> > * [ ]   load and unload chunk
> > * [ ]   clicked item, inventory, row, slot, etc.
> 
> I feel like most of the clicked stuff is already in skript
> 
> > * [ ]   item in slot
> > * [ ]   cooldowns
> 
> material cooldowns? I have already added that to SkBee, coming in the next big update
> 
> > * [ ]   hide enchants
> 
> This can already be done in SkBee
> 
> > * [ ]   itemframe item
> 
> Skript has this
> 
> > * [ ]   remove nbt
> 
> This can already be done in SkBee (its just hiding all flags)
> 
> > * [ ]   file management
> 
> I won't do this since Skent exists
> 
> > * [ ]   yaml
> 
> I won't do this since Skript-yaml is kind of the top one for yaml

i just went through the docs for skellett and picked what i thought would be useful and isn't already implemented, however you know much more so i guess most of the stuff already exit

**Comment by ethanrettinger** [comment]
> I won't do this since Skent exists
![image](https://user-images.githubusercontent.com/79817320/175023331-e04b0b2d-9d6c-4d54-9ac9-22a3d9435dd0.png)
IIRC Skent is deprecated, and while it works well it would be nice to have an addon that is actively updated to properly manage files nowadays

**Comment by ImNotStable** [comment]
(Parentheses are just reasoning ignore them if you'd like to but I think it's worth it to glance over)
* [ ]  Highest to lowest sorting system _(I understand this is in MorkazSk, but I just see it as a useless addon unless you like very miscellaneous features or are looking for something oddly specific I know there are many people that like top whatever scripts also I believe it's already somewhat obsolete since so many other addons have features it has but those addons have other very general features which make them more appealing. Sorry for being wordy)_
* [ ] Tuske like GUI _(I understand this may be an easy no but I personally love and am extremely familiar with how Tuske works and how its syntax works, I dislike skript-gui for the sole reason of stuff like this_
`
        create a gui with virtual chest inventory with 3 rows named "%{_a}%":
            run on gui close: 
                send "test" to player
        open the last gui for the player
`
_but if this is genuinely a more efficient way of creating and using GUI's, especially in the java aspect I understand. Also, I just believe it'd make SkBee a more "rounded" addon or more general because it already has features people generally look for [Scoreboards, NBT, Particles])_
* [ ] Permissions _(Many addons with permission aspects have ended up abandoned [I honestly just remembers that you made your own I apologize if this is annoying and you can ignore this if you'd like] unless we're talking about BoringSk but it only does permissions)_
* [ ] Nametag Editing _(I'm not talking about Skript's vanilla 16-character limit I was wondering if it was possible for you to implement the API for [NametagEdit](https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Developers.creole) or whatever options there are, but I think this would be nice for some scripts people create because a decent amount of people look for this type of customization honestly.)_

Honestly, I understand if a majority of these or even all of them are turned down I'm just shooting out ideas that I'd use and I've noticed other players have looked for a good addon that supports them.

I hope you have a good day and sorry about the wordiness I just wanted to give reasoning, I had the time.

**Comment by ShaneBeee** [comment]
> > I won't do this since Skent exists
> 
> ![image](https://user-images.githubusercontent.com/79817320/175023331-e04b0b2d-9d6c-4d54-9ac9-22a3d9435dd0.png) IIRC Skent is deprecated, and while it works well it would be nice to have an addon that is actively updated to properly manage files nowadays

an add-on like Skent doesn't really need to be actively updated. Same with skript-yaml. Because they generally don't touch the Bukkit API and/or Minecraft, there's really nothing to update.

That said, I should probably put a note regarding what I want to do with SkBee.
The goal with SkBee is open up the Bukkit API/Minecraft to Skripters. 
While file stuff isn't related to MC/Bukkit, I may possibly add it in the future, so its not out of questions.



> (Parentheses are just reasoning ignore them if you'd like to but I think it's worth it to glance over)
> 
> * [ ]   Highest to lowest sorting system _(I understand this is in MorkazSk, but I just see it as a useless addon unless you like very miscellaneous features or are looking for something oddly specific I know there are many people that like top whatever scripts also I believe it's already somewhat obsolete since so many other addons have features it has but those addons have other very general features which make them more appealing. Sorry for being wordy)_
> * [ ]  Tuske like GUI _(I understand this may be an easy no but I personally love and am extremely familiar with how Tuske works and how its syntax works, I dislike skript-gui for the sole reason of stuff like this_
>   `create a gui with virtual chest inventory with 3 rows named "%{_a}%": run on gui close:  send "test" to player open the last gui for the player`
>   _but if this is genuinely a more efficient way of creating and using GUI's, especially in the java aspect I understand. Also, I just believe it'd make SkBee a more "rounded" addon or more general because it already has features people generally look for [Scoreboards, NBT, Particles])_
> * [ ]  Permissions _(Many addons with permission aspects have ended up abandoned [I honestly just remembers that you made your own I apologize if this is annoying and you can ignore this if you'd like] unless we're talking about BoringSk but it only does permissions)_
> * [ ]  Nametag Editing _(I'm not talking about Skript's vanilla 16-character limit I was wondering if it was possible for you to implement the API for [NametagEdit](https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Developers.creole) or whatever options there are, but I think this would be nice for some scripts people create because a decent amount of people look for this type of customization honestly.)_
> * [ ]  Custom Enchants _(I haven't seen any skript addons execute this well or in a way where it's easily understandable but if you're looking for more item related suggestions that could be one interesting one at least I'm not sure if you would know how to execute this but I have an idea)_
> 
> Honestly, I understand if a majority of these or even all of them are turned down I'm just shooting out ideas that I'd use and I've noticed other players have looked for a good addon that supports them.
> 
> I hope you have a good day and sorry about the wordiness I just wanted to give reasoning, I had the time.

Ill respond to each part:
Sorting - If Im not mistaken Skript added a better sorting system. It has a syntax for sorting indices of a list.
GUI - there's a good chance I WONT do this. See above where I told the other user my goal with SkBee. I want to focus on opening up the Bukkit API to Skripters, I don't want to focus on creating new systems (ie: GUIs) which can technically be done in vanilla Skript already. I MIGHT do this in the future, but its not one of my goals anytime. 
Permissions - I made SkPerm, but it was a mess of an add-on. Basic vault offers a decent amount of permissions stuff, but its also very limited. Plugins like LuckPerms have sooooo much to them, that vault doesn't cover a lot of what it offers. That said, I **WILL NOT** touch LuckPerm's API. I did when I first created SkPerm, and omg it was hard to deal with. Shortly after I made that add-on, LuckPerms went and completely re-wrote their API. When I tried to SkPerm to it, I Just couldn't figure it out and gave up. So sadly, I probably won't touch permissions stuff. But we shall see in the future. 
Custom Enchants - I've had a few people ask me this. I may attempt this. I remember a while back trying to fiddle with custom enchants (outside of Skript), and lets just say, Minecraft reallllyyyyy doesn't like custom stuff. While its technically possible with the Bukkit API to make a custom enchant, they really don't work the way we think they should. They don't play nicely with the enchanting GUI. Its been a few years since I tried it, so maybe things have changed. Ill look into it


As more responses come in, ill update my list at the top with the things I think that will fit into SkBee, and Ill do my best to reply to everything put here.

**Comment by ImNotStable** [comment]
I'm just going to say thank you for replying to each part, within the sorting. I had no idea they did that so thank you also I didn't know SkPerm was that difficult to upkeep I always thought you just abandoned it. Also I think "Indicies of List" should include sort somewhere not in the syntax just the name because I just look "sort" up and that didn't pop up also what are you looking for specifically, like what type of addon is SkBee if you get what I mean?

**Comment by J-ak-e** [comment]
> The purpose of this thread is to get ideas from the people on what you guys' would like added to SkBee. This could be new stuff or maybe something from a dead or underused addon. Or maybe an addon that just hasn't been given the love from the dev that it deserves. Before suggesting things, I would like to quickly talk about what my goal with SkBee is.
> 
> ## The Goal:
> My main goal with SkBee is to open up the Bukkit API/Minecraft to Skripters. What I mean by this is, I want to provide syntax that works with things already in Minecraft. I don't want to add new "systems" so to speak (ex: GUIs) and I don't want to make "lazy syntax" for things that can already be done in vanilla Skript (meaning I don't want to make one liners for things that people are too lazy to write 3+ lines of code, or syntax that returns a static value like an expression for PI, we all know the numbers for PI, we don't need an expression for that).
> 
> ## Before Suggesting:
> * Please make sure your suggestion isn't already in Skript/SkBee/any other active addon.
> * Please make sure your suggestion is something generally Minecraft related and exists in the Bukkit API (provide API links if you know how to find them) (Paper API is acceptable as well)
> * Please make sure your suggestion does NOT require another external API
> 
> ## Suggestions:
> * [ ]  absorption hearts
> * [ ]  custom enchants
> * [ ]  load/unload chunk
> * [ ]  breed event parents

add the demo screen from skjade
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#showDemoScreen()

**Comment by Masonion** [comment]
> The purpose of this thread is to get ideas from the people on what you guys' would like added to SkBee. This could be new stuff or maybe something from a dead or underused addon. Or maybe an addon that just hasn't been given the love from the dev that it deserves. Before suggesting things, I would like to quickly talk about what my goal with SkBee is.
> 
> ## The Goal:
> My main goal with SkBee is to open up the Bukkit API/Minecraft to Skripters. What I mean by this is, I want to provide syntax that works with things already in Minecraft. I don't want to add new "systems" so to speak (ex: GUIs) and I don't want to make "lazy syntax" for things that can already be done in vanilla Skript (meaning I don't want to make one liners for things that people are too lazy to write 3+ lines of code, or syntax that returns a static value like an expression for PI, we all know the numbers for PI, we don't need an expression for that).
> 
> ## Before Suggesting:
> * Please make sure your suggestion isn't already in Skript/SkBee/any other active addon.
> * Please make sure your suggestion is something generally Minecraft related and exists in the Bukkit API (provide API links if you know how to find them) (Paper API is acceptable as well)
> * Please make sure your suggestion does NOT require another external API
> 
> ## Suggestions:
> * [ ]  absorption hearts
> * [ ]  custom enchants
> * [ ]  load/unload chunk
> * [ ]  breed event parents
> * [ ]  player demo screen
> * [x]  time span numbers `(ticks|seconds|minutes|hours) of %timespan%`

- [ ] Worldborders
- [ ] Roman Numeral Conversion
- [ ] Skin and player name changing
- [ ] Advancement events etc.

**Comment by ImNotStable** [comment]
> > The purpose of this thread is to get ideas from the people on what you guys' would like added to SkBee. This could be new stuff or maybe something from a dead or underused addon. Or maybe an addon that just hasn't been given the love from the dev that it deserves. Before suggesting things, I would like to quickly talk about what my goal with SkBee is.
> > ## The Goal:
> > My main goal with SkBee is to open up the Bukkit API/Minecraft to Skripters. What I mean by this is, I want to provide syntax that works with things already in Minecraft. I don't want to add new "systems" so to speak (ex: GUIs) and I don't want to make "lazy syntax" for things that can already be done in vanilla Skript (meaning I don't want to make one liners for things that people are too lazy to write 3+ lines of code, or syntax that returns a static value like an expression for PI, we all know the numbers for PI, we don't need an expression for that).
> > ## Before Suggesting:
> > 
> > * Please make sure your suggestion isn't already in Skript/SkBee/any other active addon.
> > * Please make sure your suggestion is something generally Minecraft related and exists in the Bukkit API (provide API links if you know how to find them) (Paper API is acceptable as well)
> > * Please make sure your suggestion does NOT require another external API
> > 
> > ## Suggestions:
> > 
> > * [ ]   absorption hearts
> > * [ ]   custom enchants
> > * [ ]   load/unload chunk
> > * [ ]   breed event parents
> > * [ ]   player demo screen
> > * [ ]   time span numbers `(ticks|seconds|minutes|hours) of %timespan%`
> 
> * [ ]  Worldborders
> * [ ]  Roman Numeral Conversion
> * [ ]  Skin and player name changing
> * [ ]  Advancement events etc.

Worlderborders 
_SkQuery and SkJade_
Roman Numeral 
_SkQuery and SkJade_
Skin changing 
_Skirt_
Nametag Changing
_I suggested it myself, he won't use api's besides the bukkit/paper API which I'm not sure he'd be willing to make it himself, as a replacement honestly you could use TAB(https://github.com/NEZNAMY/TAB)_
Advancement events
_Skream and skript-advancements_

**Comment by J-ak-e** [comment]
I think it would be nice to have a custom advancement system, i know its possible with datapacks but its very limited
