### ISSUE TITLE
Cannot remove a specific item from a compound list

### ISSUE THREAD

**Issue by superstorm192** [ShaneBeee/SkBee#197]
**Describe the bug**
I am trying to remove a certain recipe from a villager, but nothing i try works

```
{_vil} is a villager entity
set {_trade::*} to tag "Offers;Recipes" of nbt compound of {_vil}
set {_vind} to 1
delete {_trade::%{_vind}%} #works

#not a single one of these do anything
delete tag "Offers;Recipes;%{_vind}%" of {_vil}
set tag "Offers;Recipes" of {_vil} to {_trade::*}
set compound list tag "Offers;Recipes" of {_vil} to {_trade::*}
delete (tag "" of {_trade::%{_vind2}%})

#error saying it can't be deleted or set to anything
delete {_vind}th element of (compound list tag "Offers;Recipes" of {_vil})
set {_vind}th element of (compound list tag "Offers;Recipes" of {_vil}) to "{}"
```

**To Reproduce**
Use the above code or similar, no runtime errors are produced.

**Expected behavior**
Remove from a compound list and update the entity

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.

**Version Info:**
 - **SkBee Version:** 1.16.1
-  **Skript Version:** Skript 2.6.2
 - **Server Version/Platform** Paper 1.17.1

**Additional context**
I haven't figured out how to manage compound lists as there's no examples of such usage.

**Comment by ShaneBeee** [comment]
The reason none of those work, is because none of them are correct format.
Nothing here is an "issue", its just user error. 

If you need help with how NBT works, please jump on skUnity's discord, and ask in the help channels.
There's always someone around who knows how NBT works and can help you out.

**Comment by superstorm192** [comment]
I know how nbt works, I am unable to get it to work with skbee when it comes to lists. How do I correctly remove the nth element in an nbt list with skbee? What is the correct format for compound lists? The issue is that there IS no correct format for lists that has been disclosed anywhere i've looked.

**Comment by ShaneBeee** [comment]
you can't modify the nth element of a list in SkBee, you'd have to save it to a var list, modify the var list, then save it back.

**Comment by ShaneBeee** [comment]
This is why I said, hope onto skUnity's discord if you need help.

**Comment by superstorm192** [comment]
Here's an update. I was adding the tag to an entity, not a compound. However, this time I actually got a runtime error.
`set tag "Offers;Recipes" of {_vcomp} to {_trade::*}`
https://www.toptal.com/developers/hastebin/sogujefavu.md

**Comment by ShaneBeee** [comment]
Hmm, that's an odd one for sure.
I'll have to try suppress the error.
