### ISSUE TITLE
[BUG] Bounds Error When Removing

### ISSUE THREAD

**Issue by tacticalNukes** [ShaneBeee/SkBee#198]
**Describe the bug**
So when I try to remove a bound using
`remove bound with id "s1-checkpoint|1"`

I get in console:
`[Skript] [SkBee ERROR] Bound with id 's1-checkpoint|1' already exists, cannot overwrite!`

**To Reproduce**
Create a new bound
`create a new bound with id "test" between (location at player) and (location at player ~ vector(3,3,2))`

`remove bound with id "test"`

**Expected behavior**
Well I was hoping it would delete the bound

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/49035285/176175664-237dcc2f-94e0-4110-bdb6-b8316ef2e0c7.png)

**Version Info:**
 - **SkBee Version:** 1.16.2
-  **Skript Version:** 2.6.2
 - **Server Version/Platform** git-Paper-411 (MC: 1.17.1)

**Comment by tacticalNukes** [comment]
well I found out that `remove` doesn't work and causes this but if you use `delete` it works perfectly fine

**Comment by ShaneBeee** [comment]
Im looking at my code for this, and literally shaking my head, haha, I totally screwed this one up.
