### ISSUE TITLE
[BUG] 'if event-block is beacon' is not work

### ISSUE THREAD

**Issue by madebygood** [ShaneBeee/SkBee#199]
After updating the skbee, the beacon is only recognized as a potion effect.
A beacon can also be a block.

![image](https://user-images.githubusercontent.com/43653581/177058239-5982ae71-a41a-4259-b176-18e409605c9b.png)

**Comment by ShaneBeee** [comment]
you should be either:
a) be using type, ie: `if type of block = beacon:`
b) use block data `if block data of block = beacon[]:`

This isn't actually an SkBee bug, this is a Skript bug, which has horrible comparison issues.
