### ISSUE TITLE
event doesn't work

### ISSUE THREAD

**Issue by MonsieurCookie** [ShaneBeee/SkBee#2]
So I tried to make a greeting message on enter of bound
`on bound enter:`
	`send "You entered %event-bound%!"`
I tried to use this code and that doesn't work, but things like bounds at player's location works fine so registering bound works. 1.15.2 spigot git-Paper-126, Skript 2.5-alpha2, newest skBee

**Comment by ShaneBeee** [comment]
Do you get any errors? Or just nothing happens?

**Comment by MonsieurCookie** [comment]
Nothing happens, it says reload complete without erorrs, I am entering bound and nothing happens, so registering the event may be issue :P

**Comment by ShaneBeee** [comment]
Yeah, totally my fault. Ill get an update out shortly!

**Comment by MonsieurCookie** [comment]
How much it would take to fix this? Just want to know because I need to disable function of creating bounds temporarily, you don't have to hurry with fix :)

**Comment by ShaneBeee** [comment]
I forgot to reply, but its been updated :)
