### ISSUE TITLE
[BUG] NBT Compounds dont work when creating an Item

### ISSUE THREAD

**Issue by MrEnxo** [ShaneBeee/SkBee#200]
**Describe the bug**
So for example I want to have a function create an item with nbt well that does not work with compounds...

**To Reproduce**

```
on right click:
	set {_i} to diamond
	set {_n} to nbt compound of {_i}
	set tag "data;hp" of {_n} to 10
	give player item from nbt {_n}
```

**Expected behavior**
Its supposed to give you a diamond with nbt except it just gives you a normal ass diamond

**Version Info:**
 - **SkBee Version:** Latest
-  **Skript Version:** 2.6.2
 - **Server Version/Platform** 1.17

**Comment by ShaneBeee** [comment]
Closing for 2 reasons:
a) "latest" is not a version
b) there is no issue here, this is user error. If you need assistance on how to use NBT compounds for items please either see the [WIKI](https://github.com/ShaneBeee/SkBee/wiki) or ask for help from someone on skUnity's discord

**Comment by MrEnxo** [comment]
alright let me follow the wiki then and make a issue with that then 👍🏻

**Comment by MrEnxo** [comment]
well there is an issue here
im not sure if its skbee or skript
