### ISSUE TITLE
[BUG] Conflict with SkRayFall

### ISSUE THREAD

**Issue by JulienGabriel** [ShaneBeee/SkBee#205]
**Describe the bug**
skBee has a conflict with another Skript Addon, SkRayFall

**To Reproduce**
When i downloaded skBee, SkRayFall just gets disabled.

**Expected behavior**
SkRayFall doesn't disable due to skBee

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/69354617/177567219-4b64d2dd-37ca-4c44-a44f-4def4a413583.png)

**Version Info:**
 - SkBee v4.1.6
-  Skript v2.6.2
 - Paper 1.17.1

**Comment by GeoGb1** [comment]
i dont think  SkBee v4.1.6 exists

**Comment by ShaneBeee** [comment]
> i dont think SkBee v4.1.6 exists

not for at **LEAST** another 5 years.

Not only does that version info make no sense, this issue isn't an SkBee issue.
I can fix other addons
