### ISSUE TITLE
Progress of Bossbar[BUG]

### ISSUE THREAD

**Issue by Koekoeksei** [ShaneBeee/SkBee#206]
**PROGRESS OF BOSSBAR**
So I was creating a random RPG server and I tried to create a bossbar with health for entities. It wasn't that hard. But I noticed the bossbar is bugged. If I fill in `set {_healthbar} to bossbar named "HealthBar%attacker%" with title "%name of victim% &8| &c%health of victim%♥/%max health of victim%♥" with color bar red with style solid with progress 50` it will show progress 0. Everytime I fill the bossbar progress between 1 and 99 it shows progress 0. I tried it on a clean server and the bossbar was still empty. When you fill in progress 100 it show the full bar filled with the red color. But other numbers are all empty. I tried finding a solution and asking loads of people, but they all didn't know the reason why it didn't work. So I think it is a bug.

**Comment by ShaneBeee** [comment]
closing due to template missing
