### ISSUE TITLE
[BUG] SKBEE failing to load on 1.17.1

### ISSUE THREAD

**Issue by BuffoonSpoon** [ShaneBeee/SkBee#208]
**Describe the bug**
SKBee fails to load on 1.17.1 with the 1.17.0 version of skbee... 

**To Reproduce**
Create 1.17.1 server, download latest version of skbee

**Expected behavior**
The plugin to load

**Screenshots/Errors**
I cannot add the server log, as it contains sensitive information.. It gives an uptodate error after enabling some elements
It enables successfully:
- Scoreboard
- Team
- Bound
- Text
- Pathfinding
And then gived the out of date error and disabled

**Version Info:**
1.17.1 Paper
1.17.0 SKBEE

**Comment by BuffoonSpoon** [comment]
I'll get a cut down error for you
![image](https://user-images.githubusercontent.com/76260399/177852801-dfb51e5b-d169-457d-b3e5-a64b57c263ca.png)

**Comment by ShaneBeee** [comment]
Ah ok, I see what happened there. I didn't do a version check.
For now (until I get a release out), just disable structures in  SkBee config)
