### ISSUE TITLE
[BUG] Severe skript error

### ISSUE THREAD

**Issue by Leonardo-Fiori** [ShaneBeee/SkBee#21]
**Description**
I get this terrible exception a lot of times since i wrote this code... to me there is nothing wrong in it, but can you take a look? The exception is in the attached .log file. I think this may lead to a memory issue on the long run?

**Version Info:**
 - **SkBee Version:** 1.2.0
-  **Skript Version:** 2.4.1
 - **Server Version/Platform** git-Paper-243 (MC: 1.14.4)

**Exception**
[exception.log](https://github.com/ShaneBeee/SkBee/files/4646872/exception.log)

**Code, to reproduce**

> on right click:
> 	set {_cart} to clicked entity
> 	if tag "id" of nbt of {_cart} is set:
> 		if tag "id" of nbt of {_cart} is """minecraft:minecart""" or """minecraft:boat""":
> 			message "&6&lWarning &eyour vehicle will be inevitably removed after you dismount it! Get a free Boat or Minecart writing &6/boat &eor &6/minecart" to the player
> 
> on vehicle exit:
> 	set {_cart} to player's vehicle
> 	if tag "id" of nbt of {_cart} is not """minecraft:minecart""" or """minecraft:boat""":
> 		stop
> 		#if "%{_cart}%" does not contain "horse":
> 
> 	message "&6&lWarning &eyour vehicle will be inevitably removed in &660 &eseconds" to the player
> 	message "&eGet a free Boat or Minecart writing &6/boat &eor &6/minecart" to the player
> 
> 	wait 60 second
> 	eject any passenger from {_cart}
> 	kill {_cart}
>

**Comment by ShaneBeee** [comment]
> SkBee Version: 1.2.0

Update SkBee, you're 4 versions behind.

**Comment by Leonardo-Fiori** [comment]
@ShaneBeee updated 11 days ago and let it run.. exception seems to come out less frequently but it still happens

[error.log](https://github.com/ShaneBeee/SkBee/files/4704054/error.log)

**Comment by ShaneBeee** [comment]
It seems as though the entity you are trying to use is either non existent or dead:
```
[18:52:10] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Entity can't be null/dead!
[18:52:10] [Server thread/ERROR]: #!#!     at tk.shanebee.bee.api.NBT.NBTEntity.<init>(NBTEntity.java:28)
```
