### ISSUE TITLE
[SUGGESTION] Cancel Delayed Task

### ISSUE THREAD

**Issue by CollidaCube** [ShaneBeee/SkBee#210]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Normally, in skript you can delay a task by using the wait effect, but there is no way to cancel it. I think it would be cool if you could implement a way to cancel it. Maybe make a new section like `create new delayed task [[with id] %string%] by %timespawn%:` and then later you can cancel it with `cancel [delay] task [with id] %string%`

**Describe alternatives you've considered**
make the wait effect result in an id you can use to cancel the task. Something like `set {_id} to ...`

**Additional context**
none

**Comment by ShaneBeee** [comment]
I thought about this more and more, and I personally don't feel this fits into SkBee.
SkBee focuses more on Minecraft related things, this is more structural based on a Bukkit/Java task. 
Something like this probably would be best to put into skript-reflect
