### ISSUE TITLE
[BUG] Missing syntax for "nbt item compound"

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#211]
**Describe the bug**
I noticed in the wiki there's "nbt item compound" but it doesn't exist in-game

**To Reproduce**
Go to [this wiki page](https://github.com/ShaneBeee/SkBee/wiki/NBT-Compound) to learn about `nbt item compound`
go to a server with both Skbee and Skript installed and try to use `nbt item compound of %itemtype%`

**Expected behavior**
to be sent item nbt rather than an error

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/81952476/178337601-4965a6cb-d2d3-499d-8971-aa51f62b5aa4.png)

**Version Info:**
![image](https://user-images.githubusercontent.com/81952476/178337322-c238cf6c-5a8d-4565-a1d5-7e1c3749afb8.png)

**Additional context**

**Comment by ShaneBeee** [comment]
that wiki is for a future version of SkBee

**Comment by Fusezion** [comment]
ah
