### ISSUE TITLE
[BUG] Hover Text Newline Chars

### ISSUE THREAD

**Issue by ethanrettinger** [ShaneBeee/SkBee#215]
**Describe the bug**
Using a list for a TextComponent Hover Text adds visible newline "CR" characters after every line (except the last)

**To Reproduce**
1. Create list with 2+ values for hover text
2. Create text component from some text
3. Set hover event of component to the list 
4. Send the list in chat and hover 

**Expected behavior**
No newline CR chars after the line text. 

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/79817320/179778363-c80c2072-394c-4979-9288-9fdfbfe47672.png)
![image](https://user-images.githubusercontent.com/79817320/179778396-82833aaa-8855-408d-b9bd-c709193a9421.png)
![image](https://user-images.githubusercontent.com/79817320/179778405-7b21e130-d92d-47b5-9b16-3d7775891adc.png)

**Version Info:**
 - Provide output of **/skbee info**   
 **OR**
 - **SkBee Version:** (ex: 1.16.1) 1.17.2
 - **Skript Version:** (ex: Skript 2.6.1)
2.6.3
 - **Server Version/Platform** (ex: Spigot 1.15.2)
Spigot 1.19

**Additional context**
Mentioned issue and skunity discord and you said to make an issue :)

**Comment by ShaneBeee** [comment]
After much testing, and having others test, I could not replicate this.
While I was able to change one small thing that worked on your machine, that change didn't work on others.
I was told at one point this had something to do with the end user, so Im not entirely sure how to change that.
