### ISSUE TITLE
[SUGGESTION] MSPT expression

### ISSUE THREAD

**Issue by Helios3991** [ShaneBeee/SkBee#218]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Just like Skript's TPS expression, but for MSPT.

**Additional context**
It's a simple feature that will probably be useful to some people.

**Comment by ShaneBeee** [comment]
what is MSPT?

**Comment by Helios3991** [comment]
MSPT stands for Miliseconds Per Tick, and is a more accurate alternative to TPS.

**Comment by ShaneBeee** [comment]
is there Spigot/Paper API for this?

**Comment by Helios3991** [comment]
https://jd.papermc.io/paper/1.19/com/destroystokyo/paper/event/server/ServerTickEndEvent.html#getTickDuration()

**Comment by ShaneBeee** [comment]
Ok interesting... and do you have a use case for this?
Like why/how would someone use this?

**Comment by Helios3991** [comment]
It could be used to monitor server's performance, disable heavy parts in huge scripts if server starts to lag etc. Everyone using TPS in their script will benefit from this.

**Comment by ShaneBeee** [comment]
> It could be used to monitor server's performance, disable heavy parts in huge scripts if server starts to lag etc. Everyone using TPS in their script will benefit from this.

the average person I've seen use TPS is generally for a scoreboard / tablist. 

Honestly, I don't think this belongs in SkBee, seems like one of things I'll add and like 2 people will use it. 
For something like this, I think its probably best to just use skript-reflect

**Comment by ImNotStable** [comment]
A lot of people might not use it, but when I create a server, MSPT is usually private for me since most people don't understand what it is. It gives a more in-depth look at what's happening since TPS stays 20 unless MSPT is above 50.

**Comment by ShaneBeee** [comment]
Im closing this as I really don't think this fits into SkBee
Since this is something that next to no one would use, I recommend Skript-Reflect for this stuff
