### ISSUE TITLE
[BUG] Recipes Crash the Server

### ISSUE THREAD

**Issue by SUPYYT** [ShaneBeee/SkBee#219]
**Describe the bug**
Server crashes after I reload skript with 2 or more recipes

**To Reproduce**
Insert this code to skript:
https://pastebin.com/VfEtF3n3

**Expected behavior**
I reload skript and it registers all the recipes without crashing the server

**Screenshots/Errors**
Errors:
https://pastebin.com/9gvH2svh

**Version Info:**
![image](https://user-images.githubusercontent.com/109906646/180648446-6bfe30bc-b276-4bd7-ba81-16bb4356beb1.png)

**Additional context**
All the syntax should be fine.

**Comment by ShaneBeee** [comment]
this isn't actually an SkBee bug, but rather a Skript issue.

Skript isn't very good at handling long lines. I recommend breaking up the lines into small lines.
For example, setting vars to the items with names and using the var in the recipe.
When doing some testing, for some reason totem of undying kept giving me issues, here is a test I did:
```vb
on load:
	broadcast "&cThis Skript uses SkBee to work!!"
 
	set {_n} to nether star named "&e+1&c❤" with lore "&3Right click to add 1 hearth to your healthbar"
	register new shaped recipe for {_n} using totem of undying, diamond block, gold block, diamond block, redstone block, diamond block, gold block, diamond block, totem of undying with id "hearth"
	

	set {_b} to beacon named "&cRevive crafter"
	register new shaped recipe for {_b} using diamond block, red dye, diamond block, red dye, beacon, red dye, diamond block, red dye, diamond block with id "reviveTotem"
	send "Loaded &cRevive crafter" to console
	set {_t} to totem of undying named "&cRight Click to revive someone" with lore "&3This totem is used to revive someone who died"
	set {_to} to totem of undying
	register new shaped recipe for {_t} using air, {_to}, air, {_to}, {_b}, {_to}, air, {_to}, air with id "reviveTotem"
	send "Loaded &cRevive totem" to console
```
This loaded with no issues

Im going to close this simply cause its not actually the fault of SkBee and there's nothing I can do to fix it.
