### ISSUE TITLE
[SUGGESTION] Set nbt of inventory slot

### ISSUE THREAD

**Issue by Darkweasam** [ShaneBeee/SkBee#22]
**Is your feature request related to a problem? Please describe.**
I am making my own GUI using skript
I do some serious calculations using `line set slot loop-number of {_inventory} to something named something with lore something...`
I needed to edit the nbt of these items in order to keep skript size minimal, so I need something like:
´set nbt of slot 9 of {_inventory} to "{CustomModelData:1}"´. There is no errors uppon doing this, but there is no effect

**Describe the solution you'd like**
I want to be able to edit NBT values of inventory slots

Thank you for your consideration

**Comment by ShaneBeee** [comment]
You can technically already do it, ex:
```vb
set slot 8 of player's inventory to slot 8 of player's inventory with nbt "{CustomModelData:1}"
```

**Comment by ShaneBeee** [comment]
Sorry this took me so damn long to do. It was actually really easy to add.
I'll have it available in the next update!
