### ISSUE TITLE
[SUGGESTION] Number Accuracy

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#220]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to change the number accuracy in the Skript config which when I'm creating a big script some parts may require different number accuracy I just think it'd be useful to add an expression such as
`set number accuracy of %timespan% to %integer%` (There is nothing to round timespans and I don't want to have to convert it into text and back into time)

**Describe the solution you'd like**
Just one syntax to be able to change the number accuracy for a timespan which I've searched and I can't find anything for this

**Describe alternatives you've considered**
Having a function that converts it into text splits or takes the first few characters I want (which can be somewhat long depending on how you want it to function) and parsed it back into time

**Additional context**
No just something that'll change how many numbers are allowed after the decimal point which could span from 0 to anything higher

I hope this is possible and won't conflict with anything in Skript's number accuracy

**Comment by ShaneBeee** [comment]
sorry not possible with SkBee, as stuff like this is hardcoded into Skript's TimeSpan class
