### ISSUE TITLE
[SUGGESTION] Check if block is solid

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#221]
**Is your feature request related to a problem? Please describe.**
I can't find an addon that supports syntax to check if a block is solid.

**Describe the solution you'd like**
Just a syntax such as
`%block% is solid`
and if you'd like to add other possibly used but insignificant features you could use flammable and transparent like Tuske does, but I'd like a syntax like this because I need a block that you can stand through such as grass or flowers which there are so many that I'd have to make an entire list and research every non-solid block

**Describe alternatives you've considered**
Making a long list of non-solid blocks and using an if statement

**Comment by ShaneBeee** [comment]
before requesting things, I highly recommend reading the docs
https://docs.skriptlang.org/conditions.html#CondIsSolid
