### ISSUE TITLE
[BUG] Player gets stuck at "Loading terrain..." after unloading and loading world

### ISSUE THREAD

**Issue by JaydenJinx** [ShaneBeee/SkBee#224]
**Describe the bug**
A player will get stuck at "Loading terrain..." after teleporting to a world that has been loaded, unloaded, then loaded again. The player will be able to hear mobs around them in the new world, but will be stuck at the screen and unable to do anything. The player must force quit the game and restart their client.

**To Reproduce**
Load world on connect. Unload world on disconnect and teleport player to a loaded world. Reload world on join. Player loads to loaded world fine, but gets stuck when teleporting to the reloaded world. This can be temporarily fixed by restarting the server. You can do the same thing again, but still gets stuck when teleporting to the newly reloaded world.

**Expected behavior**
The player should not be stuck at the "Loading terrain..." screen.

**Screenshots/Errors**
No errors. Tried debugging both SkBee and Skript. Nothing out of the ordinary.

**Version Info:**
[12:03:22 INFO]: --- [Server Info] ---
[12:03:22 INFO]: Server Version: git-Purpur-1732 (MC: 1.19)
[12:03:22 INFO]: Skript Version: 2.6.3
[12:03:22 INFO]: Skript Addons:
[12:03:22 INFO]: SkBee Version: 1.17.3

Here's a video demo: https://youtu.be/MMG3Yu1rm_Q

EDIT 1:48PM PST: Got this error to show in console for the first time ever. https://www.toptal.com/developers/hastebin/nosetujuni.md

**Comment by ShaneBeee** [comment]
Ok I want to start with part 1:
I wasn't able to recreate that issue.

Part 2, (the crash type error):
I've gotten this a bunch of times myself. 
Long story short, based on debug messages I've added, this has nothing to do with SkBee, but it's the server software itself. It seems like it's majorly hanging when creating a new world. 
I've tested this in a standalone plugin on a sever with no other plugins, and unfortunately it does the same thing.

**Comment by JaydenJinx** [comment]
What server version are you testing with?

I can try switching back to Paper instead of Purpur.

**Comment by ShaneBeee** [comment]
Im using Paper

**Comment by JaydenJinx** [comment]
Unfortunately updating to the latest Paper update didn't help. Maybe it's the way it's written. I'll have to mess around with it and see if I can get it to work.

[23:18:02 INFO]: --- [Server Info] ---
[23:18:02 INFO]: Server Version: git-Paper-94 (MC: 1.19.1)
[23:18:02 INFO]: Skript Version: 2.6.3
[23:18:02 INFO]: Skript Addons:
[23:18:02 INFO]: SkBee Version: 1.17.3

**Comment by ShaneBeee** [comment]
im pretty certain this is just a server issue. 
When testing on Spigot, when creating a world, it hangs the server for 15 seconds.
Paper only allows a 10 second hang before it freaks out.

**Comment by JaydenJinx** [comment]
Hmmm... Any recommendations about what might help? More delay somewhere?

I notice that the server says something like: "Preparing spawn 0%", but then never gives any updates after that.

**Comment by ShaneBeee** [comment]
Im currently searching all the configs, to see if we can go past 10 seconds... stay tuned

**Comment by ShaneBeee** [comment]
update:
`config/paper-global.yml`
very bottom:
```yaml
watchdog:
  early-warning-delay: 10000
  early-warning-every: 5000
```
the early warning delay is 10 seconds, I changed it to 30000 (30 seconds)...
good news = I don't get the nasty crash/error message
bad news = the server is still hanging for a good 15 seconds to create the world

**Comment by ShaneBeee** [comment]
Closing due to this not being an SkBee issue, but rather a server issue.
