### ISSUE TITLE
[BUG] Redstone gets destroyed upon placing a structure.

### ISSUE THREAD

**Issue by Greathelloboy** [ShaneBeee/SkBee#226]
**Describe the bug**
Upon placing a structure, redstone on top of a dispenser gets destroyed. If there is a block where the dispenser should be before the structure gets loaded, the redstone loads properly.

**To Reproduce**
Place redstone on top of a dispenser or hopper (I'm pretty sure its any container block but I haven't tested it.) Save a structure with the redstone and dispenser in it and then place it. The redstone gets destroyed and drops the item.

**Expected behavior**
Redstone being placed instead of dropped.

**Screenshots/Errors**
None

**Version Info:**
[06:34:13 INFO]: --- [Server Info] ---
[06:34:13 INFO]: Server Version: git-Paper-50 (MC: 1.19)
[06:34:13 INFO]: Skript Version: 2.6.3
[06:34:13 INFO]: Skript Addons:
[06:34:13 INFO]: - Skellett v2.0.7
[06:34:13 INFO]: - skript-reflect v2.3
[06:34:13 INFO]: SkBee Version: 1.17.3

**Comment by ShaneBeee** [comment]
just tested this in vanilla Minecraft, happens in vanilla too.
This is a Minecraft issue, not an SkBee issue.
