### ISSUE TITLE
[BUG] Pufferfish Puff States

### ISSUE THREAD

**Issue by Tr4mp1** [ShaneBeee/SkBee#23]
**Describe the bug**
Pufferfish have 3 puff states normally. With the SkBe addon installed, only the first (small) and last (large) puff states render to the client.

**To Reproduce**
Spawn or find a pufferfish and approach it in survival/adventure mode

**Expected behavior**
As you approach, the pufferfish should puff from small to medium size, and then from medium to large. Instead, the medium puff state renders as the large state to the client. Everything is normal server side I think.

**Screenshots/Errors**
Video:
https://youtu.be/T9M0BEcHZ9M

**Version Info:**
 - **SkBee Version:** No idea, which ever version Minehut has as of 22/05/20
-  **Skript Version:** Skript 2.4.1-MH
 - **Server Version/Platform:** Spigot 1.15.2 (or whatever Minehut uses)

**Additional context**
Other addons installed: Skellett, SkRayFall, SkQuery, TuSKe, Vixio

**Comment by ShaneBeee** [comment]
A few things to note here:
1) 
> SkBee Version: No idea, which ever version Minehut has as of 22/05/20

This tells me nothing. I do not know which version of plugins Minehut is using. When posting issues please post the actual version of the plugin.

2) I can not replicate this issue using the latest version of SkBee which is 1.3.3.
<img width="966" alt="Screen Shot 2020-05-22 at 11 44 47 AM" src="https://user-images.githubusercontent.com/20008482/82699554-bef80300-9c21-11ea-8c80-66b3e60d1ba9.png">
<img width="966" alt="Screen Shot 2020-05-22 at 11 45 06 AM" src="https://user-images.githubusercontent.com/20008482/82699557-c0c1c680-9c21-11ea-9a50-edda7a48cd14.png">
<img width="966" alt="Screen Shot 2020-05-22 at 11 45 08 AM" src="https://user-images.githubusercontent.com/20008482/82699559-c15a5d00-9c21-11ea-9815-ed2f95346657.png">

**Comment by Tr4mp1** [comment]
I'm fairly sure the SkBee version is 1.2.0, so it is probably fixed in a later version. Sorry for wasting your time.
