### ISSUE TITLE
[BUG] SkBee loads before Skript when every other addon loads fine

### ISSUE THREAD

**Issue by Erisfiregamer1** [ShaneBeee/SkBee#230]
**Describe the bug**
SkBee loads before Skript, even though all other loaded Skript addons load fine.

**To Reproduce**
Unsure why this is occuring. Bad addon? Too many plugins?
Just in case, this is my plugin list. If there's something you know's conflicting with SkBee point it out.
` AdvancedBan, AdvancedEnchantments, AdvancedPets, AuctionMaster, AureliumSkills, BattlePass, Bazaar, BetterPortals, BetterRTP, BuycraftX, CCTV, ChestsPlusPlus, Citizens, ComplexTurrets, ControlPlayer, CrackShot, DecentHolograms, DiscordSRV, dynmap, EconomyShopGUI-Premium, Essentials, ExcellentCrates, ExtraTools, FancyCrafting, FastAsyncWorldEdit (WorldEdit), FNAmplifications, FreedomChat, Galactifun, Gehenna, GrimAC, Hyperstones, ILibrary, InfinityExpansion, ItemsAdder, JukeLooper, Lands, LandsDiscordBot, LibsDisguises, LightAPI, LiteXpansion, LoneLibs, LPC, LuckPerms, Magic, MobCapturer, Multiverse-Core, NBTAPI, NexEngine, OldCombatMechanics, OpenTerrainGenerator, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, Quests, Rankup, Referrals*, Scoreboard-revision*, SFCalc, SimpleStorage, SimpleTpa*, SimpleUtils, SkBee, Skellett, Skoice, SkQuery, skRayFall, Skript, Slimefun, SlimefunWarfare, SoulJars, spark, SpecializedCrates, Stocks*, SupremeExpansion, TabList, TradeSystem, TranscEndence, VacuumShulkerBox, Vault, VehiclesPlusPro, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldGuard`
**Expected behavior**
SkBee loads after Skript.

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.

**Version Info:**
 - Provide output of **/skbee info**   
 **OR**
 - **SkBee Version:** 1.17.3
 - **Skript Version:** Skript 2.6.1
 - **Server Version/Platform** git-Purpur-1746 (MC: 1.19.1)

**Additional context**
None.

**Comment by ShaneBeee** [comment]
see the discussion about this:
https://github.com/ShaneBeee/SkBee/discussions/214

This is not an SkBee issuer, rather a server issue changing plugin load order.
I've seen this many times on Purpur
