### ISSUE TITLE
[Bug] Console error

### ISSUE THREAD

**Issue by bloggy** [ShaneBeee/SkBee#231]
Console error on 1.18.2 server:

https://pastebin.com/NeYp97SA

Version:
This server is running Purpur version git-Purpur-1632 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: dc4a29b on HEAD)
[SkBee] Loading SkBee v1.15.1

**Comment by ShaneBeee** [comment]
severely outdated versions of SkBee are not supported
