### ISSUE TITLE
[SUGGESTION] Get recipe from item list

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#232]
**Is your feature request related to a problem? Please describe.**
I'm trying to make a Skript where I can find a recipe from an item list such as
`recipe from ingredients %itemstacks%`

**Describe the solution you'd like**
I can get a recipe from something like this
`recipe from ingredients air, oak planks, air, air, oak planks, air, air, stick and air`

**Describe alternatives you've considered**
looping all recipes and checking one by one what recipes match

**Additional context**
I've looked for something like this in Skript Hub documentation and I couldn't find anything that does this

**Comment by ShaneBeee** [comment]
Unfortunately I do not see any API to manage this, and looking thru Minecraft's code, they basically do the same thing, just looping all recipes and matching ingredients

**Comment by ImNotStable** [comment]
Oh alright I hoped there was a way thank you for looking. Have a good evening
