### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cowio** [ShaneBeee/SkBee#235]
**Describe the bug**
The {Health:20.0f} nbt of the player is not getting changed. Tried different lines of code.

**To Reproduce**
I guess try this code, and it doesn't set max health of the player to 12.5 hearts:

command /playernbt:
-trigger:
--player is op
--set {_nbt} to nbt compound of player
--set {_t} to pretty nbt of {_nbt} with split " "
--send "NBT: %{_t}%" to console

command /health:
-trigger:
--set {_n} to nbt compound from "{Health:25.0f}"
--add {_n} to nbt compound of player

**Expected behavior**
I expected it to set the nbt compound {Health:20.0f} of the player to {Health:25.0f}. Which it didnt.

**Screenshots/Errors**
No errors

**Version Info:**
<img width="424" alt="image" src="https://user-images.githubusercontent.com/25691968/184540391-e5e09fcb-4087-4051-9c9b-b08225cdb8b8.png">

**Comment by ShaneBeee** [comment]
what happens if you set it less than 20? does that work?

**Comment by Cowio** [comment]
Good question, here is the result:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/25691968/184541732-c9d6c79c-c163-4267-9eec-2c61a930f0fb.png">
I do get the {Health:18.0f} hearts, but I regenerate up to 20.0f again.

Something tells me that something changed with the nbt of the player from minecraft 1.13 to 1.19. Because I used Skbee back then at it worked perfectly for changing the maxhealth with the {Health:24.0f}. And there are no nbt tag in 1.19 that is called {MaxHealth:20.0f} as of what I can see...

**Comment by ShaneBeee** [comment]
Everything worked fine for me.
Player's max health has been an attribute for years now.
On top of that, Skript has expressions for health/max health, Im not sure why you are using NBT for this, its extremely inefficient to be doing it that way.

<img width="926" alt="Screenshot 2022-08-14 at 7 37 47 AM" src="https://user-images.githubusercontent.com/20008482/184542005-bba6cb9a-56fe-49cd-abe8-ef224fdb0a5c.png">
<img width="926" alt="Screenshot 2022-08-14 at 7 38 00 AM" src="https://user-images.githubusercontent.com/20008482/184542009-83f91f1f-6bdf-4646-8bbd-f38afb98904e.png">
<img width="966" alt="Screenshot 2022-08-14 at 7 38 11 AM" src="https://user-images.githubusercontent.com/20008482/184542010-d44f51df-9858-4e43-a06b-84bc66f4a033.png">

Closing this as a non-issue.

**Comment by Cowio** [comment]
I am not using the set players max health because it cant set half hearts only full hearts.

**Comment by ShaneBeee** [comment]
worked fine for me
<img width="966" alt="Screenshot 2022-08-14 at 7 42 21 AM" src="https://user-images.githubusercontent.com/20008482/184542124-d3217f0c-117f-4b5b-a5cc-0a7c59842687.png">
<img width="926" alt="Screenshot 2022-08-14 at 7 42 39 AM" src="https://user-images.githubusercontent.com/20008482/184542127-1bd4ec06-bbe6-49da-96d2-7826c7bfcc78.png">

**Comment by Cowio** [comment]
Oh it does work. It shows a whole heart but only heals half a heart. Thanks and sorry for wasting your time... I feel kinda dumb.
