### ISSUE TITLE
[SUGGESTION] parody scoreboard team colors with vanilla

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#236]
**Problem:**
SkBee color names for teams do not match vanilla
to get vanilla red, you must type "pink"
for blue, you must type "brown"
etc.

**Solution:**
Parody the in-game counterparts for less confusion
red, dark_red, blue, dark_blue, aqua, dark_aqua, dark_purple, light_purple, black, white, yellow, gold, gray, dark_gray, green and dark_green
either with underscores or without

**Context:**
I couldn't find documentation on this problem, so I ended up having to set the team colors in vanilla and then use effect commands to get SkBee to broadcast what it's interpretation of the colors were, after a lot of head scratching, you can imagine how shocked I was to see it tell me that blue was secretly brown the whole time

**Comment by ShaneBeee** [comment]
Not an SkBee issue, since SkBee uses Skript colors
