### ISSUE TITLE
[BUG] while hover event with useing variable 

### ISSUE THREAD

**Issue by gagore** [ShaneBeee/SkBee#237]
**Describe the bug**
useing variable caus the bug

**To Reproduce**

		set {_b} to a new text component from "&7[&bITEM&7] &r"
		set {_item} to stone named "hello" with lore "&aworld"
		set hover event of {_b} to hover event showing {_item} 
		send component {_b} # hober event does not work
		set hover event of {_b} to hover event showing stone named "hello" with lore "&cworld"
		send component {_b}

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.
![image](https://user-images.githubusercontent.com/93857579/185048299-ea1819d7-891a-45bf-b098-722cf0f222cf.png)

![image](https://user-images.githubusercontent.com/93857579/185048264-f2cca3d8-7b99-42d7-a6c0-ac72df8802d0.png)

**Version Info:**
SkBee Version: 1.17.3 & 2.0.0
Skript Version: 2.6.3
Server Version/Platform paper1.19

**Comment by ShaneBeee** [comment]
this isn't a bug, this is just a funny quirk with the syntax, this is why I added the optional `[item]` part to the syntax:
in the docs:
`[a] [new] hover event showing [item] %itemtype%`
