### ISSUE TITLE
[BUG] tag ".." of nbt of .. is parsed as what?

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#24]
**Describe the bug**
I was using Sk-NBeeT and I loaded Sk-Bee. in Sk-Bee, I can't change parse type of tag ".." of nbt of .. things. I get error `Tag ""........"" of the ... is not a text`

**To Reproduce**
I loaded Sk-Bee and I check my other scripts designed with Sk-NBeeT

**Expected behavior**
No error should be

**Version Info:**
 - **SkBee Version:** 1.3.3
-  **Skript Version:** 2.4.1
 - **Server Version/Platform** Paper 1.15.2 322

**Additional context**
You can test it with this codes. Just add them to a test server:
```
on damage of player:
		if damage cause is drowning:
			if tag "OzelEsya" of nbt of victim's helmet is """Poseidon Kaskı""":
				set {_durability} to tag "Dayaniklilik" of nbt of victim's helmet parsed as number [Skript] the object nbt of the helmet of the attacked entity parsed as a number is not a text (a_2_Survival_Rules\damageHandlers.sk, line 70: set {_durability} to tag "Dayaniklilik" of nbt of victim's helmet parsed as number')
				set {_maxdurability} to tag "MaxDayaniklilik" of nbt of victim's helmet parsed as number #[Skript] the object nbt of the helmet of the attacked entity parsed as a number is not a text (a_2_Survival_Rules\damageHandlers.sk, line 71: set {_maxdurability} to tag "MaxDayaniklilik" of nbt of victim's helmet parsed as number')
```

**Comment by ShaneBeee** [comment]
SkBee's NBT is a bit different. Rather than returning everything as a String from a tag, it returns the correct type.
So if the tag returns 2, it'll return the number 2 not "2"

This is not a bug, this is intended behaviour.
