### ISSUE TITLE
[BUG] Scoreboard error

### ISSUE THREAD

**Issue by Nowis37** [ShaneBeee/SkBee#246]
**Describe the bug**
Hello, i make many scoreboard on my servers, and i only used skbee for the scoreboard. It's working very well with minecraft 1.18 but when i try with older version, my scoreboard is like cut.

Other problem, i want use skbee 2.0.0 but when i upload it, my server don't start. (with skbee 1.16 is starting well).

**To Reproduce**
Just try with older version than 1.18.

**Screenshots/Errors**
![bug scoreboard](https://user-images.githubusercontent.com/26161603/186136895-d41eca72-1041-4a42-8b04-188ca39f05e9.png)

**Version Info:**
 - Provide output of **/skbee info**   
 **OR**
 - **SkBee Version:** (ex: 1.16)
 - **Skript Version:** (ex: Skript 2.6.1)
 - **Server Version/Platform** (ex: Paper 1.18)

Thanks for your help, you make beautiful work !

**Comment by ShaneBeee** [comment]
This isn't an issue with SkBee, this is an issue with character limit of scoreboards on older version of Minecraft.
