### ISSUE TITLE
[BUG]I created code like this, it's not available, help

### ISSUE THREAD

**Issue by lizheyo77** [ShaneBeee/SkBee#248]
on region enter:
  set {_bar} to bossbar named "myCoolBar" with title "&aHello &bWorld!" with color bar blue with style segmented 6
  if "%event-region%" contains "tcsldp":
    add player to bar players of {_bar}
    set bossbar visibility of {_bar} to true

I created code like this, it's not available, help

**Comment by ShaneBeee** [comment]
Closing due to lack of information.

It appears you didn't bother to fill out the template provided, you just deleted it and provided 0 details.
I can't fix a bug if there is no presence of a bug
