### ISSUE TITLE
[BUG] player armor change event is outdated on docs or not working properly

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#25]
**Describe the bug**
I'm trying to cancel event on player armor change but skript error saying I can't.

**Expected behavior**
https://skripthub.net/docs/?id=4139
Should use cancel event

**Screenshots/Errors**
`An on armor change event event cannot be cancelled (a_2_Survival_Rules\Survival.sk, line 51: cancel event')`

**Version Info:**
 - **SkBee Version:** 1.3.3
-  **Skript Version:** Skript 2.5-alpha3
 - **Server Version/Platform** Paper 1.15.2 322

**Additional context**
For test:
```
on player change armor:
	if event-item is diamond chestplate or diamond leggings:
		cancel event
```

**Comment by ShaneBeee** [comment]
The error literally gives you the answer. An armor change event cannot be cancelled.

**Comment by rudde0** [comment]
¯\_(ツ)_/¯

https://imgur.com/a/zKCd2vk

**Comment by ShaneBeee** [comment]
Oh my example is wrong, ill have to update that at some point.
