### ISSUE TITLE
[BUG] Scoreboard broken feature

### ISSUE THREAD

**Issue by MennoGamed** [ShaneBeee/SkBee#250]
### Describe the bug:
In SkBee v2.2.0 the following feature has been added: _"Scoreboard now only sends packets if something changed (ie: repetitively setting the same line won't send packets)"_
Now I think this feature breaks the option to create scoreboards where you have to update the same line every second, with a little bit of difference in it.

In SkBee v2.1.0 the scoreboard works as expected.

### To Reproduce
- Use SkBee v2.2.0
- Use an code that look like this, but you can use your own:
![image](https://user-images.githubusercontent.com/64696706/188569321-c07f1264-e193-4f77-a9ca-bba6b16aa87c.png)
_the code in the picture doesn't work, my mistake. But think the idea says enough_

### Expected behavior
That the scoreboard updates when the lines are changed, whether this is after 1 tick, 1 second or longer.

### Screenshots/Errors:
There are no errors in the console, but I did add a video showing what happens.

### Version Info:
 - **SkBee Version:** v2.2.0
 - **Skript Version:** v2.6.3
 - **Server Version/Platform:** git-Purpur-1774 (MC: 1.19.2)

### Additional context
I think a solution would be to just check if the line has been changed, and then update it instead of checking if a line is changed too often.
_If there is any uncertainty, feel free to ask. I will do my best to provide as much information as possible :)_

https://user-images.githubusercontent.com/64696706/188567965-6a3e7e45-81eb-4665-9f4a-f851c0b54d7f.mp4

**Comment by jurajplayercze** [comment]
I am not sure if it's the issue, but you looping all plyers, and then suddently using `{_p}`, like `set title of {_p}'s scoreboard...`

**Comment by MennoGamed** [comment]
> I am not sure if it's the issue, but you looping all players, and then suddenly using `{_p}`, like `set title of {_p}'s scoreboard...`

_the code in the picture doesn't work, my mistake. But think the idea says enough_
I had already typed under it after realizing that. It's about the counterfeiting idea. I didn't put in the direct code I'm using.

**Comment by ShaneBeee** [comment]
After doing some testing, I realized its nothing about the "sending packets only if changed", but actually due to me making the board send packets async. I guess that just doesn't work
