### ISSUE TITLE
[SUGGESTION] Touching bound vs inside bound

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#251]
**Problem**
I set some bounds to be at the corners of blocks, that way I can pretend that the bound occupies the same 3d space that a block would. This leads to problems when a player's Y level is at the exact height. If you set a bound to be +0.5 in all coords, and -0.5 in all coords from the location of a block, the average user would not expect it to count you as inside the block, when you stood on top of it. The same problem happens when a player stands right up against a block on the border.

**Describe the solution you'd like**
I believe this happens because the bound checks are using <= and >=. I propose a way to alter that. So a bound could be flagged as an "inclusive" bound, or a "block bound". Or perhaps a check for if the location, entity, etc. is "touching" the bound, or if a location is on the "surface" of the bound. Just something that exposes us to that decision if it should be <= or only <.

**Describe alternatives you've considered**
You could say to me, why don't you just make the bound ever so slightly smaller? Sure that would be a band aid. But then players, entities, locations, could theoretically occupy the space between two bounds - or a raycast to a location on a wall wouldn't technically be "touching" the edge of the bound.

**Comment by ShaneBeee** [comment]
The issue here is Skript's location for blocks adds 0.5 on all three axis, which means a block at 1,1,1 would be in Skript 1.5,1.5,1.5.
This was a bug on my behalf. When I changed some things with bounds I forgot to manage that part.
