### ISSUE TITLE
[BUG] 'none' is not a structure rotation

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#254]
**Describe the bug**
Cannot reset the rotation of a structure, because none is not recognized as a valid structure rotation

**To Reproduce**
`set rotation of {_structure} to none`

**Expected behavior**
Structure rotation would be set to none

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/6758224/190047397-f05e102e-2ef1-4332-985a-f28af4de4cab.png)

**Version Info:**
![image](https://user-images.githubusercontent.com/6758224/190047482-125d507f-d4d7-495b-88a2-3dd289ae5604.png)
![image](https://user-images.githubusercontent.com/6758224/190047532-d3421eb1-f6a7-4381-b5d0-55ba1dfb6bd7.png)
![image](https://user-images.githubusercontent.com/6758224/190047558-642a4e1b-c7ac-43a8-9d8c-039548f58274.png)

**Additional context**
`set rotation of {_structure} to ("none" parsed as structure rotation)` does work

**Comment by ShaneBeee** [comment]
unfortunately this is an issue with Skript, not SkBee.
Skript has a hard time parsing some things as the correct type, due to overlaps, and "none" is most likely used as another class.
Doing some light testing, it looks like Skript is trying to use NONE from Structure Mirror.
