### ISSUE TITLE
[BUG] Unclear scope of structure properties

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#255]
**Describe the bug**
It is unclear that changes to a temp variable that references a structure would persist, because SkBee stores the information of those properties outside of the scope of the temp variable

**To Reproduce**
`	# Load and orient structure
	set {_structure} to structure named "minecraft:example"

	set rotation of {_structure} to clockwise 180
	
	# Paste structure
	place {_structure} at {_location}`
^ this will retain the information of the structure's rotation

so if you later do this:
`	# Load and orient structure
	set {_structure} to structure named "minecraft:example"
	
	# Paste structure
	place {_structure} at {_location}`
^ this will also be rotated

**Expected behavior**
I would expect {_structure} to be a local object that has the following properties:
structure: "minecraft:example"
rotation: "clockwise 180"
and that it wouldn't effect anything outside of that code block

**Screenshots/Errors**
Source: trust me bro

**Version Info:**
![image](https://user-images.githubusercontent.com/6758224/190049004-80e60e8d-aa96-416c-a775-228ff39c7a1c.png)
![image](https://user-images.githubusercontent.com/6758224/190049029-ba4b136e-b0c1-4982-af9b-fa4623bd7f16.png)
![image](https://user-images.githubusercontent.com/6758224/190049045-86b648da-365d-4053-a7d6-3b5a7a959313.png)

**Additional context**
SkBee is a must-have, keep up the great work!

**Comment by ShaneBeee** [comment]
This is not a bug. SkBee caches structures that are loaded, to prevent attempting to load the same structure over and over again. 
These caches are not persistent, they're simply just stored in memory. 

Removing this cache could cause issues, ex:
```vb
set rotation of structure named "minecraft:example" to clockwise 180
paste structure named "minecraft:example" at {_location}
```
that would totally break this

While I understand your issue of the object being in a local var, its not storing the object, its storing the reference to the object.
This is essentially no different than many objects on the server.
Take storing an entity/player in a local var. Each time you set the local var to said entity/player, it's a reference to the same object as before.
