### ISSUE TITLE
[BUG] SkBee Deletes NBT on Blocks from other plugins for some reason

### ISSUE THREAD

**Issue by MrEnxo** [ShaneBeee/SkBee#256]
**Describe the bug**
So im making a plugin and using the Same NBT API Skbee uses and im adding custom NBT to blocks, the nbt works but whenever Skbee Tries to check the NBT it just flat out deletes it, I have even tried putting my NBT into a custom tag but still doesnt work

**To Reproduce**
use de.tr7zw.item-nbt-api and add Custom NBT to a block and then read that nbt with Skbee

**Expected behavior**
Im pretty sure it shouldn't delete my NBT but idk, it could be a user error with this API.
I can read my own nbt that I declare in my plugin but once SkBee Reads it, its deleted.
The NBT is also saved between restarts in my plugin, which if I wasnt setting the NBT right it should wipe it, if im correct.

 - **SkBee Version:** 1.18.0-BETA2
 - **Skript Version:** 2.6.2 
 - **Server Version/Platform** Paper 1.17.1

**Comment by ShaneBeee** [comment]
Definitely not your fault, SkBee's custom block class is a bit different, and was setup without other plugins in mind.
I'll have to do some rework to it, to help alleviate this issue.

**Comment by MrEnxo** [comment]
i might look into it myself to see if I can provide a temporary solution for myself

**Comment by ShaneBeee** [comment]
try the build from the latest commit, that should solve your issue... let me know

**Comment by MrEnxo** [comment]
I'm in class right now I will check when I get home

**Comment by MrEnxo** [comment]
LOLOL ok, i just tested this and yes it does work but, also as I was referring to earlier for some reason if I use set the custom tag on a block to my own NBT skbee just deletes it too, I feel like that should be looked into. Idk that could have been a me issue but 🤷🏻

**Comment by ShaneBeee** [comment]
SkBee's NBT was never intended to work with other plugins in mind. 
So I will have to do a few more changes to make sure it doesn't cause issues.

**Comment by ShaneBeee** [comment]
^
Ok try the build from the commit above. That SHOULD fix your issue.

**Comment by MrEnxo** [comment]
I'm in class again lol

**Comment by ShaneBeee** [comment]
> I'm in class again lol

RUDE... jk jk.

**Comment by MrEnxo** [comment]
Lol
