### ISSUE TITLE
[BUG]Can't use this script after upgrading 1.19.2

### ISSUE THREAD

**Issue by lizheyo77** [ShaneBeee/SkBee#258]
[07:23:05] [Server thread/ERROR]: [Skript] Line 26: (区域死亡计数.sk)
    Can't understand this condition/effect: set {bar::list1::%player%} to boss bar named "list1" with title "&c你当前区域的死亡次数: &a%{deaths::%player%}%次" with color bar blue with progress 50
    Line: set {bar::list1::%player%} to boss bar named "list1" with title "&c你当前区域的死亡次数: &a%{deaths::%player%}%次" with color bar blue with progress 50
 
[07:23:06] [Server thread/ERROR]: [Skript] Line 28: (区域死亡计数.sk)
    Can't understand this condition/effect: add player to bar players of {bar::list1::%player%}
    Line: add player to bar players of {bar::list1::%player%}
 
[07:23:06] [Server thread/ERROR]: [Skript] Line 33: (区域死亡计数.sk)
    Can't understand this condition/effect: remove player from bar players of {bar::list1::%player%}
    Line: remove player from bar players of {bar::list1::%player%}
 
[07:23:06] [Server thread/ERROR]: [Skript] Line 34: (区域死亡计数.sk)
    Can't understand this condition/effect: delete bossbar named "list1"
    Line: delete bossbar named "list1"
 
[07:23:06] [Server thread/ERROR]: [Skript] Line 39: (区域死亡计数.sk)
    Can't understand this condition/effect: set bar title of {bar::list1::%loop-player%} to "&c你当前区域的死亡次数: &a%{deaths::%loop-player%}%次"
    Line: set bar title of {bar::list1::%loop-player%} to "&c你当前区域的死亡次数: &a%{deaths::%loop-player%}%次"

**Comment by ShaneBeee** [comment]
you've provided nothing but errors.

This is why I have a template for creating bugs, so you can provide some useful information.
But you decided to just delete the template, and send a bunch of errors with no context.

Closing due to that. If you would like to open a new issue, please fill in the template.
