### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by farwl** [ShaneBeee/SkBee#26]
**Is your feature request related to a problem? Please describe.**
Sort of. I noticed Skript does not have a way to convert strings into dates.

**Describe the solution you'd like**
I'm requesting that skBee have an expression to convert strings into dates. You can't parse as date with Skript so it would be cool if skBee had an expression for this.

**Describe alternatives you've considered**
There aren't any alternatives.

**Comment by ShaneBeee** [comment]
Things like this should be suggested to Skript, not addons.
The way Skript registers objects it is not possible for an addon to add parsing ability to the already defined Skript object.

**Comment by Runakai1** [comment]
Skript has a date function.

**Comment by farwl** [comment]
Ah, thanks.
