### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SertanVS** [ShaneBeee/SkBee#263]
**Describe the bug**
using hidden item flags for gui's now gives errors (using skript-gui) dont know it it happens to vanilla guis

**To Reproduce**
options:
	pickaxe: unbreakable iron pickaxe named "&f&l&k|||&r&6&l Spawner Pickaxe &f&l&k|||" with lore "<##266DAB>&lHave Fun Mining Spawners :)" with attribute flag hidden
	fun_pickaxe: unbreakable gold pickaxe named "&f&l&k|||&r&6&l Fun Pick &f&l&k|||" with lore "<##266DAB>&lUsing This Mines 3x2... :)" with attribute flag hidden

command /cu:
	trigger:
		create a gui with virtual chest inventory with 5 rows named "&2Cus":
			format gui slot 10 with {@pickaxe}
			format gui slot 15 with {@fun_pickaxe}
		open last gui to player

**Version Info:**
 - **SkBee Version:** 2.3.2
 - **Skript Version:** 2.6.2
 - **Server Version/Platform**paper 1.19

![Screenshot_299](https://user-images.githubusercontent.com/31593334/191105106-64d0c4d0-6894-4055-a0dd-19bee7d264c6.png)

**Comment by ShaneBeee** [comment]
not a bug, its `attributes flag`  (you were missing the "s")

**Comment by SertanVS** [comment]
> not a bug, its `attributes flag` (you were missing the "s")

in the previous version i could use "with attribute flag hidden" I'll try it and see
