### ISSUE TITLE
[BUG] NBT doesn't register

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#264]
**Describe the bug**
I'm attempting to check for a specific nbt tab, it's confirmed to be there from pretty nbt, but within conditions it won't show

**To Reproduce**
`command /hoe:
    trigger:
        give player wooden hoe with all flags hidden named "&7ImNotStable's Hoe" with lore "" and "&7&lCommon" with nbt (nbt compound of "{custom: {farminghoe: true}}")

on right click:
    cancel event
    player's tool is wooden hoe
    send "1"
    send pretty nbt of nbt compound of player's tool
    set {_} to tag "custom;farminghoe" of nbt compound of player's tool
    send "%{_}%"
    if nbt compound of player's tool has tag "custom;farminghoe":
        send "2"`

**Expected behavior**
It to send "2"

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/51060503/191861717-9b2c947f-f6b1-421d-acb6-8e6eaffdabeb.png)

**Version Info:**
Server Version: git-Paper-387 (MC: 1.18.2)
Skript Version: 2.6.3
Skript Addons:
- Beamer v1.0.3
- skUtilities v0.9.2
- skRayFall v1.9.28
- SkQuery v4.1.7
- SkJade v1.4.2
- Khoryl v1.0.6
SkBee Version: 2.3.2
SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
This is an error on your behalf.
You are using the wrong tag

This is explained in the docs:
<img width="856" alt="Screenshot 2022-09-22 at 3 26 39 PM" src="https://user-images.githubusercontent.com/20008482/191862296-05004d59-a5fb-4fb0-8779-d69a87280e44.png">

If you need further help with how NBT works, I recommend asking for help on skUnity's Discord before reporting something like this as a bug.
