### ISSUE TITLE
[BUG] Scoreboard syntax

### ISSUE THREAD

**Issue by jurajplayercze** [ShaneBeee/SkBee#266]
**Describe the bug**
Just little problem with one type of syntax for scoreboard expression
We are able to use this syntax where can be objects(players)
```
toggle [score]board[s] of %players% [[to ]((on|true)|(off|false))]
```
But this syntax contain only one object(player)
```
line %number% of [score]board[s] of %player%
```
So i can't use it for more players at once. 

So this did not work for me
![image](https://user-images.githubusercontent.com/83863655/192105303-4c05b18d-ffc5-4ad6-b61b-ead9b1327d2d.png)
![image](https://user-images.githubusercontent.com/83863655/192105315-3ad53f7d-deac-4b53-9128-5adb420a36c2.png)

**Version Info:**
 - **SkBee Version:** 2.3.2
 - **Skript Version:** 2.6.3
 - **Server Version/Platform** 1.19.1

**Comment by ShaneBeee** [comment]
that was a typo on my behalf when I wrote it
The first option you CAN use multiple players
The second one you CANT
<img width="628" alt="Screenshot 2022-09-24 at 8 19 05 AM" src="https://user-images.githubusercontent.com/20008482/192105865-aae47faf-036e-4051-aafd-9b171a470696.png">

**Comment by jurajplayercze** [comment]
Yeah. I mentioned that only one syntax is broken. 
![image](https://user-images.githubusercontent.com/83863655/192106055-16e4e4d6-c613-4f41-9fc9-c9e3de396924.png)

**Comment by ShaneBeee** [comment]
my bad, I miss read how you wrote it
