### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Logr07** [ShaneBeee/SkBee#269]
**Describe the bug**
I am not able to set nbt tag to "now" (time). It does not set the tag and sends error to console. Problem is with line 37.
![image](https://user-images.githubusercontent.com/79524478/193352140-f507c544-8826-4da5-b4e2-25a83a2b4c35.png)

**To Reproduce**
Use command /vapo and it will not set tag "date".

**Expected behavior**
Set tag "date" to now (like this: 30/09/2022, 22:36)

**Screenshots/Errors**
error in console:
![image](https://user-images.githubusercontent.com/79524478/193352609-fb87131e-c8d2-4d0a-b75e-d445792fba77.png)
nbt of given item:
![image](https://user-images.githubusercontent.com/79524478/193352793-7ec22cb2-ffa8-47d5-8c39-f469ed809294.png)

**Version Info:**
 - Provide output of **/skbee info**   
 **OR**
 - **SkBee Version:** 2.3.2 (I posted few hours ago similar issue, so I have that updated version)
 - **Skript Version:** 2.6.1
 - **Server Version/Platform** git-Purpur-1632 (MC: 1.18.2)

**Additional context**
x

**Comment by ShaneBeee** [comment]
I wouldn't call this a bug. You can't set an NBT tag to a Skript type.
