### ISSUE TITLE
ScoreBoard Not Working

### ISSUE THREAD

**Issue by ProvokedEel** [ShaneBeee/SkBee#27]
**Describe the bug**
The scoreboard will not appear in game. I have consulted with the Skript discord and no one can figure it out. Thus it must be a bug. My hunch is that another plugin I have installed on the MineHut server is conflicting with it.

on join:
	while player is online:
		clear scoreboard of player
		#wait 0.5 second
		set title of player's scoreboard to "&6&lStoneHut Gaming"
		set line 9 of player's scoreboard to "&a&r"
		set line 8 of player's scoreboard to "&8User: &f%player%"
		set line 7 of player's scoreboard to "&6&l&r-----------------------"
		set line 6 of player's scoreboard to "&aBal: %balance of player%"
		set line 5 of player's scoreboard to "&6&l-----------------------&r"
		set line 4 of player's scoreboard to "&a&r"
		set line 3 of player's scoreboard to "&7         stonehut.minehut.gg"
		wait 5 seconds

List of Plugins
![image](https://user-images.githubusercontent.com/66457192/83837724-2d7a9d80-a6c5-11ea-97a7-a834a09bbddc.png)

**Comment by ShaneBeee** [comment]
Can not reproduce.
I used your exact code, and here is the outcome:
<img width="966" alt="Screen Shot 2020-06-05 at 1 51 25 PM" src="https://user-images.githubusercontent.com/20008482/83921761-ef689280-a733-11ea-965f-506dcee4144e.png">

My guess is another plugin is maybe overriding your scoreboard.

**Comment by ProvokedEel** [comment]
Thank you for the reply, do you have any idea which one. I love this addon on my other server, thank you for making it!

**Comment by ShaneBeee** [comment]
Not sure. you're going to have to remove plugins and figure out which one is causing the issue.
I think SkRayFall can cause issues. In the SkRayFall config, theres a setting to do with scoreboards, try setting that to false. 
Other than that, I have no clue.

**Comment by ProvokedEel** [comment]
I tried that, ended up changing to KiteBoard. Thanks though.
