### ISSUE TITLE
SkBee automatically disabled

### ISSUE THREAD

**Issue by power2220** [ShaneBeee/SkBee#273]
Server version: Paper 1.19.2 
SkBee version: 2.4.0

SkBee is automatically disabling itself, I don't know why.

[09:38:43] [Server thread/INFO]: ================ [SCore] ================
--
520 | [09:38:43] [Server thread/INFO]: [SkBee] Enabling SkBee v2.4.0
521 | [09:38:43] [Server thread/INFO]: [SkBee] Dependency Skript is not enabled, plugin disabling.
522 | [09:38:43] [Server thread/INFO]: [SkBee] This could mean SkBee is being forced to load before Skript.
523 | [09:38:43] [Server thread/INFO]: [SkBee] Disabling SkBee v2.4.0

Here's the full logs if needed
https://mclo.gs/DDslILm

**Comment by ShaneBeee** [comment]
Its disabling itself because something on your server is forcing Skript to load after SkBee

see this discussion:
https://github.com/ShaneBeee/SkBee/discussions/214
