### ISSUE TITLE
[BUG] nbt of file not working

### ISSUE THREAD

**Issue by c0dingnoobi** [ShaneBeee/SkBee#276]
**Describe the bug**   
When loading nbt (in this case .dat) files using ```nbt compound of file %string%``` it fails to get the file with an error stacktrace.

**To Reproduce**   

1. Try to set a variable to playerdata .dat file ```nbt compound of file %string%```
2. See error in console

**Expected behavior**   
Loading the file correctly into the variable

**Screenshots/Errors**   
![image](https://user-images.githubusercontent.com/97745777/199308167-447f85fb-6b41-4e1f-bbf3-52019d4e3632.png)
![image](https://user-images.githubusercontent.com/97745777/199308193-411e69eb-7792-4474-9fbd-7ca6e8f0ec5e.png)

**Version Info:**
```
Please provide output of '/skbee info' here!
```
![image](https://user-images.githubusercontent.com/97745777/199309021-3e0c0720-2971-43c1-a3cf-2b431297a841.png)

**Additional context**   
Can't think of any idk.

**Comment by ShaneBeee** [comment]
Could you please show code that you used to get this

**Comment by c0dingnoobi** [comment]
Sure. 
![image](https://user-images.githubusercontent.com/97745777/199313922-70e88a16-a337-4eeb-b1e5-2e47ef42faf5.png)
Ignore the upper part. 
Made kind of debug to tell me if the path exists. Broadcasts true

**Comment by c0dingnoobi** [comment]
Thanks, works as expected now.

**Comment by ShaneBeee** [comment]
Glad to hear it works

Just a note: I keep issues open until I actual push a release.
This way if someone has the same issue, they don't need to re-report it since its there

**Comment by c0dingnoobi** [comment]
Oups my bad. Didn't thought of that.
