### ISSUE TITLE
[SUGGESTION] 'xp of %player%'

### ISSUE THREAD

**Issue by not-3than** [ShaneBeee/SkBee#279]
**Is your feature request related to a problem? Please describe.**
Not a problem with SkBee. I recently deleted TuSKe since it is outdated and causes lots of issues, but it had one effect that I really like having, 'player's xp', as seen here: https://skripthub.net/docs/?id=1274
I am wondering if you can add this to SkBee. Skript has 'player's level' but that doesn't give the player's exact xp amount, and you can only change it by levels.

**Describe the solution you'd like**
A 'player's xp' expression that can be manipulated by the server to add single experience points or large portions of experience points. There is no other addon (that I know of or that is listen on SkriptHub) that has this capability. It would be nice to be able to change the xp value instead of being restricted to the level value.

**Describe alternatives you've considered**
I could download TuSKe, to use it, but it is outdated, and everyone bullies me if I have it downloaded.

**Additional context**
![image](https://user-images.githubusercontent.com/67490606/200046422-310e3321-1469-4f05-9eaf-cdefa65eb619.png)

**Comment by ShaneBeee** [comment]
I highly recommend looking at the docs before suggesting something:
https://skripthub.net/docs/?id=4086
