### ISSUE TITLE
[SUGGESTION] add clientsided entities + armor stnads

### ISSUE THREAD

**Issue by DontSharee** [ShaneBeee/SkBee#286]
It would be cool for you to add clientsided armor stands and entities. Using protocollib for this probably.

**Comment by ShaneBeee** [comment]
As I've stated many times, I will not be adding anymore APIs/Libraries (ie: protocolLib), and I will not be doing anything via NMS (unless necessary)
That said, I will not be adding this, but thank you for the suggestion
