### ISSUE TITLE
[SUGGESTION] Add PlayerCommandSendEvent to manipulate commands sent to players

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#287]
**Is your feature request related to a problem? Please describe.**
I hate that I have no way of changing the commands that appear when tabbing with just "/" in my Minecraft Server and I would like a way to set it so specific commands are shown only.

**Describe the solution you'd like**
Any way to change the commands that appear, at one point I tried to use `on tab complete` which obviously didn't work but I assume it'd be an event with an expression like `%tab completions%`

**Describe alternatives you've considered**
I attempted to use Command Blocker on 1.18.2 but there were many issues with the latest version, I ran into multiple errors.

**Comment by ShaneBeee** [comment]
Are you referring to the command map sent to the player?
the command right after `/` isn't part of tab completions.

When the player logs into the server, a list (command map) of all commands the player has permission for is sent to the client.
The commands the player can see is strictly client side.

I could add the event for when this map is sent to the player, and you could modify it then.

**Comment by ImNotStable** [comment]
Yeah, I would love something like that. I think others might because some commands such as TAB or Tebex leave commands for default players in that list.
