### ISSUE TITLE
Recipes in recipe book

### ISSUE THREAD

**Issue by DwlPl** [ShaneBeee/SkBee#29]
Hello.
I added a new recipe to the server and it was a hoe.
It is made like a simple hoe, only gold ingots are named.
I unlocked it in the recipe book.
When he shows it to me in the recipe book, he shows that I don't have the needed items even if I have them.
I will add that all names match.

**Comment by ShaneBeee** [comment]
Thats a glitch on Spigot/Minecraft's end, due to Minecraft not supporting NBT in recipes, therefor spigot had to do hacky methods for that to work, but the client doesn't recognize them. 
I have no control over that.
