### ISSUE TITLE
[SUGGESTION] Quit reason

### ISSUE THREAD

**Issue by not-3than** [ShaneBeee/SkBee#291]
**Is your feature request related to a problem? Please describe.**
I want to get the reason a player has left the server, so my combatlog system can only combatlog people if they purposefully quit, not if they get kicked.

**Describe the solution you'd like**
When a player quits, a syntax that gives me the reason the player has quit (like how paper servers by default show this in console)

**Describe alternatives you've considered**
I can make it in skript-reflect pretty easily, but I feel this will be useful not only for me but for others as well, which is why it should be added.

**Additional context**
https://jd.papermc.io/paper/1.17/org/bukkit/event/player/PlayerQuitEvent.html#quitMessage()

**Comment by ShaneBeee** [comment]
you meaning like the one Skript already has?
https://docs.skriptlang.org/expressions.html#ExprMessage
`[the] (quit|leave|log[ ]out|kick)( |-)message`

**Comment by not-3than** [comment]
Sorry, no. I mean the reason the player disconnected not the quit message. I think I gave the wrong link, but there is a getReason() on that same page.
