### ISSUE TITLE
[SUGGESTION] Tablist utilities

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#294]
**Is your feature request related to a problem? Please describe.**
So today I'm looking into my options for tablist addons for skript, and I noticed from SkriptHub that the options are pretty few and far between - and often outdated.

**Describe the solution you'd like**
It would be amazing if you could bring a project like https://github.com/TlatoaniHJ/Tablisknu under the umbrella of SkBee, as the tablist is a really big part of making custom servers. Furthermore, I believe something like this heavily aligns with SkBee's mission statement to "help make your server the best it can be".
Not to mention that all other HUD elements like the boss bar and scoreboard have already found their homes here - away from other abandoned projects.

**Describe alternatives you've considered**
Right now I have two options, really.

1.) Create my own system with packets and such to handle scoreboards
which I could do sure, but I don't think something like that is within the grasp of the average skript user, who I worry will have to deal with 3rd party plugins that they don't know how to incorporate into their skripts via something as advanced as reflection, and have to sacrifice the control and creativity that skript brings them.

2.) Use Tablisknu
a project which has not been updated for 3 years, and which I am about to find out whether or not it breaks my server and which features actually still function.

**Additional context**
My name a Jeff

**Comment by ShaneBeee** [comment]
So what exactly are you looking for here?
Just saying "more tablist stuff" doesn't really tell me what you're looking for.

**Comment by boxic** [comment]
The ability to create, update, and manipulate tablists in similar (or more advanced) ways to the addon I referenced, Tablisknu.

- Create a new tablist
- Add players to said tablist (as in they now see that tablist, I don't mean making them appear online on that tablist)
- Edit the "tabs" of the tablist directly as if it were a grid of cells, see Tablisknu's Array Tablist feature
- Modify the player skulls, names, ping, and scoreboard value that appears in said tabs
- Tablist settings, like if new players should appear on the tablist (assuming it's not an array tablist) like normal
- Edit the header and footer by referring to their lines like `set line 2 of {-tablist}'s tablist header to "%{_player-count}% Players Online"`
- Hide/show specific players on tablists
- Delete a tablist

these sorts of things

**Comment by ShaneBeee** [comment]
Unfortunately that all requires either NMS or packets, both of which I won't be doing.

**Comment by boxic** [comment]
sadge, fair enough. but on the bright side, I think the outdated addon still mostly works - but I had to pivot away from working on that for today, so I will do some more thorough testing later.

welp, thanks for responding then!
