### ISSUE TITLE
[SUGGESTION] Support for minecraft 1.16

### ISSUE THREAD

**Issue by varion500** [ShaneBeee/SkBee#30]
SkBee is not supported for minecraft 1.16. (spigot 1.16.1)
(When) will it be supported?

**Comment by ShaneBeee** [comment]
1) This isn't the place to be asking when another plugin is going to update
2) I am one of the devs of Skript, the plugin has already been updated to work for 1.16, hence how I have a working test environment. On that note, the 1.16 support in SkBee was just an update to the NBT-API, and has nothing to do with Skript.
