### ISSUE TITLE
[BUG] Invalid Syntax in Bossbar Wiki

### ISSUE THREAD

**Issue by Baezor1** [ShaneBeee/SkBee#311]
**Describe the bug**   
There are a few small errors in the examples in the bossbar wiki. Every example that changes the color of a bossbar says `with color bar %color%` instead of `with color %color%`

**To Reproduce**   
You can find it here https://github.com/ShaneBeee/SkBee/wiki/Bossbars

**Expected behavior**   
The syntax just needs to be corrected to avoid users complaining that it is broken.

**Screenshots/Errors** 
![Screen Shot 2023-01-01 at 3 09 50 PM](https://user-images.githubusercontent.com/64096464/210184635-7bc0033f-a905-4fef-8e75-40a1d289c188.png)
![Screen Shot 2023-01-01 at 3 10 32 PM](https://user-images.githubusercontent.com/64096464/210184646-6e6d051b-9d53-4be9-bd6d-444622c67a8e.png)

~~**Version Info:**~~
This is a wiki issue, so none needed.

~~**Additional context**~~

**Comment by LoganLilypad** [comment]
Currently, the syntax provided in the examples is valid. They were written when SkBee had its own datatypes for colors to prevent clashing with the Skript color datatype (hence why they are prefixed with `bar`). And now both datatypes are supported interchangeably, and the plan is to migrate over to the normal Skript datatype soon. Once that does happen, I'll update the wiki accordingly.

**Comment by Baezor1** [comment]
Ahh, well it was giving me errors when I directly copy and pasted it.

**Comment by ShaneBeee** [comment]
closing as I've updated the wiki, removing "bar color"
