### ISSUE TITLE
[BUG] Issue with return in Skript-Reflect since SkBee 2.7.0

### ISSUE THREAD

**Issue by joshwenke** [ShaneBeee/SkBee#312]
**To Reproduce**   
I use this code for inventory clicks. On SkBee 2.7.0 it now has a problem with the `return` statement

`
import:
  org.bukkit.event.inventory.InventoryClickEvent

#Inventory Click Event Stuff
expression [event( |-)]([number ]key|hot[[ ]bar][ key])[ button]:
  return type: integer
  get:
    return event.getHotbarButton() + 1 if event.getHotbarButton() != -1
    return -1

expression [event( |-)]([number ]key|hot[[ ]bar][ key])[ button]( |-)slot:
  return type: integer
  get:
    return event.getHotbarButton() if event.getHotbarButton() != -1
    return -1
`

So sorry... not at a computer to be able to provide the Skript error. I also have not thoroughly tested or documented the issue. Just wanted to bring this up in case there was a problem with the update yesterday. We rolled back to the former SkBee and the issue goes away. Might be an issue with skript-reflect too. Haven't tested!

**Comment by ShaneBeee** [comment]
Closing due to lack on info.
I just loaded your code on a server with only Skript and Skript-Reflect, has an error.
this is not related to SkBee
