### ISSUE TITLE
[BUG] Bound Resize bug

### ISSUE THREAD

**Issue by DontSharee** [ShaneBeee/SkBee#316]
**Describe the bug**   
The resize bound effect does not work.

**To Reproduce**   
Create a bound, then do 'resize bound with id "BOUND" between {l1} and {l2}

**Expected behavior**   
It should resize the bound, but it doesn't and produces an error

**Screenshots/Errors**   

https://i.imgur.com/q3X3GwV.png

**Version Info:**
```
Please provide output of '/skbee info' here!
v2.5.4 but also tested in 2.7.0 and doesn't work.
```

**Additional context**   
None

**Comment by ShaneBeee** [comment]
You're using the syntax incorrectly, try `resize bound bound with id ...`
the example in the docs is wrong, but the syntax is:
`<resize [full] bound %bound% (within|between) %location% and %location%>`
