### ISSUE TITLE
Empty tag ".." returning {} instead of <none>

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#32]
paper 1.16.1
Skript 2.5-alpha3
SkBee 1.4.2

```
on BlockPlaceEvent:
	if tag "OzelEsya" of nbt of event.getItemInHand() is set:
		broadcast "%tag ""OzelEsya"" of nbt of event.getItemInHand()%"
		broadcast "true"
```

it should return <none> if my tool don't contain OzelEsya but it returning {}
you can try with flint and stell. It don't have tag "OzelEsya" but returning "{Damage:0}" when testing that code.

https://prnt.sc/tc68wa

**Comment by ShaneBeee** [comment]
Ill have to fiddle around with this some more. 
When I wrote it, I tried to have it return null, but it ended up erroring.

This isn't a bug, this is intended behaviour, but I will mark it as an enhancement and see if I can make it work.
