### ISSUE TITLE
[BUG] Bedrock (Geyser) scoreboard remains after hidden

### ISSUE THREAD

**Issue by SandsByte** [ShaneBeee/SkBee#323]
Firstly, would like to say this plugin extension is incredible, so thank you.

This issue is **not** related to the most recent update. It had existed prior. I believe it is _an issue with Bedrock clients only_.

Players enter a command which toggles the scoreboard.

However, some data remains when the scoreboard is toggled "off" for Bedrock clients (Paper + Geyser).

Setting the title does not help (rightfully so) as the board should be hidden.

```
on join:
	set {a::%player%::b} to true

command /sb [<text>]:
	trigger:
		if arg-1 is "off":
			set {a::%player%::b} to false if {a::%player%::b} is true
			sbup(player)
			send "&cToggled scoreboard off." to player
		if arg-1 is "on":
			set {a::%player%::b} to true if {a::%player%::b} is false
			sbup(player)
			send "&aToggled scoreboard on." to player

function sbup(p: player):
	if {a::%{_p}%::b} is true:
		toggle board of {_p} true if board of {_p} is false
	else if {a::%{_p}%::b} is false:
		toggle board of {_p} false if board of {_p} is true
	set title of board of {_p} to " "
```
(scoreboard toggled off on Bedrock)
[![scoreboard-off.png](https://i.postimg.cc/JhFJMdxx/scoreboard-off.png)](https://postimg.cc/f3xkvC6S)

**Comment by ShaneBeee** [comment]
When reporting an issue, please fill in the template. 

You have deleted the template that was provided, and ignored what I was asking for, ie: Skript, SkBee, server versions.

That said, I tested and yes this is a bug.

**Comment by SandsByte** [comment]
I'm sorry about that. Unrelated, I think the reason there was no template is an issue with Github. I can reproduce it as well...

1. Visit the repo Issues tab _without_ being signed in
2. Select New Issue
3. Sign into account

This opens a new issue without any template nor instruction. I sincerely apologize and wouldn't have deliberately deleted the template :( I will keep this in mind in the future. Thank you again.

**Comment by ShaneBeee** [comment]
> I'm sorry about that. Unrelated, I think the reason there was no template is an issue with Github. I can reproduce it as well...
> 
> 1. Visit the repo Issues tab _without_ being signed in
> 2. Select New Issue
> 3. Sign into account
> 
> This opens a new issue without any template nor instruction. I sincerely apologize and wouldn't have deliberately deleted the template :( I will keep this in mind in the future. Thank you again.

ahh, duly noted, thanks for letting me know.
