### ISSUE TITLE
[SUGGESTION] Event-Entity within Bound events

### ISSUE THREAD

**Issue by ImNotStable** [ShaneBeee/SkBee#324]
**Is your feature request related to a problem? Please describe.**
I'd like a way to detect when an entity exits/enters a specific zone

**Describe the solution you'd like**
An event-entity expression within
on bound enter:
on bound exit:
or
on [%entitydata%] bound enter:
on [%entitydata%] bound exit:

**Describe alternatives you've considered**
I've thought about
on entity target:

and

on zombie move:
but move is too lag intensive and entity target doesn't do exactly what I want

**Comment by ShaneBeee** [comment]
> on zombie move:
> but move is too lag intensive and entity target doesn't do exactly what I want

This is literally how it would be handled in the back end.
Currently for the bound enter/exit event, I'm using the player move event, looping all bounds, and checking if the player has border hoped. That itself is a pretty big event for the server.
Now imagine this same thing happening for every single entity on the server? Say "bye bye TPS"

That said, I'm sorry but no I will not be adding this event.

**Comment by ImNotStable** [comment]
Alright didn't realize that's the backend of the event I apologize, thought you did it some other way.
