### ISSUE TITLE
[BUG] Scoreboard Flicker V2.7.3+

### ISSUE THREAD

**Issue by savoryninja1** [ShaneBeee/SkBee#335]
**Describe the bug**   
SkBee versions 2.7.3+ cause java scoreboards to flicker constantly
SkBee introduced a fix for bedrock scoreboards but in a result it also causing damage to the java side

**Expected behavior**   
Scoreboard should be smooth and have no flickering on the java side like previous version of SkBee like SkBee 2.7.2

**Screenshots/Errors**   
```
on join:
	while player is online:
		wait 0.5 seconds
		ScoreBoard(player)

function ScoreBoard(p: player):
	toggle {_p}'s scoreboard on
	set title of {_p}'s scoreboard to "ServerName"
	set line 14 of {_p}'s scoreboard to "&7stuff"
	set line 13 of {_p}'s scoreboard to "&7stuff"
	set line 12 of {_p}'s scoreboard to "&7stuff"
	set line 11 of {_p}'s scoreboard to "&7stuff"
	set line 10 of {_p}'s scoreboard to "&7stuff"
	set line 9 of {_p}'s scoreboard to "&7stuff"
	set line 8 of {_p}'s scoreboard to "&7stuffs"
	set line 7 of {_p}'s scoreboard to "&7stuff"
	set line 6 of {_p}'s scoreboard to "&7stuff"
	set line 5 of {_p}'s scoreboard to "&7stuff"
	set line 4 of {_p}'s scoreboard to "&7stuff"
	set line 3 of {_p}'s scoreboard to "&7stuff"
	set line 2 of {_p}'s scoreboard to "&7stuff"
	set line 1 of {_p}'s scoreboard to "server.ip"
```

**Version Info:**
```
SkBee-2.7.3.jar
SkBee-2.7.4.jar
```

**Additional context**   
You should just revert the changes back to SkBee 2.7.2 scoreboards or fix it mainly because most people don't care about the bedrock side

**Comment by ShaneBeee** [comment]
have you tried not toggling the scoreboard on every time you update your scoreboard?
There's literally no reason to do that
