### ISSUE TITLE
[BUG] Error turning off the scoreboard

### ISSUE THREAD

**Issue by Drakemlumme** [ShaneBeee/SkBee#337]
### **Describe the bug**   
_I have a code with the scoreboard, with a boolean variable, when the variable is "true" the scoreboard is turned on, and when it is "false" it is turned off.
I made it possible to turn off the scoreboard in a GUI, by setting the variable to false, but when I do it an error starts spamming me in the console many times (in any case the scoreboard does turn off)_

### **To Reproduce**   
_I don't know, I think doing a periodic event that compares a boolean and turns the scoreboard on or off_

### **Expected behavior**   
_turn off the scoreboard without errors in the console_

### ****Screenshots/Errors****   
https://pastebin.com/qzM5HAPM
https://i.ibb.co/fXvXrX5/sc.png

### **Version Info:**
```
--- [SkBee Loading Info] ---
- [NBTAPI] Found Spigot: v1_18_R2! Trying to find NMS support
- [NBTAPI] NMS support 'MC1_18_R2' loaded!
- NBT Elements successfully loaded
- Recipe Elements successfully loaded
- Scoreboard Elements successfully loaded
- Scoreboard Objective Elements successfully loaded
- Team Elements successfully loaded
- Bound Elements successfully loaded
- Text Component Elements successfully loaded
- Pathfinding Elements successfully loaded
- Structure Elements disabled via config
- Other Elements successfully loaded
- Virtual Furnace Elements disabled via config
- World Creator Elements disabled via config
- Game Event Elements successfully loaded
- BossBar Elements successfully loaded
- Statistic Elements successfully loaded
- Villager Elements successfully loaded
- Advancement Elements disabled via config
- World Border Elements successfully loaded
- Particle Elements successfully loaded
- Minecraft Tag elements successfully loaded
- RayTrace elements successfully loaded
- Plugin is up to date!
--- [Server Info] ---
Server Version: git-Paper-388 (MC: 1.18.2)
Skript Version: 2.6.4
Skript Addons:
- skript-placeholders v1.5.2
- skUtilities v0.9.2
- skript-reflect v2.3
- skRayFall v1.9.28
- skript-worldguard v1.0-alpha1-nightly-caec763
SkBee Version: 2.7.4
SkBee Website: https://github.com/ShaneBeee/SkBee
```

### **Additional context**   
_Thanks for your time_

**Comment by ShaneBeee** [comment]
this is most likely already fixed in a future release.
I had some bugs that I already fixed and I think this issue stems from them.

**Comment by Drakemlumme** [comment]
I will be attentive in the future releases

**Comment by Drakemlumme** [comment]
Shane fixed it
