### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iCodeDreamsMC** [ShaneBeee/SkBee#34]
**Describe the bug**
Pasting Structures does not work with SkBee, it worked in SkNBeet (Outdated). 

**To Reproduce**
Copy and paste the example on skripthub for the structure block load / paste effect

```
command teststr:
    trigger:
        paste "house" at location of player with rotation 90 and with mirror left to right
```

**Expected behavior**
It should paste the structure that is saved with that structure name.

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/58913119/86538595-ed295d80-bec4-11ea-967f-683d043093ff.png)

**Version Info:**
 - **SkBee Version:** (ex: 1.4.2)
-  **Skript Version:** (ex: Skript 2.5-alpha5)
 - **Server Version/Platform** (ex: Paper MC 1.16.1 - 59)

**Comment by ShaneBeee** [comment]
Yes I already know about this

There’s literally a console message stating that structure elements do not work in 1.16.x

**Comment by iCodeDreamsMC** [comment]
Will it be fixed?

**Comment by ShaneBeee** [comment]
> Will it be fixed?

Read the message in console, it literally answers that for you. Its not broken, the API for structures has yet to be updated.
