### ISSUE TITLE
[SUGGESTION] Fishing

### ISSUE THREAD

**Issue by ElijahJunaid** [ShaneBeee/SkBee#340]
Adding a disable fishing events for SkBee in Config

**Comment by ShaneBeee** [comment]
SkBee doesn't have fishing events?!?!

**Comment by Fusezion** [comment]
Guessing he's referring to anything fishing. so probably would be a nice thing to add `fishing` toggle in the config.yml

**Comment by ElijahJunaid** [comment]
> Guessing he's referring to anything fishing. It would also be a nice thing to add `fishing` toggle in the config.yml

Correct! Specifically the "Fish Event State" expression.

**Comment by ShaneBeee** [comment]
Could you give a reason for this?
It’s not so easy to add a toggle for 2 expressions.

**Comment by ElijahJunaid** [comment]
> Could you give a reason for this? It’s not so easy to add a toggle for 2 expressions.

There's about half a dozen different add-ons that interfere with eachother with the "Fish Event State" expression, and while uninstalling the others is possible, it'd be a downside because of what the other add-ons add that SkBee doesn't.
It'd be nice to toggle it, so people could keep this add-on, instead of having to decide between two.
