### ISSUE TITLE
Recipes - 2x2 and 3x3 registering

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#345]
**Describe the bug**   
Do to the way skbee wishes to support crafting table recipes in shaped format it does a check for `> 4` and if it returns true we specify crafting table registered format to be as
```
A1 A2 A3
B1 B2 B3
C1 C2 C3
```
otherwise
```
A1 A2
B1 B2
```

**To Reproduce**   
1. register any recipe using 4-3 ingredients
2. attempt to craft it as a single row 
3. give up and format it as an axe head

**Expected behavior**   
It would follow my 1 line for 3 items format vs. forces it as a inventory crafting format

**Screenshots/Errors**   
**Normal Recipe for 3 items**
![image](https://user-images.githubusercontent.com/81952476/219276786-a26eddbc-b5f7-42bd-8c0c-3b3f6df22c7f.png)
**Skbee Register for 3 item recipes**
![image](https://user-images.githubusercontent.com/81952476/219276873-7b325884-9a0d-4f2c-bbf9-9ffad7e47979.png)
![image](https://user-images.githubusercontent.com/81952476/219276918-7824d565-253b-41c0-8471-9c48bd43ae30.png)
![image](https://user-images.githubusercontent.com/81952476/219276949-dc0a4111-b354-4cdb-93eb-6ae12b3a46fc.png)

**Version Info:**
```
[05:35:13 INFO]: --- [SkBee Loading Info] ---
[05:35:13 INFO]: - [NBTAPI] Found Spigot: v1_19_R1! Trying to find NMS support
[05:35:13 INFO]: - [NBTAPI] NMS support 'MC1_19_R1' loaded!
[05:35:13 INFO]: - NBT Elements successfully loaded
[05:35:13 INFO]: - Recipe Elements successfully loaded
[05:35:13 INFO]: - Plugin is not up to date!
[05:35:13 INFO]: -  - Current version: v2.7.4
[05:35:13 INFO]: -  - Available update: v2.7.5
[05:35:13 INFO]: -  - Download available at: https://github.com/ShaneBeee/SkBee/releases
[05:35:13 INFO]: --- [Server Info] ---
[05:35:13 INFO]: Server Version: git-Paper-215 (MC: 1.19.2)
[05:35:13 INFO]: Skript Version: 2.6.4
[05:35:13 INFO]: Skript Addons:
[05:35:13 INFO]: - Skacket v1.0.13
[05:35:13 INFO]: - skript-gui v1.3
[05:35:13 INFO]: - skript-yaml v1.4.1
[05:35:13 INFO]: - skript-reflect v2.3
[05:35:13 INFO]: - SkJade v1.4.2
```

**Additional context**   
I'm aware this is on 1 version behind, but knowing this wasn't fixed didn't update to test,

**Comment by Fusezion** [comment]
forgot to include skbee's ingredients of 
![image](https://user-images.githubusercontent.com/81952476/219277997-b3411709-44ce-4ecd-ab57-7c4be50e5628.png)

also Shane if you can propose how I should go about fixing this I'll include it in that pr since I have no clue currently

**Comment by ShaneBeee** [comment]
Honestly, I'd hardly call this a bug.
This was intended.
It even states in the wiki 4 ingredients or less will create a 2x2 shaped recipes for the player's crafting grid:
https://github.com/ShaneBeee/SkBee/wiki/Shaped-Recipe#setting-the-ingredients

**Comment by Fusezion** [comment]
> Honestly, I'd hardly call this a bug. This was intended. It even states in the wiki 4 ingredients or less will create a 2x2 shaped recipes for the player's crafting grid: https://github.com/ShaneBeee/SkBee/wiki/Shaped-Recipe#setting-the-ingredients

Must of never read that part. I know when I was looking at that portion that it was formatted and figured it wouldn't of been overlook. Still believe we'd be better off including some form of a change for this. Since in return we basically remove slab format recipes

**Comment by ShaneBeee** [comment]
I'm definitely open for suggestions and change.
Like I said, its not a bug, it was intentional.
That said, Its not perfect. Im sure you've seen the code for recipes... it's one of the things that was hard to interpret to Skript.
I'm ok with a change, but I don't think it should break any current behaviour. 
I've done enough breaking changes in SkBee lately that has utterly pissed off the community, I don't wanna piss them off even more :D

**Comment by Fusezion** [comment]
> I've done enough breaking changes in SkBee lately that has utterly pissed off the community, I don't wanna piss them off even more :D

Glad to hear that for another week

> I'm ok with a change, but I don't think it should break any current behaviour.

Sadly I don't see skript being able to include proper formatting without including a breaking change.
While I call it a breaking change it's more so no one will notice this via an error but rather how it'd have to be formatted.
As I proposed we'd call `air` a `null` value in registration and work around that to count 2x2 and 3x3 recipes. The only part that breaks in this is players with existing 2x2 code from this would have to modify their could to be `item, item, air, item, item`

The only other solution which I'm against and gonna say probably you as well is including a new shaped syntax exclusively for 2x2 recipes. *still would end up breaking existing code to format as `item, item, item`

**Comment by ShaneBeee** [comment]
Ok I did a change to recipes, so you will still require `air` in your code, but it won't actually register empty rows.

using this code:
```vb
on load:
	set {_i} to diamond block named "&bMrBlock"
	set {_1} to diamond ore
	register new shaped recipe for {_i} using {_1}, {_1}, {_1}, air, air, air, air, air and air with id "test_diamond"
```
Old Output:
<img width="729" alt="Screenshot 2023-02-18 at 8 57 34 AM" src="https://user-images.githubusercontent.com/20008482/219878305-5bf5518f-e2b8-4c75-ba53-e7155bedaa4b.png">
If you see the shape `Shape: [123], [   ], [   ]` you will notice blank lines, thus forcing the recipe only to work on the top row.

After Changes:
<img width="729" alt="Screenshot 2023-02-18 at 8 58 23 AM" src="https://user-images.githubusercontent.com/20008482/219878343-aaa594af-ada3-4e00-baa5-cbb1e66f220d.png">
You will now see the recipe will only register the rows with actual ingredients, thus allowing the recipe to work on any line!
<img width="258" alt="Screenshot 2023-02-18 at 8 59 13 AM" src="https://user-images.githubusercontent.com/20008482/219878394-6ececa8d-54a6-477e-87ff-613249566400.png">
<img width="258" alt="Screenshot 2023-02-18 at 8 59 19 AM" src="https://user-images.githubusercontent.com/20008482/219878396-9e9db58b-5d6d-4ef8-b69b-0590b1a2f81b.png">
<img width="258" alt="Screenshot 2023-02-18 at 8 59 24 AM" src="https://user-images.githubusercontent.com/20008482/219878397-cec95283-d72d-40e7-aa4d-b60819e9067f.png">

Ingredients will still return as air in SkBee's recipe ingredient expression. This was intentionally done a while back to make sure people understood the shape of recipes which may have had blank rows:
<img width="466" alt="Screenshot 2023-02-18 at 9 00 37 AM" src="https://user-images.githubusercontent.com/20008482/219878488-f9aae57f-b049-407c-8583-cb2eb6628fcc.png">

**Comment by Fusezion** [comment]
yup that's about what I was thinking thanks for taking the time to do it. This also should mean it allows sword shapes too which is even better as I had someone in skunity ask took awhile to explain
