### ISSUE TITLE
[BUG][Craft Scheduler Thread - 827/WARN]: [SkBee] Plugin SkBee v1.4.2 generated an exception while executing task 191

### ISSUE THREAD

**Issue by Galajus** [ShaneBeee/SkBee#35]
**Describe the bug**
Showing randomly

**To Reproduce**
I dont know, this can show 2h after start. In one sesion (10-20h) i se 2 that errors in my logs

**Expected behavior**
only warn in console

**Screenshots/Errors**
https://prnt.sc/tceano

**Version Info:**
 - **SkBee Version:** 1.4.2
-  **Skript Version:** Skript 2.5-alpha5
 - **Paperspigot 369

**Additional context**
that is my plugins: https://prnt.sc/tcexuj

**Comment by ShaneBeee** [comment]
I may have to remove virtual furnaces for the time being. 
The API I created/using is still in beta, and this shows its not working as it should

**Comment by Galajus** [comment]
Oh, i like and use this addon :( How risky is using this furnaces?
Thank you for response!

**Comment by ShaneBeee** [comment]
I did a small update, which hopefully fixes this issue.
Its not the fix I really want, but its a temp bandaid which should suppress the error.

Please try [**THIS BUILD**](https://github.com/ShaneBeee/SkBee/releases/tag/1.4.4-Beta1) and let me know if it resolves the issue.

**Comment by Galajus** [comment]
The error has disappeared :D

i found one more issue, when result slot is full furnace doesn't stop smelting items :(
https://prnt.sc/te90z5

**Comment by ShaneBeee** [comment]
> The error has disappeared :D

ok good to know. Ill close this issue and mark it as fixed. 

> i found one more issue, when result slot is full furnace doesn't stop smelting items :(

gonna have to create a new issue for that. I need to keep issues separate so I can manage them individually and mark them as completed when they're solved
