### ISSUE TITLE
[SUGGESTION] Bounds - Parenting System

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#352]
**Describe the solution you'd like**
I'd like to see a parenting system added into skbee bounds, a system like this should effect all normal systems of a child bound such as it's values, members/owners if not I talk about a priority system in the next section

This should also effect `bound at player` currently this defaults to plural and returns all bounds it should default to the priority bound and return as single if applicable 

**Describe alternatives you've considered**
The best alternative I've thought about is a cloning/copy system which I talk about in more details at #352
Another alternative is a priority system this system would let you make 2 bounds with whatever one having the higher priority number taking control in that region.

**Additional context**
I know a lot of servers now use bounds for complex systems like plots and they like to create multiple bounds which at times can become 9 bounds taking up 9 chunks with middle one being the only minable this type of system would allow servers to decrease to 2 bounds and add a value to the middle labeling minable.

Parents shouldn't override same values with different settings so if Bound1 says `Mining = false` and Bound2 says `Mining = True` it should allow mining not prevent it

**Comment by ShaneBeee** [comment]
closing as this has been here for nearly a year.
If you wish to try again, please feel free to re-open
