### ISSUE TITLE
[BUG] NBT Tag Expression Causing Unexpected Behavior

### ISSUE THREAD

**Issue by hapily04** [ShaneBeee/SkBee#360]
**Describe the bug**   
If I have a check for a tag on the nbt of an item in the right click event it causes the item to not be "verified" in a sense in for example a block place event to get the player's tool UNLESS I right click the item before I place it. This will be elaborated upon further in the report.

**To Reproduce**   
`on right click:`
`	tag "enchantments;miner" of nbt compound of tool is set`

`on block place:`
`	broadcast player's tool`

**Expected behavior**   
The tool should be broadcasted as not air if I am not holding air (which I'm not).

**Screenshots/Errors**   
https://i.imgur.com/ENoHvSY.mp4

**Version Info:**
https://prnt.sc/E1lj1xGnHCE2

**Additional context**   
This problem was resolved entirely when I removed the right click event snippet with the in-line condition for the skbee expression.

**Comment by ShaneBeee** [comment]
well that's an odd one, I'll look into it
