### ISSUE TITLE
[SUGGESTION] Display entity utilities

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#361]
**Is your feature request related to a problem? Please describe.**
Like many since the release of display entities, I've attempted to wrap my head around quaternions, matrices, and such. But the two major problems with that are for one, as much as I want to use these to their fullest potential, I can't justify the time needed to learn singular value decomposition. And secondly, there's no reason to do it alone, when as a community I'm sure many others are feeling they have to do the same. Why not have an official resource that handles it for everyone

**Describe the solution you'd like**
Utilities for manipulating display entities, specifically the transformations.
Including official support for matrices and quaternions, I'm sure there are plenty java libraries to choose from that can handle this.

**Describe alternatives you've considered**
Learning myself. I understand quaternions a little bit better now, but I'll be honest - my brain is burnt, and I have other responsibilities that have to take priority over learning linear algebra from youtube

**Additional context**
Thanks again for this incredible resource, truely a cornerstone of the skript community!

**Comment by Fusezion** [comment]
As far as I'm aware SkriptLang plans to implements Display entities unless I misunderstood something, along with that I believe Shane already stated he doesn't intend to add them to Skbee, as such I doubt any utility will be added to this addon

**Comment by boxic** [comment]
I particularly mean advanced display controls, and the accompanying arithmetic

The problem I have with an addon like Lusk is there's little security that it'll be maintained, unfortunately

**Comment by ShaneBeee** [comment]
I have talked about adding stuff for display entities, but as with everything else I will add, it will be simple.

The majority of things I add to this addon are almost nearly directly related to the Bukkit methods, take particles for example.

You've mentioned some advanced math, I don't quite understand why or even how you expect SkBee to do the work for you.

IF I do add syntax for display entities, it will most likely match the Bukkit methods.

**Comment by ShaneBeee** [comment]
You guys can follow the progress here https://github.com/ShaneBeee/SkBee/pull/344

**Comment by J-ak-e** [comment]
> I particularly mean advanced display controls, and the accompanying arithmetic
> 
> The problem I have with an addon like Lusk is there's little security that it'll be maintained, unfortunately

I won't forget that one 😔
