### ISSUE TITLE
[SUGGESTION] Minimessage custom fonts

### ISSUE THREAD

**Issue by SubGplayz** [ShaneBeee/SkBee#373]
**Is your feature request related to a problem? Please describe.**
The minimessage feature does not support fonts from my testing. I was trying to use custom fonts, but it did not change the font.

**Describe the solution you'd like**
minimessage font support

**Describe alternatives you've considered**
I have seen it working in plugins such as [this one](https://modrinth.com/plugin/miniplaceholders/), but that doesnt work with skript and is limited to only chat.

**Additional context**
I was testing it with placeholders using skript-placeholders, it could be some sort of incompatibility but i doubt it

What papi shows:
![image](https://user-images.githubusercontent.com/68687751/228646231-4dd906f0-f615-4d4f-91ca-8fef283cedf1.png)

What skript w. skbee shows:
![image](https://user-images.githubusercontent.com/68687751/228647045-f56bfc7e-c212-4c08-bcc9-8a439808bcf5.png)

skript used:
```
command /brokenminifont:
    trigger:
        set {_m} to mini message from placeholder "nameplates_background_prefix" from player
        send {_m}
```

what should be shown:
![image](https://user-images.githubusercontent.com/68687751/228647352-167f6a4e-0506-48cd-b1cb-f47d92cc7aff.png)

**Comment by ShaneBeee** [comment]
`send {_m}` <-- you're sending it as a Skript message not as a component.
Try actually sending as a component and see what happens

**Comment by SubGplayz** [comment]
Sorry I hadn't responded, Just tried as you said to send it as a component, and it still did the same thing, any ideas why? I think I send it correctly, but my code is wrong alot of the time so it might be wrong

Code:
```
command /brokenminifont:
    trigger:
        send mini message from placeholder "nameplates_background_prefix" from player
```

Output:
![image](https://user-images.githubusercontent.com/68687751/233425273-b23c4f4e-e95e-4809-9952-62e0f0af2750.png)

**Comment by ShaneBeee** [comment]
again, you're just sending as a Skript message.
You need to use SkBee's send component 
`send component (text component/mini message here)`
