### ISSUE TITLE
[SUGGESTION] Block break animation

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#374]
**Is your feature request related to a problem? Please describe.**
No, it helps us to create more content related with block simulations.

**Describe the solution you'd like**
There was some addon had this feature but it is outdated. Something just like the expression below would be great.
![image](https://user-images.githubusercontent.com/26517681/229612849-811683c6-6a5d-4897-b62c-9415571d3463.png)

**Describe alternatives you've considered**
Maybe with skript-reflect but SkBee has very good features and this feature will be good for the community. 

**Additional context**
I mean something like this:
`effect packet block break animation at %block% [with ]state %number% [for %-players%]`
If players not specified, all players will selected by default maybe.

Thanks for reading my suggestion.

**Comment by ShaneBeee** [comment]
https://skripthub.net/docs/?id=8332

**Comment by rudde0** [comment]
Oh sorry, my bad, thanks for reply.

**Comment by rudde0** [comment]
Need quick answer for a thing. Isn't there any way to clear this break animation? You mention that 0 doesn't clear the break animation in skripthub. So can't we reset the break process?

**Comment by ShaneBeee** [comment]
unfortunately its not easy, I dunno why but that's just what the PaperAPI provides.
What ive done to "clear" it is set the break state on a block either high up in the sky or low down to bedrock, because you can only show it to a player for 1 block, this will reset the current block

**Comment by rudde0** [comment]
Thanks for idea. <3
