### ISSUE TITLE
1.16.1 load structure issue [BUG]

### ISSUE THREAD

**Issue by K9Lil** [ShaneBeee/SkBee#38]
**Describe the bug**

**To Reproduce**
Please include clear steps to reproduce the behavior

**Expected behavior**

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.

**Version Info:**
 - **SkBee Version:** (ex: 1.0.0)
-  **Skript Version:** (ex: Skript 2.5-alpha3)
 - **Server Version/Platform** (ex: Spigot 1.15.2)

**Additional context**

**Comment by ShaneBeee** [comment]
Closing as there is not a spec of info here.

**Comment by K9Lil** [comment]
sorry its my first time I posted accidentaly im editing
