### ISSUE TITLE
[SUGGESTION] Expression - All values of a block data/state tag.

### ISSUE THREAD

**Issue by 24GDude** [ShaneBeee/SkBee#380]
**Is your feature request related to a problem? Please describe.**
This feature request isn't about a problem, although it would be extremely useful for a few of my server projects and 
isn't on any other addon. SkBee has lots of blockdata expressions and effects that have helped me in this and I think 
this would be necessary to include with all the other block data features. An example of this would be if you tried to get all the values for the rotation tag on a player head. Since a player head's rotate tag can be anything between 0 and 9, so the expression would return `0, 1, 2, 3, 4, 5, 6, 7, 8 and 9`

**Describe the solution you'd like**
I would like an expression that would look like the following: `[all] values of block[ ](data|state) tag %string% of %blocks%`

**Comment by ShaneBeee** [comment]
This won't be possible for me to do, since Bukkit has no api for possible states

**Comment by 24GDude** [comment]
Ah okay, I was possibly thinking something you could do along the lines of the aliases file skript has, except for values of a blockstate tag. I think this would take a while though since theres lots of different values.

**Comment by ShaneBeee** [comment]
> Ah okay, I was possibly thinking something you could do along the lines of the aliases file skript has, except for values of a blockstate tag. I think this would take a while though since theres lots of different values.

as of right now, I had to do janky code to make the "tags" work.
For example, the block data for oak stairs is:
`minecraft:oak_stairs[facing=north;half=bottom;shape=straight;waterlogged=false]`
basically what I did to get the tags is make it a string, and split up all the bits between `[]`, then I had to split the part at `=`
Then you can get/set the tag.
As for the values in there, I had to then put it all back together and parse it.
So as of right now, there's no way to get the default/allowed values of those states.
And typing them all out, that aint going to happen.

All these values are on McWiki and really easy to find.

**Comment by 24GDude** [comment]
Alright, thanks for letting me know. I try using McWiki for the values.
