### ISSUE TITLE
[Question] NBT Tags of inventories?

### ISSUE THREAD

**Issue by xFreakss** [ShaneBeee/SkBee#383]
Can i use SKBee to modify nbt of inventories?

I'm trying to use it to filter inventories when using `on inventory click:`

Actually i check for inventory name, which is not ideal because players can rename a chest

**Comment by ShaneBeee** [comment]
An inventory itself does not have NBT.
The contents of an inventory are stored in the NBT of an Entity/Block, which can be modified, but probably not whilst said inventory is currently opened.

If you need more help please use the help channels on skUnity's discord, as this issue tracker is for issues/suggestions with SkBee.
