### ISSUE TITLE
Server crashes/lags a lot

### ISSUE THREAD

**Issue by Proeis** [ShaneBeee/SkBee#384]
This causes the server to crash.

`on  load:`
` set {_c} to gci2("Cobblestone")`
` register shaped recipe for {runeplate} using {_c}, {_c}, {_c}, {_c}, block of raw iron of mending named "&fMega Compressed Iron" with all flags hidden, {_c}, {_c}, {_c} and {_c} with id "rune_plate"`
` register shaped recipe for {smeltingtouch} using coal block of mending named "&fMega Compressed Coal" with all flags hidden, {scorchedstone}, coal block of mending named "&fMega Compressed Coal" with all flags hidden, {scorchedstone}, {runeplate}, {scorchedstone}, coal block of mending named "&fMega Compressed Coal" with all flags hidden, {scorchedstone} and coal block of mending named "&fMega Compressed Coal" with all flags hidden with id "smelting_touch_rune"`
` set {_d} to gci("Diamond")`
` register shapedd recipe for {reductionrune} using {lapiscrystal}, {_d}, {lapiscrystal}, {necromancershard}, {runeplate}, {necromancershard}, {lapiscrystal}, {_d} and {lapiscrystal} with id "reduction_rune"
`
 
 I did some debugging by removing some parts of the script but it either still crashes or lags way way too much (30 seconds to reload the script). The variables are items and work fine. No errors in logs.
 
 I don't know if this is a SkBee bug or smth but if it is. Please help me.
 
 Thx

**Comment by ShaneBeee** [comment]
This isn't a problem with SkBee, this is an issue with your code.
Skript doesn't like really long lines, so break your lines up.

If you need further help, please join the skUnity discord and ask for help there. Im sure someone can provide further support, but this GitHub issue tracker is not the place for personal support.

**Comment by Proeis** [comment]
thx
