### ISSUE TITLE
1.16.1 Loading and Saving Structures (not working)[BUG]

### ISSUE THREAD

**Issue by K9Lil** [ShaneBeee/SkBee#39]
**Describe the bug**

The bug with loading structure and saving structure does not currently work in 1.16.1 for some reason

**To Reproduce**

When creating a skript with the syntax
`save between {loc1} and {loc2} as "test"` will result in an error same with loading
`load "test" at location of player`

**Expected behavior**

I expected for the code to save a structure between 2 location saved within 2 different variable to then be
pasted at will using load "test" at location of player

**Screenshots/Errors**

![image](https://user-images.githubusercontent.com/68028162/86957585-2c9bb800-c118-11ea-83c4-69dc2a424650.png)
![image](https://user-images.githubusercontent.com/68028162/86958062-d418ea80-c118-11ea-9c3c-8fbfc728f2df.png)

**Version Info:**

SkBee Version: 1.4.3
**Skript Version:** 2.4.1-MH it is minehut if its skript version related il report to minehut
Server Version/Platform git-Paper-79 1.16.1

**Additional context**

**Comment by ShaneBeee** [comment]
This is now like the 10th time someone has reported this to me.

I really wish you guys would read the console before reporting "bugs" .... especially we its not a bug, and I CLEARLY already know about this.

<img width="914" alt="Screen Shot 2020-07-08 at 11 48 41 AM" src="https://user-images.githubusercontent.com/20008482/86958514-26560d80-c111-11ea-98ae-d8815149fd3b.png">
