### ISSUE TITLE
[SUGGESTION] Spawn entity which is visible to specific players

### ISSUE THREAD

**Issue by 2002Spiele** [ShaneBeee/SkBee#391]
**Is your feature request related to a problem? Please describe.**
I hate that I have to install an addon for packets to make entities invisible to specific players.

**Describe the solution you'd like**
I'd like SkBee to make a new effect which makes entities invisible to all players except the specified ones. (maybe also make SkBee remember to always keep them visible to only those players and invisible to others, even after the client is asking for all entities in their radius)

**Describe alternatives you've considered**
As mentioned above, you could use an addon which sends packets to players to make them invisible, but making it a single effect inside SkBee would make it a lot cleaner

**Additional context**
Why I am suggesting this:
- I am suggesting this feature especially for display entities. Sometimes, you might want to spawn text displays infront of a player which shows information about stuff, but it shouldn't show it to other people.

What this could be used for:
- An example, how this feature would be useful, would be to show information about a block/entity above the block/entity, or some text display trying to lead you to some location.

**Comment by ShaneBeee** [comment]
I will add an effect for showing/hiding entities to/from players
