### ISSUE TITLE
[BUG] On Anvil Prepare doesn't detect virtual anvils

### ISSUE THREAD

**Issue by DereWah** [ShaneBeee/SkBee#394]
**Describe the bug**   
When using the "on anvil prepare event", only anvils opened with the essentials /anvil command or with a physical anvil are detected. When a virtual anvil ( one created with skript and opened to the player) is clicked no event is fired.

**To Reproduce**   
Run this skript 
```
command /openanvil:
	trigger:
		set {_gui} to anvil inventory named "Custom Anvil"
		open {_gui} to player
		
		
on anvil prepare:
	send index of event-slot to player
	send anvil rename text of event-inventory to player
```

then place a physical anvil or use the essentials command /anvil. You will receive event messages only for physical / essentials anvils.

**Expected behavior**   
It should listen for anvil events regardless if those are physical or created with Skript.

**Version Info:**
```
SkBee 2.9.0
```

**Additional context**   
I'm on a paper 1.19.3 server with Skript 2.6.4

**Comment by ShaneBeee** [comment]
Unfortunately this is not an issue with SkBee, but the event from Paper itself.
The event isn't called for fake anvils it appears.
There is nothing I can do about that.
