### ISSUE TITLE
[BUG] Registering recipes

### ISSUE THREAD

**Issue by veeonthewall** [ShaneBeee/SkBee#396]
**Describe the bug**   
 Registering certain recipes prevents lines below it from running

**To Reproduce**   
Set a variable to an item
Register a SHAPED recipe for the variable with xyz ingredient and xyz id.

**Expected behavior**   
When reloading, the lines below it should run as normal.

**Screenshots/Errors**   

https://github.com/ShaneBeee/SkBee/assets/105337781/f39b7716-7620-4d79-a584-a699468e4b9a

**Version Info:**
Client: 1.19.4
Server: 1.19.4
SkBee version: 2.9.0
Skript version: 2.6.4

Please provide output of '/skbee info' here!
<img width="390" alt="Screen Shot 2023-05-21 at 12 40 45 PM" src="https://github.com/ShaneBeee/SkBee/assets/105337781/ca3c3f90-fbc2-4bed-a829-40f361461d0d">

**Additional context**   

Notice the "broadcast 400" above the recipe lines and "broadcast 3049" after

**Comment by ShaneBeee** [comment]
closing as non-skbee issue.
See the video I sent on Minehut
