### ISSUE TITLE
[SUGGESTION] Tablist addons

### ISSUE THREAD

**Issue by s-wendel** [ShaneBeee/SkBee#398]
**Is your feature request related to a problem? Please describe.**
I really like tablists

**Describe the solution you'd like**
Add a tablist feature similar to Tablisknu to SkBee :-)
[https://github.com/TlatoaniHJ/Tablisknu](url)

**Describe alternatives you've considered**
Forking Tablisknu but I'm too silly to do it

**Additional context**
Add features from Tablisknu please!

**Comment by ShaneBeee** [comment]
so what feature from tablisknu do you want?

You’re issue currently tells me nothing.
I've personally never used tabslisknu, so I have no clue what it is capable of doing.
You can't just plop another addon in here and say "please copy that one" without providing a dash of detail of what you want.

That said, I will tell you this...
SkBee will only be using the Bukkit/Paper APIs. I won't be using external APIs, NMS or packets.
So if your request requires those, then I won't be doing it.

As of right now you can't fully customize a tablist with Skript and SkBee, I don't know what else you're looking for... probably cause you never stated it.

**Comment by s-wendel** [comment]
Modifiable / interpolatable columns / rows with skins & names

Didn't know SkBee stayed in between Bukkit/Papers though, so disregard this issue. Thank you :-)

**Comment by ShaneBeee** [comment]
sorry, yeah unfortunately its too much of a pain to deal with external APIs and the such.
