### ISSUE TITLE
[MINOR BUG] Checking for nbt on an item adds an nbt tag to the item.

### ISSUE THREAD

**Issue by Boxeyy** [ShaneBeee/SkBee#399]
**Describe the bug**   
When checking if an item has a specific NBT tag it always adds 'tag:{}' to the nbt compound of said item, even if the item does not contain any NBT tags. This results in the item becomming unstackable with other items of the same type.

**To Reproduce**   
```
on right click:
  if tag "tag;test" of nbt compound player's tool is set:
    send "test"
```
**Expected behavior**   
The expected behavior should be, well... the nbt tag 'tag:{}' not getting added to the item.

**Screenshots/Errors**   
![image](https://github.com/ShaneBeee/SkBee/assets/67805827/e0822699-9c6f-464d-817e-a69003db1460)
![image](https://github.com/ShaneBeee/SkBee/assets/67805827/dc1ceb83-9804-45e6-93fa-b80f12b7ea35)
![image](https://github.com/ShaneBeee/SkBee/assets/67805827/10e17af7-cbca-4e7a-80f4-22131500c3d8)
First image: The nbt compound of the item.
Second image: The item which has been modified.
Third image: The default item.

**Version Info:**
```
--- [Server Info] ---
Server Version: git-Paper-372 (MC: 1.18.2)
Skript Version: 2.7.0-beta2
Skript Addons:
- skript-placeholders v1.5.2
- skript-gui v1.3
- DiSky v4.8.0
- SkJade v1.4.3
SkBee Version: 2.9.0
SkBee Website: https://github.com/ShaneBeee/SkBee
```

**Additional context**   
N/A

**Comment by ShaneBeee** [comment]
This is not a bug.
`tag "tag;test" of nbt compound player's tool` this will return the value of "test", well for "test" to have a value, it first would have to create "tag", since its in that compound.
Since this is a getter, I very well can't stop after "tag"
