### ISSUE TITLE
[SUGGESTION] Allow the ability to access command arguments in on tab complete

### ISSUE THREAD

**Issue by WhoCutTheCheese** [ShaneBeee/SkBee#401]
**Is your feature request related to a problem? Please describe.**
I'm trying to make argument-specific tab completions, but I can't access the arguments from the command.

**Describe the solution you'd like**
Allow the ability to access arguments of the command you're tab completing.

**Describe alternatives you've considered**
I attempted to use event-string to get the arguments, but that didn't work.

**Additional context**
Here's what I tried:
```
on tab complete:
	if event-string contains "servermanager", "sm", "unguard:servermanager" or "unguard:sm":
		set tab completions for position 1 to "create" and "delete"
		if event-string contains "servermanager create", "sm create", "unguard:servermanager create" or "unguard:sm create":
			set tab completions for position 2 to "GAME_SERVER" and "LOBBY"
```

**Comment by Fusezion** [comment]
You're already able to get tab arguments by using the tab arguments expression located here https://skripthub.net/docs/?id=4377
