### ISSUE TITLE
[SUGGESTION] delete/copy nbt 

### ISSUE THREAD

**Issue by ahmadMsaleem** [ShaneBeee/SkBee#403]
A way to delete the entier nbt with a single line, and a way to copy the item nbt to give it for another item if it possible.

skRayFall have the "no nbt" I couldn't find any addon that have the copy nbt
https://github.com/eyesniper2/skRayFall/blob/master/src/main/java/net/rayfall/eyesniper2/skrayfall/general/expressions/ExprNoNbt.java

**Comment by ShaneBeee** [comment]
> A way to delete the entier nbt with a single line,

What exactly are you trying to delete?

> way to copy the item nbt to give it for another item if it possible.

you can already do this.

**Comment by ahmadMsaleem** [comment]
I apologize for the misunderstanding about the copy and the delete nbt, they both exist but I didn't knew

**Comment by ShaneBeee** [comment]
so this can be closed?

**Comment by ahmadMsaleem** [comment]
Yes

sön 11 juni 2023 kl. 18:17 skrev Shane Bee ***@***.***>:
