### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by s-wendel** [ShaneBeee/SkBee#408]
**Describe the bug**   
The expression **'tag "tag;example" of nbt compound of player's tool is set'**  (for example) sets the nbt of the item to {tag:{}} rather than the default nbt of an item which is {}

**To Reproduce**   

Running any expression to check if a tag is set such as **'tag "tag;example" of nbt compound of player's tool is set'**

**Expected behavior**   
The NBT tag tag{} isn't added

**Screenshots/Errors**   
Before the expression
![image](https://github.com/ShaneBeee/SkBee/assets/45246939/3314f26e-6f11-4449-a77b-650ef34afd2e)

After the expression
![image](https://github.com/ShaneBeee/SkBee/assets/45246939/705d8c84-6126-4730-a8d6-1ae5f05dbc4c)

**Version Info:**
![image](https://github.com/ShaneBeee/SkBee/assets/45246939/fedbd00c-5c08-4c2d-97f5-9d147651e157)

**Additional context**   
None :-)

**Comment by ShaneBeee** [comment]
1) this is intended behaviour, it is not a bug
2) please don't report bugs on outdated versions of SkBee
