### ISSUE TITLE
[SUGGESTION] Event addition relating to spellcasting

### ISSUE THREAD

**Issue by ElijahJunaid** [ShaneBeee/SkBee#409]
**Is your feature request related to a problem? Please describe.**
  Yes, the inability to actually change a spell despite there being an expression for it.

**Describe the solution you'd like**
As discussed, adding an event for when the mob wants to choose the event, so you can use the expression.

**Describe alternatives you've considered**
I've quite literally tried every alternative I could think of.

**Additional context**
N/A

**Comment by ShaneBeee** [comment]
The only event in Bukkit/Paper APIs is:
<img width="558" alt="Screenshot 2023-06-18 at 8 51 23 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/1c936bca-505f-46dc-a119-d4fef770c322">

It doesn't appear to have an option to change the spell though, so im not sure if this is going to give you what you want or not
