### ISSUE TITLE
[BUG] Structure Last Location

### ISSUE THREAD

**Issue by ElijahJunaid** [ShaneBeee/SkBee#410]
**Describe the bug**   
Last placed location of structure not working.

**To Reproduce**   
`set {_loc} to last placed location of structure {_t}`

**Expected behavior**   
It to set {_loc} to the last placed location of structure {_t}.

**Screenshots/Errors**   
![image](https://github.com/ShaneBeee/SkBee/assets/121450694/99b83230-09e2-411c-9a9b-9fcf88d0fe78)

**Version Info:**
![image](https://github.com/ShaneBeee/SkBee/assets/121450694/735fb16a-511b-47c6-a68d-99c8b7c8bc15)

**Additional context**   
Yes uh, the example doesn't seem correct... You're setting a structure, placing a structure then saving it. You aren't actually getting the last placed location of structure <input variable>.

**Comment by ShaneBeee** [comment]
you used the syntax incorrectly:
https://skripthub.net/docs/?id=9240

**Comment by ShaneBeee** [comment]
closing as non-issue
