### ISSUE TITLE
[SUGGESTION] Future Skript Syntax Conflict

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#411]
**Describe the bug**   
In the *long* distance future of Skript 2.8 most likely, I have a PR for enhancing their world syntax. This will include a `save %worlds%` effect which will most likely conflict with structure's `save [structure[s]] %structures%`

the best possible fix is to just remove the `structure` optional stuff similar to how saving nbt files are 

**To Reproduce**   
N/A

**Expected behavior**   
N/A

**Screenshots/Errors**   
N/A

**Version Info:**
N/A

**Additional context**   
N/A

**Comment by ShaneBeee** [comment]
Im changing this to a suggestion. It's hard to label something as a bug that doesn't exist.
While I understand this is a possibility in the future, it's just that... a possibility.

**Comment by ShaneBeee** [comment]
Im going to close this for now, strictly because it's a PR targeting Skript for 6-7 years from now. 
I'll be dead by then.... so to my successor please update this.
