### ISSUE TITLE
[SUGGESTION] Path points (without requiring an entity)

### ISSUE THREAD

**Issue by 2002Spiele** [ShaneBeee/SkBee#414]
**Is your feature request related to a problem? Please describe.**
I've been working on a script which add "minions" to the server. They'd also require pathfinding, but I have to spawn an invisible entity at the minion and set their path target to the goal location. After it starts pathfinding, I am taking the path points and make the minion move to the points.
However, it does take a few ticks until the invisible entity starts pathfinding. Sometimes, it also doesn't pathfind at all. Some permanent solution to this would be great, and it fits to the SkBee's path target and path points expressions :)

**Describe the solution you'd like**
Having an expression to get the path points from one location to another would help me a lot.

**Describe alternatives you've considered**
Spawning an invisible entity on the start location, setting its path target to the goal location, wait ticks until path points of the entity is set and make the visible entity move towards the invisible one.

**Additional context**
---

**Comment by ShaneBeee** [comment]
To the best of my knowledge, there is no API in Bukkit or Paper for something like this.

**Comment by ShaneBeee** [comment]
Never heard back from you...
I also don't see any API in Bukkit/Paper for creating fake pathfinding
