### ISSUE TITLE
Nested NBT Not Working

### ISSUE THREAD

**Issue by SGGTheHub** [ShaneBeee/SkBee#42]
**Describe the bug**
When i try to use nested NBTs, it gives me an error.

**To Reproduce**
add "{Enchants:[{Type:""Sharpness"",Lvl:5}] to nbt of command sender's tool
set {_tag} to "%tag ""Enchants;Sharpness"" of nbt of command sender's tool%"

**Expected behavior**
It should return 5

**Screenshot**
![Error Screenshot](https://user-images.githubusercontent.com/67205910/87320284-0cf6fc00-c52b-11ea-9168-3814bee93fee.PNG)

**Version Info:**
 - **SkBee Version:** 1.4.5
-  **Skript Version:** 2.5-alpha5
 - **Server Version/Platform** Paper 1.16.1

**Comment by ShaneBeee** [comment]
Thats not how nested NBT works.
I dont fully know how to explain it, but NBT has keys and values.
Enchants would be the key
anything stored in it is the value.

Nested tags are keys. And obviously sharpness is not a key
