### ISSUE TITLE
[SUGGESTION] Add PlaceHolderAPI to SkBee

### ISSUE THREAD

**Issue by Jeremylo1** [ShaneBeee/SkBee#420]
**Is your feature request related to a problem? Please describe.**
The current issue is that Skript addons that handle placeholders have become obsolete. This situation limits users' ability to efficiently integrate or create placeholders within their Skript scripts.

**Describe the solution you'd like**
I would like SkBee to be able to manage placeholders by integrating with the PlaceholderAPI plugin or other similar plugins. This feature would provide greater flexibility and allow better integration with other plugins and features. Moreover, it would enable users to continue using their older Skript scripts (<= 2.6.4) with placeholders.

**Describe alternatives you've considered**
An alternative would be to revert back to Skript 2.6.4, but this would limit the utilization of new Skript features and uses.

**Additional context**
Placeholder management is a key feature for many Skript users. Adding this feature to SkBee could help maintain the addon's relevance and usefulness for the Skript community, especially since SkBee is clearly the most closely monitored and regularly updated addon by its developers.

_And thanks again for what you've done with this addon ;)_

**Comment by Fusezion** [comment]
Hey, thanks for taking time to create an issue reguarding this, however we don't currently plan to add any more apis into SkBee that isn't apart of CraftBukkit/Spigot/PaperMC and in addition you're saying the existing current addons that handle placeholders have become obsolete. This is pretty far from the truth with the fact [skript-placeholders](https://github.com/APickledWalrus/skript-placeholders) still works perfectly fine and isn't limited to really anything.

**Comment by Jeremylo1** [comment]
Oh, I'm sorry, indeed, after checking it seems that the plugin is not compatible with Minecraft version 1.20.1, that's why Skript using placeholders generate errors. In addition, the following information is displayed once the plugin is loaded.

![image](https://github.com/ShaneBeee/SkBee/assets/11772547/bb023783-5d16-40de-a531-6c52ccb5f9ef)

I'll contact the developer of "skript-placeholders" and sorry for the inconvenience :/

**Comment by Fusezion** [comment]
Perfectly fine, hope to see if it goes well.
