### ISSUE TITLE
[SUGGESTION] Update custom head texture wiki

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#421]
**Is your feature request related to a problem? Please describe.**
Players keep coming around sending nbt including the `Display` nbt compound and give the reason well the wiki shows it so I thought it's manditory

**Describe the solution you'd like**
Remove the `Display` nbt compound from the custom head texture wiki page

**Describe alternatives you've considered**
None it's the only valid way to do this

**Comment by ShaneBeee** [comment]
fixed :)
