### ISSUE TITLE
[SUGGESTION] Creating Custom Brewing Recipes

### ISSUE THREAD

**Issue by HaciGandalf** [ShaneBeee/SkBee#424]
I have left the necessary links below. What I want it to be is to use the items we want to brew the items we want on the potion counter

**Links:**
https://www.spigotmc.org/threads/updated-creating-custom-brewing-recipes.472074/
https://youtu.be/IZSlJpvWlTI?t=34

**Comment by ShaneBeee** [comment]
I will possibly add brewing recipes in the future, but I definitely won't be using that method.
I don't really want to make janky listeners, you guys can do that in Skript yourself.

Paper I believe has a potion brewing system so I would end up using that instead.

**Comment by HaciGandalf** [comment]
I have no idea how to code the system, you already know this business better than me. Thank you for your feedback i will be looking forward to this feature. Thank you for continuing to develop this beautiful addon.

**Comment by Fusezion** [comment]
> I have no idea how to code the system, you already know this business better than me. Thank you for your feedback i will be looking forward to this feature. Thank you for continuing to develop this beautiful addon.

I'll see if I can get a test build tonight or tomorrow rn I want to finish merchant recode. I'll assign myself for now

**Comment by Fusezion** [comment]
Great news! I went ahead and build a quick build based off of #423 so any changes and breaking changes there are included here
```applescript
register [a] [new] brewing[[ ]stand] recipe with id %string% for %itemstack% using %recipechoice/itemtype% with input %recipechoice/itemtype%
```
this build doesn't quite yet support ability to remove custom recipes or reset all potion recipes
as I have to rework that full class

you can download the nightly build [here](https://github.com/ShaneBeee/SkBee/actions/runs/5482883113) via the artifact at the very bottom

**Comment by ShaneBeee** [comment]
this is now in SkBee 3.0.0 as a section (requires PaperMC server)
