### ISSUE TITLE
Client side borders [SUGGESTION]

### ISSUE THREAD

**Issue by K9Lil** [ShaneBeee/SkBee#43]
**Is your feature request related to a problem? Please describe.**
This feature is releated to the problem that it dosent look like there are any skript compatible client side borders and It would help alot with custom features/gamemodes

**Describe the solution you'd like**
You can set a player's world border size, center the border to a location and possibly damaging features and warning things as well with the uses of checking the size, resetting the size, possibly saving the client side border to a varibale? or just saving in general

**Describe alternatives you've considered**
none I need this or I will shit myself

**Additional context**
All features in which Skellett includes in there syntax plus maybe some more usefull ones

**Comment by Leautis** [comment]
will be a nice addition since not many addons have worldborder support

**Comment by ShaneBeee** [comment]
I will not be adding this, as this would heavily rely on packets, which SkBee does not do
