### ISSUE TITLE
[SUGGESTION] Chunk Enter Event

### ISSUE THREAD

**Issue by ElijahJunaid** [ShaneBeee/SkBee#430]
**What I am trying to accomplish**
I'm trying to accomplish the ability to detect when a player enters a chunk

**Current method of accomplishing goal**
The current method is to use skript-reflect to use a MorkazSk event or install MorkazSk and use that event.

**What I think should be added:**
I think this should be added because it would resolve installing dependencies that aren't needed. All it is a chunk enter event, which shouldn't be that hard.

**Comment by ShaneBeee** [comment]
https://docs.skriptlang.org/events.html?search=#player_chunk_enters

**Comment by Fusezion** [comment]
Added to 2.7 Skript if or might be 2.8 will need to check
