### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by Echo69420** [ShaneBeee/SkBee#431]
I know I can get help in the discord but I came here to solve the problem a different way. Ingredients of recipe. I asked on the discord how to replace spaces with _ (so if you know how to do that please tell me). My request is to have the required name of item not have to be entirely "minecraft:item_item" and just have it be able to take the perfectly normal name of an item? And obviously I need to know how to replace spaces with underscores to change my item into the right name of the item to fit the ingredients of recipe, and it doesn't work.
replace " " with "_" is the (not working) problem
Thank you. Please change.

**Comment by ShaneBeee** [comment]
This is an issue tracker, not a place to ask for help with your scripts.
Please keep that to Discord

**Comment by Echo69420** [comment]
Hi if you're not a replybot can you read my issue please thank you

**Comment by ShaneBeee** [comment]
I'm a human, and I already replied.
