### ISSUE TITLE
Fixing ingredients of recipe.

### ISSUE THREAD

**Issue by Echo69420** [ShaneBeee/SkBee#432]
Let me make an entire new issue so there is no way to misread what is no longer there and doesn't matter.
Please update SkBee so that you don't have to entirely enter "minecraft:item_2ndwordtoitem" and can just enter in an item as normal not as if you're using an in game command. So that you could put something like "diamond pickaxe" and it will work, because right now, the only way you can get that to work is (using quotes) "minecraft:diamond_pickaxe".
Yes I do actually need this.
My "project" does not work because of this

**Comment by ShaneBeee** [comment]
im going to ban you from here if you continue doing this
If you need help writing scripts, use discord, this is an issue tracker not a help channel.
