### ISSUE TITLE
[BUG] NBT error

### ISSUE THREAD

**Issue by ManInMyVan** [ShaneBeee/SkBee#434]
### What happened?

`with nbt` gives an error when you have nbt with multiple brackets (ex: `with nbt from "{Echantments:[]}"` works, but `with nbt from "{Enchantments:[{id:protection,lvl:1}]}"` does not.)

### Steps to reproduce

here's a skript that triggers this bug:
```
command /a:
    trigger:
        give player 2 of stone with nbt from "{Enchantments:[{}]}"
```

### Expected behavior

It should not give an error.

(this script does not give an error:
```
command /a:
   trigger:
        give player 2 of stone with nbt from "{Enchantments:[]}"
```
)

### SkBee Version

2.14.1

### Server Version

git-Paper-549 (1.19.4)

### SkBee Info

--- [SkBee Loading Info] ---
- [NBTAPI] Found Spigot: v1_19_R3! Trying to find NMS support
- [NBTAPI] NMS support 'MC1_19_R3' loaded!
- NBT Elements successfully loaded
- Recipe Elements successfully loaded
- Scoreboard Elements successfully loaded
- Scoreboard Objective Elements successfully loaded
Team Elements successfully loaded
Bound Elements successfully loaded
- Game Event Elements successfully loaded
- BossBar Elements successfully loaded
- Statistic Elements successfully loaded
- Villager Elements successfully loaded
- Advancement Elements successfully loaded
- World Border Elements successfully loaded
- Particle Elements successfully loaded
- Minecraft Tag elements successfully loaded
- RayTrace elements successfully loaded
- Fishing elements successfully loaded
- Display Entity elements successfully loaded
Checking for update failed!
--- [Server Info] ---
Server Version: git-Paper-549 (MC: 1.19.4)
Skript Version: 2.7.0-beta2
Skript Addons:
- skript-placeholders v1.5.2
SkBee Version: 2.14.1
SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
so what's the error?

**Comment by ManInMyVan** [comment]
Oh sorry, I forgot to include that

**Comment by ManInMyVan** [comment]
'give player 2 of stone with nbt from "{Enchantments:[{}]}"' can't be added to a player because the former is neither an item type, an inventory nor an experience point

**Comment by ShaneBeee** [comment]
I tried this on both Skript 2.6.4 (latest stable release) and Skript 2.7.0-beta3 (latest beta release) and I could not reproduce the error on their.

I recommend updating Skript and trying again, then report back.

**Comment by ManInMyVan** [comment]
It still happens

**Comment by ShaneBeee** [comment]
could you please send a screenshot of the error.
Im really curious what is causing this

**Comment by ManInMyVan** [comment]
(I'm making a compress skript)
![2023-07-11_15 44 10](https://github.
![Screenshot 2023-07-11 154755](https://github.com/ShaneBeee/SkBee/assets/113963219/fd5af33e-0950-4d76-87a8-397ae40a9568)
com/ShaneBeee/SkBee/assets/113963219/95f342d2-03ac-45c8-89c7-90a7f35a23de)

**Comment by ManInMyVan** [comment]
![Screenshot 2023-07-11 154755](https://github.com/ShaneBeee/SkBee/assets/113963219/ce7d3b3a-f877-4bc3-a1e7-cab3a3037c7a)

**Comment by ShaneBeee** [comment]
oh, that's not a SkBee issue, that's a Skript thing, you have to double up your inner quotes.

**Comment by ManInMyVan** [comment]
Wdym?

**Comment by ManInMyVan** [comment]
@ShaneBeee

**Comment by ManInMyVan** [comment]
nvm
