### ISSUE TITLE
[SUGGESTION] Place a structure without updates

### ISSUE THREAD

**Issue by GDudeUnderscore** [ShaneBeee/SkBee#437]
### Suggestion

When placing a structure, you could have the option to do so without updating neighboring blocks in the structure

### Alternatives

I dont think there is any existing alternatives, but if this isn't possible, maybe you could add a way to loop all blocks in a structure so you could then place those blocks without updates.

**Comment by ShaneBeee** [comment]
There doesn't appear to be anything in the API to prevent updates

**Comment by GDudeUnderscore** [comment]
is there a way to add a way to loop all blocks in a structure?

**Comment by ShaneBeee** [comment]
you can loop the block states of a structure, but that's probably not what you're looking for.
The blocks don't exist til its placed in the world, the block states will just be like fake versions of the blocks

**Comment by ShaneBeee** [comment]
closing as there is currently no possible way to do this.
