### ISSUE TITLE
[SUGGESTION] Add integrity to structure place

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#438]
### Suggestion

Add support for the integrity field of `Structure#place` method
This basically is how ruin stuff work where when you do `0.5` it skips about half of the blocks to placed
Supports 0-1

### Alternatives

None

**Comment by ShaneBeee** [comment]
<img width="1452" alt="Screenshot 2023-07-12 at 1 41 44 PM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/e7970981-7246-4689-9d90-b7d48745f18c">

**Comment by Fusezion** [comment]
ah didn't know you did it as a property
