### ISSUE TITLE
[BUG] deprecated behaviour

### ISSUE THREAD

**Issue by Ferrlix** [ShaneBeee/SkBee#439]
### What happened?

Skript is creating timing, deprecated behaviour

![image](https://github.com/ShaneBeee/SkBee/assets/126913961/abaf4ac4-41c4-441d-8788-b2b08a37dd6a)

### Steps to reproduce

1. load only skbee and load a skript that made use of it
2. behold errors
3.

### Expected behavior

a clean console

### SkBee Version

2.14.1

### Server Version

git-Paper-"a3c760e"

### SkBee Info

authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:12:52 [Server] [WARN] Plugin 'Skript' is creating timing 'org.skriptlang.skript.lang.script.Script@75fad403: line 79' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:12:53 [Server] [INFO] Ferrlix issued server command: /paper version
13.07 11:13:11 [Server] [WARN] Plugin 'Skript' is creating timing 'org.skriptlang.skript.lang.script.Script@495be975: line 250' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:13:11 [Server] [WARN] Plugin 'Skript' is creating timing 'org.skriptlang.skript.lang.script.Script@30eab7dc: line 93' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:13:29 [Server] [WARN] Plugin 'Skript' is creating timing 'org.skriptlang.skript.lang.script.Script@495be975: line 250' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:13:29 [Server] [WARN] Plugin 'Skript' is creating timing 'org.skriptlang.skript.lang.script.Script@30eab7dc: line 93' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:13:29 [Server] [WARN] Plugin 'Skript' is creating timing 'org.skriptlang.skript.lang.script.Script@495be975: line 238' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:13:29 [Server] [WARN] Plugin 'Skript' is creating timing 'org.skriptlang.skript.lang.script.Script@2e7866f: line 12' - this is deprecated behavior, please report it to the authors: Njol, Mirreski, SkriptLang Team, Contributors
13.07 11:13:30 [PebbleHost] hunterkupp@gmail.com ran command: skbee info
13.07 11:13:30 [Server] [INFO] --- [SkBee Loading Info] ---
13.07 11:13:30 [Server] [INFO] - [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
13.07 11:13:30 [Server] [INFO] - [NBTAPI] NMS support 'MC1_20_R1' loaded!
13.07 11:13:30 [Server] [INFO] - NBT Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Recipe Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Scoreboard Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Scoreboard Objective Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Team Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Bound Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Text Component Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Pathfinding Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Structure Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Other Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Virtual Furnace Elements disabled via config
13.07 11:13:30 [Server] [INFO] - World Creator Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Game Event Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - BossBar Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Statistic Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Villager Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Advancement Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - World Border Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Particle Elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Minecraft Tag elements successfully loaded
13.07 11:13:30 [Server] [INFO] - RayTrace elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Fishing elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Display Entity elements successfully loaded
13.07 11:13:30 [Server] [INFO] - Plugin is up to date!
13.07 11:13:30 [Server] [INFO] --- [Server Info] ---
13.07 11:13:34 [Server] [INFO] Server Version: git-Paper-"a3c760e" (MC: 1.20.1)
13.07 11:13:34 [Server] [INFO] Skript Version: 2.7.0-beta3
13.07 11:13:34 [Server] [INFO] Skript Addons:
13.07 11:13:34 [Server] [INFO] SkBee Version: 2.14.1
13.07 11:13:34 [Server] [INFO] SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

it seems to speed up with more addons / more skripts. not sure which yet. SkBee is by far my most used and useful addon so its top of my list :)

**Comment by Fusezion** [comment]
Hi, this issue is unrelated to Skbee and is apart of [Skript](https://github.com/SkriptLang/Skript) they are aware that paper has decided to deprecate the old timings in favor of using Spark however no current plans on that as far as I'm aware if you want to say updated on this you can find it over on their issue tracker by searching timings
