### ISSUE TITLE
[BUG] PotionEffectType doesn't work in potion effect add event

### ISSUE THREAD

**Issue by ManInMyVan** [ShaneBeee/SkBee#443]
### What happened?

My error is `Can't compare a potion with a potion` am I doing it wrong?

### Steps to reproduce

here's my skript
```
on potion effect added:
	if event-potioneffecttype is strength:
		cancel event
```

### Expected behavior

It should work and should make strength not be able to be applied to entities

### SkBee Version

2.15.0

### Server Version

git-Paper-68 (MC: 1.20.1)

### SkBee Info
```
--- [SkBee Loading Info] ---
- Other Elements successfully loaded
- [NBTAPI] Found Spigot: v1_20_R1! Trying to find NMS support
- [NBTAPI] NMS support 'MC1_20_R1' loaded!
- NBT Elements successfully loaded
- Text Component Elements successfully loaded
- Advancement Elements successfully loaded
- BossBar Elements successfully loaded
- Bound Elements successfully loaded
- Display Entity elements successfully loaded
- Fishing elements successfully loaded
- Game Event Elements successfully loaded
- Particle Elements successfully loaded
- Particle Elements successfully loaded
- RayTrace elements successfully loaded
- Recipe Elements successfully loaded
- Scoreboard Elements successfully loaded
- Scoreboard Objective Elements successfully loaded
 Statistic Elements successfully loaded
- Structure Elements successfully loaded
- Minecraft Tag elements successfully loaded
- Team Elements successfully loaded
- Villager Elements successfully loaded
- Virtual Furnace Elements disabled via config
- World Border Elements successfully loaded
- World Creator Elements successfully loaded
- Checking for update failed!
- Checking for update failed!
--- [Server Info] ---
Server Version: git-Paper-68 (MC: 1.20.1)
Skript Version: 2.6.4
Skript Addons:
- skript-gui v1.3
- Skellett v2.0.9
- MorkazSk v1.3
- SkQuery v4.1.9
SkBee Version: 2.15.0
SkBee Website: https://github.com/ShaneBeee/SkBee
```

### Additional Information

I tried asking on the skUnity Discord, but couldn't find an answer

Also please add an example for this event on [skripthub.net](https://skripthub.net/docs/?id=7659)

**Comment by Fusezion** [comment]
Alright after a little bit more searching this might actually be an underlining Skript issue that just wasn't ever noticed 
![image](https://github.com/ShaneBeee/SkBee/assets/81952476/3a4c994b-5456-47c8-b2c5-8e02b3bfc754)

In the below screenshot I changed the order of the event-value registration and in return it changed error
![image](https://github.com/ShaneBeee/SkBee/assets/81952476/cf9bebea-f739-484d-85bc-d96af303b331)

You can fix this on your end for now by doing `event-potioneffectype` -> `potion effect type`

**Comment by Fusezion** [comment]
Shane when you get time, we will need to decide if it's worth while to register an EventValueExpression or some other expression for these as this isn't fixed when running a 2.7 server

**Comment by ManInMyVan** [comment]
> You can fix this on your end for now by doing event-potioneffectype -> potion effect type

That disables all effects, not just strength.

**Comment by Fusezion** [comment]
> That disables all effects, not just strength.

Then it seems very unlike anything can be done until skript fixes this issue, I'll keep this open as a reminder and depends if we just add a new custom expressions to hopefully fix this

**Comment by ShaneBeee** [comment]
it appears Skript doesn't have a Comparator for PotionEffectType.
This is the same reason Skript no likie:
`if block data of event-block = stone[]:` <-- this I fixed in Skript 2.7.x

I'll just add a temp comparator until Skript fixes this.

**Comment by ManInMyVan** [comment]
Also please add an example for this event on [skripthub.net](https://skripthub.net/docs/?id=7659)

**Comment by Fusezion** [comment]
> Also please add an example for this event on [skripthub.net](https://skripthub.net/docs/?id=7659)

moved that to another just so we don't forget
