### ISSUE TITLE
[SUGGESTION] Remove flickering from show block damage effect

### ISSUE THREAD

**Issue by CallinBrumback** [ShaneBeee/SkBee#444]
### Suggestion

Whenever you set block damage animation buy doing this...
`make player see damage of event-block as 0.5`
They stage sets fine, but as soon at you left click the block or a player starts mining the block, the animation disappears.
I would like the animation to stay when the player clicks the block.

A work around that I have tried is resetting the block animation, but if the player continues to mine the block the animation flickers on and off every tick.

### Alternatives

I used to use MorkazSK to show block animation to the player, and its version of block break animation doesn't make the animation disappear when the player clicks the block or mines it.

I would like it to be similar to MorkazSK's version of it.

### Additional Information

MorkazSK no longer works for me, that is the reason I am making this suggestion.

**Comment by Fusezion** [comment]
The break stage flickering issue is only fixable via packets which is cancelling whatever packet is called for break stages.
In addition I'm unable to fin anything related to block break stage/damage inside MorkazSk

**Comment by Fusezion** [comment]
Alright so I found where MorkazSk has this effect, they require the usage of ProtocolLib for theirs to work

**Comment by CallinBrumback** [comment]
> Alright so I found where MorkazSk has this effect, they require the usage of ProtocolLib for theirs to work

I just looked for ProtocolLib in my plugins folder and it wasn't there lol, I don't know why I didn't double check for that.  I was assuming MorkazSK randomly stopping working was related to it being such an old addon. I must have accidently removed ProtocolLib when I was removing unused plugins/addons.

**Comment by Fusezion** [comment]
Skripthub's required plugins and required version tag is broken is the tool we use for generating docs as such it wasn't easily found

**Comment by ShaneBeee** [comment]
Closing as there's no way for me to fix this, other than using packets.
And I won't be using packets in SkBee.
