### ISSUE TITLE
[ENHANCEMENT] Add examples for potion effect events

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#445]
**Suggestion**
add an example for this event on [skripthub.net](https://skripthub.net/docs/?id=7659)

**Why?**
Not existing

_Originally posted by @ManInMyVan in https://github.com/ShaneBeee/SkBee/issues/443#issuecomment-1639099796_

**Comment by ManInMyVan** [comment]
> https://github.com/ShaneBeee/SkBee/issues/443#issuecomment-1639099796_

Well actually if you check the bottom of the original comment/description of the issue, I had asked for documentation on this event when I posted the issue.

**Comment by Fusezion** [comment]
> > [#443 (comment)](https://github.com/ShaneBeee/SkBee/issues/443#issuecomment-1639099796)_
> 
> Well actually if you check the bottom of the original comment/description of the issue, I had asked for documentation on this event when I posted the issue.

I'm well aware of that, however the main focus of that issue would have been the bug, we prefer having it spread across multiple issues for management
