### ISSUE TITLE
[SUGGESTION] Publish to modrinth

### ISSUE THREAD

**Issue by cootshk** [ShaneBeee/SkBee#448]
### Suggestion

A modrinth page please

### Alternatives

Curseforge page - doesnt have a plugin tab (i dont think)

### Additional Information

Helpful for API ~~scripts~~ skripts and such

**Comment by Fusezion** [comment]
This is findable on both SkUnity and Spigot 
honestly I don't see any use in us adding this to Modrinth for the reasons below

1. Modrinth honestly should focus more on mods not really plugins, while it works it just seems dumb
2. CurseForge even if they did is a poor site for us
3. Maybe Paper Hanger we could
4. Making another page that must be maintained is something we don't really want. SkBee as it stands only maintains the spigot page and sometimes skunity but not as much as it's automatic with each new release

**Comment by ShaneBeee** [comment]
^
Basically everything Fusezion said. I have no desire to post on another page, when SkBee can EASILY be found on Spigot, skUnity and GitHub.
