### ISSUE TITLE
[SUGGESTION] Strict NBT check

### ISSUE THREAD

**Issue by ManInMyVan** [ShaneBeee/SkBee#449]
### Suggestion

If this already exists I couldn't find it.
Please add a way to do strict nbt checks
(ie: `number of ancient debris with nbt of "{}" in player's inventory`
would not count the items you get from
`number of ancient debris with nbt of "{Enchantments:[{id:""unbreaking"",lvl:0}]}" in player's inventory` ).

### Alternatives

Here's my skript:
```
command /comp [<string>]:
	trigger:
		set {_enetherite} to ancient debris with nbt from "{Enchantments:[{id:""minecraft:unbreaking"",lvl:0s}],HideFlags:1,display:{Name:'[{""text"":""Enchanted Netherite"",""italic"":false,""color"":""aqua""}]'}}"
		set {_ebnetherite} to netherite block of unbreaking 0 named "&9Enchanted Netherite Block" with enchants flag hidden
		if arg-1 is set:
			if arg-1 is "all" or "netherite":
				set {_n} to floor(number of ancient debris with nbt of "{}" in player's inventory / 64)
				remove ({_n} * 64) of ancient debris with nbt from "{}" from player's inventory
				give player {_n} of {_enetherite}
		else:
			set {_n} to floor(number of {_enetherite} in player's inventory / 64)
			remove ({_n} * 64) of {_enetherite} from player's inventory
			give player {_n} of {_ebnetherite}		
on tab complete of "/comp":
	set tab completions for position 1 to "all" and "netherite"
```
`set {_n} to floor(number of ancient debris with nbt of "{}" in player's inventory / 64)` doesn't work here since the item you get is ancient debris just with more nbt, so it takes the ancient debris with more nbt and the ancient debris with no nbt, it's supposed to only take the ancient debris with no nbt.

**Comment by Fusezion** [comment]
this is technically possible and what you're looking for I believe
![image](https://github.com/ShaneBeee/SkBee/assets/81952476/461ee434-d7d1-4244-9e65-ccd1be490254)

**Comment by ManInMyVan** [comment]
I'm trying to count & remove only items *without* nbt

**Comment by Fusezion** [comment]
> Author

1. then the `amount of ancient debris with nbt from "{}"` is correct
2. in addition you could use skript's native `plain %itemtypes%` expression which forces a plain item
just note that it breaks items with existing nbt like potions

**Comment by ManInMyVan** [comment]
`plain %itemtypes%` worked, ty
