### ISSUE TITLE
[BUG] NBT compound contains always returns false

### ISSUE THREAD

**Issue by basedSkeleton** [ShaneBeee/SkBee#454]
### What happened?

I'm trying to block certain items with NBT from use on my server
`on right click:
   if full nbt compound of player's tool contains "hello":
      cancel event`
If I attempt to right click with an item with "hello" in it's nbt, the item is placed anyway.

### Steps to reproduce

1. Use "nbt compound contains" in your skript
2. Notice that the condition always returns false

### Expected behavior

It should return true when that string is in the nbt compound.

### SkBee Version

Latest

### Server Version

Paper 1.20.1

### SkBee Info

--- [Server Info] ---
Server Version: git-Paper-49 (MC: 1.20.1)
Skript Version: 2.7.0-beta3
Skript Addons:
SkBee Version: v2.15.1
SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
I'm genuinely confused why people think NBT compounds (not a string) can use a string comparison?
You can't do `if player contains "bob":` or `if player's tool contains "bob":`

Needless to say, this is not a bug, you are trying to do a string comparison on a non-string object.

**Comment by basedSkeleton** [comment]
> I'm genuinely confused why people think NBT compounds (not a string) can use a string comparison? You can't do `if player contains "bob":` or `if player's tool contains "bob":`
> 
> Needless to say, this is not a bug, you are trying to do a string comparison on a non-string object.

This exact same code used to work until a newer release.

**Comment by ShaneBeee** [comment]
in the past, `nbt of %object%` returned a string, now it returns the compound.
This was changed last August. It's been almost a year ago.
And you can wrap it as a string (same as wrapping a player/item/etc as a string). This is nothing out of the ordinary for Skript.
You can also use `pretty nbt of %nbtcompound%` which returns a stringified version.
