### ISSUE TITLE
[BUG] BellRingEvent doesn't exist on Spigot 1.18.2

### ISSUE THREAD

**Issue by Lennord** [ShaneBeee/SkBee#455]
### What happened?

Hello good night,

Following your update of your plugin [2.16.0], when I turn on my server, I have an error that appears.

Error: https://pastebin.com/LAK18Wee

Sincerely, Mr.Lennord !

### Steps to reproduce

1. Start the server
2. Loading Error

### Expected behavior

I expect the plugin to start fine without errors.

### SkBee Version

2.16.0

### Server Version

Paper 1.18.2 (388-latest)

### SkBee Info

Following this problem, I cannot put the skbee information because the plugin has been deactivated following the error.

**Comment by ShaneBeee** [comment]
ahh... this must be something that is newer and we unfortunately didn't check if the class was available on older versions.
I will get that fixed soon. Thank you for reporting.

For the time being please downgrade to SkBee 2.15.1

**Comment by Lennord** [comment]
> ahh... this must be something that is newer and we unfortunately didn't check if the class was available on older versions. I will get that fixed soon. Thank you for reporting.
> 
> For the time being please downgrade to SkBee 2.15.1

Okay, thanks a lot.
