### ISSUE TITLE
[SUGGESTION] "quaternion from [vector] %vector%"

### ISSUE THREAD

**Issue by MikosDrafle** [ShaneBeee/SkBee#457]
### Suggestion

Add a functionality to create a quaternion from degree angles in world space, for example:

quaternion from [vector] vector(45,90,0)

### Alternatives

Use a more complicated cross product system which creates a third vector for you

### Additional Information

I don't really know math LOL

**Comment by ShaneBeee** [comment]
I wouldn't know the math for this either.
I'll leave this here for a while, hopefully someone does a PR or provides the math or something.

**Comment by MikosDrafle** [comment]
I do have the math for at least a bit, but this one's broken since the pitch, yaw and roll affect each other weirdly.
![image](https://github.com/ShaneBeee/SkBee/assets/60538588/5bbe10b2-c79d-4ddb-9948-896761218d54)

**Comment by MikosDrafle** [comment]
![image](https://github.com/ShaneBeee/SkBee/assets/60538588/6a850c0d-6f0f-4103-8b11-77044dbceeb7)
I found a website that allows you to do this, and I am yet to inspect the javascript code for it.

**Comment by nylhus** [comment]
Do you mean converting Euclidean vectors into a quarterion?

**Comment by MikosDrafle** [comment]
> Do you mean converting Euclidean vectors into a quarternion?

Yeah. Something like this rotation into a quaternion.
![image](https://github.com/ShaneBeee/SkBee/assets/60538588/ba676919-5eab-4caf-b3fe-fbae729ad21b)

**Comment by MikosDrafle** [comment]
Found something...
Source: Three.js's source code

setFromEuler( euler, update ) {

		const x = euler._x, y = euler._y, z = euler._z, order = euler._order;

		// http://www.mathworks.com/matlabcentral/fileexchange/
		// 	20696-function-to-convert-between-dcm-euler-angles-quaternions-and-euler-vectors/
		//	content/SpinCalc.m

		const cos = Math.cos;
		const sin = Math.sin;

		const c1 = cos( x / 2 );
		const c2 = cos( y / 2 );
		const c3 = cos( z / 2 );

		const s1 = sin( x / 2 );
		const s2 = sin( y / 2 );
		const s3 = sin( z / 2 );

		switch ( order ) {

			case 'XYZ':
				this._x = s1 * c2 * c3 + c1 * s2 * s3;
				this._y = c1 * s2 * c3 - s1 * c2 * s3;
				this._z = c1 * c2 * s3 + s1 * s2 * c3;
				this._w = c1 * c2 * c3 - s1 * s2 * s3;
				break;

			case 'YXZ':
				this._x = s1 * c2 * c3 + c1 * s2 * s3;
				this._y = c1 * s2 * c3 - s1 * c2 * s3;
				this._z = c1 * c2 * s3 - s1 * s2 * c3;
				this._w = c1 * c2 * c3 + s1 * s2 * s3;
				break;

			case 'ZXY':
				this._x = s1 * c2 * c3 - c1 * s2 * s3;
				this._y = c1 * s2 * c3 + s1 * c2 * s3;
				this._z = c1 * c2 * s3 + s1 * s2 * c3;
				this._w = c1 * c2 * c3 - s1 * s2 * s3;
				break;

			case 'ZYX':
				this._x = s1 * c2 * c3 - c1 * s2 * s3;
				this._y = c1 * s2 * c3 + s1 * c2 * s3;
				this._z = c1 * c2 * s3 - s1 * s2 * c3;
				this._w = c1 * c2 * c3 + s1 * s2 * s3;
				break;

			case 'YZX':
				this._x = s1 * c2 * c3 + c1 * s2 * s3;
				this._y = c1 * s2 * c3 + s1 * c2 * s3;
				this._z = c1 * c2 * s3 - s1 * s2 * c3;
				this._w = c1 * c2 * c3 - s1 * s2 * s3;
				break;

			case 'XZY':
				this._x = s1 * c2 * c3 - c1 * s2 * s3;
				this._y = c1 * s2 * c3 - s1 * c2 * s3;
				this._z = c1 * c2 * s3 + s1 * s2 * c3;
				this._w = c1 * c2 * c3 + s1 * s2 * s3;
				break;

			default:
				console.warn( 'THREE.Quaternion: .setFromEuler() encountered an unknown order: ' + order );

		}

**Comment by MikosDrafle** [comment]
I have coded up a skript-reflect version of this expression.

```
expression quaternion from [vector] %vector%:
    return type: quaternion
    get:
        set {_x} to x of expr-1
        set {_y} to y of expr-1
        set {_z} to z of expr-1

        set {_c1} to cos({_x} / 2)
        set {_c2} to cos({_y} / 2)
        set {_c3} to cos({_z} / 2)

        set {_s1} to sin({_x} / 2)
        set {_s2} to sin({_y} / 2)
        set {_s3} to sin({_z} / 2)

        # Assuming the angle is already in XYZ format:
        set {_q_x} to {_s1} * {_c2} * {_c3} + {_c1} * {_s2} * {_s3}
        set {_q_y} to {_c1} * {_s2} * {_c3} - {_s1} * {_c2} * {_s3}
        set {_q_z} to {_c1} * {_c2} * {_s3} - {_s1} * {_s2} * {_c3}
        set {_q_w} to {_c1} * {_c2} * {_c3} + {_s1} * {_s2} * {_s3}

        set {_quat} to quaternion({_q_x}, {_q_y}, {_q_z}, {_q_w})
        return {_quat}
```

**Comment by wallysaurus** [comment]
No reason to code up functions, Minecraft/Spigot uses JOML's Quaternions and Vectors for display entity rotation, and the library already has built in functions for Quaternion -> Euler angle conversions.
https://joml-ci.github.io/JOML/apidocs/org/joml/Quaternionf.html#rotateXYZ(float,float,float)

It's as easy as:
```
import:
	org.joml.Vector3f
	org.joml.Quaternionf
	java.lang.Math

	le spawn item display at location 0.8 block above player
	set {_display} to last spawned item display
	set display item of {_display} to stone

	set {_rot} to ({_display}.getTransformation().getLeftRotation().clone()).rotationZ(Math.toRadians(0))
```
