### ISSUE TITLE
Get blocks around edge of bound [SUGGESTION]

### ISSUE THREAD

**Issue by K9Lil** [ShaneBeee/SkBee#46]
**Is your feature request related to a problem? Please describe.**
No this feature is not related to any problems
**Describe the solution you'd like**
Syntax to be able to detect the blocks at the edge of a bound 
![image](https://user-images.githubusercontent.com/68028162/87870276-7def4700-c963-11ea-8f26-5c1aa24e996d.png)
for example you could specify a y-level then get a list of all the blocks around the edge of a bound

**Describe alternatives you've considered**
Not really any alternatives to this

**Comment by ShaneBeee** [comment]
I've been thinking about this one a few times and here is my feedback:
1) This could easily be done yourself in Skript using the block within expression. Long story short you could get a list of all blocks in an area. Then do another list that is smaller (the cuboid within the other) and remove from the first list
2) I really dont think a syntax like this would be used by anyone. This to me seems like a 1 person thing to cut down on the code you need to write, syntax sugar as we like to call it.

That said, I will not be implementing this feature.
