### ISSUE TITLE
[SUGGESTION] More entity sorting like Nearest

### ISSUE THREAD

**Issue by xKarubin** [ShaneBeee/SkBee#462]
### Suggestion

Skbee has a Nearest entity expression so I had a suggestion for 3 more sort entity expressions: Arbitrary, Furthest and Random. I am making a Tower Defense game so this could come in handy.

### Alternatives

Not important I think.

**Comment by ShaneBeee** [comment]
Arbitrary = what do you mean by this?
Further = the API doesn't support this
Random = you can already do this with vanilla Skript

**Comment by ShaneBeee** [comment]
closing due to lack of response
