### ISSUE TITLE
[BUG] Key MiniMessage Tag Broken

### ISSUE THREAD

**Issue by hapily04** [ShaneBeee/SkBee#465]
### What happened?

I attempted to test minimessage's `key` tag and it didn't work as expected. When I tested the same string in a plugin using the MiniMessage (default) singleton it worked as advertised on the MiniMessage documentation.

### Steps to reproduce

Simply use this MiniMessage string (this is the one I tested):
"<key:key.jump> hi"
Exact code: 
```
command /test:
	trigger:
		send minimessage from "<key:key.jump> hi" to player
```

### Expected behavior

https://prnt.sc/ObiOFCgx71wO

### SkBee Version

2.16.1

### Server Version

Paper 1.19.4

### SkBee Info

https://prnt.sc/kzP07WTvMiBX

**Comment by ShaneBeee** [comment]
solved on discord
