### ISSUE TITLE
[BUG] Issues with nbt and recipes of villager

### ISSUE THREAD

**Issue by superstorm192** [ShaneBeee/SkBee#478]
### What happened?

I kept downsizing my code until I literally had nothing left and it still breaks so I decided to pull up a bug report.
`set tag "Offers;Recipes" of {_vilc} to tag "Offers;Recipes" of {_vilc}`
this simple equals assignment throws an error: https://hastebin.com/share/ozizupisin.markdown
`set tag "Offers;Recipes" of {_vilc} to nbt compound from "[{maxUses:0,priceMultiplier:0f,buy:{id:""minecraft:barrier"",Count:1b},buyB:{id:""minecraft:air"",Count:1b},sell:{id:""minecraft:barrier"",Count:1b}}]"`
when I add a hardcoded compound, Skbee throws this error:
[Skript] [SkBee ERROR] Message: MalformedNBT: Expected '{' at position 0: <--[HERE]
And when I remove the [], it just clears the trades on the villager.
I ran into this issue when trying to add one trade at the end of the villager trades and remove a certain trade from a villager.

### Steps to reproduce

1. Have a villager with trades
2. run `set tag "Offers;Recipes" of {_vilc} to tag "Offers;Recipes" of {_vilc}` on the villager through skript
3. check server console and villager trades

### Expected behavior

I expect it to set the villager trades to the desired outcome
Also I expect "[]" to be a valid list compound

### SkBee Version

2.17.0

### Server Version

Paper 1.20.1

### SkBee Info

Server Version: git-Paper-119 (MC: 1.20.1)
 Skript Version: 2.6.4
16:14:29.354
Skript Addons:
- skript-gui v1.3-alpha3
- skript-reflect v2.3
- SkQuery v4.1.6
- skLib v1.1.0
SkBee Version: 2.17.0
SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by superstorm192** [comment]
`set tag "Offers;Recipes" of {_vilc} to tag "Offers;Recipes" of {_vilc}` should work fine then, not throw an error. I also tried "tags" but that doesn't exist.

**Comment by superstorm192** [comment]
![image](https://github.com/ShaneBeee/SkBee/assets/10588108/4d48f27c-2be9-4ce4-99cd-39ea310d50a8)

**Comment by ShaneBeee** [comment]
> `set tag "Offers;Recipes" of {_vilc} to tag "Offers;Recipes" of {_vilc}` should work fine then, not throw an error. I also tried "tags" but that doesn't exist.

Ill take a look into this, apparently the tag type is returning incorrectly for the "Offers" tag
