### ISSUE TITLE
[SUGGESTION] Smithing Recipes Update

### ISSUE THREAD

**Issue by pwuddle** [ShaneBeee/SkBee#479]
### Suggestion

Since 1.20 the smithing table recipes have changed due to different templates being added, so currently it seems like the smithing recipe syntax is a little broken. (Also a minor bug report then I guess)

### Alternatives

Addition of a third materialchoice.

![image](https://github.com/ShaneBeee/SkBee/assets/105949629/82956ba6-a86e-479b-99ce-3202f688f61f)

**Comment by ShaneBeee** [comment]
this is currently already planned, see #418

**Comment by Fusezion** [comment]
Reopening with the commit https://github.com/ShaneBeee/SkBee/commit/9cc9d7821641ca453896fc3e6793001df1199f77 being added, just to be reminded to add to next releases patch-notes
