### ISSUE TITLE
Change Armor event not cancellable

### ISSUE THREAD

**Issue by lucasboss45** [ShaneBeee/SkBee#48]
**Describe the bug**
For some reason the change armor is not cancellable despite the example in the documentation showing that you can

**To Reproduce**
Try to cancel a change armor event from SkBee

**Expected behavior**
The event cancels normally

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/29255472/89126013-a38f5b00-d4e2-11ea-9d8a-141b47edb832.png)

**Version Info:**
 - **SkBee Version:** 1.4.7
-  **Skript Version:** 2.4.1
 - **Server Version/Platform** git-Paper-375 (MC: 1.15.2)

**Comment by ShaneBeee** [comment]
I will have to update examples.
According to Paper's JavaDocs, that event is not cancellable.
