### ISSUE TITLE
[BUG] ingredients of recipe {_id} returns <none>

### ISSUE THREAD

**Issue by superstorm192** [ShaneBeee/SkBee#480]
### What happened?

```
command /testrecipe:
	description: makes a recipe under "test"
	permission: deseyad.editrecipies
	trigger:
		set {_res} to iron sword
		set {_ing::*} to barrier, barrier, barrier, barrier, iron ingot, barrier, barrier, barrier, barrier
		set {_id} to "test"
		register new shaped recipe for {_res} with ingredients {_ing::*} with id {_id}
		send "test result: %result of recipe {_id}%"
		send "test ingredients: %ingredients of recipe {_id}%"
```
the test ingredients returns \<none\> when it should return the ingredients
the test result item returns correctly, meaning the recipe is registered

### Steps to reproduce

1. add the above code in skript and load it
2. use /testrecipe command
3. put an iron ingot surrounded by barriers in a crafting table to make sure the recipe has indeed been registered
4. notice the "test ingredients: <none>"

### Expected behavior

The "ingredients of recipe {_id}" should return the list of items that are the ingredients of the recipe with id of {_id}

### SkBee Version

2.17.0

### Server Version

Paper 1.20.1

### SkBee Info

Server Version: git-Paper-119 (MC: 1.20.1)
Skript Version: 2.6.4
Skript Addons:
- skript-gui v1.3-alpha3
- skript-reflect v2.3
- SkQuery v4.1.6
- skLib v1.1.0
SkBee Version: 2.17.0
SkBee Website: https://github.com/ShaneBee/SkBee

**Comment by ShaneBeee** [comment]
so this issue is happening because when using the id "test" in a recipe, it defaults to "skbee:test"

When searching for the recipe, it requires the full "skbee:test" key.... this isn't technically a bug, as much as it's just a silly way to SkBee handled this.
But I will change this expression to support getting the correct ID

**Comment by superstorm192** [comment]
Alright thanks, I can confirm that setting the id to "deseyad:test" allows it to work fine.
