### ISSUE TITLE
[BUG] block vanishing in creative mode when clicked

### ISSUE THREAD

**Issue by superstorm192** [ShaneBeee/SkBee#483]
### What happened?

```
on inventory click:
	set {_comp} to nbt compound of event-slot
#	set {_oof2::1} to tag "SkullOwner" of {_comp} #and "display" doesn't delete the item
	set {_oof2::1} to tag "SkullOwner;Properties" of {_comp} #this, however, does delete the item
```
For some reason, when setting the variable, it deletes the item in event-item if you are in creative mode. doing it to player's cursor slot is fine. It seems to only happen in creative mode with these certain conditions.

### Steps to reproduce

1. run the above code in a skript
2. go into creative mode
3. put any item in the slot that you have selected with your hotbar
4. open inventory
5. click said item while it's in your hotbar
6. notice that the item disappears
7. comment out line 4 and uncomment line 3
8. notice the item doesn't disappear

### Expected behavior

the item should not disappear when getting this tag from it.

### SkBee Version

2.16.1

### Server Version

1.20.1

### SkBee Info

Server Version: git-Paper-119 (MC: 1.20.1)
Skript Version: 2.6.4
Skript Addons:
- skript-gui v1.3-alpha3
- SkQuery v4.1.9
SkBee Version: 2.16.1
SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by superstorm192** [comment]
Wait, i haven't been sending all of skbee info this whole time? I just now noticed the list above ---[Server Info]---

**Comment by ShaneBeee** [comment]
> Wait, i haven't been sending all of skbee info this whole time? I just now noticed the list above ---[Server Info]---

most people don't, but don't worry about it. 
I've been able to replicate the issue, not to try fix it

**Comment by superstorm192** [comment]
it would happen to any item actually, i forgot i had `event-slot is player's hotbar slot` my code

**Comment by ShaneBeee** [comment]
yeah, its actually a bug from a while back, that I fixed, then I broke apparently.
Its an issue with Skript itself I think, but im going to try find a work around

**Comment by superstorm192** [comment]
before i make a bug report about it, has registering a smithing recipe been updated?

**Comment by ShaneBeee** [comment]
we're aware of it being broken, we're actually removing it in the next release (as Bukkit actually removed it and created 2 new recipes).
In the future we'll create the new recipes

**Comment by ShaneBeee** [comment]
ok, after doing some testing, this is either:
a) A Skript bug
b) A server bug

```vb
on inventory click:
	set name of event-slot to "test"
```
this does the exact same thing, the item vanishes.
I think its an issue with creative mode, and how Skript handles it... there's nothing I can do about this unfortunately.

im going to have to close this as a non-skbee issue since Skript does the same thing

**Comment by superstorm192** [comment]
```
	set {_test} to index of event-slot	
	set {_oof2::*} to tag "SkullOwner;Properties;textures" of nbt compound of slot {_test} of player's inventory
```
this also causes the item to vanish, this was my only workaround idea.

**Comment by ShaneBeee** [comment]
yeah, same thing ... Skript issue.
It has to do with Skript updating the player's inventory, which I guess doesn't work when in creative mode
