### ISSUE TITLE
[SUGGESTION] Possibility to make boss bar title formattable

### ISSUE THREAD

**Issue by ItsMhugg** [ShaneBeee/SkBee#489]
### Suggestion

For the boss bar creation, add the possibility to format the title.
I want to use custom font with the `<font:name>` beacon but because we cannot format the title its impossible to use.

Here a syntax preview :
`set {_bar} to boss bar named "le-bar" with formatted title "<font:name> Hello skBee !" with color pink with progress 100`

### Alternatives

For alternative, just add an option to use custom font like
`set {_bar} to boss bar named "le-bar" with title "Hello skBee !" with color pink with progress 100 using/with font "%font%"` :)

**Comment by ShaneBeee** [comment]
as much as I would love to add this, it appears Paper does not have API for using components in BossBars

**Comment by ShaneBeee** [comment]
That would require me to re-write the entire system to utilize both BossBarr system.
That is not something I'm willing to do just to be able to use a font in the title

**Comment by GStudiosX2** [comment]
that is true though i guess the OP if they wanted to could fork and do it or someone else or you do it eventually i dont know

**Comment by ShaneBeee** [comment]
closing due to this is not something we can do right now
