### ISSUE TITLE
[BUG] NBT sub tag being added when checking not set nbt tag

### ISSUE THREAD

**Issue by sluhtie** [ShaneBeee/SkBee#492]
### What happened?

When checking a NBT tag that has a sub-tag (Ex: "custom;isGen"), it will add the custom tag as an empty compound tag to the block/entity that has been checked.
I believe to remember this also happens when checking NBT files.

### Steps to reproduce

1. Write any line of code that checks a nbt tag of an item
**Example:**
```
on place:
    tag "custom;isGen" of nbt of block = 1
    send "1"
```
2. Then check the nbt of the block. 
It will display custom:{} as empty tag in the nbt if not set.

![Screenshot 2023-09-10 001444](https://github.com/ShaneBeee/SkBee/assets/97464371/e1d95093-f3ce-4696-9ff7-8b4bdf56c3fa)

### Expected behavior

The tag not being added when checking its value and it's not set

### SkBee Version

2.18.0

### Server Version

Paper 1.20.1

### SkBee Info

![grafik](https://github.com/ShaneBeee/SkBee/assets/97464371/da565894-f453-4270-97be-d0495a7b8dab)

**Comment by ShaneBeee** [comment]
not a bug (as I said on discord)
this is intended behaviour

**Comment by sluhtie** [comment]
> not a bug (as I said on discord) this is intended behaviour

how would I then prevent this from happening?
when using the has tag expression it still gets added
