### ISSUE TITLE
[SUGGESTION] Adding url contents syntax 

### ISSUE THREAD

**Issue by ahmadMsaleem** [ShaneBeee/SkBee#496]
### Suggestion

Adding a something that's give you the input of raw link

like the url contents from skUtilities, 

### Alternatives

Why not use skUtilities? It is very outdated

**Comment by ShaneBeee** [comment]
SkBee's main goal is to open up the Bukkit API (Minecraft specific features) to Skripters.
I generally don't add stuff that is outside of the realm of Bukkit/Minecraft.

File/Web stuff should definitely be done in another addon.

**Comment by ahmadMsaleem** [comment]
I understand, I guess there's a reason to download skquery 🥲

**Comment by ShaneBeee** [comment]
the problem with adding something as simple as getting the URL content, then people want more... 
There's soooo much you can do with content downloaded from the web that has nothing to do with Bukkit/Minecraft, and people are just going to get a string? What do they do with it?
They're going to ask me for 100+ other syntaxes to manage the returned content.

That said, I really just don't think this fits in SkBee. 
I think if another addon is available, that would be the route to go.
Or possibly the creation of another addon.
But isn't there already WebSK? I think pikachu has one called WebAddon.
There's already many options for this.

Closing as not planned.
