### ISSUE TITLE
 [BUG] Recipe using named items.

### ISSUE THREAD

**Issue by ImCardiaK** [ShaneBeee/SkBee#505]
### What happened?

When creating a new crafting recipe and adding multiple renamed Netherite ingots to it in any way, the server crashes, or the milliseconds (ms) display an unimaginable number.

### Steps to reproduce

1. Create new crafting recipe.
2. Add two renamed netherite ingot to the items needed for crafting.
3. execute /sk reload (skript)
4. LOOK CONSOLE or Look ms

### Expected behavior

That the craft script does not crash the server.
And/or that it doesn't give a huge MS time.

### SkBee Version

2.18.3

### Server Version

Paper 1.19.3 -431

### SkBee Info

Server Version: bgit-Paper-431 (MC: 1.19.3)
Skript Version: b2.6.4
Skript Addons:
bskRayFall v1.9.28
bSkQuery v4.1.9
SkBee Version: b2.18.3
SkBee Website: bhttps://github.com/ShaneBeee/SkBee

**Comment by Fusezion** [comment]
Please provide your code, you used.

**Comment by ImCardiaK** [comment]
Oh ! Awesome !
Thank you for your help ! 🔥
I hadn't thought of doing it like that!

It works now! (Even if the ms are still a little high compared to without)
