### ISSUE TITLE
[SUGGESTION] Player head - Crafting recipes

### ISSUE THREAD

**Issue by ImCardiaK** [ShaneBeee/SkBee#506]
### Suggestion

For my server, I need to use custom player heads in crafting recipes. However, to do this, I need the addon to recognize "player head" as well as the name of the head.

This doesn't seem to work when I do:
```
set {_lunetor} to player head named "&7Lunétor" with nbt from "(nbt)"
register new shaped recipe for iron sword named "&6Épée Lunetor" using air, {_lunetor}, air, air, air, air, air, air, and air with id "lunetor"
```

Do you perhaps have a better way to do this? If not, my suggestion would be to add this as a possibility!
Thank you!

### Alternatives

I haven't considered any other alternative.

### Additional Information

SkBee - Version: 2.18.3
Paper - 1.19.3-431

**Comment by Fusezion** [comment]
Hey! So the way the system works is like this.

`player head` = `material choice` meaning any player head will work no matter the nbt
`player head named ""` = `exact choice` meaning all nbt must be a 1 to 1 match
`player head with lore ""` = `exact choice`
`player head with nbt from "{}"` = `exact choice`

Sadly there's not much else we can do in the case here your code seems to already be set up to that it's just your item is incorrect

**Comment by Fusezion** [comment]
Alright, as it's been 2 days without a reply and based off the context this is a suggest that we can't add as it's just a limitation in the way Minecraft handles recipes, I'm gonna go ahead and close this.
