### ISSUE TITLE
[BUG] Skbee not loading

### ISSUE THREAD

**Issue by Bassalo** [ShaneBeee/SkBee#508]
### What happened?

When I start my server, this gets send in the console **https://hastebin.com/share/hevifiqavi.php**. 

I have skript **2.7.1**

Fusezion said on discord: _ughh, it's implying a failure in loading nbt-api  but doesn't apparently catch it meaning it thinks it's successful_ (no idea if it helps or not)

### Steps to reproduce

I don't really have steps as I got told it's not normal, but you just have to have these addons (the screenshot attached) and start the server

![image](https://github.com/ShaneBeee/SkBee/assets/111898803/5e70d081-f589-4f1e-a782-dcd593acb81f)

### Expected behavior

I expected Skbee to load normally but I guess mine is broken for some reason, I have no idea what I did wrong :(

### SkBee Version

2.18.3

### Server Version

Paper 1.20.1

### SkBee Info

https://hastebin.com/share/gokidaxelu.ruby

**Comment by Bassalo** [comment]
I can't update to 1.20.2, yes I'm on Minehut you can blame me

**Comment by Bassalo** [comment]
I forgot to mention but, I was getting that too when I was on 1.19.4

**Comment by ShaneBeee** [comment]
I've recently tested on 1.19.4, and cannot replicate.
Appears to load fine for me
<img width="1022" alt="Screenshot 2023-10-17 at 9 07 37 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/84ce00b0-fd4a-449f-88a4-3929ebe0c417">

**Comment by ShaneBeee** [comment]
Just to test, It also loaded fine on 1.20.1, therefor ... I cannot replicate this issue
<img width="818" alt="Screenshot 2023-10-17 at 9 11 30 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/43702a2a-e476-4b0d-9889-ce426382735f">

**Comment by Bassalo** [comment]
What paper version do you use? I got told it's maybe that

**Comment by Bassalo** [comment]
Yes I see, well if I can't get the same version I guess it's why I get it to not load

**Comment by Fusezion** [comment]
Have you tried downgrading skbee to a version before the 1.20.1 bump?

**Comment by Bassalo** [comment]
I will be testing that, thanks

**Comment by ShaneBeee** [comment]
> Yes I see, well if I can't get the same version I guess it's why I get it to not load

for the record, I just downloaded 1.19.4 and 1.20.1 from paper's website, and setup those 2 servers to test.
The latest builds are definitely available from their website.

**Comment by Bassalo** [comment]
Okay I see, but from Minehut I don't see something to update Paper :/

**Comment by Bassalo** [comment]
Downgrading Skbee to 2.18.1 worked tho, thanks for the support !

**Comment by ShaneBeee** [comment]
ok, I started up a Minehut server, I still cannot replicate the issue
<img width="1450" alt="Screenshot 2023-10-17 at 9 47 53 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/fbdc0285-36d2-467f-b965-1c3adcf9c8a8">
<img width="1450" alt="Screenshot 2023-10-17 at 9 48 06 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/a348e7a0-d05f-4a4d-8400-7cb580170d39">

**Comment by Fusezion** [comment]
📸 🖼️

**Comment by Bassalo** [comment]
I don't know what I do wrong, maybe because of Minehut?

**Comment by ShaneBeee** [comment]
closing due to I cannot replicate this.
