### ISSUE TITLE
[BUG] Nbt stuffs in local variables are broken when update 1.4.11 to 1.5.0 SkBee

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#51]
**Describe the bug**
I'm trying to assign new nbt value to item in local variable but I can't

**To Reproduce**
1. Register an item to local variable with nbt {test:"test stuff"}
2. try to add new value like {test:"new test stuff"}
3. give this local variable to player

**Expected behavior**
Should overwrite new value to nbt. Like same as 1.4.11

**Version Info:**
 - **SkBee Version:** (ex: 1.0.0) 1.5.0
-  **Skript Version:** (ex: Skript 2.5-alpha3) Skript 2.5 beta 2
 - **Server Version/Platform** (ex: Spigot 1.15.2) Paper 1.16.2

**Additional context**
No issue in 1.4.11 so I will use that for now <3

**Comment by ShaneBeee** [comment]
Im getting an error from that:
```
[11:37:44 ERROR]: [Skript] [SkBee ERROR] Invalid NBT: {test:123 321}
```
that would be due to the fact that its not a valid NBT string.

**Comment by ShaneBeee** [comment]
closing due to user error.

**Comment by rudde0** [comment]
look, it is working but

```
command /item:
	trigger:
		set {_i} to diamond sword with nbt "{test:1234}"
		send "&aNBT: %nbt of {_i}%"
		set {_v} to "123321"
		add "{new:""%player's location%""}" to nbt of {_i}
		set player's tool to {_i}
		send "&aNBT: %nbt of player's tool%"
```

it isn't working:
```
command /item:
	trigger:
		set player's held item to diamond sword with nbt "{test:1234}"
		set {_i} to player's held item
		send "&aNBT: %nbt of {_i}%"
		set {_v} to "123321"
		add "{new:""%player's location%""}" to nbt of {_i}
		set player's tool to {_i}
		send "&aNBT: %nbt of player's tool%"
```

when trying to get {new:"LOCATION"} nbt

**Comment by ShaneBeee** [comment]
what exactly isn't working?

**Comment by rudde0** [comment]
{new:""loc""} can't added to the item when set {_i} to player's held item

**Comment by rudde0** [comment]
I couldn't explain the issue before because I installed SkBee 1.5.0 to my server and it break almost everything in important stuff and I downgraded the version immediately. I installed newest SkBee to my test server right now for try explain the issue.

**Comment by ShaneBeee** [comment]
Fixed.
If you are in a rush, you can grab the artifact here
https://github.com/ShaneBeee/SkBee/suites/1117908411/artifacts/15796017
