### ISSUE TITLE
[SUGGESTION] MMOCore Fishing

### ISSUE THREAD

**Issue by sorandno** [ShaneBeee/SkBee#519]
### Suggestion

Please add fishing detection with MMOCore Plugin.

It won't detect it.

### Alternatives

on fish:
  if fish event state = caught fish:

It doesn't respond to this script.

### Additional Information

MMOCore Plugin
https://www.spigotmc.org/resources/mmocore.70575/

**Comment by ShaneBeee** [comment]
SkBee will not be adding any hooks to other plugins.
