### ISSUE TITLE
[SUGGESTION] Display Entity Item to return itemstack

### ISSUE THREAD

**Issue by boxic** [ShaneBeee/SkBee#522]
### Suggestion

Currently DisplayEntity - Display Item aka `[the] display item of %entities% ` only returns the vanilla item, I want it to return the actual item.
What do I mean "actual item"? I mean with nbt data, because today I had a bunch of display entities with items with custom model data as their display item, and I wanted to know which custom object they were colliding with -- but I couldn't, because this statement just returned "leather horse armor" instead of the item stack with nbt or whatever

### Alternatives

I just named the display entities to avoid it, but I think it should still be changed, because as time goes on, more and more people are gonna be using display entities with custom model data, since it's crazy useful

**Comment by Fusezion** [comment]
Just to add a bit more to this, the reason it shows up as a plain item Boxic is because the `ItemType#toString` is just terrible and doesn't display all information

**Comment by boxic** [comment]
weird, when I set {_item} to display item of the display, then compared custom model data of {_item}, it didn't work properly for me
