### ISSUE TITLE
[BUG] Extremely Slow File Reloading With Custom Recipes

### ISSUE THREAD

**Issue by skTanky** [ShaneBeee/SkBee#524]
### What happened?

When I reload my file with a shaped crafting recipe, the server either crashes/times me out without reloading

        register new shaped recipe for {@revivebeaconitem} using diamond block, {@heartitem}, diamond block, totem of undying, beacon, totem of undying, diamond block, {@heartitem} and diamond block with id "revive_beacon"`

### Steps to reproduce

1. Create shaped recipe (Not tested with shapeless)
2. Reload file

### Expected behavior

Would expect the file to reload without issue

### SkBee Version

2.18.4

### Server Version

Paper 1.19.4

### SkBee Info

![image](https://github.com/ShaneBeee/SkBee/assets/121093474/b4b27aa7-a463-4f70-be85-0c8fdea04618)

**Comment by ShaneBeee** [comment]
This isn't an SkBee issue, this is actually a Skript issue.
You are trying to put too many expressions in one line.

I recommend breaking up the ingredients and doing it in multiple lines (ex: using a list).

**Comment by skTanky** [comment]
Alright thanks
