### ISSUE TITLE
[SUGGESTION] Add remove for delete tag x of nbt compound of y

### ISSUE THREAD

**Issue by EquipableMC** [ShaneBeee/SkBee#525]
### Suggestion

I feel like having remove should also be an option for removing nbt tags from items, since remove and delete basically mean the same thing, and it would be smart to have both.

### Alternatives

Example:
remove tag "test" of nbt compound of event-block 
This would remove the entire tag, just like delete
I know syntax exist for removing stuff from an existing tag, but if you wanted to remove the entire tag, remove should also be an option.

**Comment by ShaneBeee** [comment]
That wouldn't work.
The remove changer is setup in Skript as `remove %object1% from %object2%` 
ex: `remove 1 from health of player`
object1 = `1` (a number)
object2 = `health of player` (an expression which has the remove changer)
the delete changer is setup in Skript as `delete %object%`
ex: `delete tag "x" of nbt of player's tool`
object = `tag "x" of nbt of player's tool` (an expression which has a delete changer)


These are two entirely different things.

**Comment by EquipableMC** [comment]
Oh alright, I did not realize that
