### ISSUE TITLE
[BUG] smething creates wrong item

### ISSUE THREAD

**Issue by theuwufurry** [ShaneBeee/SkBee#526]
### What happened?

smithing transform creates wrong item

### Steps to reproduce

1.

function item(item:item, name:string, lore:strings, variable:string, moddeldata:int):
    set {items::%{_variable}%} to unbreakable {_item} named {_name} with lore {_lore::*} with model data {_moddeldata}
on load:
	item(diamond sword, "<##5E5D5D>S<##5D5B5D>t<##5C585C>a<##5B565C>b<##5A545C>i<##59515B>l<##584F5B>i<##574D5B>z<##564B5B>e<##55485A>d <##54465A>P<##53445A>e<##534159>t<##523F59>r<##513D59>i<##503A58>f<##4F3858>i<##4E3658>e<##4D3458>d <##4C3157>S<##4B2F57>w<##4A2D57>o<##492A56>r<##482856>d", ("&8COSMETIC"), "stabilizedpetrified", 79669)
	item(stone sword, "&8Petrified Sword", ("<##00FFE0>T<##07F8E1>h<##0DF0E2>e <##14E9E3>s<##1BE2E4>w<##22DBE4>o<##28D3E5>r<##2FCCE6>d <##36C5E7>h<##3CBDE8>a<##43B6E9>s <##4AAFEA>l<##51A8EB>e<##57A0EC>f<##5E99EC>t <##6592ED>y<##6B8AEE>o<##7283EF>u <##797CF0>j<##8075F1>u<##866DF2>s<##8D66F3>t <##945FF3>l<##9A57F4>i<##A150F5>k<##A849F6>e <##AF42F7>y<##B53AF8>o<##BC33F9>u<##C32CFA>r <##C924FB>f<##D01DFB>a<##D716FC>t<##DE0FFD>h<##E407FE>e<##EB00FF>r"), "petrifiedsword", 49019)
command /givepet:
    trigger:
        set player's tool to {items::stabilizedpetrified}

2.

on load:
    register smithing transform recipe:
        id: "theuwufurry:stabilizedpetrifedsword"
        result: {items::stabilizedpetrified}
        template: netherite scrap
        base: {items::petrifiedsword}
        addition: diamond sword

3.<img width="820" alt="Screenshot 2023-11-25 172423" src="https://github.com/ShaneBeee/SkBee/assets/50066996/75070d99-165a-4edd-8310-2fcc97822c73">

### Expected behavior

creates wrong item

item should have looked like

![image](https://github.com/ShaneBeee/SkBee/assets/50066996/a1b2e18c-6b11-4e21-a568-fc18b8a9e56f)

### SkBee Version

3.0.0-beta 2

### Server Version

purpur 1.20.2

### SkBee Info

![image](https://github.com/ShaneBeee/SkBee/assets/50066996/2de0bcef-0525-4ae2-a1d2-8d78c6d5a31c)

### Additional Information

useing purpur a fork of paper

**Comment by Fusezion** [comment]
Please double check you set recipe ods correctly. Looking at internal code it's all setup correctly

**Comment by theuwufurry** [comment]
uh yes when i do /givepet it gives me the correct item

**Comment by Fusezion** [comment]
Are you checking recipe ids or are you just running a command saying they're the same without checking

**Comment by theuwufurry** [comment]
command /givepet:
trigger:
set player's tool to {items::stabilizedpetrified}

this command gives the item and it gave me the correct item

when i set the result it to it give wrong item

**Comment by Fusezion** [comment]
So you're running a command and not checking recipe id

**Comment by theuwufurry** [comment]
how do i do that

**Comment by ShaneBeee** [comment]
doing a bunch of testing, I believe this is an issue with Minecraft.
Smithing recipes aren't really meant to take a bunch of items and make a new item, but rather merge them.
Therefor its taking your petrified sword and applying its data to your new sword, kind of overriding.

**Comment by Fusezion** [comment]
Ah if that's the case we might want to add papers copyNBT setting

**Comment by ShaneBeee** [comment]
might be a good addition
