### ISSUE TITLE
[NOT WORKING]

### ISSUE THREAD

**Issue by AnantAgr123** [ShaneBeee/SkBee#529]
### What happened?

Its not working when i insteall or upload it in my server the server is 1.20.1 but doesnt works..

### Steps to reproduce

1.
2.
3.

### Expected behavior

e

### SkBee Version

3.0.0Beta2

### Server Version

1.20.1 paper

### SkBee Info

e

### Additional Information

e

**Comment by Fusezion** [comment]
Please follow the instructions given when you're making the issue, this is not a place for you to joke around or make joke issues, either provide info or nothing will happen, closing issue as this is just a joke to you apparently
