### ISSUE TITLE
[BUG] Pathfinding Problems

### ISSUE THREAD

**Issue by WallyTube** [ShaneBeee/SkBee#53]
**Describe the bug**
I've tried using pathfinding for 3 different addons now. None of the pathfinding effects work. I've also used both Minehut and my own localhost servers to test this.

**To Reproduce**
Use the pathfinding effect. [Pathfind link](https://skripthub.net/docs/?id=4354)

**Expected behavior**
The chicken to pathfind to 6 blocks in front of the player, or to the set variable.

**Screenshots/Errors**
The chicken doesn't pathfind, it just spawns at the player.

**Version Info:**
 - **SkBee Version:** 1.5.1
-  **Skript Version:** Latest
 - **Server Version/Platform** Spigot 1.16.1

**My Code:**
![image](https://user-images.githubusercontent.com/69739715/91250073-c09ffe00-e71d-11ea-86b6-5adc510f9b08.png)

**Comment by WallyTube** [comment]
Putting this code in the original post was a little buggy.

**My Code:**
```command /chicken:
	trigger:
		spawn a chicken at the player
		set path target of last spawned chicken to {path}

command /setpath:
    trigger:
        set {path} to player's location```

**Comment by ShaneBeee** [comment]
> Server Version/Platform Spigot 1.16.1

<img width="792" alt="Screen Shot 2020-08-25 at 9 14 18 PM" src="https://user-images.githubusercontent.com/20008482/91254737-fb9f3300-e717-11ea-9d41-d324b30c68d3.png">
