### ISSUE TITLE
[BUG] SkBee stuck on update check

### ISSUE THREAD

**Issue by Ribi333** [ShaneBeee/SkBee#536]
### What happened?

So, whenever I load my server that uses Paper 1.20.2 and SkBee 3.0.1, SkBee starts loading and it just never stops. 

### Steps to reproduce

1. Server using Paper 1.20.2
2. Skript 2.7.3 and SkBee 3.0.1
3. Start/restart the server
Not sure if it is reproduceable but you can try if you want.

### Expected behavior

For SkBee to load.

### SkBee Version

3.0.1

### Server Version

Paper 1.20.2

### SkBee Info

I can't even log into my server as it is not starting.

### Additional Information

This is what console says everytime I try restarting/starting when it gets to loading SkBee:
[message4.txt](https://github.com/ShaneBeee/SkBee/files/13627456/message4.txt)

**Comment by Ribi333** [comment]
Works now, thanks!
I am guessing I won't be alerted when SkBee updates, right?

**Comment by ShaneBeee** [comment]
Correct.
If the server is hanging and there is no error, I can't do anything to fix it.
My guess is its a connection issue to GitHub, but still, it should eventually timeout and throw an error.
Something would be helpful in this case

**Comment by ShaneBeee** [comment]
Closing as there is nothing I can do to fix an issue when no errors is present.
As stated earlier, just disable the update check, and you'll have to manually check this repo for updates
