### ISSUE TITLE
[SUGGESTION] Use PersistentDataContainer public namespace

### ISSUE THREAD

**Issue by Koozu1** [ShaneBeee/SkBee#538]
### Suggestion

It seems like the written nbt tags use the PersistentDataContainer api to store the data. It also seems like the data is kept in a private namespace and so cannot be accesses for example via a java plugin. 
I suggest to at least have an option to use a public namespace.

### Alternatives

To always use public namespace.

### Additional Information

i.getItemMeta().getPersistentDataContainer().getKeys() doesn't return any keys with an item created with skBee with a nbt tag.

**Comment by ShaneBeee** [comment]
The only places in SkBee that use PDC for NBT is:
- "custom" tag on nbt of entity
- NBT of non tile entity blocks (its stored in the chunk's PDC)

Neither of which are using private/hidden kids as you have stated

**Comment by ShaneBeee** [comment]
closing due to lack of response
