### ISSUE TITLE
[BUG] ciritical bug plz fix quickly

### ISSUE THREAD

**Issue by arts7493** [ShaneBeee/SkBee#54]
**Describe the bug**
skbee break other plugin's interact events
break farmland, no perm user can step pressure plate
if remove skbee, all features works(ex. can't break farmland, no perm user can't step pressure plate)
sry bad english
maybe this patch is problem
- Added an “entity physical interact” event, called when an entity physically interacts with a block (ie: trampling farmland)
**To Reproduce**
Please include clear steps to reproduce the behavior

**Expected behavior**

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.

**Version Info:**
 - **SkBee Version:** (ex: 1.0.0) 1.5.2
-  **Skript Version:** (ex: Skript 2.5-alpha3) 2.4.1
 - **Server Version/Platform** (ex: Spigot 1.15.2) paper 1.15.2

**Additional context**

**Comment by ShaneBeee** [comment]
Im not sure I quite understand your issue. 
Can you show some code you're using that caused the problem.

**Comment by arts7493** [comment]
not require code
just install SkBee 1.5+
and trampling farmland or step pressure plate

i prevented break farmland from trampling with plugin but it doesn't work
but remove skbee plugin, it works

**Comment by ShaneBeee** [comment]
Seems to work fine for me:

<img width="966" alt="Screen Shot 2020-08-29 at 1 59 01 PM" src="https://user-images.githubusercontent.com/20008482/91646028-eff58a00-e9ff-11ea-80f7-dd4a1bbd7001.png">
<img width="966" alt="Screen Shot 2020-08-29 at 1 59 04 PM" src="https://user-images.githubusercontent.com/20008482/91646030-f421a780-e9ff-11ea-81ed-36d143e8960b.png">
<img width="966" alt="Screen Shot 2020-08-29 at 1 59 41 PM" src="https://user-images.githubusercontent.com/20008482/91646032-f4ba3e00-e9ff-11ea-84e0-3f2eb47c05d6.png">
<img width="966" alt="Screen Shot 2020-08-29 at 1 59 45 PM" src="https://user-images.githubusercontent.com/20008482/91646033-f5eb6b00-e9ff-11ea-9c8e-2187843294c7.png">

**Comment by arts7493** [comment]
first you should prevent to break farmland with other, not skript code

**Comment by ShaneBeee** [comment]
This has been fixed.
If you're in a rush for it, here is an artifact
https://github.com/ShaneBeee/SkBee/suites/1117380186/artifacts/15784085

**Comment by arts7493** [comment]
thanks :)
