### ISSUE TITLE
Merge by TextComponent

### ISSUE THREAD

**Issue by AsuDev2** [ShaneBeee/SkBee#545]
### Suggestion

It would be great if we can merge text components by a text component delimiter. An example of how this can be useful is for chat related stuff. If you need to manipulate chat and break down words into their own components (example [item]) and you want to merge all the comps later by a delimiter and have that delimiter have functionality like a text component (If you split your message up by " ",  then merge it later, the " " will have no events like hovering). 

Here is example code:
`set {_merger} to text component from " "`
`set hover event of {_merger} to a new hover event showing "&7Click to message &b%{_sender}%"`
`set {_comp} to merge components {_comps::*} with {_merger}`

This will make sure that the delimiter " " will have the hover event applied to it. Currently, this code will run with no errors, but the delimiter has no events at all (even when applied).

### Alternatives

I don't know of any other alternatives.

**Comment by Fusezion** [comment]
This shouldn't be too hard and was something I was sorta aware of. I believe the method I did requires components, so that's easy. The only painful part is retaining hover events. If you need to retain, you really shouldn't merge via " " as it's a whole new component

**Comment by ShaneBeee** [comment]
the delimiter probably has no hover event because its a space, there's nothing to hover over
