### ISSUE TITLE
[SUGGESTION] Add Tebex Support

### ISSUE THREAD

**Issue by CollidaCube** [ShaneBeee/SkBee#549]
### Suggestion

I was thinking of adding support for tebex expressions and stuff but I don't know if that is something you would admit into SkBee or if I should just put it in a different plugin? To be clear, I'm writing the code for this feature.

### Alternatives

I've considering DMing you on discord but people don't usually appreciate that lol

### Additional Information

Tebex has an [SDK](https://github.com/tebexio/Tebex-Minecraft/tree/main/sdk) that I believe a lot of people would love to have access to in skript.

**Comment by Fusezion** [comment]
SkBee's current suggestion model is only to add things that bukkit provides via their api. We don't intend to add any more apis to skbee as it can easily become bloated due to this. This is the type of thing that's better off inside it's own addon where it's easily maintained.
