### ISSUE TITLE
Knowledge Book

### ISSUE THREAD

**Issue by Zarcrix** [ShaneBeee/SkBee#55]
Hey! 
When I try using the knowledge book (running the command) I get a "internal error occurred while performing this command" error. Everything else to do with recipes works fine except for this, any ideas why?

Thanks for your time !

**Comment by ShaneBeee** [comment]
So what's the error?
What about the rest of the stuff from the issue template you deleted?

**Comment by ShaneBeee** [comment]
Im going to need to rest of that error. Thats about 1/4 of the error, I need the actual error part which is below that.

**Comment by ShaneBeee** [comment]
closing due to lack of response.
