### ISSUE TITLE
[SUGGESTION] Add slot support for item flags of expression

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#554]
### Suggestion

Add support for slots in the `item flags of %itemtypes%` expression

### Alternatives

n/a

### Additional Information

this just allows updates to items in real time like `clear item flags of items in player's inventory`

**Comment by ShaneBeee** [comment]
I'm going to say no to this one right now.
Skript has an issue with slots, for example in the InventorySlot (I think thats the one), `#getItem` returns a clone of the ItemStack. Which creates a bunch of extra work to re-set the ItemStack.
This is just a royal pain in the butt to deal with, and just makes for really messy code.

If player's need be, they can loop the items in the inventory and manage it themselves.
