### ISSUE TITLE
[SUGGESTION] Get NBT copy of NBT compound

### ISSUE THREAD

**Issue by cheeezburga** [ShaneBeee/SkBee#557]
### Suggestion

Would love to just be able to get a copy of an NBT compound directly. A workaround type thing that I'm using at the moment is just `set {_copy} to nbt copy of "%{_originalNBT}%"`. I'm not sure if it's possible to allow getting the NBT copy of an NBT compound, or if there are any issues or conflicts or anything, but I feel like it'd be useful.

### Alternatives

The only alternative that I've tried is the one described in the Suggestion field.

### Additional Information

N/A

**Comment by Fusezion** [comment]
What are you proposing exactly as syntax usage since the whole point of `nbt copy of %compound%` is to allow creating copies of it all

**Comment by ShaneBeee** [comment]
> What are you proposing exactly as syntax usage since the whole point of `nbt copy of %compound%` is to allow creating copies of it all

im assuming he means getting a copy of a compound
ex: `set {_copy} to nbt copy of {_nbt}`

**Comment by Fusezion** [comment]
Yeah I realized that shortly after you pushed the commit
