### ISSUE TITLE
[SUGGESTION] Set/delete/clear NBT file in variable

### ISSUE THREAD

**Issue by cheeezburga** [ShaneBeee/SkBee#559]
### Suggestion

I was trying to clear the compound in a NBT file variable, and couldn't find a way to do so. I tried the following:
```
set {var} to nbt from file "path/to/file/here.dat" # setup

set {var} to empty nbt compound # obviously just sets the variable to empty nbt compound, losing the reference to the NBT file
delete {var} # just deletes the variable obviously

set value within {var} to empty nbt compound # error: value within {var} can't be set to anything
delete value within {var} # error: value within {var} can't be deleted/cleared

!set nbt of {var} to empty nbt compound # error: an nbt compound can't be set to anything
```
If I'm just missing something then nevermind, but if not then would love to be able to do this if its possible.

### Alternatives

I also tried the following, which I thought fit better under this Alternatives section:
![image](https://github.com/ShaneBeee/SkBee/assets/47320303/b23845cb-9a7e-46ba-a3de-e71fddb5e8f9)
The path in the screenshot is the path of the NBT file stored in the variable. Also tried doing the same thing in the screenshot but with a `save nbt file from nbt from file "path.dat"` in between, and it still didn't work.

**Comment by ShaneBeee** [comment]
so the first suggestion I can do, I'm going to add a reset option, so resetting the NBT compound will clear it.

The second one there, that just won't work.
Setting a var to an nbt file, creates a reference to that file. 
From there you can set tags, then save the file.
Just straight up doing it without a var won't work.

**Comment by cheeezburga** [comment]
Appreciate it, for sure will be useful. And ye fair, I guess I never really thought about how the variable keeps track of the file but Fuse explained it to me and I get why that just isnt a possibility now.
