### ISSUE TITLE
[BUG] Unable to load or set nbt of block

### ISSUE THREAD

**Issue by SkriptStudy** [ShaneBeee/SkBee#561]
### What happened?

set tag "Lit" of nbt of event-block to true
nbt of event-block

The nbt value of the block remains unchanged, and all nbt values of the block are not imported.
For example, if a block is waterlogged or Lit

### Steps to reproduce

1.set tag "Lit" of nbt of event-block to true
2. 
3.message "%nbt of event-block%"

### Expected behavior

1. candle is lit or waterlogged
2. grass block of snowy
3. More nbt data . basic lit or waterlogged is also not output.

### SkBee Version

3.1.0

### Server Version

Spigot 1.20.4

### SkBee Info

![image](https://github.com/ShaneBeee/SkBee/assets/157591881/1ee7c1f5-97d4-4060-a6e5-d2282536c24b)

**Comment by ShaneBeee** [comment]
thats because none of those are valid NBT tags, thats block data

**Comment by SkriptStudy** [comment]
It worked in the previous version, but now the Minecraft version has changed, so the way it works. I didn't know.
Thank you for letting me know.

**Comment by ShaneBeee** [comment]
Im not sure what you're talking about, NBT has never supported the things you're talking about.
