### ISSUE TITLE
[SUGGESTION] Allow strings in expressions that call for text components

### ISSUE THREAD

**Issue by cheeezburga** [ShaneBeee/SkBee#564]
### Suggestion

Allow for strings to be provided as input, instead of having to turn them all into components. For example
```
set component lore of tool to ("asfd", "", keybind component of "key.swapOffhand")
# this errors, and requires the following to work

set component lore of tool to (text component of "asdf", text component of "", keybind component of "key.swapOffhand")
```

### Alternatives

Just making all the strings components.

**Comment by ShaneBeee** [comment]
ok, I added this to the lore one. I don't see anywhere else that really needs strings, so if you see any, please let me know
