### ISSUE TITLE
[SUGGESTION] Getting the name of the fishing caught entity

### ISSUE THREAD

**Issue by EquipableMC** [ShaneBeee/SkBee#571]
### Suggestion

There is currently no way to get the name of the fishing caught entity, though there should be. When broadcasted, it returns "dropped diamond". There should be a way to get just the name (like diamond) or if it is named, like named test, it returns "test".

### Alternatives

it should be `name of fishing caught entity`

**Comment by ShaneBeee** [comment]
it returns "dropped diamond" because its a dropped item, and thats how their toString() works.
if you want the item, you use skript's `item of %entity%` expression

**Comment by EquipableMC** [comment]
So it would be item of dropped entity? I don't understand sorry
