### ISSUE TITLE
[SUGGESTION] Expand Unleash Event

### ISSUE THREAD

**Issue by JakeGBLP** [ShaneBeee/SkBee#572]
### Suggestion

The current Unleash Event is using the [org.bukkit.event.entity.EntityUnleashEvent](https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/EntityUnleashEvent.html) class which is outdated since [org.bukkit.event.player.PlayerUnleashEntityEvent](https://jd.papermc.io/paper/1.20/org/bukkit/event/player/PlayerUnleashEntityEvent.html), which extends it and adds player API to it, exists. 

### Alternatives

reflect i guess

### Additional Information

https://github.com/ShaneBeee/SkBee/blob/master/src/main/java/com/shanebeestudios/skbee/elements/other/events/OtherEvents.java#L568

https://jd.papermc.io/paper/1.20/org/bukkit/event/player/PlayerUnleashEntityEvent.html

https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/EntityUnleashEvent.html

**Comment by Fusezion** [comment]
Shouldn't replace existing event but adding support for getting player should be fine. PlayerUnleashEntityEvent is exactly as it sounds an event called when the player does it themselves

**Comment by ShaneBeee** [comment]
I just added a player getter... easy peasy!

**Comment by Fusezion** [comment]
> I just added a player getter... easy peasy!

just wanting to be sure can you try to use `event-entity` if we have one

**Comment by ShaneBeee** [comment]
yes, I tested, works fine
