### ISSUE TITLE
[SUGGESTION] Virtual Trade GUI

### ISSUE THREAD

**Issue by TheAbsolutionism** [ShaneBeee/SkBee#574]
### Suggestion

I am inquiring for a potential feature of adding a virtual trade gui, granted if possible.
I believe having this feature may support some skripters.

The purpose behind this proposal, has to deal with custom items needing to be replaced in shopkeepers when updating the server version. Though this is more of a personal request, due to I have an overwhelming amount of shopkeepers and had to update my server from 1.20.1 to 1.20.4 because of the recent wave of players crashing servers. With the ability to make a custom/virtual trade gui through skript, allows all items to automatically be updated, rather than manually replacing all old items with the new items.

My propsed syntax
`
set {_trade} to a virtual trade gui
add trade %itemstack% [and %itemstack%] with [the] result %itemstack% to %virtual trade%

or

add trade to %virtual trade% :
   set offer 1 to %itemstack%
   set offer 2 to %itemstack%
   set result to %itemstack%
`

I understand if this suggestion is not worth the time to create or is not able to be made!

Thank you

### Alternatives

I have currently not looked into other alternatives, due to the fact that having control over this feature via Skript would be beneficial.

**Comment by Fusezion** [comment]
you're already able to do virtual guis by using a merchant over a villager for trades

**Comment by TheAbsolutionism** [comment]
My apologies, I did not know SkBee had that feature already. I was only looking for the term "trade" in the docs.
Shane has helped me in the discord as well.
But thank you as well Fusezion.

Sorry for the issue post!
