### ISSUE TITLE
SkBee ignores the enable-player-collisions parameter

### ISSUE THREAD

**Issue by ZConnorZ** [ShaneBeee/SkBee#58]
Most likely, because of SkBee, there is no way to disable player collisions. (paper.yml)

**To Reproduce**
Set the parameters in paper.yml: enable-player-collisions: false (Paper.yml)

**Expected behavior**
Collisions will work between players, even if you have disabled it.

**Version Info:**
 - SkBee 1.6.0
-  Skript 2.5 (Latest release)
 - Paper 1.16.3 (build 206)

**Additional context**
I don't understand why, but only when on the skbee, server the collisions are still working, even if I disabled them...

**Comment by ShaneBeee** [comment]
for funnies, try disabling scoreboards in the SkBee config.
I wonder if it has something to do with that.

That is literally the only thing I can think of.

**Comment by ZConnorZ** [comment]
Yes, it worked

**Comment by ShaneBeee** [comment]
Im going to close this. I do not believe this is fixable.

SkBee scoreboards use teams. And I think Paper is also using teams to disable player collisions. Since each player has their own team I think thats what messes this up, and unfortunately there is nothing I can do about that.
