### ISSUE TITLE
can't write single quote in item nbt

### ISSUE THREAD

**Issue by CirrusPreeminent** [ShaneBeee/SkBee#583]
### What happened?

When I try to add single quote in item NBT there will be backslash (\\) come out of nowhere

This is the script:
```
on pick up:
    send "test1"
    If event-item is stick:
        set {_e} to event-item
        send "test2"
        set {_test::*} to lore of {_e}
        send "%{_test::*}%"
        If lore of {_e} contains "&bเส้นใยแมงมุมมีความแข็ง":
            send "test3"  
            set {_nbt} to nbt compound of {_e}
            set {_oldnbt} to tag "display;Lore" of {_nbt}
            set {_newnbt} to "{""extra"":[{""text"":""""},{""bold"":false,""italic"":false,""underlined"":false,""strikethrough"":false,""obfuscated"":false,""color"":""white"",""text"":""""}],""text"":""""}', '{""extra"":[{""bold"":false,""italic"":false,""underlined"":false,""strikethrough"":false,""obfuscated"":false,""color"":""white"",""text"":""""}],""text"":""""}', '{""extra"":[{""bold"":false,""italic"":false,""underlined"":false,""strikethrough"":false,""obfuscated"":false,""color"":""dark_gray"",""text"":""[""},{""italic"":false,""color"":""white"",""text"":""ข้อมูลไอเทม""},{""italic"":false,""color"":""dark_gray"",""text"":""]""}],""text"":""}', '{""extra"":[{""bold"":false,""italic"":false,""underlined"":false,""strikethrough"":false,""obfuscated"":false,""color"":""aqua"",""text"":""เส้นใยแมงมุมมีความแข็ง""}],""text"":""""}', '{""extra"":[{""bold"":false,""italic"":false,""underlined"":false,""strikethrough"":false,""obfuscated"":false,""color"":""aqua"",""text"":""มากกว่าเหล็กกล้า""}],""text"":""""}', '{""extra"":[{""bold"":false,""italic"":false,""underlined"":false,""strikethrough"":false,""obfuscated"":false,""color"":""white"",""text"":""""}],""text"":""""}', '{""extra"":[{""bold"":false,""italic"":false,""underlined"":false,""strikethrough"":false,""obfuscated"":false,""color"":""yellow"",""text"":""ระดับ:""},{""italic"":false,""color"":""white"",""text"":""""},{""italic"":false,""text"":""""}],""text"":""""}"
            set tag "display;Lore" of nbt compound of event-item to {_newnbt}
        
```
        
This is the result of item NBT tag Lore after edit:

```Lore: ['{"extra":[{"text":""},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}\', \'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}\', \'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_gray","text":"["},{"italic":false,"color":"white","text":"ข้อมูลไอเทม"},{"italic":false,"color":"dark_gray","text":"]"}],"text":"}\', \'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"เส้นใยแมงมุมมีความแข็ง"}],"text":""}\', \'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"มากกว่าเหล็กกล้า"}],"text":""}\', \'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}\', \'{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"ระดับ:"},{"italic":false,"color":"white","text":""},{"italic":false,"text":""}],"text":""}']}```

From the result you can see that before every single quote, there will be a backslash(\\) Infront of it where it not suppose to. 

### Steps to reproduce

Change NBT of item and include single quote to it

### Expected behavior

The result NBT shouldn't have back slash before single quote.

### SkBee Version

3.3.0

### Server Version

git-Paper-196 (MC: 1.20.1)

### SkBee Info

![image](https://github.com/ShaneBeee/SkBee/assets/153276550/f27e99b2-bb22-4502-99b1-35e3cc974e49)
![image](https://github.com/ShaneBeee/SkBee/assets/153276550/39623207-0395-4dc8-be88-fa36af82a2dc)

### Additional Information

I have ask in skript issue and the said it is something to do with skbee, So that why I am here.
I also ask in discord community but seem no one know about it

**Comment by ShaneBeee** [comment]
using your code, nothing happens at all.
Your NBT is written wrong, so I can't reproduce anything here

**Comment by CirrusPreeminent** [comment]
So, yeah maybe this was not your thing. But i have shorten the code so you could reproduce it just it case you wanna test.

script:
```
command /testnbt:
    trigger:
        If player's tool is stick:
            set {_e} to player's tool
            set {_test::*} to lore of {_e}
            set {_nbt} to nbt compound of {_e}
            set {_oldnbt} to tag "display;Lore" of {_nbt}
            set {_newnbt} to "{""extra"":[{""text"":""I don\'t want slash""}],""text"":""""}"
            set tag "display;Lore" of nbt compound of player's tool to {_newnbt}
            set {_newnbt} to nbt compound of player's tool
            send "before: %{_nbt}%"
            send "after: %{_newnbt}%"        
```

Steps to reproduce:
1. give yourself a normal stick.
2. Holding stick in your hand and change lore of the item to "test" <without double quote> (I personally use ```/lore add test```)
3. run command ```/testnbt```
4. you will able to see the resulted before and after NBT change in-game chat, *If not you can just check item NBT in other way*

Expected Result:
You will see from the in-game chat that NBT of stick after change will going to be "I don\\'t want slash" and that is where i don't want to have backslash I just only want single quote in NBT.

FYI:
Even the lore of an item has been set to "I don\'t want slash" correctly. BUT that isn't the case here. I have some other plugin that will check the NBT matches of an items. And if one items has backslash and one didn't it wouldn't check as the same item even it is.

**Comment by ShaneBeee** [comment]
yeah this is out of my control, SkBee doesn't touch the innards of the NBT itself
if you don't want the slash to be there, don't put it there.

**Comment by CirrusPreeminent** [comment]
Silly me I forget to remove the backslash in the above comment. But i will eventually print ```\\'``` with additional slah before single quote after all. Thanks you for everything anyway.
