### ISSUE TITLE
[BUG] Send mini message title only works for title, not subtitle. 

### ISSUE THREAD

**Issue by Asleeepp** [ShaneBeee/SkBee#593]
### What happened?

When using send mini message title, mini message only works for the title, not the subtitle.
 

### Steps to reproduce

1.Use this effect command in game: `!send title component mini message from "<color:#F0F000>test" with subtitle "<color:#F0F000>test x2"`

### Expected behavior

For subtitle to support mini message

### SkBee Version

3.4.0

### Server Version

Purpur 1.20.4

### SkBee Info

21:53:25 [INFO] --- [SkBee Loading Info] ---
21:53:25 [INFO] - [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
21:53:25 [INFO] - [NBTAPI] NMS support 'MC1_20_R3' loaded!
21:53:25 [INFO] - NBT Elements successfully loaded
21:53:25 [INFO] - Text Component Elements successfully loaded
21:53:25 [INFO] - Advancement Elements successfully loaded
21:53:25 [INFO] - BossBar Elements successfully loaded
21:53:25 [INFO] - Bound Elements successfully loaded
21:53:25 [INFO] - Damage Source elements disabled (Requires Minecraft 1.20.4+)
21:53:25 [INFO] - Display Entity elements successfully loaded
21:53:25 [INFO] - Fishing elements successfully loaded
21:53:25 [INFO] - Game Event Elements successfully loaded
21:53:25 [INFO] - Particle Elements successfully loaded
21:53:25 [INFO] - RayTrace elements successfully loaded
21:53:25 [INFO] - Recipe Elements successfully loaded
21:53:25 [INFO] - Scoreboard Elements successfully loaded
21:53:25 [INFO] - Scoreboard Objective Elements successfully loaded
21:53:25 [INFO] - Statistic Elements successfully loaded
21:53:25 [INFO] - Structure Elements successfully loaded
21:53:25 [INFO] - Minecraft Tag elements successfully loaded
21:53:25 [INFO] - Team Elements successfully loaded
21:53:25 [INFO] - Tick Manager elements successfully loaded
21:53:25 [INFO] - Villager Elements successfully loaded
21:53:25 [INFO] - Virtual Furnace Elements disabled via config
21:53:25 [INFO] - World Border Elements successfully loaded
21:53:25 [INFO] - World Creator Elements successfully loaded
21:53:25 [INFO] --- [Server Info] ---
21:53:25 [INFO] Server Version: git-Purpur-2134 (MC: 1.20.4)
21:53:25 [INFO] Skript Version: 2.8.3
21:53:25 [INFO] Skript Addons:
21:53:25 [INFO] - skript-placeholders v1.5.2
21:53:25 [INFO] - skript-itemsadder v1.2
21:53:25 [INFO] - skript-particle v1.2.0
21:53:25 [INFO] - skript-reflect v2.4
21:53:25 [INFO] - ItemsAdder v3.6.3-beta-12
21:53:25 [INFO] SkBee Version: 3.4.0
21:53:25 [INFO] SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
you didn't type mini message for the subtitle

**Comment by Asleeepp** [comment]
ah yeah, that worked. didn't know you had to do it for both haha.
