### ISSUE TITLE
[BUG] Stop current task, does not stop the current task

### ISSUE THREAD

**Issue by ForgenDT** [ShaneBeee/SkBee#594]
### What happened?

Bonjour,
The tasks continue to work even though I use "stop current task".

### Steps to reproduce

1. create a task
2. call the task
3. do the checks
4. if the task should no longer exist, we stop it.

### Expected behavior

```vbs
function entity_task(ent_uuid: text, timespan: integer):
	set {_speed} to "%{_timespan}% seconds" parsed as timespan
	run {_speed} later repeating every {_speed}:
		# broadcast "_timespan: %{_timespan}%"
		if {db_entity::%{_e_uuid}%::*} is not set:
			broadcast "&6Entity %{_e_uuid}% not exist. %now%"
			stop current task
		else:
			if chunk at {db_entity::%{_e_uuid}%::location} is not loaded:
				broadcast "&6Entity not loaded. %now%"
				stop current task
			else:
				broadcast "Task work"
```
in my case, the task executes every 30 seconds, and when I delete the entity,
(broadcast "&6Entity %{_e_uuid}% not exist. %now%") is executed every 30 seconds as if (stop current task) was not working...

It doesn't do it all the time, sometimes it works, but sometimes it doesn't.

### SkBee Version

3.3.0

### Server Version

Paper 1.20.4

### SkBee Info

--- [SkBee Loading Info] ---
 - [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
 - [NBTAPI] NMS support 'MC1_20_R3' loaded!
 - NBT Elements successfully loaded
 - Text Component Elements successfully loaded
 - Advancement Elements successfully loaded
 - BossBar Elements successfully loaded
 - Bound Elements successfully loaded
 - Damage Source elements successfully loaded
 - Display Entity elements successfully loaded
 - Fishing elements successfully loaded
 - Game Event Elements successfully loaded
 - Particle Elements successfully loaded
 - RayTrace elements successfully loaded
 - Recipe Elements successfully loaded
 - Scoreboard Elements successfully loaded
 - Scoreboard Objective Elements successfully loaded
 - Statistic Elements successfully loaded
 - Structure Elements successfully loaded
 - Minecraft Tag elements successfully loaded
 - Team Elements successfully loaded
 - Tick Manager elements successfully loaded
 - Villager Elements successfully loaded
 - Virtual Furnace Elements disabled via config
 - World Border Elements successfully loaded
 - World Creator Elements successfully loaded
 - Plugin is up to date!
--- [Server Info] ---
Server Version: git-Paper-436 (MC: 1.20.4)
Skript Version: 2.8.3
Skript Addons:
 - skript-gui v1.3
 - skript-reflect v2.4
 - skRayFall v1.9.28
 - SkJson v3.0.3
SkBee Version: 3.3.0

**Comment by ShaneBeee** [comment]
I have tested this time and time again, this is my code:
```vb
on load:
	run task 1 second later repeating every second:
		if {-a} is not set:
			broadcast "&bSTOPPING TASK"
			stop current task
		else:
			broadcast "&aTASK RUNNING"
```
Result:
<img width="430" alt="Screenshot 2024-03-25 at 1 14 56 PM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/41afc21e-4da2-499d-921a-2a2c0f70c2b3">

I am not able to replicate the issue.

**Comment by Fusezion** [comment]
Alright so I accidentally managed to replicate this issue when using a loop 4 times and spamming it

![image](https://github.com/ShaneBeee/SkBee/assets/81952476/c7dbf870-8cb5-43b6-8073-a2ea40fec414)

```
command /multi-create:
    trigger:
        loop 4 times:
            wait (random element out of 5 ticks, 10 ticks, 15 ticks and 20 ticks)
            execute console command "/create-bossbar testing-%loop-counter% How are you? You're pretty hot. %random color out of colors% 5 second"

command /create-bossbar <id:string> <message:string> <color:color> <duration:timespan>:
    trigger:
        set {_bossbar} to createTimedBossbar({_id}, {_message}, {_color}, {_duration})
        add players to {_bossbar}
```

the task that was used was this
```

    run task {@count-down-delay} later repeating every tick:
        if any:
            {-debug} is true
            now > {_endDate}
            bossbar progress of {_bossbar} <= 0
        then:
            broadcast "cry - ended - %{_random}%"
            delete bossbar within {_bossbar}
            delete {timedBossbars::%{_bossbar}%}
            stop current task
        remove {_decreaseRate} from bossbar progress of {_bossbar}
    return {_bossbar}
```

## Results from further testing of this feature

It's caused by multiple calls happening in a short period of time, screenshot below is from
```
on load:
    loop 5 times:
        wait 0.5 ticks
        set {_endDate} to a second from now
        set {_random} to random uuid
        run task {@count-down-delay} later repeating every tick:
            if any:
                now > {_endDate}
                {-debug} is true
            then:
                broadcast "cry - ended - %{_random}%"
                stop current task
```
![image](https://github.com/ShaneBeee/SkBee/assets/81952476/7c3e9a0f-eeb1-4452-91bf-0a052ce9b7cd)

**Comment by ShaneBeee** [comment]
I did a small rework to the task cancellation.
Im hoping it fixed this issue.
Ive done a decent amount of testing and have yet to be able to get it to not working, so fingers crossed.
