### ISSUE TITLE
[SUGGESTION] PlayerAttemptPickupItemEvent

### ISSUE THREAD

**Issue by rudde0** [ShaneBeee/SkBee#596]
### Suggestion

this event will allow us to add some features even player is not able to pick up(due to full inventory etc.) in pickup event.

### Alternatives

I made it with skript-reflect but much of reflect methods are can be cpu-intensive.

### Additional Information

it's bukkit event: https://jd.papermc.io/paper/1.20/org/bukkit/event/player/PlayerAttemptPickupItemEvent.html

**Comment by ShaneBeee** [comment]
Im curious, why would you need this over just using the pickup event?

**Comment by rudde0** [comment]
> Im curious, why would you need this over just using the pickup event?

I'm sending the dropped item to the seperate inventory if player's inventory is full.

**Comment by ShaneBeee** [comment]
whoops didn't mean to close this one
