### ISSUE TITLE
[SUGGESTION] Raytracing entity filter

### ISSUE THREAD

**Issue by GDudeUnderscore** [ShaneBeee/SkBee#597]
### Suggestion

I would like if you can filter out certain entities while using a raytrace

### Alternatives

tried using another addon, skirt, but it was too outdated to work.

**Comment by ShaneBeee** [comment]
this has been implemented and will be available in a future update
https://github.com/ShaneBeee/SkBee/pull/588

**Comment by ShaneBeee** [comment]
whoops, this one too shouldn't have been closed yet. MY BAD
