### ISSUE TITLE
[BUG] Setting Fishing Time

### ISSUE THREAD

**Issue by 3Fendi3** [ShaneBeee/SkBee#605]
### What happened?

When I try to set the min and max of fishing time, it works up to 30 seconds, when I select a time greater than 30 seconds, the max time will be set correctly but the min time will be set to 5 seconds
`     

        set {_x} to random integer between {_min} and {_max}

        set min wait time of fish hook to "%{_x}% seconds" parsed as timespan

        set max wait time of fish hook to "%{_x}% seconds" parsed as timespan

        send "&aTime: %{_x}%"

        send "&aMin time: %min wait time of fish hook%"

        send "&aMax time: %max wait time of fish hook%"
`
![image](https://github.com/ShaneBeee/SkBee/assets/130778580/a15bb7a0-d021-4f98-b284-bf113782e25b)

### Steps to reproduce

1.
2.
3.

### Expected behavior

min and max time should be set to the same value

### SkBee Version

3.4.2

### Server Version

paper 1.19.4

### SkBee Info

[20:45:17 INFO]: --- [Server Info] ---
[20:45:17 INFO]: Server Version: git-Paper-550 (MC: 1.19.4)
[20:45:17 INFO]: Skript Version: 2.8.2
[20:45:17 INFO]: Skript Addons:
[20:45:17 INFO]: - skript-placeholders v1.5.2
[20:45:17 INFO]: - skript-reflect v2.4
[20:45:17 INFO]: - SkJade v1.4.3
[20:45:17 INFO]: SkBee Version: 3.4.2

**Comment by Fusezion** [comment]
I'm not 100% sure on what is causing this as it seems to just reset min to the default, I'll do some testing myself and see if I can spot why this occurs it's possible it's an issue with bukkit and unrelated to SkBee

**Comment by Fusezion** [comment]
Alright I've located the issue with the system and have made a fix that appears to work I'll get a pr out shortly and should likely make it into the next patch if everything goes to plan
