### ISSUE TITLE
[BUG] Auto Alphabetizing of NBT tags

### ISSUE THREAD

**Issue by Zoidmire** [ShaneBeee/SkBee#607]
### What happened?

While adding NBT to an item, something is alphabetizing the values turning:
{AttributeModifiers:[{AttributeName:generic.max_armor,Amount:16d,Slot:chestplate,Operation:0,UUID:[I;-1623373971,-1055374012,-2090507132,1761916046]}]}
into:
{AttributeModifiers:[{Amount:16d,AttributeName:generic.max_armor,Operation:0,Slot:chestplate,UUID:[I;-1623373971,-1055374012,-2090507132,1761916046]}]}

### Steps to reproduce

1.grab a chest plate
2.set player's held item to player's held item with nbt compound from "{AttributeModifiers:[{AttributeName:generic.max_armor,Amount:16d,Slot:chestplate,Operation:0,UUID:[I;-1623373971,-1055374012,-2090507132,1761916046]}]}"
3.Profit

### Expected behavior

You will get a chestplate that no longer shows Armor tooltips, and equipping it will not increase your armor anymore, essentially breaking the item. I've double checked the uuid to int array and it seems to be fine. I believe the Amount showing before the AttributeName is breaking the item. Unfortunately I cannot figure out a way to add the nbt in it's original form to check, as whatever is going on is parsing every attempt into the alphabetized version.

### SkBee Version

3.4.1

### Server Version

Purpur 1.20.4

### SkBee Info

NBTAPI - 1_20_R3
SERVER - git-Purpur-2154 (1.20.4)
SKRIPT -  2.8.3
ADDONS - skript-reflect 2.4

**Comment by ShaneBeee** [comment]
thats not a valid attribute
