### ISSUE TITLE
[BUG] Java Exception has occurred

### ISSUE THREAD

**Issue by EquipableMC** [ShaneBeee/SkBee#608]
### What happened?

When you execute SkBee, pong should open up but it does not

### Steps to reproduce

1. Download SkBee 3.4.3
2. Execute it
3. then it will throw `A Java Exception has occurred.`

### Expected behavior

Pong is meant to open up

### SkBee Version

3.4.3

### Server Version

N/A

### SkBee Info

N/A

**Comment by Asleeepp** [comment]
Try opening it with OpenJDK Platform Binary. 
![image](https://github.com/ShaneBeee/SkBee/assets/119438940/eec1fb46-9b77-4873-bfe0-2395a2ef6966)

**Comment by EquipableMC** [comment]
Alright will do

**Comment by ShaneBeee** [comment]
can you provide the exception

**Comment by EquipableMC** [comment]
How do I? Just take a screenshot of when you open it?

**Comment by ShaneBeee** [comment]
well, where is the exception occurring?

**Comment by EquipableMC** [comment]
![image](https://github.com/ShaneBeee/SkBee/assets/66171067/75837b3d-bf01-4a48-a8b1-170b085f862d)
Sorry for the very late reply

**Comment by ShaneBeee** [comment]
can you please run it in console and send the exception

**Comment by EquipableMC** [comment]
What is the command?

**Comment by honkling** [comment]
`java -jar /path/to/SkBee.jar`

**Comment by EquipableMC** [comment]
Thank you, I'll try when I get home

**Comment by EquipableMC** [comment]
It just keeps opening in OpenJDK and not Java SE.

**Comment by EquipableMC** [comment]
Okay so, when I manually click it, it throws the exception, but running the command makes it work just fine... I am confused.

**Comment by ShaneBeee** [comment]
Im going to close this for now due to:
- I can no way shape or form replicate this error, nor can honkling.
- Without any stracktrace, I can't trace back where this is originating from.
- Im thinking this is a java issue on your end. Im not trying to pass the blame I just can't think or see where this could come from.
