### ISSUE TITLE
[BUG] set {_nbt} to nbt compound of loop-mob

### ISSUE THREAD

**Issue by pewy007** [ShaneBeee/SkBee#61]
**Describe the bug**
I can set {_nbt} to nbt compound of event-mob, but can not with loop-mob

**To Reproduce**
It said "loop-mob is neither an item stack nor an entity type"

**Expected behavior**
I want to change loop-mob's nbt

**Screenshots/Errors**

**Version Info:**
 - SkBee 1.7.0
-  Skript 2.5
 - Paper 1.16.3

**Additional context**

**Comment by ShaneBeee** [comment]
I can not reproduce this

Test Code:
```vb
on load:
	set {_l} to location of spawn of world "world"
	loop mobs in radius 20 around {_l}:
		send "Mob: %loop-mob%" to console
		set {_nbt} to nbt compound of loop-mob
		send "NBT: %pretty nbt of {_nbt}%" to console
```

output:
<img width="842" alt="Screen Shot 2020-10-08 at 10 28 15 AM" src="https://user-images.githubusercontent.com/20008482/95493190-fe18bd80-0950-11eb-91c1-1a0f2f73ab10.png">

**Comment by ShaneBeee** [comment]
Closing. Could not replicate, and have no other responses.
