### ISSUE TITLE
[BUG] World Template loading from a path

### ISSUE THREAD

**Issue by Alphabastii** [ShaneBeee/SkBee#612]
### What happened?

My Problem is i have a path to load the world template 

set {_clone} to a new world creator named "skyblocksk/welten/welt_%player%" to clone world "skyblocksk/templates/skyblock" without saving

but the path can't found or loaded 

on main path the plugin can load the template...

(sry my english is not the best)

### Steps to reproduce

1. create a path test/template/map
2. put your map on the map path
3. try to load it but not working...

### Expected behavior

The Template world is copy and loaded on my world path the map named: world_alphabastii
after creation of world player is teleporting to the new map

### SkBee Version

3.4.3

### Server Version

Paper 1.20.4

### SkBee Info

[14:32:38 INFO]: --- [Server Info] ---
[14:32:38 INFO]: Server Version: git-Paper-436 (MC: 1.20.4)
[14:32:38 INFO]: Skript Version: 2.8.0
[14:32:38 INFO]: Skript Addons:
[14:32:38 INFO]: - Skellett v2.0.10
[14:32:38 INFO]: - skRayFall v1.9.28
[14:32:38 INFO]: - SkQuery v4.1.10
[14:32:38 INFO]: SkBee Version: 3.4.3

**Comment by ShaneBeee** [comment]
The expression takes in a world, as seen here:
```vb
[a] [new] world creator (with name|named) %string% to (0¦copy|1¦clone) %world% [save:without saving]
```
So unfortunately that has nothing to do with SkBee as that is Skript's expression (for the world itself)

**Comment by Alphabastii** [comment]
i m using your addon skbee expressions but is half working.... 

set {clone} to a new world creator named "skyblocksk/welten/welt%player%" to clone world "skyblocksk/templates/skyblock" this ist not script self  this feature come from your addon....

**Comment by ShaneBeee** [comment]
Let me try this again
<img width="937" alt="Screenshot 2024-04-12 at 8 44 13 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/13e7012e-a91e-4a32-8298-5cd49534d28b">
The expression from SkBee takes in a World object (as seen circled here)
And to get the world, you are using **Skript**'s expression `world %string%`
That is not an SkBee expression.
If Skript's expression can't pick up a world of yours, there is nothing I can do about that, as it's not SkBee's expression, it is Skript's expression!

**Comment by Alphabastii** [comment]
now understand what i m not understand is why i can save a map on a custom path and i can't load the template map? now you say skript self has the problem?

**Comment by ShaneBeee** [comment]
Im honestly not sure. 
I did a test and it worked fine for me, so maybe its a per machine thing.
Its most likely not even Skript's fault, its probably how internally the server handles worlds in sub directories.
This is a thing I didn't even know was possible til now.

**Comment by Alphabastii** [comment]
interestering is same problem on windows(GamingPC) and linuxserver to load the map from a path who i have created my skript i can loading from a sub path my template many edits later no more working after this i m trying to find out how is not broken..

**Comment by ShaneBeee** [comment]
do me a favour and run this test:
```vb
command /test:
	trigger:
		set {_w1} to world "skyblocksk/templates/skyblock"
		send "W1: %{_w1}%"

		set {_w2} to world("skyblocksk/templates/skyblock")
		send "W2: %{_w2}%"
```
tell me what both of those output

**Comment by Alphabastii** [comment]
say now <none>
![Screenshot 2024-04-12 181725](https://github.com/ShaneBeee/SkBee/assets/49566322/cb9379ff-18ce-4fba-a0eb-35983d72b53a)

**Comment by Alphabastii** [comment]
but the map is inside on my path

**Comment by ShaneBeee** [comment]
ok, then its a Skript issue, as that is a Skript expression and function!

**Comment by Alphabastii** [comment]
another path is working who my world is saved
![Screenshot 2024-04-12 181933](https://github.com/ShaneBeee/SkBee/assets/49566322/2099fc67-25f4-40f5-99f4-7bf005f5bd0a)
