### ISSUE TITLE
[SUGGESTION] Place a structure without updating blocks contained within it

### ISSUE THREAD

**Issue by Budgo** [ShaneBeee/SkBee#613]
### Suggestion

There should be some sort of additional specification you can make while creating or placing (or both) structures. I imagine syntax could look something like `structure static of {_s}` if it were to be a structure property, or `place [structure] %structure% at %location% [without updates]` if it were an amendment to creation.

### Alternatives

I've considered migrating off of structures entirely, but that's barely an improvement and also causes some issues.

### Additional Information

I can't seem to find a blockstate tag on the MC wiki that prevents sand and such from falling, and I have honestly no idea how plugins such as WorldEdit manage to do it.

**Comment by Fusezion** [comment]
From my 2 minutes of searching on bukkit I can't seem to find anyway to achieve no block updates when placing a structure using the normal method.

The way you can do it in Skbee currently is just looping blockstates of a structure and setting the block data based off the offset to the blockdata of the blockstate

**Comment by ShaneBeee** [comment]
Yeah, what fuse said.
Minecraft doesn't have anyway to do that.
