### ISSUE TITLE
[BUG] Bossbar player removal bug

### ISSUE THREAD

**Issue by MissingReports** [ShaneBeee/SkBee#614]
### What happened?

For some reason with old syntax where you could do ``remove player from **bar players of** {_bar}`` it allowed {_bar} to be a clone of the actual bossbar but with the new syntax where you do ``remove player from {_bar}`` then you need the exact copy of the bossbar, you can only get that during creation of the bossbar or by doing ``boss bar of id "mybar"``, the only way to remove a boss bar from the boss bar object without the id is by using reflect and doing this ``remove player from boss bar of id {_bar}.getKey().getKey()``

This can be fixed by making an expression to get the id of a bar or by making the behavior of the new syntax the same as of the old syntax

### Steps to reproduce

1. Make a bossbar object
2. Get a copy of the boss bar object
3. Try to remove players from the cloned boss bar

### Expected behavior

From how the old syntax worked I was expecting it to just hide the bossbar

### SkBee Version

3.4.3

### Server Version

Paper 1.20.4

### SkBee Info

![image](https://github.com/ShaneBeee/SkBee/assets/96932973/29f15b3b-43e1-469e-bd8a-30d1c7dad1d3)

### Additional Information

Using paper instead of spigot

**Comment by ShaneBeee** [comment]
what do you mean by a clone?
How are you cloning something in Skript?
Your steps to reproduce don't actually give me an idea of what you've done

**Comment by MissingReports** [comment]
I've done something similar to this
`on load:
    set {boss::plains::bossbar} to # create bossbar here
    
on death:
    set {_bar} to {boss::plains::bossbar}
    set bar progress of {_bar} to 100
    remove all players from {_bar} # This won't remove the player`

**Comment by ShaneBeee** [comment]
Ok so the issue is actually with `remove all players`
I found this out a couple weeks ago, it's a weird Skript quirk.
I've actually already figured this one out and fixed it, will appear in the next update!
for the time being you may have to loop and remove each player individually
