### ISSUE TITLE
Error console to paste structure variables

### ISSUE THREAD

**Issue by Lennord** [ShaneBeee/SkBee#62]
Hello, when I paste with a variable, it gives me an error in the console...

Spigot: 1.16.3
Skbee: 1.7.1
Code: paste arg 1 at {Network.worldedit.use.save.location.pos.use.%player%.%arg 1%}
Error console: https://pastebin.com/MKDebhAB

**Comment by ShaneBeee** [comment]
Thanks for letting me know. The issue has been fixed and will appear in the next update.

**Comment by Lennord** [comment]
> Thanks for letting me know. The issue has been fixed and will appear in the next update.

Ok, Thanks ! ;)

**Comment by WallyTube** [comment]
I'm also experiencing this bug. Minehut is running on the latest version of skbee, so is this going to get fixed in the next update release?

**Comment by ShaneBeee** [comment]
> so is this going to get fixed in the next update release?

Seriously?
<img width="1019" alt="Screen Shot 2020-10-15 at 5 01 36 PM" src="https://user-images.githubusercontent.com/20008482/96197937-3481aa00-0f08-11eb-8b38-7035dd1172f0.png">
