### ISSUE TITLE
[BUG] translate component doesent translate properly

### ISSUE THREAD

**Issue by MCdragonmasters** [ShaneBeee/SkBee#622]
### What happened?

![image](https://github.com/ShaneBeee/SkBee/assets/116000479/9a049eee-65c5-4251-a6e3-39b35665fda9)

### Steps to reproduce

1.set {testvar} to random element out of all blocks
2.send "%{testvar}% - %translate component from {testvar}%"
3.

### Expected behavior

translate properly

### SkBee Version

3.4.3

### Server Version

Paper 1.20.4

### SkBee Info

![image](https://github.com/ShaneBeee/SkBee/assets/116000479/98eb05aa-4021-4c00-a102-5eb3e0db7c76)

**Comment by Fusezion** [comment]
When using components you must use the `send component` effect.

**Comment by MCdragonmasters** [comment]
how do i use that?

**Comment by Asleeepp** [comment]
According to what this person has sent in a skript-help channel, this does seem to be a bit weird, and imo shouldn't be invalid as for some reason the component works without the `send component` effect, and also seems to be inconsistent, which is shown by what the person sent in the help channel below.
![image](https://github.com/ShaneBeee/SkBee/assets/119438940/c914d156-ad7c-42c8-a759-16119766c867)

Also it's very weird that it defaults to Air, and not to <none> or something else.

**Comment by Fusezion** [comment]
Ofcourse the `#toString` will still work for default value, but the actual usage that is dependent on language settings will not work. This isn't a bug nor an issue just a limitation in the fact components can't be evaluated early on.

![image](https://github.com/ShaneBeee/SkBee/assets/81952476/f064a4f9-631d-4511-b216-aaa1d83c54c2)
![image](https://github.com/ShaneBeee/SkBee/assets/81952476/b69cb179-46d7-4d9b-b7b9-5a3c26c40247)


`random element out of all blocks` is not a valid use-case when we don't support blockdata itemtypes like `westward facing oak stairs`

**Comment by MCdragonmasters** [comment]
but how would i get this into a message

**Comment by MCdragonmasters** [comment]
like `broadcast "test %component {var}%"`

**Comment by Fusezion** [comment]
You can ask in an [SkUnity](https://discord.gg/skript) help channel, but this is where this issue ends.

**Comment by MCdragonmasters** [comment]
thats where i started tho

**Comment by MCdragonmasters** [comment]
please reopen the issue this bug is not fixed
![image](https://github.com/ShaneBeee/SkBee/assets/116000479/12de16d0-308f-4278-b598-044f7bb9a228)

**Comment by MCdragonmasters** [comment]
`set {bb1} to random element out of all blocks
 set {bb2} to translate component of {bb1}`

**Comment by ShaneBeee** [comment]
there is no bug, you are improperly stringifying a component which strips out the stuff which should be sent to the client, ie: the lang stuff

**Comment by MCdragonmasters** [comment]
it should say "Warped Sign" but it says "Air"

**Comment by MCdragonmasters** [comment]
also even without the "%%" it still says "Air"

**Comment by ShaneBeee** [comment]
Works fine for me:
<img width="514" alt="Screenshot 2024-04-28 at 11 05 28 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/44c5758c-2e79-410c-af0e-6b3d3cb9f408">

**Comment by MCdragonmasters** [comment]
keep doing it ull get a block that isnt air that translates to air eventually
