### ISSUE TITLE
[BUG] nbt of event-entity end crystal returns <none>

### ISSUE THREAD

**Issue by 811Alex** [ShaneBeee/SkBee#63]
**Describe the bug**
When trying to get the NBT of an exploding end crystal, I get \<none\>. It only seems to happen with end crystals.

**To Reproduce**
```
on exploding:
	broadcast "NBT: %the nbt of the event-entity%"
```

**Expected behavior**
Instead of \<none\> it should return the NBT, like with other entities.

**Version Info:**
 - **SkBee Version:** v1.7.1
-  **Skript Version:** 2.5
 - **Server Version/Platform** Paper 1.16.3 (build 231)

**Comment by ShaneBeee** [comment]
Im not exactly sure why that is not working, but use `nbt compound of event-entity` instead.

**Comment by ShaneBeee** [comment]
Nevermind I figured it out. I had a death check for entities, and for some reason I guess the explode event for ender crystals is called after its dead.

Its been fixed and will appear in the next update.
