### ISSUE TITLE
[BUG] LP Rank Weight

### ISSUE THREAD

**Issue by ItsMeVans** [ShaneBeee/SkBee#630]
### What happened?

The skBee Tab feature is not compatible with the luck perms rank weighting system so the ranks in tab are unorganized

### Steps to reproduce

1. Make a rank
2. Enter a weight
3. Press tab to see the ranks is not according to weights

### Expected behavior

The ranks are not according to the weights entered

### SkBee Version

3.5.0

### Server Version

1.19.4

### SkBee Info

Idk man

### Additional Information

No other thing

**Comment by ShaneBeee** [comment]
does it work when SkBee is not installed?

**Comment by ItsMeVans** [comment]
No I am using skbee tab feature so rank weights don't work

**Comment by ShaneBeee** [comment]
What is the SkBee tab feature?
To the best of my knowledge, SkBee doesn't have any tab features.

**Comment by ShaneBeee** [comment]
Yeah I honestly have no clue what you're referring to.
