### ISSUE TITLE
[BUG] Cant understand expression when returning blank nbt compound

### ISSUE THREAD

**Issue by Blizzmond** [ShaneBeee/SkBee#637]
### What happened?

Title

### Steps to reproduce

Run my code

### Expected behavior

Return tag1, tag2, tag3

### SkBee Version

3.5.0

### Server Version

1.20.4 paper

### SkBee Info

Checking for update failed on some

### Additional Information

I found a SkBee bug
```
set {_n} to blank nbt compound
set float tag "tag1" of {_n} to {_tag1}
set float tag "tag2" of {_n} to {_tag2}
set float tag "tag3" of {_n} to {_tag3}
return {_n}

#####################

set {_tags::*} to getTags({_p})
broadcast {_tags::*} ## broadcasts tag1, tag2, tag3

set {_tag1} to float tag "tag1" of {_tags::*}
set {_tag2} to float tag "tag2" of {_tags::*}
set {_tag3} to float tag "tag3" of {_tags::*}
```

Err: Can't understand this expression float tag "tag1" of {_tags::*}

**Comment by Fusezion** [comment]
based off the reading of documentation `%nbttype% %string% of %nbtcompound%` , we do not support plural compounds `{_tags::*}` skript just doesn't have a meaningful error and we don't have one we could provide either
