### ISSUE TITLE
[BUG] MalformedNBT |  SkBee-3.5.1.jar | Spigot 1.20.6

### ISSUE THREAD

**Issue by yzz17** [ShaneBeee/SkBee#638]
### What happened?

[SkBee ERROR] Message: MalformedNBT: Expected '{' at position 0: <--[HERE]

### Steps to reproduce

1. #CODE# give 1 of echo shard named "&5test" with nbt compound from "[enchantments={levels:{unbreaking:1},show_in_tooltip:false}]" to player
2. /minecraft:give yzz17 minecraft:echo_shard[enchantments={levels:{unbreaking:1},show_in_tooltip:false}] 1

I have been reading the changes and I know that it is probably not a bug, but I think it would be good for many people to kindly ask the question, is Skbee's internal syntax on NBT the same as vanilla?

### Expected behavior

Well... placing the NBT that works in vanilla in skbee, but requests the use or the previous "syntax"?  also try to get the nbt from skript with "set {_nbt} to nbt compound from loop-item" but it returns "{}" or null in other words                                                       I am aware that it is a transition stage of changes in this aspect, I appreciate your time

### SkBee Version

3.5.1

### Server Version

Spigot 1.20.6

### SkBee Info

[15:43:06 INFO]: --- [Server Info] ---
[15:43:06 INFO]: Server Version: 1.20.6-2211-3d25693 (MC: 1.20.6)
[15:43:06 INFO]: Skript Version: 2.9.0-beta1
[15:43:06 INFO]: Skript Addons:
[15:43:06 INFO]: - skUtilities v0.9.2
[15:43:06 INFO]: SkBee Version: 3.5.1
[15:43:06 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
that's not NBT, that is vanilla data components for commands.

**Comment by yzz17** [comment]
> that's not NBT, that is vanilla data components for commands.

Thank you!, although these changes are good, they are somewhat difficult to understand for people who do not speak English. it's strange having to use the [ ] for give commands, hence what confused me. <3

**Comment by ShaneBeee** [comment]
Yeah Mojang changed it so commands can use components a little easier, they made it like block states (the `/setblock` command)
