### ISSUE TITLE
[BUG] add player head with nbt not working

### ISSUE THREAD

**Issue by Demz1001** [ShaneBeee/SkBee#64]
**Describe the bug**
I am making so if a player picks up a player head it will get a custom skin/skull owner

**To Reproduce**
the code I am using 
```
on pick up of player head:
    If event-item is player head named "&9Bag of Iron":
        wait 3 tick
        remove 1 player head named "&9Bag of Iron" from player's inventory
        add 1 player head with nbt "{SkullOwner:{Id:[I;-1314636157,803950115,-1411847302,88566445],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDk4MGQxNmVkMmYxZGJmOWExZDU0ZmFiZGU5MTY2MWU0NjJmOGU5ZmFjZWI2OWE3NTgxM2ZhYjg3Y2VkZmNmZiJ9fX0="}]}}}" to player's inventory
```

**Expected behavior**
It says 
![image](https://user-images.githubusercontent.com/60315876/96498325-34591580-124c-11eb-992e-ebcab5d1fcb8.png)
on load.

**Version Info:**
 - **SkBee Version:** v1.7.1
-  **Skript Version:** Skript 2.5
 - **Server Version/Platform** Paper 1.16.3

**Comment by ShaneBeee** [comment]
This isn't an SkBee issue, this is user error. Skript requires inner strings/text to be double quoted.
