### ISSUE TITLE
[BUG] Command map is NOT in skript

### ISSUE THREAD

**Issue by Texbio** [ShaneBeee/SkBee#643]
### What happened?

in [The Next Big One [3.3.0]](https://github.com/ShaneBeee/SkBee/releases/tag/3.3.0) you said that command map was being added to skript but I can't find it. Please re-add it back

### Steps to reproduce

1. download latest skbee and skript
2. try anything to do with command map

### Expected behavior

working

### SkBee Version

3.5.2

### Server Version

1.20.4

### SkBee Info

[Skript] Server Version: git-Paper-496 (MC: 1.20.4)
[Skript] Skript Version: 2.9.0-beta1 (skriptlang-github)
[Skript] Installed Skript Addons: 
[Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[Skript]  - SkBee v3.5.2 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: None

**Comment by ShaneBeee** [comment]
https://docs.skriptlang.org/expressions.html?search=#ExprSentCommands
