### ISSUE TITLE
[SUGGESTION] All custom worlds expression

### ISSUE THREAD

**Issue by Andrei965** [ShaneBeee/SkBee#644]
### Suggestion

Hello! While experimenting with the world creator feature, I noticed the absence of a functionality to iterate over all worlds created using Skbee. The current approach using the vanilla all worlds expression only retrieves worlds registered in Multiverse, thus excluding those created by Skbee.

### Alternatives

One potential workaround is to use variables to store the names of the worlds and retrieve them as needed. However, this method has a significant limitation: if a world file is deleted, there is no mechanism to detect this change, resulting in an outdated list of worlds.

### Additional Information

Expression: all (custom|skbee) worlds

**Comment by Andrei965** [comment]
Apologies for the confusion! It appears the issue was on my end. I was running the same code on an identical server, but the world in question wasn't present on that server 🤦‍♂️.

That said, implementing a custom worlds expression specifically for Skbee-created worlds would still be beneficial, as it would provide an efficient way to manage temporary worlds.

**Comment by ShaneBeee** [comment]
Ok, thats fair. Ill see what I can do.
