### ISSUE TITLE
Create world with custom world generator

### ISSUE THREAD

**Issue by MaledKhaoSan** [ShaneBeee/SkBee#646]
### Suggestion

Hello! That sounds like a great idea to enhance the SKBee World Creator, I have some suggestion that to
make SKbee world creator can create world with world generator

like a customworld for example

a customworld pack that create with TERRA
can use with multiverse core 

```java
/mv create test normal -g TERRA:Overworld
```
<img width="1470" alt="Screenshot 2567-06-02 at 15 30 34" src="https://github.com/ShaneBeee/SkBee/assets/81904457/8ba29c28-17ef-442d-92dd-f96fdce05dca">

### Alternatives

-

### Additional Information

Expression: all (custom|skbee) worlds

**Comment by ShaneBeee** [comment]
Im pretty sure that's what this is for:
<img width="1072" alt="Screenshot 2024-06-02 at 9 47 16 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/027ac1d5-e089-42d8-84cf-abd35fa13f75">

**Comment by ShaneBeee** [comment]
closing as im pretty sure this is already supported
