### ISSUE TITLE
[SUGGESTION] add open book effect

### ISSUE THREAD

**Issue by deathsou** [ShaneBeee/SkBee#65]
Hey, I've tried tons of times to use Skellett Book syntax and have found that only like 50% of it works. This sucks, because I want to be able to open a book to a player. This would be like for rules, announcements, and other cool features for minigames/ other things.

A way of making/editing/opening books would be a great addition to the already great addon 😛 

I've already tried setting players' tool to a book- obviously this doesn't let them open it.

Thanks man! (also great work with the tab complete- really helps a lot.)

-Death Source

**Comment by WallyTube** [comment]
+1 on this. I've been able to format a book with skellet, but I can't seem to get the players to open it.

**Comment by ShaneBeee** [comment]
I just realized, Skript has an open book effect coming in 2.5.1, but I can work on adding some stuff for editing said books

**Comment by deathsou** [comment]
> I just realized, Skript has an open book effect coming in 2.5.1, but I can work on adding some stuff for editing said books

Yeah, that would be cool! Any idea when 2.5.1 is coming out?
Also: any way to write colored texts in books with links? Would that be supported by Skript-2.5.1?

**Comment by ShaneBeee** [comment]
> Yeah, that would be cool! Any idea when 2.5.1 is coming out?

no current ETA

> Also: any way to write colored texts in books with links? Would that be supported by Skript-2.5.1?

That is something I'll working into SkBee...
Just doing some preliminary testing right now:
<img width="966" alt="Screen Shot 2020-10-20 at 7 32 02 PM" src="https://user-images.githubusercontent.com/20008482/96665961-f838ba00-130a-11eb-9723-a5fe31300dd4.png">
<img width="966" alt="Screen Shot 2020-10-20 at 7 34 06 PM" src="https://user-images.githubusercontent.com/20008482/96666080-3d5cec00-130b-11eb-9e95-9c262bbec40e.png">
