### ISSUE TITLE
[SUGGESTION] Teleport with teleport flags

### ISSUE THREAD

**Issue by MissingReports** [ShaneBeee/SkBee#655]
### Suggestion

Paper has these things called "TeleportFlags", which let you do cool things

Examples of teleport flags: retain passengers, retain vehicle, retain open inventory

New effect: ``teleport %entities% to %object% (with|using|and) %teleportflags%``

Example: ``teleport player's vehicle to {_location} and retain passengers

### Alternatives

I don't have other alternatives in mind

### Additional Information

Paper has an API here: https://jd.papermc.io/paper/1.20.6/org/bukkit/entity/Entity.html#teleport(org.bukkit.Location,io.papermc.paper.entity.TeleportFlag...)

One downside with ``retain passengers`` or ``retain vehicle`` is you can't do crazy teleports with it. It'd just say flag the entity with the "invalid movement detected" by bukkit. I believe it's because Paper uses move packets instead of teleport packets to do it

**Comment by ShaneBeee** [comment]
I believe Skript has a plan to do this, possible there is a PR for it
