### ISSUE TITLE
[BUG] Piercing NBT

### ISSUE THREAD

**Issue by 3Fendi3** [ShaneBeee/SkBee#659]
### What happened?

`                        
make player shoot arrow at speed 4
set byte tag "PierceLevel" of nbt from last shot arrow to 10
send "&c%last shot arrow.getPierceLevel()%" to player
send "&b%tag type of tag "PierceLevel" of nbt compound of last shot arrow%" to player

send nbt of last shot arrow to player
`
![image](https://github.com/ShaneBeee/SkBee/assets/130778580/60a98c58-83ea-4024-8df2-ccde931ae1a2)
Why does boolean appear after checking the tag type if it is a byte?
And it doesn't save at all, even though it's in nbt, the arrow doesn't fly through the mobs

### Steps to reproduce

Custom shoot from any item

### Expected behavior

tag type should be byte
piercing should work

### SkBee Version

3.5.3

### Server Version

paper 1.20.6

### SkBee Info

![image](https://github.com/ShaneBeee/SkBee/assets/130778580/b5118aa0-ecdc-4f7f-992a-6819bbb7ec74)

**Comment by ShaneBeee** [comment]
> Why does boolean appear after checking the tag type if it is a byte?

This is a mistake on my part

> And it doesn't save at all, even though it's in nbt, the arrow doesn't fly through the mobs

That is unfortunately out of my control. 
If the tag is set, it appears Minecraft knows about it, but what Minecraft does with it, that I can't do anything about.
