### ISSUE TITLE
[SUGGESTION] System of all commands chat... (added and delete)

### ISSUE THREAD

**Issue by Lennord** [ShaneBeee/SkBee#66]
Hello, I have an idea, would it be possible to create a system to delete all the orders in the order chat? And also that we can make a system to delete and add commands?

Example:
 on tab complete:
    delete all commands for player

on tab complete:
   add "/help" to all commands for player

**Comment by ShaneBeee** [comment]
I probably won't be adding this.

The commands that show up after typing `/` are not tab completions, they are part of the command map.
I would have to use hackery to add/remove from that map and resend to the players, frankly I do not want to do this.

If your plugins properly have permissions set up for commands, only commands the player has permission for will be send to the player when they log in.
