### ISSUE TITLE
[BUG] NBT Compound from 

### ISSUE THREAD

**Issue by Sorvent** [ShaneBeee/SkBee#660]
### What happened?

In 1.21 the syntax "NBT Compound from" thinks it's a date.

![image](https://github.com/ShaneBeee/SkBee/assets/153697947/684e4040-4a15-4c12-b36c-743373611721)

### Steps to reproduce

1. Create a Spigot Server with version 1.21
2. Create a Skript with the line: set {ruby} to an emerald with nbt compound from "{""minecraft:custom_model_data"":1,""minecraft:custom_name"":'{""italic"":false,""text"":""Ruby""}'}" #(or anything else you want to try)
3. Reload said Skript

### Expected behavior

the variable {ruby} should be an item you can give to players, craft, etc.

### SkBee Version

3.5.3

### Server Version

Spigot 1.21

### SkBee Info

--- [Server Info]: ---
Server Version: 4208-Spigot-146439e-9ef69aa (MC: 1.21)
Skript Version: 2.8.7
Skript Addons:
- Skellett v2.0.10
- Skuishy v2.6
- Skungee v2.0.0-BETA-5
- PixelSkScoreboard v1.4.0-SNAPSHOT
SkBee Version: 3.5.3
SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

Works as expected on Paper 1.20.6. I am also using Spigot since paper is not available for 1.21

**Comment by ShaneBeee** [comment]
please send the FULL output of `/skbee info`

**Comment by Sorvent** [comment]
Sorry about that!

- [NBTAPI]: Found Minecraft: 1.21! Trying to find NMS support
- NBT Elements DISABLED!
- - Your server version [1.21]: is not currently supported by the NBT-API
- - This is not a bug!
- - NBT elements will resume once the API is updated to work with [1.21]
- Text Component Elements disabled
- - Text components require a PaperMC server.
- Advancement Elements successfully loaded
- BossBar Elements successfully loaded
- Bound Elements successfully loaded
- Damage Source elements successfully loaded
- Display Entity elements successfully loaded
- Fishing elements successfully loaded
- Game Event Elements successfully loaded
- Particle Elements successfully loaded
- RayTrace elements successfully loaded
- Recipe Elements successfully loaded
- Scoreboard Elements successfully loaded
- Scoreboard Objective Elements successfully loaded
- Statistic Elements successfully loaded
- Structure Elements successfully loaded
- Minecraft Tag elements successfully loaded
- Team Elements successfully loaded
- Tick Manager elements successfully loaded
- Villager Elements successfully loaded
- Virtual Furnace Elements disabled via config
- World Border Elements successfully loaded
- World Creator Elements successfully loaded
- Chunk Generator Elements disabled via config
- Plugin is up to date!
--- [Server Info]: ---
Server Version: 4208-Spigot-146439e-9ef69aa (MC: 1.21)
Skript Version: 2.8.7
Skript Addons:
- Skellett v2.0.10
- Skuishy v2.6
- Skungee v2.0.0-BETA-5
- PixelSkScoreboard v1.4.0-SNAPSHOT
SkBee Version: 3.5.3
SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by ShaneBeee** [comment]
ok, now read that top few lines

**Comment by Sorvent** [comment]
I see, didnt know that. Sorry bout that
