### ISSUE TITLE
[SUGGESTION] Taking custom NBT on items into account when creating recipes

### ISSUE THREAD

**Issue by bailletced** [ShaneBeee/SkBee#67]
**Is your feature request related to a problem? Please describe.**
I am trying to make recipes with custom NBT tags on items. 
Like showed the wiki, setting custom names/attributes on an item (ex: sharpness for a sword) allows to include these specials item in recipes.
However, creating recipes with item whose have custom NBT tags doesn't seems to be taken into account. 

**Describe the solution you'd like**
Taking into acount custom NBT of items when creating recipes.

**Describe alternatives you've considered**
Playing with item's name/lore will work but has the inconvenience to complicate things in case of working with multi-lang items. (items who have their name/lore changing depending on the choosen language)
![image](https://user-images.githubusercontent.com/39328003/98354346-dcc6f200-2020-11eb-81e9-41c28e42eda3.png)
![image](https://user-images.githubusercontent.com/39328003/98354539-20216080-2021-11eb-8a94-1f9ed089e774.png)

The two items are same but translated in french/english. 
That being said, I think working with NBT could be a nice new feature as allowing creation of a single recipe including N item translated differently. 

**Additional context**
Here is a quick code to show what I tried to do with NBT + recipe: 
(Minecraft 1.16.4 -- Skbee 1.8.2 -- Skript v2.5)

```
set {_test} to end rod
set {_nbt} to nbt compound of {_test}
set tag "tag;skill" of {_nbt} to "mental-attack"
set {_i5} to item from nbt {_nbt}
set {_i1} to diamond sword named "&aEmerald Sword"
register new shaped recipe for {_i1} using air, emerald, air, air, emerald, air, air, {_i5} and air with id "emerald_sword" in group "custom_swords"
```
Although custom NBT tag is set, the recipe is still available with a "normal" end rod

**Comment by ShaneBeee** [comment]
This is just how it works.

Minecraft does not support NBT in recipes. Spigot added methods to allow for doing this, but as far as I know, that only works for ItemMeta (stuff that Minecraft has set) and not custom NBT unfortunately.

**Comment by ShaneBeee** [comment]
Closing this due to the fact this is completely out of my control.
