### ISSUE TITLE
[SUGGESTION] New Scoreboard syntax

### ISSUE THREAD

**Issue by Asleeepp** [ShaneBeee/SkBee#671]
### Suggestion

Since Minecraft have updated scoreboards a little, I think SkBee should get an overhaul on its scoreboard syntax, going for a section/structure to do stuff instead, something like

```
create a new scoreboard with id "your id":
    title: Title
    numbers: " "
    objectives: # i don't really know much about objectives so idk here
    lines:
        1:
        2:
        3:
        4:
```

Then you could make some wacky syntax for example

```
every 10 seconds:
    refresh scoreboard [with id] "your id" for all players
```

current syntax could stay, but it'd just edit the scoreboard with ids
`set line 1 of scoreboard [with id] "your id" to "stuff"`

I think this would be a nice overhaul to scoreboards, atleast in my opinion  

Of course, what i said above is just a suggestion 

### Alternatives

I guess the current scoreboard syntax? i don't know 😅

**Comment by ShaneBeee** [comment]
So this is a lot to unpack here.

Im going to start with explaining how scoreboards work:
Scoreboard Elements (objectives, teams, scores) = Vanilla scoreboard stuff (you can't set lines on a vanilla scoreboard)
SkBee Scoreboards (Setting titles/lines) = FastBoard API (which uses packets to manipulate team based scoreboard stuff on the client.

Ok, now that that is out of the way... scoreboards don't have IDs, so Im not sure how an id based scoreboard would be created without actually creating random objects in SkBee.
I could potentially have an ID based wrapper, and some sort of system that could be used in a section.

That said, what you’re proposing would essentially have the exact same outcome of a function, ex:
```applescript
function updateBoard(p: player):
	set title of scoreboard of {_p} to "le title"
	set line 1 of scoreboard of {_p} to "something: %{var::%uuid of {_p}%}%"
	# and so on

on some event:
	updateBoard(player)
```

So with that said, I don't see how a section would provide anything new and/or useful in this context.

Also wanted to circle back to the first part of my message, objectives/teams (vanilla scoreboard stuff) have nothing to do with SkBee scoreboards (fastboards)

**Comment by Asleeepp** [comment]
Ah, okay I see, I was just hoping for some sort of refresh, as I felt that the scoreboard syntax that SkBee currently has could be condensed into an id-based section sort of thing, like chunk generators are, I guess I didn't know as much as I thought I knew about scoreboards 😅
