### ISSUE TITLE
[SUGGESTION] Temporary boss bars

### ISSUE THREAD

**Issue by MissingReports** [ShaneBeee/SkBee#672]
### Suggestion

Temporary boss bars that aren't identified by IDs, they are mostly used for per-player progress

I'm not completely sure but I think boss bars are persistent across server restarts. if this is true that means to create a per-player progress your server would have to store a boss bar for each player

New Syntax: ``[new] boss[ ]bar [(named|with id) %string%] with title %string% [with (color|colour) %color%] [with style %bossbarstyle%] [with progress %number%]`` if the ID isn't set then it's temporary

### Alternatives

I don't have any alternatives

### Additional Information

Use ``createBossBar(String title, BarColor color, BarStyle style, BarFlag... flags)`` instead of ``createBossBar(NamespacedKey key, String title, BarColor barColor, BarStyle barStyle, BarFlag... barFlags)``

**Comment by ShaneBeee** [comment]
whats the issue with them being stored?
why can't you just delete the Bossbar when the player logs out?

**Comment by MissingReports** [comment]
let's say i make a new bossbar for every player in afk, and 80 players were afk and suddenly the server crashes
now let's say the server crashes at least 1 time a month for some reason

this means you're storing 80 bossbars that are useless a month

**Comment by MissingReports** [comment]
and it wouldn't even be that hard to make a temporary bossbar

**Comment by ShaneBeee** [comment]
that's fair, ill work on adding temp ones
