### ISSUE TITLE
[BUG] Wind Burst triggers block explode event

### ISSUE THREAD

**Issue by 2002Spiele** [ShaneBeee/SkBee#674]
### What happened?

Hitting an entity with a mace enchanted with Wind Burst triggers the [On Block Explode](https://skripthub.net/docs/?id=10438) event.
`past event-itemtype` also ends up returning air, which I guess is not intended

### Steps to reproduce

1. Write a script using the [On Block Explode](https://skripthub.net/docs/?id=10438) event
2. Reload the script
3. Use a mace with Wind Burst and use its enchantment
4. The code inside the event will run

### Expected behavior

It shouldn't trigger the [On Block Explode](https://skripthub.net/docs/?id=10438) event, cause the event is supposed to run for explosions caused by blocks, as its description says.
I expected it to trigger the vanilla On Explode event at least, but that's not the case.

### SkBee Version

3.5.5

### Server Version

Paper 1.21 (Experimental, build #24)

### SkBee Info

```
--- [SkBee Loading Info] ---
- [NBTAPI] Found Minecraft: 1.21! Trying to find NMS support
- [NBTAPI] NMS support 'MC1_21_R1' loaded!
- NBT Elements successfully loaded
- Text Component Elements successfully loaded
- Advancement Elements successfully loaded
- BossBar Elements successfully loaded
- Bound Elements successfully loaded
- Damage Source elements successfully loaded
- Display Entity elements successfully loaded
- Fishing elements successfully loaded
- Game Event Elements successfully loaded
- Particle Elements successfully loaded
- RayTrace elements successfully loaded
- Recipe Elements successfully loaded
- Scoreboard Elements successfully loaded
- Scoreboard Objective Elements successfully loaded
- Statistic Elements successfully loaded
- Structure Elements successfully loaded
- Minecraft Tag elements successfully loaded
- Team Elements successfully loaded
- Tick Manager elements successfully loaded
- Villager Elements successfully loaded
- Virtual Furnace Elements disabled via config
- World Border Elements successfully loaded
- World Creator Elements successfully loaded
- Chunk Generator Elements disabled via config
- Plugin is not up to date!
-  - Current version: v3.5.5
-  - Available update: v3.5.6
-  - Download available at: https://github.com/ShaneBeee/SkBee/releases
--- [Server Info] ---
Server Version: 1.21-26-77c763b (MC: 1.21)
Skript Version: 2.8.7-nightly-b9b1ceb
Skript Addons:
- DiSky v4.17.2
- skript-reflect v2.4
SkBee Version: 3.5.5
SkBee Website: https://github.com/ShaneBeee/SkBee
```

**Comment by ShaneBeee** [comment]
I have 0 control over what events the server calls.

**Comment by 2002Spiele** [comment]
Okay, guess it is a paper issue then?

**Comment by ShaneBeee** [comment]
Yep (or maybe Bukkit?!?!?)
Skript/Addons just register listeners for Bukkit/Paper events. 
We don't call them. We don't control them in any way.

**Comment by 2002Spiele** [comment]
Oh alright, will remember that for the future. I had no idea.
