### ISSUE TITLE
[BUG] Adding to compound list tags of offline players not working

### ISSUE THREAD

**Issue by sluhtie** [ShaneBeee/SkBee#675]
### What happened?

I noticed that I can't add to a compound list tag of an offline player. Setting or adding to a int tag of a offline players works tho.
This is my original code:
```applescript
function punish(p: player, t: offline player, r: string):
    broadcast 1
    set {_history::*} to getHistory({_t})
    set {_count} to (size of {_history::*} where [string tag "Reason" of input = {_r}])
    set {_duration} to ({_count}+1st element of (lore of {-bans::%{_r}%}))
    set {_punish} to nbt from "{Type:""%name of {-bans::%{_r}%}%"",Duration:""%{_duration}%"",Expire:%unix timestamp of {_duration} parsed as timespan from now%,Reason:""%{_r}%""}"
    set (uuid tag "Punisher" of {_punish}) to uuid of {_p}
    if {_t} is online:
        add {_punish} to (compound list tag "custom;Punishments" of {-data::%uuid of {_t}%})
    else:
        add {_punish} to (compound list tag "custom;Punishments" of nbt of {_t} parsed as offline player)
        broadcast "&coffline"
    broadcast pretty nbt of {_punish} with split "    "
    broadcast {_duration}
```

### Steps to reproduce

I used the following effect commands to test:
**Working:** `!add 1 to int tag "custom;Test" of nbt of offlineplayer("KrombacherSpezi")`
<img width="842" alt="Bildschirmfoto 2024-07-11 um 11 48 36" src="https://github.com/ShaneBeee/SkBee/assets/97464371/9ea8a00f-0900-40cd-8c66-029e8c988f48">

**Not working:** `!add (nbt from "{Test:1b}") to compound list tag "custom;Test" of nbt of offlineplayer("KrombacherSpezi")`
<img width="830" alt="Bildschirmfoto 2024-07-11 um 11 49 09" src="https://github.com/ShaneBeee/SkBee/assets/97464371/611ae43d-8984-4939-b418-1b5135d57cce">

### Expected behavior

That you can add to nbt compound lists of offline players

### SkBee Version

3.5.6

### Server Version

Purpur 1.20.4

### SkBee Info

<img width="695" alt="Bildschirmfoto 2024-07-11 um 11 50 17" src="https://github.com/ShaneBeee/SkBee/assets/97464371/e0d5a187-b6fb-4539-9acd-52b1e5a627cc">

**Comment by ShaneBeee** [comment]
You have a couple things wrong here:
1) You are trying to parse an offline player as an offline player:
<img width="858" alt="Screenshot 2024-07-11 at 7 24 25 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/c6c1f669-5aa8-4d48-a286-9da59aa7e06e">

In Skript, you can only parse text.

2) You are trying to add nbt to a compound list tag, that is already an int tag.
<img width="923" alt="Screenshot 2024-07-11 at 7 24 50 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/d1420f7b-e146-4b06-88c8-7af0e1f9e7d2">

I feel like it would be obvious why this wouldn't work. 

To finish this off, I did a bare bones test:
```applescript
on load:
	set {_n} to nbt of offlineplayer("ShaneBee")

	send "Before:"
	send pretty nbt of (compound tag "custom" of {_n}) with split " "

	add nbt from "{bloop:5}" to compound list tag "custom;Test" of {_n}

	send "After:"
	send pretty nbt of (compound tag "custom" of {_n}) with split " "
```
Outcome:
<img width="437" alt="Screenshot 2024-07-11 at 7 28 35 AM" src="https://github.com/ShaneBeee/SkBee/assets/20008482/8e1529c8-14f5-4bb2-8c65-73aa06ca4d76">

**Comment by sluhtie** [comment]
I agree, I looked over my skript and I had a few more Issues in it. Totally my fault. At first, the offline player I was giving to the function wasn't even set 🤦‍♂️
