### ISSUE TITLE
[SUGGESTION] Villager offers

### ISSUE THREAD

**Issue by MissingReports** [ShaneBeee/SkBee#676]
### Suggestion

A way to change villager offers / trades

New Element: ``%villager%'s (offers|trades)``

Example: ``clear entity's offers``

### Alternatives

I don't have any alternatives in mind

### Additional Information

Spigot has handy methods to do that: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/Merchant.html#getRecipes() and https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/Merchant.html#setRecipes(java.util.List)

**Comment by ShaneBeee** [comment]
isn't this already a thing?
https://skripthub.net/docs/?id=10680

**Comment by MissingReports** [comment]
oh bruh, i was searching for keywords like "offers" and "trades" so i didn't see it
mb
