### ISSUE TITLE
[BUG] Registered shapeless recipe won't craft anymore.

### ISSUE THREAD

**Issue by GentlemanCheesy** [ShaneBeee/SkBee#677]
### What happened?

A recipe that was previous registered on 1.20.6 using Skbee no longer is craftable when registered on 1.21.
Here is an example of how i registered it, trying both local and global variables.
![image](https://github.com/user-attachments/assets/b769c20f-948e-4b74-a5f6-4838614ffc09)
The recipe shows up correctly in the guide book and mods such as EMI:
![image](https://github.com/user-attachments/assets/e431aa09-02d5-4e63-b942-f6c06dd3ee48)
However it is not craftable when bringing the items to a crafting table. I double checked and both item's components match up.
![image](https://github.com/user-attachments/assets/a64330fa-6824-4483-995c-cac7f6e62e5f)
This recipe still is craftable in 1.20.6. I'll include both versions of the server's plugins used below.
I also have other recipes both shapeless and shaped, that work just fine, here is one:
![image](https://github.com/user-attachments/assets/1c7cb685-aa16-4c03-bc2c-597a03426868)
![image](https://github.com/user-attachments/assets/38f171e7-48b6-4e3a-a715-4e41f75351f6)

### Steps to reproduce

1. Load the script as seen in the above image.
2. Check that the recipe is in fact registered.
3. Try crafting the recipe.

### Expected behavior

The above recipe should craft just like the other recipes i have added that do work.

### SkBee Version

3.5.7 & 3.5.5

### Server Version

Paper 1.21 & 1.20.6

### SkBee Info

1.21:
![image](https://github.com/user-attachments/assets/ba9ef739-c6f0-4841-939b-def65f07ef02)
1.20.6
![image](https://github.com/user-attachments/assets/82202a9e-aea7-4500-81a8-16dd41690787)

**Comment by ShaneBeee** [comment]
I can confirm this is broken. Now I have to figure out if this is an SkBee bug or a server bug.
The fact it works on one version and not the other... tells me this is a server bug.

**Comment by ShaneBeee** [comment]
update:
Ok I new this sounded familiar...
this is a Paper Bug:
<https://github.com/PaperMC/Paper/issues/10962>

I'll keep this issue open until Paper solves this.

**Comment by UWUplus** [comment]
I've tried to work around this, it seems like a restart of the server works some magic to get the recipes to register.
