### ISSUE TITLE
[BUG] Glow an entity (DisplayItem) generates an error and prevents the sk file from working

### ISSUE THREAD

**Issue by McGuard83** [ShaneBeee/SkBee#686]
### What happened?

One of my scripts could not run anymore (it worked fine before), so I looked for the line that was causing the problem because no error was displayed when loading the script.

The line in question is the following:
make {_entite.%location of loop-block%} glow green for player
the entity in question is a display item

All other functions work like size, movement etc. but concerning coloring it does not work and generates an error in my logs:

![image](https://github.com/user-attachments/assets/d269ff87-9ad9-42d0-b60c-a1b000d035ef)

### Steps to reproduce

1. Lorsque cette ligne est dans le code, quelque soit sa place
2.
3.

### Expected behavior

Glowing item display

### SkBee Version

3.5.7

### Server Version

Paper 1.20.1

### SkBee Info

![image](https://github.com/user-attachments/assets/54deca7c-6ab3-42e5-a21c-1d8b1498978f)

**Comment by ShaneBeee** [comment]
the error in that image is from PoaSK not SkBee, so you'll need to report it to them.
