### ISSUE TITLE
[SUGGESTION] ItemComponent - Attribute Modifier Apply add a way to set?

### ISSUE THREAD

**Issue by theuwufurry** [ShaneBeee/SkBee#687]
### Suggestion

make a way to set / replace attributes with 

 ItemComponent - Attribute Modifier Apply
 
 

### Alternatives

i want to be able to replace a attribute number that has the same id

for example 

    apply attribute modifier to event-item:
        attribute: armor
        id: "%{_i}%crum"
        slot: any_slot_group
        amount: {_math}
        operation: add_number
        
     when it runs i want it to replace the amount if the id matches
     
     ### Additional Information

_No response_

**Comment by theuwufurry** [comment]
oh thats sad

**Comment by theuwufurry** [comment]
is there a way to remove a specific attribute modifier with id or do you just have to clear the item?

**Comment by Fusezion** [comment]
U haven't checked as I'm at work but If it hasn't changed from MultiMap it likely isn't possible

**Comment by ShaneBeee** [comment]
ok, Im adding expression to get modifiers and modifier properties from items.
While this may not seem like the easiest route for users to remove, at least its an option.
