### ISSUE TITLE
[BUG] 1.20.6+ with all item flags doesn't work

### ISSUE THREAD

**Issue by Kastor07** [ShaneBeee/SkBee#696]
### What happened?

Used "with all item flags" and it did not work

### Steps to reproduce

1. Load up 1.20.6 or 1.21
2. make a gui item or get an item with all item flags (specifically a sword)
3. it doesnt work

### Expected behavior

for it to... hide the item flags?

### SkBee Version

3.5.9

### Server Version

Paper 1.20.6 & also tested on 1.21

### SkBee Info

![image](https://github.com/user-attachments/assets/6eedfe87-600a-4ee3-9611-af00e88a3759)

### Additional Information

here is the code: make gui 14 with unbreakable iron sword with all item flags named "&cInsane" with lore "&c&lCOMING SOON%nl%&7Click to choose!"

here is a picture of it not working: 
![image](https://github.com/user-attachments/assets/9bc6eeb1-51d2-4a89-82aa-943ccc150c41)
YES, i tested in GMC and GMS

**Comment by ShaneBeee** [comment]
This isn't a bug with SkBee, this is an unfortunate thing that Minecraft has done in a weird weird.
the hide attribute flag can only be used on custom attribute modifiers.

Here are some ways to get around it:
https://github.com/ShaneBeee/SkBee/wiki/Tricks-Hide-Attribute-Modifiers

**Comment by Kastor07** [comment]
Ah, so, as of currently, there is no way for you to do this without modifying the item (as far as i can tell)
Well, thats actually good news for me lol. I don't use the vanilla attributes anyways haha
