### ISSUE TITLE
[BUG] NBT

### ISSUE THREAD

**Issue by 3add** [ShaneBeee/SkBee#698]
### What happened?

Item NBT's aren't working. The get request works (string tag "e" of {_nbt}) but the set doesn't (set string tag "e" of {_nbt} to "string")

### Steps to reproduce

1. Use the set nbt function of skbee in your skripts

### Expected behavior

Just for it to store the nbt correctly

### SkBee Version

3.6.0

### Server Version

1.21.1

### SkBee Info

11.08 10:58:43 [Server] [INFO] --- [SkBee Loading Info] ---
11.08 10:58:43 [Server] [INFO] - [NBTAPI] Found Minecraft: 1.21.1! Trying to find NMS support
11.08 10:58:43 [Server] [INFO] - [NBTAPI] NMS support 'MC1_21_R1' loaded!
11.08 10:58:43 [Server] [INFO] - NBT Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Text Component Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Advancement Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - BossBar Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Bound Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Damage Source elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Display Entity elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Fishing elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Game Event Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Item Component Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Particle Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - RayTrace elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Recipe Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Scoreboard Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Scoreboard Objective Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Statistic Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Structure Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Minecraft Tag elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Team Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Tick Manager elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Villager Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Virtual Furnace Elements disabled via config
11.08 10:58:43 [Server] [INFO] - World Border Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - World Creator Elements successfully loaded
11.08 10:58:43 [Server] [INFO] - Chunk Generator Elements disabled via config
11.08 10:58:43 [Server] [INFO] - Plugin is up to date!
11.08 10:58:43 [Server] [INFO] --- [Server Info] ---
11.08 10:58:43 [Server] [INFO] Server Version: 1.21.1-DEV-7d7f123 (MC: 1.21.1)
11.08 10:58:43 [Server] [INFO] Skript Version: 2.9.1
11.08 10:58:43 [Server] [INFO] Skript Addons:
11.08 10:58:43 [Server] [INFO] - DiSky v4.17.2
11.08 10:58:43 [Server] [INFO] - skript-reflect v2.4
11.08 10:58:43 [Server] [INFO] SkBee Version: 3.6.0
11.08 10:58:43 [Server] [INFO] SkBee Website: https://github.com/ShaneBeee/SkBee

**Comment by 3add** [comment]
> ### What happened?
> Item NBT's aren't working. The get request works (string tag "e" of {_nbt}) but the set doesn't (set string tag "e" of {_nbt} to "string")
> 
> ### Steps to reproduce
> 1. Use the set nbt function of skbee in your skripts
> 
> ### Expected behavior
> Just for it to store the nbt correctly
> 
> ### SkBee Version
> 3.6.0
> 
> ### Server Version
> 1.21.1
> 
> ### SkBee Info
> 11.08 10:58:43 [Server] [INFO] --- [SkBee Loading Info] --- 11.08 10:58:43 [Server] [INFO] - [NBTAPI] Found Minecraft: 1.21.1! Trying to find NMS support 11.08 10:58:43 [Server] [INFO] - [NBTAPI] NMS support 'MC1_21_R1' loaded! 11.08 10:58:43 [Server] [INFO] - NBT Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Text Component Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Advancement Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - BossBar Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Bound Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Damage Source elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Display Entity elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Fishing elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Game Event Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Item Component Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Particle Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - RayTrace elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Recipe Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Scoreboard Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Scoreboard Objective Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Statistic Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Structure Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Minecraft Tag elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Team Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Tick Manager elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Villager Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Virtual Furnace Elements disabled via config 11.08 10:58:43 [Server] [INFO] - World Border Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - World Creator Elements successfully loaded 11.08 10:58:43 [Server] [INFO] - Chunk Generator Elements disabled via config 11.08 10:58:43 [Server] [INFO] - Plugin is up to date! 11.08 10:58:43 [Server] [INFO] --- [Server Info] --- 11.08 10:58:43 [Server] [INFO] Server Version: 1.21.1-DEV-7d7f123 (MC: 1.21.1) 11.08 10:58:43 [Server] [INFO] Skript Version: 2.9.1 11.08 10:58:43 [Server] [INFO] Skript Addons: 11.08 10:58:43 [Server] [INFO] - DiSky v4.17.2 11.08 10:58:43 [Server] [INFO] - skript-reflect v2.4 11.08 10:58:43 [Server] [INFO] SkBee Version: 3.6.0 11.08 10:58:43 [Server] [INFO] SkBee Website: https://github.com/ShaneBeee/SkBee
> 
> ### Additional Information
> _No response_

Error Message (console)
11.08 10:59:45 [Server] [ERROR] Tried to load invalid item: 'No component with type: 'minecraft:page'; No component with type: 'minecraft:page' missed input: {page:"0"}'

**Comment by ShaneBeee** [comment]
well, thats because its not a component. 
Minecraft only supports their components, not custom ones.
All custom nbt on an item needs to go in the "minecraft:custom_data" tag

**Comment by ShaneBeee** [comment]
after re-reading your issue.... 
this is intended behaviour, I recommend reading the changelog
