### ISSUE TITLE
The last spawned entity doesn't work with NBT entity

### ISSUE THREAD

**Issue by Romitou** [ShaneBeee/SkBee#7]
Hi ShaneBee, as always, thanks for this addon!
Simple and effective, I use NBT regularly but I don't know if this is a bug, but when I spawn an armor stand with NBT, the expression `last spawned entity` doesn't show the last spawned entity **if I spawn it with NBT**. I don't know if my English is correct so this is a example :

```py
# Position of player: X: 200, Y: 60, Z: 40
spawn an armor stand at location of player
broadcast "%location of last spawned entity%"
# Output: "X: 200, Y: 60, Z: 40"

# Position of player: X: 20, Y: 30, Z: 400
spawn an armor stand at location of player with nbt "{NoGravity:1b}"
# Output: "X: 200, Y: 60, Z: 40"
```
I use the latest version, 1.2.0.
![image](https://user-images.githubusercontent.com/35146758/79671629-2d354a00-81cc-11ea-9565-1aae551e986a.png)

I think this work if I apply the NBT after spawn, but I want to know if this is normal or not.
Thank you and have a good night (or day ?) !

**Comment by ShaneBeee** [comment]
`last spawned entity` is an expression from Skript, and Skript sets the last spawned entity in its spawn effect. I'm not sure if I'm able to do that in my code. I will take a look and see if I can figure it out.

**Comment by legofreak1999** [comment]
Field:
EffSpawn.lastSpawned = org.bukkit.entity.Entity

Should do the job.

https://github.com/SkriptLang/Skript/blob/c4b9c6dd0d24edb6f52b4581a41619ba14d6c68b/src/main/java/ch/njol/skript/effects/EffSpawn.java

https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprLastSpawnedEntity.java

**Comment by ShaneBeee** [comment]
I've already fixed it
https://github.com/ShaneBeee/SkBee/commit/79e83512b250086f9a6d41c810b901896018ce8c

It'll be in the next update.

**Comment by legofreak1999** [comment]
ah okay XD

**Comment by Romitou** [comment]
Thank you for work to fix this!
