### ISSUE TITLE
Creation of full bound modifies the y-coordinate of location variables

### ISSUE THREAD

**Issue by Dismade** [ShaneBeee/SkBee#70]
When I create a full bound between 2 location variables, ( for example {pos1} and {pos2} ) the y-coordinate {pos1} and {pos2} are changed to 0 (for the first one) and 255 (for the second one). Meaning if the original y-coord of {pos1} was 60 and the original y-coord of {pos2} was 70, the y-coord of {pos1} will be changed to 0 and the y-coord of {pos2} will be changed to 255 (or vice versa). This obviously seems to be because of the creation of a full bound from the lowest point (0) and the highest point (256).

**Comment by Dismade** [comment]
Just want to mention that this isn't a big problem since I can just assign temporary variables, {_pos1} and {_pos2}, then use those to create a full bound and {pos1} and {pos2} are untouched.

**Comment by ShaneBeee** [comment]
Ahh good catch. I got some cloning to do.
Thanks for letting me know
