### ISSUE TITLE
[BUG] Items with item flags do not stack with themselves upon being given, but DO stack after double clicking

### ISSUE THREAD

**Issue by Budgo** [ShaneBeee/SkBee#701]
### What happened?

When I give myself an item with its item flags hidden, it works just fine. However, if I give myself an exact copy of that item using the `give item` syntax, it does not automatically stack with the first item in my inventory. Even stranger is that when I attempt to stack the items manually, they stack perfectly fine--not quite sure what changes, since both items then retain their flags.

### Steps to reproduce

1. Create any function that gives you an item with item flags
2. Run it once
3. Run it again

### Expected behavior

I expected the second item to increment the amount of the first item, as would be the case with any other "give" effect.

### SkBee Version

2.9.6

### Server Version

git-Paper-22 (MC: 1.20.5)

### SkBee Info

![image](https://github.com/user-attachments/assets/26c42af2-02c0-4f63-9679-ea8ccd430bd3)

**Comment by Fusezion** [comment]
preferably I'd like code tested by yourself vs. me making something and it doing exact opposite

**Comment by Budgo** [comment]
```
function test(p: player):
	set {_item} to stone
	add hide enchants and hide attributes and hide dye and hide unbreakable to item flags of {_item}
	give {_p} {_item}
```

**Comment by Budgo** [comment]
Really strange, as I also tested it on a 1.20.5 server with only Skript and SkBee, and the same thing occurred. Maybe it's a version mismatch? You appear to be on 1.21 and I'm on 1.20.5?

**Comment by ShaneBeee** [comment]
I tested, and could not replicate.
Im using 1.21.1.

I recommend updating your server. 
1.20.5 is not supported.
You should be using either 1.20.6 or 1.21.1

**Comment by Budgo** [comment]
I seem to have fixed it. Unsure what was causing the issue, but a fresh install/server seems to have worked like a charm. Ah well.
