### ISSUE TITLE
[SUGGESTION] Recipe input item match from only NBT in custom_data tag

### ISSUE THREAD

**Issue by Fiopon** [ShaneBeee/SkBee#704]
### Suggestion

Recipes to have a less restricted item with nbt input.
As it stands, if I have a custom item, and someone renames the item, it cannot be used in recipes where I specify the custom item as an ingredient.

Example:
`on load:
	set {_customItem} to diamond with nbt from "{""minecraft:custom_data"":{custom_item_id:""ruby""}}"
	register new shapeless recipe for 1 of diamond using {_customItem}, {_customItem} and light blue dye with id "diamond_from_rubies"`

If a player, for whatever reason, renames their ruby item, it will no longer work as an ingredient in the recipe

My suggestion is to create "loose" matching items.
`set {_customItem} to loose match of diamond with nbt from "{""minecraft:custom_data"":{custom_item_id:""ruby""}}"`
This would only check if the item is a diamond, and if it has at LEAST the nbt tags specified. Any additional tags the item has would be ignored

### Alternatives

I really cannot think of any other alternatives, other than _maybe_ only checking for the basic "diamond" item and then looping the inputs, locking the output if the diamonds dont have the ruby tag, but that seems not so straightforward

**Comment by Fusezion** [comment]
Simple short answer is impossible.

Due to how minecrafts or well bukkits recipe choices work we only have material and exact. Currently the api lacks this functionality

**Comment by Fusezion** [comment]
Have updated my original messages with a but more detail however due to current api limitations I've deemed this as not planned/wont fix
