### ISSUE TITLE
[SUGGESTION] Cancel drops on "Break Blocks with Effects"

### ISSUE THREAD

**Issue by R4far** [ShaneBeee/SkBee#714]
### Suggestion

https://skripthub.net/docs/?id=11939
I would like to see the ability to cancel the drops when using this effect.

### Alternatives

.

**Comment by ShaneBeee** [comment]
why?
Also, there is no option in that method to not have drops of the block

**Comment by R4far** [comment]
> why? Also, there is no option in that method to not have drops of the block

Oh that's sad to hear. It would have been very useful for me, because I am doing a custom mining system where I break the blocks with this effect but I don't really want the block drops

`on block damage:
	set {_miningSpeed} to (double tag "custom;miningSpeed" of custom nbt of player's tool) ? 1
	set {_split::*} to "%type of event-block%" split at " block"
	set {_blockHardness} to {hardness::%{_split::1}%}
	set {_uniqueID} to (random integer between 0 and 99999)
	
	set {whichBreaking::%player%} to event-block
	set block break speed attribute of player to 0

#	set {_timeToBreakInSeconds} to "%ceil({_blockHardness} / {_miningSpeed}) / 20% seconds" parsed as timespan

	loop ceil({_blockHardness} / {_miningSpeed}) times:
		if {whichBreaking::%player%} is not event-block:
			showBlockBreakStage(player, location of event-block, -1, {_uniqueID})
			stop
		set {_currentHealth} to {_blockHardness} if {_currentHealth} is not set
		set {_breakStage} to (({_blockHardness} - {_currentHealth}) / {_blockHardness}) * 10
		showBlockBreakStage(player, location of event-block, {_breakStage}, {_uniqueID})
		remove {_miningSpeed} from {_currentHealth}
		wait a tick
	break event-block with effects using air
	give player ({_split::1} parsed as item type) named {hardness::%{_split::1}%::name}
	showBlockBreakStage(player, location of event-block, -1, {_uniqueID})

on block damage abort:
	delete {whichBreaking::%player%} if {whichBreaking::%player%} is set`

**Comment by ShaneBeee** [comment]
yeah looking at the API there is no way to do that.
So your best bet is to set the block to air and manually figure out the particles yourself.

**Comment by R4far** [comment]
> yeah looking at the API there is no way to do that. So your best bet is to set the block to air and manually figure out the particles yourself.

Okay, thanks for the quick reply! But sadly, doing that for every custom block in my mining system would be way to much work lol
