### ISSUE TITLE
Scoreboard causes issues with /team [BUG]

### ISSUE THREAD

**Issue by Spennncer** [ShaneBeee/SkBee#72]
Hello! Hopefully you can help me on this issue I have.

**Describe the bug**
I am trying to use the /team command in parallel with the SkBee scoreboards in skript. When I load SkBee with the scoreboard elements set to true in the config, my teams will lose their prefix/suffix, colors, and the modified nametags above the player. With SkBee loaded, the color returns to white and I lose prefix/suffix. If I set the scoreboard elements to false in the config and restart the server, my team elements work again.

**To Reproduce**
I started by creating a test team with Skript already loaded (SkBee is not loaded).
- /team add TEST
- /team modify TEST color aqua
- /team join TEST
Result: Name in tab list shows "<name>" and is the color aqua

- /team modify TEST prefix "TESTPrefix "
Result: Name in tab list shows "TESTPrefix <name>" and is the color aqua.

- stop server and load SkBee with Skript
Result: Name in tab list shows "<name>" and is the color white. Nametags above player head is white.

**Expected behavior**
I would expect the color and prefix of the team to remain the same in the tablist after loading SkBee, and to see the modified nametags above players' heads, but they do not.

**Screenshots/Errors**
(I can add screenshots if you need it)

**Version Info:**
 - **SkBee Version:** >> **1.8.3**
-  **Skript Version:** >> **Skript 2.5.1**
 - **Server Version/Platform** Spigot 1.14.4

**Additional context**
No additional plugins. Only Skript and SkBee. Is there something obvious I'm missing with this issue?
Thank you

**Comment by ShaneBeee** [comment]
Unfortunately there is really no way to get around this. 
SkBee uses teams to be able to do the scoreboards the way they are (long lines and no flicker).

That said, I am aware of the fact that SkBee boards do not pair well with the vanilla team command.

**Comment by Spennncer** [comment]
Wow I didn't realize SkBee uses the teams in the background to do that, but that's cool. If you're certain there is no way to get around it, I'll try to rework my team color issue.

Thank you!

**Comment by ShaneBeee** [comment]
Closing as this is something I can no change.
