### ISSUE TITLE
[SUGGESTION] set score %string% below %player% to %number% for %player%

### ISSUE THREAD

**Issue by MrScopes** [ShaneBeee/SkBee#74]
**Is your feature request related to a problem? Please describe.**
Not really, it would just be nice to have.

**Describe the solution you'd like**
Skrayfall has the syntax `set score %string% below %player% to %number% for %player%` to set the score below the player's nametag to something with a name beside it

**Describe alternatives you've considered**
Skrayfall seems to be the only addon with support for this.

**Comment by ShaneBeee** [comment]
Due to how scoreboards work in SkBee, I really dont think this feature will work unfortunately
