### ISSUE TITLE
[SUGGESTION] Tab completion imrovements

### ISSUE THREAD

**Issue by MrScopes** [ShaneBeee/SkBee#75]
**Is your feature request related to a problem? Please describe.**
It would be cool if %event-string% in tab completions would show the full command currently executed (prior to the current give argument), so `event-string` in `/hi here he<typing here>` would be `hi here`

**Describe alternatives you've considered**
Just feeding back all available info for the command

**Comment by ShaneBeee** [comment]
Im pretty sure I could make this happen

**Comment by MrScopes** [comment]
> Im pretty sure I could make this happen

that would be pretty awesome, I have a lot of potential uses for this
