### ISSUE TITLE
NBT elements disables on 1.16.4?

### ISSUE THREAD

**Issue by Shownie** [ShaneBeee/SkBee#76]
Im sure nbt elements are enabled on config but on this server nbt elements automaticls disables and none of them work

**Version Info:**
 - **SkBee Version:** 1.8.3
-  **Skript Version:** 2.5.1
 - **Server Version/Platform** Paper Spigot 1.16.4

**Comment by ShaneBeee** [comment]
Works fine for me.
<img width="926" alt="Screen Shot 2020-11-23 at 3 34 51 AM" src="https://user-images.githubusercontent.com/20008482/99957641-e3ea4180-2d3c-11eb-97fc-c88059753f76.png">

**Comment by ShaneBeee** [comment]
Closing due to no further response.
