### ISSUE TITLE
[BUG] Scoreboard interfering with Skellet

### ISSUE THREAD

**Issue by Retard69420** [ShaneBeee/SkBee#77]
**Describe the bug**
Whenever I try using skBee scoreboard with Skellet teams, Skellet teams gets broken. I use Skellet for creating teams then adding players to it in order to change their name tag and sort tab from Owner to Default.

```
create nametag "a-owner"
set prefix of nametag "a-owner" to "&8[<##E72D2D>&lO&8] &7"
add player to nametag "a-owner"
```
Whenever I use skBee scoreboards the Skellet sorting and nametags completely break and there is no difference between having it and not having them. When I remove skBee scoreboard Skellet is fixed. I think skBee's groups is conflicting with Skellet groups.

**To Reproduce**
Please include clear steps to reproduce the behavior

**Expected behavior**
I expect the tablist to sorted in the order of Skellet groups assigned to them for example:

Player - "a-owner"
Player - "b-person"
Player - "c-thing"

And their nametags to be prefixed with their group

**Screenshots/Errors**
If applicable, add screenshots/errors to help explain your problem.

**Version Info:**
 - **SkBee Version:** (1.8.3)
 - **Skellet Version:** (1.9.11-MH)
-  **Skript Version:** (Skript 2.5.1-MH)
 - **Server Version/Platform** (Paper 1.16.4)

**Additional context**

**Comment by ShaneBeee** [comment]
This is something I definitely know about.

SkBee uses scoreboards for each player, which is why teams for the main server's scoreboard do not work.
Unfortunately there is nothing I can do about this.

In this case, I might recommend just disabling SkBee boards, and use Skellett's scoreboards
