### ISSUE TITLE
[WIKI] SpigotMC Link

### ISSUE THREAD

**Issue by JerryTheSlime16** [ShaneBeee/SkBee#79]
The link to the SpigotMC resource of SkBee leads you to a hidden wiki page.

Image below along with the link it sends you to.

![image](https://user-images.githubusercontent.com/30807739/100806844-cf6e0f00-33f6-11eb-8a30-94aa196e09a7.png)

**Comment by ShaneBeee** [comment]
Fixed :)

thanks for letting me know
