### ISSUE TITLE
[SUGGESTION] Fishing events

### ISSUE THREAD

**Issue by deathsou** [ShaneBeee/SkBee#80]
**Is your feature request related to a problem? Please describe.**
Hey! I was looking through some old fishing events so that I could make custom fishing knocback/damage.

**Describe the solution you'd like**
I would like it if we could have these 3 events, which Njol considered adding but never did:
on catch: (When a fish is caught it calls this.)

on cast: (When a fishing tackle is spawned.)

on reel: (When a fishing tackle is recalled.)
([https://github.com/Njol/Skript/issues/139])

**Describe alternatives you've considered**
I've tried using the skellett one, believe it doesn't work. I've tried on fish but then again that's for any time u throw the rod.

**Comment by ShaneBeee** [comment]
I know there are some plans to do this in Skript already.
I'll take a look at how its being prepared. If its slated for 2.6 (which could be a while) I may look into adding it to SkBee for the time being.
