### ISSUE TITLE
NBT Compound [BUG]

### ISSUE THREAD

**Issue by DiscStrad** [ShaneBeee/SkBee#81]
**Describe the bug**
Cant set Compound tags

**To Reproduce**
`set tag "Item;xp" of nbt of {_item} to 0`
That wont set {Item:{xp:0}} it changes nothing 

**Expected behavior**
It should set the Compound tag to the specified number

**Screenshots/Errors**
There is no error it just wont work

**Version Info:**
 - **SkBee Version: 1.8.4**
-  **Skript Version: 2.5.1**
 - **Server Version/Platform: Paper 1.16.3** 

**Additional context**
I can get the Compound Tag but I can not set it

**Comment by ShaneBeee** [comment]
Not a bug:
<img width="1135" alt="Screen Shot 2020-12-08 at 5 04 38 PM" src="https://user-images.githubusercontent.com/20008482/101560180-84647680-3977-11eb-9628-a767d995dd12.png">
