### ISSUE TITLE
[BUG] HEX values in scoreboard

### ISSUE THREAD

**Issue by HvadFanSkalJegHedde** [ShaneBeee/SkBee#82]
**Describe the bug**
When using HEX values in the scoreboard like:
`<##38a3a5>&lO<##34b7aa>&lw<##41caaa>&ln<##5ddca4>&le<##80ed99>&lr`
It'll make the 4th letter the closest to a standard Minecraft color (in this case §4 or &4). It'll change color no matter what. Antoher example would be:
`<##67eba0>1<##67eba0>2<##67eba0>3<##67eba0>4<##67eba0>5<##67eba0>6<##67eba0>7<##67eba0>8`
In this case, the number 5 will just be black.

**To Reproduce**
```vb
command /bug:
    trigger:
        clear scoreboard of player
        toggle scoreboard of player on
        set title of player's scoreboard to "Bug"
        set line 1 of player's scoreboard to "<##67eba0>1<##67eba0>2<##67eba0>3<##67eba0>4<##67eba0>5<##67eba0>6<##67eba0>7<##67eba0>8"
```

That's all it'll take, the number 5 will just turn black.

**Expected behavior**
I expected it to be the color I set it to.

**Screenshots/Errors**
This code:
![image](https://user-images.githubusercontent.com/47789511/102023269-570b3480-3d8c-11eb-872c-c1785c464b85.png)

Gives this:
![image](https://user-images.githubusercontent.com/47789511/102023223-3347ee80-3d8c-11eb-9193-b1cd01a0e6b5.png)

**Version Info:**
 - **SkBee Version:** 1.9.0
-  **Skript Version:** Skript 2.5.2-MH (Version for Minehut, It shouldn't matter)
 - **Server Version/Platform** Paper version git-Paper-261 (Minecraft 1.16.4)

**Additional context**
I have no clue about what's causing this, it could be something I've done.

**Comment by ShaneBeee** [comment]
Unfortunately I don't think theres anything I can do about this.
This system uses team prefixes which I believe max out at 64 lin characters s. After 64 characters, it's split and then uses suffixes. Due to that, anything after 64 characters, the colours are bound to get screwed up.
This is mainly due to how poorly Bukkit handles coloured stuff.
