### ISSUE TITLE
[BUG] Joining a custom world breaks /schedule command

### ISSUE THREAD

**Issue by vanjmali** [ShaneBeee/SkBee#84]
**Describe the bug**
Running the command `/schedule function <function name> <delay time>` will always run it instantly instead of delaying it with the delay set if ran by a player in a custom world created by SkBee.

**To Reproduce**
1. Create a new world in the server using SkBee
2. Enter the newly created world
3. Run the command `/schedule function <function name> <delay time>` with a datapack installed and proper function name

**Expected behavior**
Execute the function from the datapack after specified delay.

**Version Info:**
 - **SkBee Version:** 1.9.0
-  **Skript Version:** 2.5.3
 - **Server Version/Platform** Paper 1.16.4

**Comment by ShaneBeee** [comment]
Hmm, that seems odd. 
I have a feeling this might be a server issue. 
SkBee uses Bukkit's world creator system to create/load a new world, no special hidden magic or anything. 

I've never heard of that command, nor have I ever used MC functions, so I really have no way of testing/verifying this issue, and on top of that, really have no clue how I would be able to fix it if it is in fact an SkBee issue.

**Comment by vanjmali** [comment]
Alright, thanks.
I assume the bug is depending on Bukkit if they are going to fix it, right?

I could sent you a dummy datapack for you to test the command with, but since you don't know how to use that command and you say it's the server issue, I don't think you would be able to anything about it.
