### ISSUE TITLE
[SUGGESTION] Chest Animation

### ISSUE THREAD

**Issue by GoldenMyst** [ShaneBeee/SkBee#86]
**Is your feature request related to a problem? Please describe.**
Yes, packets are confusing to use and doesn’t seem to work for me.

**Describe the solution you'd like**
I would like something to display chest animations.
Ex: ‘play chest [(open|close)] animation at event-block [for %timespan% [with (sound|no sound)]]’

**Describe alternatives you've considered**
I tried using packets but they didn’t seem to work for me and it was confusing for the most part.

**Additional context**
![074123DC-DB8E-404C-8909-8205E144D22C](https://user-images.githubusercontent.com/74118946/102838590-74a35400-43b3-11eb-8333-71629476c9ea.gif)

**Comment by ShaneBeee** [comment]
Spigot added some methods for changing the block states of openable blocks. I could add this fairly easily.
I will not be adding a time span as that can be handled by the user. 
As for the sound thing, that doesn't appear to be an option for Spigot.
