### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [ShaneBeee/SkBee#90]
**Describe the bug**
Line 0 of the scoreboard doesn't work sometimes

**To Reproduce**
loop all players then do this
`set line 0 of loop-player's scoreboard to "This is line 0"`

**Expected behavior**
The scoreboard 

**Screenshots/Errors**
https://imgur.com/a/VHs16cb

**Version Info:**
 - **SkBee Version:** 1.9.1
-  **Skript Version:** 2.5.3
 - **Server Version/Platform** Paper 1.16.4

**Additional context**
The server is cracked

**Comment by ShaneBeee** [comment]
Thats because SkBee scoreboards are specifically lines 1 to 15

**Comment by MinecraftMan1013number2** [comment]
I've used line 0 before

**Comment by ShaneBeee** [comment]
In SkBee, you most definitely have not.

I literally have it hard coded to only be lines 1-15
<img width="535" alt="Screen Shot 2021-01-10 at 4 54 56 PM" src="https://user-images.githubusercontent.com/20008482/104140127-a1200f80-5364-11eb-831a-606759c34580.png">

**Comment by MinecraftMan1013number2** [comment]
with skRayFall i have tho. Why dont u make it so u can do 0?

**Comment by ShaneBeee** [comment]
For what reason?

**Comment by MinecraftMan1013number2** [comment]
just bc idk. all u would have to do is change 1 number, right?

**Comment by ShaneBeee** [comment]
> just bc idk. 

if thats your reasoning, then no... Im not changing it.

> all u would have to do is change 1 number, right?

nope, I would have to rewrite a good chunk of the board class, shifting 1-15 -> 0-14, thus breaking any single scoreboard any other user has that is currently using line 15

**Comment by MinecraftMan1013number2** [comment]
oof ok

**Comment by MinecraftMan1013number2** [comment]
oof ok
