### ISSUE TITLE
[BUG] Warn when setting NBT tag to variable

### ISSUE THREAD

**Issue by tandpfun** [ShaneBeee/SkBee#92]
**Describe the bug**
Whenever I set a variable to the Fuse NBT tag (Paper 1.8.8), I get the below spigot warning. I'm accessing this tag every tick, so it spams the console.

**To Reproduce**
Set the Fuse nbt tag of a primed tnt. Set a variable to the value of the nbt tag with `set {_seconds} to tag "Fuse" of %entity%`. Check console.

**Expected behavior**
No warns in console.

**Screenshots/Errors**
`[Server] WARN Adding mismatching tag types to tag list`

**Version Info:**
 - **SkBee Version:** 1.9.1
-  **Skript Version:** 2.5.3
 - **Server Version/Platform** Paper 1.8.8

**Comment by ShaneBeee** [comment]
> Set the Fuse nbt tag of a primed tnt. Set a variable to the value of the nbt tag with `set {_seconds} to tag "Fuse" of %entity%`. Check console.

This isn't even valid code. Not sure how I could check it.

On that note, it looks like its a warning from Minecraft itself, and there's probably nothing I can do about that.

**Comment by tandpfun** [comment]
It seems to be valid code, as it works. Entity is the primed tnt. Any idea what could cause the error, or how to turn it off?

**Comment by ShaneBeee** [comment]
I can 100% guarantee you that is not valid code.

If that code DOES work for you, it is NOT SkBee code and you should report it to whomever makes the add-on that provides that syntax.

**Comment by tandpfun** [comment]
Whoops, I had a typo. I meant `set {_seconds} to tag "Fuse" of nbt of loop-value-2`, sorry.

**Comment by ShaneBeee** [comment]
can you please show also how you are setting the fuse tag in the first place. I want to make sure my test is the same as what you are doing

**Comment by tandpfun** [comment]
I'm basically looping every tnt every tick and setting the custom name of the tnt to the time until it explodes.

```
set {_seconds} to tag "Fuse" of nbt compound of loop-value-2
                if {_seconds}/20 is less than 0.5:
                    set {_todisplay} to "&c&l%{_seconds}/20%"
                else if {_seconds}/20 is less than 1:
                    set {_todisplay} to "&e&l%{_seconds}/20%"
                else:
                    set {_todisplay} to "&a&l%{_seconds}/20%"
                
                set tag "CustomName" of nbt compound of loop-value-2 to "%{_todisplay}%"
                set tag "CustomNameVisible" of nbt compound of loop-value-2 to 1
```

I've tested and confirmed that it is getting the tag causing the error, I'm not sure why tho.

**Comment by ShaneBeee** [comment]
ok, so my guess what is going on here, is because you are getting the NBT and changing it too many times, too often.

I did a test by getting the compound once, and modifying the compound and the error seems to stop.

Ex:
```java
// Get the NBT compound
set {_n} to nbt compound of loop-value-2
// Get the tag from the NBT compound
set {_seconds} to tag "Fuse" of {_n}

// Your other stuff here

// Set the tags of the compound itself
set tag "CustomName" of {_n} to "%{_todisplay}%"
set tag "CustomNameVisible" of {_n} to 1
```

**Comment by tandpfun** [comment]
Still getting the error with that new code. Is setting the {_n} variable supposed to be in the loop?

**Comment by ShaneBeee** [comment]
>  Is setting the {_n} variable supposed to be in the loop?

yes, since its the compound of the loop-value

> Still getting the error with that new code.

I couldn't replicate. Needless to say, I don't think there's anything I can do about this, since the error/warning is coming from Minecraft itself.
