### ISSUE TITLE
[SUGGESTION] Guardian Beam

### ISSUE THREAD

**Issue by GoldenMyst** [ShaneBeee/SkBee#94]
**Is your feature request related to a problem? Please describe.**
A way to create/stop a guardian beam from location to another.

**Describe the solution you'd like**

**EFFECTS**
create [guardian] beam (from|between) %location% (to|and) %location% (with id|named) %string%
create [guardian] beam (from|between) (with id|named) %string% (from|between) %location% (to|and) %location%
stop [guardian] beam (with id|named) %string%
draw [guardian] beam (from|between) %location% (to|and) %location% ((with id|named) %string%|for %timespan%)

**EXPRESSIONS**
start[ing] location of [guardian] beam [with id] %string%
end[ing] location of [guardian] beam [with id] %string%

**Describe alternatives you've considered**
I tried using an invisible guardian but it doesn’t seem right

**Additional context**

**Comment by ShaneBeee** [comment]
Due to the fact that Bukkit does not have API for this, and I would have to use packets, im going to pass on this.
Theres already a packet addon that I believe would allow for this goal.
I just dont feel this fits what SkBee does.
