### ISSUE TITLE
[SUGGESTION] Clear/Reset Events

### ISSUE THREAD

**Issue by GoldenMyst** [ShaneBeee/SkBee#95]
**Is your feature request related to a problem? Please describe.**
Clear events for items, mobs; potion effects & display names.

**Describe the solution you'd like**
(clear|reset) (name|lore|nbt|enchant[ment[s]|content] of %itemstack% - reset some data from items (books, shulkers too)
(clear|reset) %entities%’s (potions|[potion] effects) - clear %entities%’s potion effects
clear %entities%’s display name - clears entities’ display name

**Describe alternatives you've considered**
•••

**Additional context**
•••

**Comment by ShaneBeee** [comment]
this can all be done with Skript already.
